### PR TITLE
Scrub BindVar values from log statements to hide PII

### PR DESCRIPTION
**Pull request by eeSeeGee**
There's probably an elegant way to do this in a targeted manner, but this needs to go ASAP.

Signed-off-by: Aaron Young <young@squareup.com>

### CODE REVIEW

**Comment by demmer** [comment]
The current behavior is expected and it is something that we rely on at Slack for debugging.

In our internal systems we treat the vttablet log and the mysql error log as possibly containing PII so we control access to those log files to prevent information from mistakenly leaking.

Note that the `queryserver-config-terse-errors` flag prevents these bind vars from escaping _outside_ of the vttablet process by redacting the information returned over GRPC to the vtgate/application.

**Comment by sougou** [comment]
Yeah. This is very critical as a "last line of defense". There has to be at least one place where you can see all the data while troubleshooting production issues.

**Comment by sougou** [comment]
I'll close this unless it's still needed for your use case. If so, we'll need to add a flag for this.

**Comment by eeSeeGee** [comment]
We merged it in our fork, you can close until I have the time to wrap it in a flag.

**Pull request closed without merging**
