### PR TITLE
Add slim Docker file for functional testing using vttestserver

### PR DESCRIPTION
**Pull request by kalfonso**
This is based on the vitess/lite image which will provide as slim down version to use in testing

### CODE REVIEW

**Comment by kalfonso** [comment]
To use this image the schema folder must be copied to a known location within the container and point ```vttestserver``` to it

**Comment by morgo** [comment]
@kalfonso LGTM in principle. This is not an area I understand well, may I ask what functionality the `vitess/lite` images were missing / why it is better to have a separate Docker file?

**Comment by kalfonso** [comment]
@morgo this allows to use only the minimum binaries required to run vttestserver(it uses vtcombo) which we use in our integration tests with Docker. The other Vitess/lite images are fine for production but I wanted to have a lite image to run vttestserver

**Comment by sougou** [comment]
@kalfonso can you resolve merge conflicts?

**Pull request merged**
