### PR TITLE
Support specifying expected primary in ERS/PRS

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

This PR allows a `EmergencyReparentShard`/`PlannedReparentShard` request to contain the alias of the primary we expect to be the current primary for the action to succeed. If this alias is incorrect or stale, the reparent fails with an error indicating there is a failed precondition/mismatch.

This is useful to prevent races between external automation that runs reparents and Vitess _(`vtorc` and `vtctld`)_, which may reparent a shard in the time external automation is creating/processing it's own reparent request. With this support added, automation with a stale view of the world will encounter an error instead of triggering an potentially unnecessary reparent

In the future, Vitess could use this field internally to be more explicit but because everything uses shard locks, it should never encounter a mismatch

## Related Issue(s)

Resolves https://github.com/vitessio/vitess/issues/16430

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by mattlord** [comment]
You'll want to add support for this in the client command, no? Here: go/cmd/vtctldclient/command/reparents.go

**Comment by timvaillancourt** [comment]
> You'll want to add support for this in the client command, no? Here: [go/cmd/vtctldclient/command/reparents.go](https://github.com/vitessio/vitess/blob/main/go/cmd/vtctldclient/command/reparents.go)

@mattlord oh thanks, yes I'll add support for the CLI binary 👍👀

**Comment by timvaillancourt** [comment]
Added:
```bash
tvaillancourt@tvailla-ltmxctu vitess % ./bin/vtctldclient EmergencyReparentShard --help 2>&1 | grep expected-primary
      --expected-primary string          Alias of a tablet that must be the current primary in order for the reparent to be processed.
```
👍

**Comment by arthurschreiber** [comment]
@timvaillancourt Can we have that same cli flag for `PlannedReparentShard` as well? 😬

**Comment by timvaillancourt** [comment]
@arthurschreiber in the original issue we discussed adding this to PRS too but the recommendation was to use the new primary flag to fence things. Of course that only works if all systems agree on a candidate, which isn't guaranteed

I'd be on board with adding this to PRS too if no objections

**Comment by arthurschreiber** [comment]
Adding this to PRS would make our operations a lot more robust. Obviously, PRS takes a lock before modifying a shard, so no two PRS operations can run at the same time, but we'd also like to guarantee that we don't fail over a shard during the buffer cooldown period we have set.

We can check the time when the current primary started serving, but we can't guarantee that a PRS from some other automation or manual call jumps in between the check of the timestamp and the call to PRS. Allowing us to specify the expected current primary for PRS as well would allow us to abort if the primary got changed unexpectedly.

**Comment by mattlord** [comment]
I think the idea of being able to enforce a specific sequence or state machine for the shard leadership/primaryship makes a lot of sense for both ERS and PRS, FWIW. 🙂

**Comment by timvaillancourt** [comment]
@arthurschreiber / @mattlord yeah, I think it's a good idea for both so I'll update this PR to add that

As mentioned, Vitess could use this internally, too (probably +1 release). It would never hit a conflict but it wouldn't hurt either

**Comment by timvaillancourt** [comment]
I think I prefer the field-name `RequiredPrimary` now but let's vote on it

🎉 for `ExpectedPrimary`
🚀 for `RequiredPrimary`

Or other suggestions appreciated

**Review by GuptaManan100 — APPROVED** [review]
LGTM!

**Comment by deepthi** [comment]
> I think I prefer the field-name `RequiredPrimary` now but let's vote on it
> 
> 🎉 for `ExpectedPrimary` 🚀 for `RequiredPrimary`
> 
> Or other suggestions appreciated

RequiredCurrentPrimary OR ExpectedCurrentPrimary :)

**Review by deepthi — APPROVED** [review]
LGTM. You will want to possibly make the naming change before merging.

**Comment by timvaillancourt** [comment]
> LGTM. Once the flag name is final, you should edit the PR description to document command usage. I've added a label that prevents merge, and you can remove the label and merge it at that point.

Sounds good! It looks like there weren't many strong opinions on naming

I think I've flip/flopped back to leaving this as-is. My reasoning is if I say what I'm asking to do out loud it is "do X reparent and I expect Y to be still be the primary". And I feel adding `Current` is redundant because there can only be a single primary

**Pull request merged**
