### PR TITLE
bytes2: Add tests for StringUnsafe and Reset methods

### PR DESCRIPTION
**Pull request by glokta1**
## Description
Add tests for `StringUnsafe()` and `Reset()` methods.

Part of #14931 

Improves test coverage of package to 100%
## Checklist

-   [X] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [X] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [X] Tests were added or are not required
-   [X] Did the new or modified tests pass consistently locally and on CI?
-   [X] Documentation was added or is not required

### CODE REVIEW

**Comment by glokta1** [comment]
I'm not quite sure why the Codecov test is failing?

**Comment by mattlord** [comment]
Thank you, @glokta1 ! 

The overall project level coverage decrease is almost certainly due to intermediate commits between your PR branch's HEAD and the `vitessio/vitess` branch's HEAD. You can pull and merge (not rebase) the latest from `vitessio/vitess/main` into your PR branch to address that part.

That's also related to the failing `codecov/project` test (which is not blocking). I'm tweaking that behavior here so that it's informational only and those tests don't fail (perhaps we'll change that in the future): https://github.com/vitessio/vitess/pull/14967

Once you merge in the latest from `origin/main` or whatever name you gave the `vitessio/vitess` remote and push that to your PR, then we should be good and we can get this approved and merged. Thanks again!

**Comment by glokta1** [comment]
Thanks Matt, should be good to go now :D

**Review by mattlord — APPROVED** [review]
Thanks again for the contribution, @glokta1 ! ❤️

**Comment by mattlord** [comment]
Something still seems off with the project level results (we're still ramping up on use of codecov), but more importantly/relevantly we can see that the `bytes2` package is now at 100%: https://app.codecov.io/gh/vitessio/vitess/pull/14940/tree/go/bytes2

**Review by dbussink — APPROVED** [review]

**Pull request merged**
