### PR TITLE
Incremental backup & recovery: restore-to-timestamp

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

Context: https://github.com/vitessio/vitess/issues/11227#issuecomment-1578773690
Followup to https://github.com/vitessio/vitess/pull/11097 and https://github.com/vitessio/vitess/pull/13156

Previously, PITR which stands for Point in TIME Recovery, really only supported position-point. The restore flag `--restore-to-pos` supports GTID sets, not _time_.

This WIP PR implements a restore-to-time recovery. The user only supplies a timestamp, and Vitess evaluates the sequence of full-backup + incremental-backups to bring the database to that point in time.

There has to be some granularity. Right now we aim for `1sec` but we may also support `1micro`.

Right now we assume timestamps are all UTC.

It will be possible to restore `builtin` backups as well as `Xtrabackup`s. In either case, the restore-to-time functionality is based on binary logs: applying binlog entries starting with the full backup and up to desired timestamp.

As always, this process relies on, and expects, MySQL GTIDs.

The process for restoring a point-in-time will not necessarily choose the most optimal path. Because timestamps are not absolute across servers, and most importantly on  lagging replicas, it is _possible_ that the process will choose to begin with an older full backup, and apply more binary logs, than a possible later full backup (which obviously then requires applying less binary logs). The basic premise is: given a database, we don't have an authoritative timestamp to associate with its state. Authoritative tiemstamps are only found in the binary logs. Heuristically, we could use some methods to get a good or even excellent approximation (e.g. write & read a heartbeat). We may iterate on that later on.

### Ready to review: summary of changes

In an incremental backup, we add the following information to the backup MANIFEST:

```json
{
  "FirstTimestamp": "2023-06-15T09:48:17Z",
  "FirstTimestampBinlog": "vt-0000000100-bin.000002",
  "LastTimestamp": "2023-06-15T09:49:50Z",
  "LastTimestampBinlog": "vt-0000000100-bin.000003"
}
```
This tells us what's the very first transaction timestamp found in this incremental backup, and in which binlog file, and what's the very last one, in which binlog file. As a reminder, it's possible to have a single binary log or a range of binary logs in an incremental backup.

With these numbers, and of course with the GTID positions in the MANIFEST files, it's possible to determine a sequence of `1` full backup + `n` incremental backups that will allow us to restore to a point in time (in `1sec` resolution, up to, and excluding, a given timestamp).

This works by reading relevant binary logs using `mysqlbinlog --stop-datetime="<the timestamp>"`.

For now, invoking the restore is done per tablet, via e.g.:

```shell
$ vtctlclient -- RestoreFromBackup --restore_to_timestamp "2023-06-15T09:49:50Z" zone1-0000000100
```

Timestamp must be in `RFC3339` format.

We have two major tests introduced:

- unit testing for finding the restore path
- `endtoend` testing (`backup_restore_to_time`) which takes multiple incremental backups, records times and data per data, then restores to recorded timestamps, expecting recorded data.

## Related Issue(s)

- https://github.com/vitessio/vitess/issues/11227
- Documentation: https://github.com/vitessio/website/pull/1534

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Going to force-push due to too many conflict to deal with by hand.

**Comment by shlomi-noach** [comment]
Ready to review!

**Comment by shlomi-noach** [comment]
Converting to `Draft` because we want to refactor the tests a bit: we want to have distinct tests for `Xtrabackup` and tests for `builtin`. That's because we want to test `Xtrabackup` with `percona-server`, and we want to test `builtin` with `mysql-server`.

**Comment by shlomi-noach** [comment]
Once https://github.com/vitessio/vitess/pull/13395 is merged, I'll refactor the tests in this PR to run within the same workflows introduced in https://github.com/vitessio/vitess/pull/13395

**Comment by shlomi-noach** [comment]
tests are now refactored into existing `backup_pitr` and `backup_pitr_xtrabackup`, as per https://github.com/vitessio/vitess/pull/13395

**Comment by shlomi-noach** [comment]
Ready to review (again) !

**Comment by shlomi-noach** [comment]
Documentation PR: https://github.com/vitessio/website/pull/1534

**Review by GuptaManan100 — APPROVED** [review]

**Review by deepthi — APPROVED** [review]

**Pull request merged**
