### PR TITLE
Add flag to VTOrc to enable/disable its ability to run ERS

### LINKED ISSUE #13258: Feature Request: Add VTOrc flag to toggle its ability to run ERS
### Feature Description

Add flag to VTOrc to toggle its ability to run ERS.

### Use Case(s)

This is required when the users want VTOrc to fix the replication issues, but don't want it to run any reparents. It is reasonable to expect that some users would want to still run ERS manually while still wanting to automate everything else.

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR adds a flag to VTOrc to toggle its ability to run an ERS.

## Related Issue(s)

- Fixes #13258 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required - https://github.com/vitessio/website/pull/1492

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
LGTM

**Comment by GuptaManan100** [comment]
Website PR - https://github.com/vitessio/website/pull/1492

**Review by harshit-gangal — COMMENTED** [review]
vtorc can do PRS?

**Review by harshit-gangal — COMMENTED** [review]
looks good otherwise.

**Review by deepthi — APPROVED** [review]

**Pull request merged**
