### PR TITLE
fix wrong spells in tablet.go

### PR DESCRIPTION
**Pull request by AllenZMC**
Make the comment more readable

### CODE REVIEW

**Comment by sougou** [comment]
@AllenZMC could you recreate this PR with DCO: `git commit -s`?

**Comment by AllenZMC** [comment]
I am working on it , why close it? please wait

**Comment by sougou** [comment]
I had to close it because github's DCO check doesn't go green even if you fix the DCO.

**Comment by AllenZMC** [comment]
ok, I have recreated this PR, see #5089. Thanks

**Pull request closed without merging**
