### PR TITLE
Adds comments to UnserveCommon to find potential Deadlock

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR adds a lot of comments in all the Close functions in `unserveCommon` called before killing all OLAP queries. The comments are added recursively inside the Close functions as well to be able to debug a potential Deadlock in `DemotePrimary`.

## Related Issue(s)

#9936 

## Checklist
- [x] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm
fingers crossed!

**Comment by GuptaManan100** [comment]
Yep that would certainly be better! Do we want to add these many comments? WDYT @mattlord @rohit-nayak-ps

**Comment by rohit-nayak-ps** [comment]
> Yep that would certainly be better! Do we want to add these many comments? WDYT @mattlord @rohit-nayak-ps

* Not sure if all users facing this issue can easily set verbosity levels on and off
* Since the issue is not consistently reproducible, having logs all the time is at least needed until we find the root cause
* Since logging is only during shutdown it should have negligible affect on log sizes

In any case we can  revisit once we have this in production for a month or two, or until we find the root cause. Maybe we can consolidate the consecutive logs in `unserveCommon()`.

**Comment by GuptaManan100** [comment]
Alright! I'll make the changes

**Comment by GuptaManan100** [comment]
@mattlord @rohit-nayak-ps I have made the changes for consecutive logs in `unserveCommon`. However, I haven't made the change for the verbosity level that @mattlord suggested after talking to @deepthi. We are currently not using the verbosity levels anywhere else, and when we do, it should be a much larger change.

I agree with both of you that we should merge this on main and revisit once we have found the bug and fixed it.

**Review by mattlord — APPROVED** [review]
Thanks! The TableGC CI test is also one that's flaky IIRC... we could potentially modify that test to print out the tail end of the tablet INFO logs on failure. I wonder if we're hitting the same issue w/o knowing it.

**Pull request merged**
