### PR TITLE
Refactor: use NonEmpty() instead of !IsEmpty()

### PR DESCRIPTION
**Pull request by systay**
## Description
This is not super important, but it does take it's toll. Whenever reading an `if` statement that is using an identifier, and we are checking that it's not empty, we write something like this:

```golang
if !to.QTable.Alias.As.IsEmpty() { ... }
```

The distance between the `!` and the `IsEmpty()` is quite a few characters apart, and that forces me to do an extra mental step when reading code. I much prefer using `NotEmpty` for this:

```golang
if to.QTable.Alias.As.NotEmpty() { ... }
```

This makes the code slightly more readable, and we can use all the readability we can get.

### CODE REVIEW

**Review by harshit-gangal — APPROVED** [review]

**Comment by arthurschreiber** [comment]
Small nitpick: The code calls this `NonEmpty`, your PR description calls it `NotEmpty`.

**Review by arthurschreiber — APPROVED** [review]

**Comment by systay** [comment]
> Small nitpick: The code calls this `NonEmpty`, your PR description calls it `NotEmpty`.

Hehe... Good point. Which one do you prefer? I think `NotEmpty` sounds better, don't you?

**Comment by harshit-gangal** [comment]
> > Small nitpick: The code calls this `NonEmpty`, your PR description calls it `NotEmpty`.
> 
> Hehe... Good point. Which one do you prefer? I think `NotEmpty` sounds better, don't you?

doit

**Review by GuptaManan100 — APPROVED** [review]
LGTM!

**Pull request merged**
