### PR TITLE
update grpc 1.16 to 1.23.0 | protobuf 1.2 to 1.3.2

### PR DESCRIPTION
**Pull request by derekperkins**
It has been a long time since we've upgraded these dependencies, so it seems like we should take advantage of bug fixes and hopefully some underlying performance improvements.

### CODE REVIEW

**Comment by sougou** [comment]
@rafael @tirsen (or @derekperkins) would any of you be able to run some perf comparisons on this before I merge?

**Comment by derekperkins** [comment]
We don't have great metrics in place to report on perf changes. :(

**Comment by derekperkins** [comment]
Since I originally submitted this, there was a patch release on golang/protobuf from 1.3.1 to 1.3.2, so I amended my commit to target that release.

**Comment by sougou** [comment]
@derekperkins build looks broken.

**Comment by derekperkins** [comment]
This PR is now obsolete because of the move to Go modules, but I still think it should happen. Looking at go.mod, I think we still should upgrade, since there were CVEs not addressed until 1.23. I'm not sure what the mod upgrade path looks like, but here is what is currently listed.

1.3.2
https://github.com/vitessio/vitess/blob/master/go.mod#L23

(though it also lists 1.2.1 indirectly)

grpc 1.21.1
https://github.com/vitessio/vitess/blob/master/go.mod#L72

**Pull request closed without merging**
