### PR TITLE
add support for BIGINT UNSIGNED <--> java.math.BigInteger

### PR DESCRIPTION
**Pull request by tpetr**
This PR adds support for `java.math.BigInteger` to the Vitess JDBC driver:
- Add support for `BigInteger` parameters in `VitessPreparedStatement`s
- Add an explicit `getBigInteger()` to `VitessResultSet`
- Update unit tests to flex `BigInteger` for both classes.

@harshit-gangal @acharis

### CODE REVIEW

**Comment by harshit-gangal** [comment]
Currently there are 3 way to use BigInteger.

setBigDecimal("mysql_bigIntCol", new BigDecimal("1234567890"))
setLong("mysql_bigIntCol", Long.parseLong("1234567890")) if value can fit within a long
setString("mysql_bigIntCol", "1234567890") to let the JDBC driver convert the string for you

Statement and PreparedStatement method does not allow any other way.

The method you have added will only be accessible if you type cast them into VitessStatement or VitessPreparedStatement.

Do you really need to add this or can you use the above way as workaround?

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/vitessio/vitess/3847#-:-LAXWDr80qCP2-9A2cyr:b-eh611)*

**Comment by tpetr** [comment]
@harshit-gangal Apologies for the slow response. We need this because [JDBI](http://jdbi.org/) calls `VitessPreparedStatement.setObject()` to bind parameters when constructing a query. If one of the parameters is a `BigInteger` you currently get an exception like this:

```
java.sql.SQLException: Cannot infer the SQL type to use for an instance of java.math.BigInteger
	at io.vitess.jdbc.VitessPreparedStatement.setObject(VitessPreparedStatement.java:379)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setObject(HikariProxyPreparedStatement.java)
	at org.skife.jdbi.v2.ObjectArgument.apply(ObjectArgument.java:35)
	at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter$MyRewrittenStatement.bind(ColonPrefixNamedParamStatementRewriter.java:167)
	... 88 common frames omitted
```

**Comment by harshit-gangal** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3847#-:-LBKLLYr0M44igpzaoId:bnfp4nl)*

**Comment by acharis** [comment]
LGTM

**Pull request merged**
