### PR TITLE
Move vtCompose into own directory to avoid conflicting main() functions

### PR DESCRIPTION
**Pull request by JavierR14**
@systay detected that the main() function would conflict with the client.go main() when you tried to do `go build`. This no longer happens with vtcompose.go being in its own directory.

- `docker compose up -d` is still run from the compose directory and vtcompose.go still creates all required files in the compose directory (not the new vtcompose directory).

### CODE REVIEW

**Comment by jawabuu** [comment]
@JavierR14 Just taking a look at the recent compose example changes.
I beleieve a default docker-compose.yml file should be restored which will remove the need for golang dependency for beginners.
Do you still handle the use case of a user connecting to their existing database as was before?

**Comment by systay** [comment]
@jawabuu This PR is solving a problem that is stopping the code base from compiling fully, so I'm going to go ahead and merge this for now, even if there is an active discussion here. I'm doing this because this discussion doesn't seem to be directly related to the moving of the `main` method here.

You are, of course, welcome to continue the discussion here, but maybe it'd be more visible to other interested if you raised an issue instead?

**Comment by jawabuu** [comment]
@systay Well received.

**Comment by systay** [comment]
Thanks for understanding. How about here? 
https://github.com/vitessio/vitess/issues/new/

**Pull request merged**
