### PR TITLE
Pulling bootstrap resources from vitess-resources

### PR DESCRIPTION
**Pull request by shlomi-noach**
A new repository, https://github.com/vitessio/vitess-resources, was created so as to mirror various resources needed by the Vitess build/bootstrap process. Instead of relying on those resources to exists in their original locations (e.g. `apache.,org`), we put them in https://github.com/vitessio/vitess-resources and fetch it from there.

This is an ongoing process; we'll iterate some resources one by one.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
The downside to this approach is that if we change version, e.g. `etcd` version, we need to go fetch the relevant binaries for that version (`limux`, `darwin`, `amd64`, `arm64`), so it's  abit of a manual process.

**Comment by shlomi-noach** [comment]
Hmmm, an alternative to storing the files in `git`, is to create a dummy "release" in this repo, and upload all relevant files as artifacts.

**Comment by shlomi-noach** [comment]
ok, experimental: https://github.com/vitessio/vitess-resources/releases/tag/v1.0

**Comment by shlomi-noach** [comment]
Getting the artifacts from https://github.com/vitessio/vitess-resources/releases/edit/v1.0 makes more sense to me than getting them from `git`.

Actually, we can also create a `resources` release in this very repo. We don't need an external repo.

**Comment by shlomi-noach** [comment]
For now, let;s stick with https://github.com/vitessio/vitess-resources

with the exception of `chrome` extensions, all `bootstrap.sh` dependencies are now moved to https://github.com/vitessio/vitess-resources, making the build process more reliable, as we control where the artifacts are.

**Review by deepthi — APPROVED** [review]
I like it!

**Comment by shlomi-noach** [comment]
Leaving open just for a while longer in case anyone sees a problem with this approach.

**Pull request merged**
