### PR TITLE
jdbc: detect unions starting with parens as select-or-show statements

### PR DESCRIPTION
**Pull request by acharis**
the driver currently routes a statement like:
`(select id from foo) union all (select id from bar)`
to executeUpdate, which can't return a result set, instead of execute, which can.

Signed-off-by: Alex Charis <acharis@hubspot.com>

### CODE REVIEW

**Comment by harshit-gangal** [comment]
That check was taken from connector-j. Checking for open brackets does not ensure it will be a select query.
Can you see if you can get rid of open braces?

**Comment by acharis** [comment]
Can you link to the mysql-connector-j code where you got that?
And, in fact, looking at the grammar in https://github.com/vitessio/vitess/blob/master/go/vt/sqlparser/sql.y
I think starting with a parenthesis _does_ in fact ensure that it is a select. I'm, of course, happy to be shown I'm wrong.

The larger issue, I think, is that we're not dealing with leading comments, afaict.

**Comment by harshit-gangal** [comment]
Check this.

https://github.com/mysql/mysql-connector-j/blob/release/5.1/src/com/mysql/jdbc/StatementImpl.java#L769

**Comment by acharis** [comment]
Alright, checked.

The mysql-connector-j code you've linked to is actually pretty solid:
They skip leading comments, find the first alpha character and uppercase it, and check for equality with 'S'.
_Then_ they call this `maybeSelect` and actually use that information in the negative, which is to say: they draw the conclusion that the query under consideration is definitely _not_ a select by looking at `!maybeSelect`.

The code previous to this PR does the following:
It skips whitespace, then takes the next character and checks it case-insensitively for equality with 'S'. And _then_ it uses that information definitively to decide whether to `executeQuery` or `executeUpdate`.

So that is pretty deficient.

But looking again at the mysql-connector-j code has inspired me to add the comment skipping bits, which I initially hesitated to do for performance reasons. I'll update this PR with that "soon".

**Comment by harshit-gangal** [comment]
This looks good. 
Could you please add some tests here : https://github.com/vitessio/vitess/blob/master/java/jdbc/src/test/java/io/vitess/util/StringUtilsTest.java

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3894#-:-LCowBxT4RSnCd5ZHvvD:bex9u2)*

**Comment by harshit-gangal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3894#-:-LCp5POZ6hX4dxFsttEs:bnfp4nl)*

**Comment by acharis** [comment]
force pushed here as well to resolve conflicts

**Pull request merged**
