### PR TITLE
Online DDL declarative migrations now use schemadiff, removing tengo

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

Now that #9719 is merged, we switch `-declarative` migrations from using `tengo` into using `schemadiff`. In this change:

- `executor.go` now uses `schemadiff`'s declarative diff based on `SHOW CREATE TABLE` output from original and ghost tables
- There is one less table to create in the interim of the process
- We utilize existing Vitess DB connections, and remove use of `sqlx`
- No need to create a temporary account
- No longer using `tengo` library
- Removed some boilerplate parsing code
- Removed many package dependencies (see `go.mod`)

Tests-wise, the PR remains covered by `onlineddl_declarative`.

## Related Issue(s)

- #9719 
- #6926 

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

**Review by vmg — COMMENTED** [review]
This is, again, great just from the sheer amount of dependencies it removes. I don't have a good enough understanding of the subsystem to approve the changes so I'm basically giving my thumbs up to the `go.mod` diff. :)

**Comment by shlomi-noach** [comment]
call for review :pray:

**Review by harshit-gangal — APPROVED** [review]

**Comment by shlomi-noach** [comment]
Tracking issue: https://github.com/vitessio/vitess/issues/10203

**Pull request merged**
