### PR TITLE
V3 conversion to srvtopo interfaces.

### PR DESCRIPTION
**Pull request by alainjobart**
@sougou this is how the conversion to the new srvtopo stuff would work. I added a bunch of '...2' methods to show the difference. I only implemented StreamExecute so far, it's a good subset of the functionality.

It may conflict with your other PR a bit, but probably not significantly.

Also, it will probably trigger some other cleanup in a few places, not sure yet.

### CODE REVIEW

**Comment by alainjobart** [comment]
@sougou just looked at your other PR, I see you changed a few things that I also changed, but I don't see anything too bad.

I think the Ksid type you have should be moved to srvtopo, and used from there. We probably want to rename it too, since it can be either ksids or keyrange. That way I can pass it directly to the Resolve methods, instead of having to unpack them. Or I could use the vindexes.Ksid type in srvtopo, if the dependency is OK. I kinda wanted to keep them separate.

**Comment by sougou** [comment]
Currently `Ksid` and `Ksids` are a vindex-only concept. I'm wondering if there's benefit to pushing it down to srvtopo.
If we do, I'm guessing the filtered replication code will benefit because it also uses the vindex.
If we don't, then vindex can redefine these structs without having far-reaching effects.

I'm leaning towards keeping these within vindex. What do you think?

**Comment by sougou** [comment]
LGTM
I just realize that this is going to hugely conflict with my v3 refactor. Maybe you submit it and I'll deal with the fallout.

**Comment by alainjobart** [comment]
You probably should do your work first, and I'll adapt mine. I'm short on time to work on this, and this would drag for a bit, blocking you. So go ahead, I'll resume my work on this when you're not changing the API too much.

**Comment by alainjobart** [comment]
This is obsolete now, closing it.

**Pull request closed without merging**
