### PR TITLE
Tablet throttler: (feature flagged) get remote tablets metrics from Realtime Stats

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

This is a design change for how the tablet throttler collects metrics of remote tablets. Specifically, how a shard's `PRIMARY` tablet collects the data from the rest of the shard.

Commonly (and by default) the information the throttler gathers is the replication lag metric. Up till now, the throttler contacted the rest of the shards tablets via HTTP and hit their `/throttler/check-self` API call.

This PR now makes use of `RealtimeStats`, which in an already existing mechanism in `vitess` that uses the stream API, and lets you listen on health-status events that are published by all tablets. The `TxThrottler` uses RealtimeStats to gather replication lag, and now the tablet throttler, too, with some nuances.

As of this PR:

- `RealtimeStats` include two new fields `ThrottlerMetric` and `ThrottlerMetricError`.
- It also includes a `ThrottlerReplicationLagSeconds` which right now is not populated, but I have plan for the future so I added it here. Ignore it.
- `state_manager` checks a throttler's self-metric, and publishes the result in `RealtimeStats`.
- Note that a throttler metric error is distinguishable from just a health error. The throttler having an error with some metrics should not and will not cause the entire `HealthCheck` to be in error.
- All tablets thus push their throttler's collected metrics, periodically, in `--health_check_interval` interval.
- A new feature flag, `--feature-throttler-read-realtime-stats` (default: `false`), determines whether the `PRIMARY` throttler reads metrics by hitting the tablets HTTP API (the old behavior), or whether it listens for health checks and realtime stats by subscribing to the stream API.

Notes:

- To use this new functionality you probably want `--health_check_interval` to be low, as low as `1s`.
- Rollout bottoms-up. Only enable `--feature-throttler-read-realtime-stats` on the `PRIMARY` once all the replicas have this change.

The overall architecture of the tablet throttler remains pretty much the same, I made minimal changes to enable the new functionality. Baby steps. In the future, we can simplify the tablet throttler's architecture (e.g. getting read of the cluster probes, which right now still exist and are dormant, but still serve a purpose).

## Related Issue(s)

This is an experimental PR. No linked issue at this time.

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by harshit-gangal** [comment]
How about primary always using StreamHealth API and if it sees throtter metrics it continues using that for that tablet otherwise switches to Http API for that tablet?

**Comment by shlomi-noach** [comment]
> How about primary always using StreamHealth API and if it sees throttler metrics it continues using that for that tablet otherwise switches to Http API for that tablet?

Interesting suggestion. It would have to be on per-tablet basis, because one `REPLICA` tablet might be updated, another wouldn't. Also, A tablet might be downgraded. So to make this happen we'd need to track "was there a _recent_ tablet heath entry for this specific tablet, and if not, we should hit the HTTP API". Does that sound right?

**Comment by harshit-gangal** [comment]
> > How about primary always using StreamHealth API and if it sees throttler metrics it continues using that for that tablet otherwise switches to Http API for that tablet?
> 
> Interesting suggestion. It would have to be on per-tablet basis, because one `REPLICA` tablet might be updated, another wouldn't. Also, A tablet might be downgraded. So to make this happen we'd need to track "was there a _recent_ tablet heath entry for this specific tablet, and if not, we should hit the HTTP API". Does that sound right?

that's the thought. 

This can make code more complex. Is it worth it for this case, that part I'm not sure. But, it just eases the adoption.

**Comment by shlomi-noach** [comment]
Question: after I `Subscribe` here:
```go
		healthCheck := discovery.NewHealthCheck(ctx, discovery.DefaultHealthCheckRetryDelay, discovery.DefaultHealthCheckTimeout, throttler.ts, throttler.cell, strings.Join(throttler.knownCells, ","))
		healthCheckCh = healthCheck.Subscribe()
```

What happens if later on, new tablets are added to the topology? Do es my subscription include the stats for those new tablets?

**Comment by harshit-gangal** [comment]
> ```go
> NewHealthCheck
> ```

There is is topowatcher in there. That keeps loading the cells-tablet view which included addition and removal of tablets.

**Comment by shlomi-noach** [comment]
I have a local change that removes `--feature-throttler-read-realtime-stats`. As soon as the primary tablet sees incoming stats for a given probe (ie remote tablet) it stops actively probing that tablet.

I do see a problem with this implementation: it's really important for `--health_check_interval` to be reasonable. Because if it's `10s` or if it's `1s` make a ton of difference throttler-resolution -wise. But both will cause the throttler to avoid actively probing the remote tablet.
As result, if you deploy the change, and your `--health_check_interval` is high, then the throttler has poor granularity and will not work as expected. And, because we remove `--feature-throttler-read-realtime-stats`, you override the default high-frequency throttler rate.

**Comment by shlomi-noach** [comment]
A flag-free implementation is in https://github.com/vitessio/vitess/pull/13034

**Comment by hkdsun** [comment]
> As result, if you deploy the change, and your --health_check_interval is high, then the throttler has poor granularity and will not work as expected. And, because we remove --feature-throttler-read-realtime-stats, you override the default high-frequency throttler rate.

That sounds like a good reason to keep the flag around and have users enable it once they've read the disclaimer of "make sure your `--health_check_interval` is low enough for tablet throttling to behave well", or produce a warning if misconfigured, or something such.

**Comment by shlomi-noach** [comment]
We're not going to pursue this path. Instead, we will convert throttler's HTTP calls with RPC calls.

**Pull request closed without merging**
