### PR TITLE
[vtctld] Migrate GetSrvKeyspace as GetSrvKeyspaces in VtctldServer

### LINKED ISSUE #7679: Migrate GetSrvKeyspace to VtctldServer

### PR DESCRIPTION
**Pull request by ajm188**
## Description

This PR migrates the `GetSrvKeyspace` command and rpc to the newer `VtctldServer`, renamed as `GetSrvKeyspaces`. Changes:
* Support multiple cells at once.
* Return a mapping of cell => srvkeyspace, rather than a single srvkeyspace
* Support specifying no cells at all, in which case we look up all cells in the topo on behalf of the caller and return a full mapping.

## Related Issue(s)

- Closes #7679 

## Checklist
- [ ] Should this PR be backported? **No**
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Deployment Notes

<details>
<summary>Example usage:</summary>

```
❯ vtctldclient --server "localhost:15999" GetSrvKeyspaces commerce zone1
{
  "zone1": {
    "partitions": [
      {
        "served_type": 1,
        "shard_references": [
          {
            "name": "0"
          }
        ]
      },
      {
        "served_type": 2,
        "shard_references": [
          {
            "name": "0"
          }
        ]
      },
      {
        "served_type": 3,
        "shard_references": [
          {
            "name": "0"
          }
        ]
      }
    ]
  }
}
❯ vtctldclient --server "localhost:15999" GetSrvKeyspaces commerce zone2
{
  "zone2": null
}
❯ vtctldclient --server "localhost:15999" GetSrvKeyspaces commerce
{
  "zone1": {
    "partitions": [
      {
        "served_type": 1,
        "shard_references": [
          {
            "name": "0"
          }
        ]
      },
      {
        "served_type": 2,
        "shard_references": [
          {
            "name": "0"
          }
        ]
      },
      {
        "served_type": 3,
        "shard_references": [
          {
            "name": "0"
          }
        ]
      }
    ]
  }
}
❯ vtctldclient --server "localhost:15999" GetSrvKeyspaces -h
Usage:
   GetSrvKeyspaces <keyspace> [<cell> ...] [flags]

Flags:
  -h, --help   help for GetSrvKeyspaces

Global Flags:
```

</details>

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [x]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Review by doeg — APPROVED** [review]
Thanks!!! 🌻

**Comment by ajm188** [comment]
Latest commit reimplementing the legacy command using the new implementation:

<details>
<summary>Before</summary>

```
❯ vtctlclient -server "localhost:15999" GetSrvKeyspace zone1 commerce
{
  "partitions": [
    {
      "served_type": 1,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": [
      ]
    },
    {
      "served_type": 2,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": [
      ]
    },
    {
      "served_type": 3,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": [
      ]
    }
  ],
  "sharding_column_name": "",
  "sharding_column_type": 0,
  "served_from": [
  ]
}
```

</details>

<details>
<summary>After</summary>

```
❯ vtctlclient -server "localhost:15999" GetSrvKeyspace zone1 commerce
{
  "partitions": [
    {
      "served_type": 1,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": [
      ]
    },
    {
      "served_type": 2,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": [
      ]
    },
    {
      "served_type": 3,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": [
      ]
    }
  ],
  "sharding_column_name": "",
  "sharding_column_type": 0,
  "served_from": [
  ]
}
```

</details>

**Review by doeg — APPROVED** [review]
Love to reimplement a legacy command using a new implementation. Still looks good to me! 

@deepthi @rohit-nayak-ps would you mind looking at this one too, when you get a chance? :D

**Review by deepthi — APPROVED** [review]
Nice work! You always do such a nice job with comments and unit tests :100:

**Pull request merged**
