### PR TITLE
VerticalSplitClone no longer supports -min_rdonly_healthy_tablets

### PR DESCRIPTION
**Pull request by chrisrgithub**
...but still allows -min_rdonly_tablets.  Changed it to that.

### CODE REVIEW

**Comment by deepthi** [comment]
Can you fix the DCO? The Details link will tell you what to do.
If there's an error you observed that this PR fixes, please include the error message in the description.

**Comment by dkhenry** [comment]
@chrisrgithub We can't approve this until the DCO is addressed.

**Comment by deepthi** [comment]
I believe this file has been added to the wrong place. It should be a change to the existing file of that name in examples/helm.

**Comment by chrisrgithub** [comment]
I have modified this branch locally to correct the file placement.  Will confer with Deepthi on how to re-apply and modify or restart this PR.

**Comment by chrisrgithub** [comment]
Deepthi states that this PR will get updated correctly, and it appears so.

**Pull request merged**
