### PR TITLE
Add datadog plugin for tracing

### PR DESCRIPTION
**Pull request by kalfonso**
Signed-off-by: Karel Alfonso Sague <kalfonso@squareup.com>

### CODE REVIEW

**Comment by kalfonso** [comment]
@systay you might be familiar with this change

**Comment by tirsen** [comment]
I think we've had different opinions on dependencies on these commercial third parties. That said DataDog is pretty popular and if you don't use it there is only a tiny bit of overhead for the dependency.

**Comment by deepthi** [comment]
> I think we've had different opinions on dependencies on these commercial third parties. That said DataDog is pretty popular and if you don't use it there is only a tiny bit of overhead for the dependency.

@kalfonso FTR, can you document the change in binary sizes /docker images here? 
Also are there any license implications from the packages we are importing?

**Comment by derekperkins** [comment]
What about hiding these behind build tags?

**Comment by sougou** [comment]
I took a look at the implementation. Looks lightweight, and it ironically depends on opentracing, which we already depend on.

So, lets move ahead with this. If this becomes a problem in the future, we can reconsider our options.

**Pull request merged**
