### PR TITLE
sqlparser: support stream specific columns

### PR DESCRIPTION
**Pull request by derekperkins**
## Description
Enable selecting specific columns instead of only `stream * from tbl`

## Related Issue(s)
https://github.com/vitessio/vitess/issues/6306

## Checklist
- [x] Should this PR be backported? - hoping to get it into v13
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by GuptaManan100** [comment]
Yes, there is a circular dependency, unfortunately right now there is no good way to fix this other than delete those lines from the files (yes the ones which will be generated again and overwritten).

**Review by GuptaManan100 — APPROVED** [review]
LGTM!

**Comment by derekperkins** [comment]
Digging deeper, this doesn't provide much of a win because the whole message row is still loaded into memory, as the message manager can't guarantee that nobody will call `stream *`. I'll revisit this later with another proposal, probably something around setting visible/invisible columns in the table comments.

**Comment by derekperkins** [comment]
Thanks to @GuptaManan100 and @systay for helping me debug the ast setup

**Pull request closed without merging**
