### PR TITLE
Online DDL: improved row estimation via ANALYE TABLE with --analyze-table strategy flag

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

In Online DDL `ALTER TABLE` migrations, Vitess estimates the number of table rows via `SHOW TABLE STATUS`. This number can be very skewed. As the migration runs, Vitess indicates its `progress` in `_vt.schema_migrations` as a `[0..100]` value. This column is also exposed in `SHOW VITESS_MIGRATIONS` output.

The problem is that `table_rows` can be so skewed that:

- At some stage `rows_copied` is actually _higher_ than `table_rows`. The migration shows `99%` or `100%` for hours until it actually completes.
- Or, the migration suddenly terminates at `75%`.

This happens because the estimated number of rows can be very much higher or very much lower than the actual number of rows in the table. The user experience is poor as the user is never sure what the actual status is.

This PR offers the following two mitigations:

1. Use of `ANALYZE TABLE`. We introduce a new voluntary DDL strategy flag: `--analyze-table`. When given, Vitess will run an `ANALYZE TABLE` on the original table before starting the migration. This is then followed by the same existing `SHOW TABLE STATUS` command that gets the estimated number of table rows. An `ANALYZE TABLE` execution improves the statistics. The number will still be skewed, but usually closer to the truth. **NOTE** this runs on the `PRIMARY` tablet. Normally `ANALYZE TABLE` commands are non-blocking, and can operate concurrently to `INSERT/DELETE/UPDATE` commands. But under very heavy load it is known to cause interference.
2. When `rows_copied` exceeds `table_rows`, Vitess automatically increases `table_rows` value to match `rows_copied`. This is just a cosmetic fix.

Flag to be documented.

## Related Issue(s)

- https://github.com/vitessio/vitess/issues/13437
- #6926 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Review by mattlord — APPROVED** [review]
LGTM. Could you please create a brief issue (largely copy and paste from the description) and link to the docs PR?

IMO, this has long outlived its usefulness https://github.com/vitessio/vitess/issues/6926 (I know you mentioned that as the linked issue).

**Comment by shlomi-noach** [comment]
Created issue: https://github.com/vitessio/vitess/issues/13437

**Comment by shlomi-noach** [comment]
Docs PR: https://github.com/vitessio/website/pull/1525

**Review by GuptaManan100 — APPROVED** [review]
LGTM

**Pull request merged**
