### PR TITLE
[WIP] - Removes do not replicate functionality - Do not merge yet - Requires Discussion

### PR DESCRIPTION
**Pull request by rafael**
# Description

The feature on this PR creates a file on disk whenever a tablet explicitly stops replication. If this file is present on disk, vttablet won't start replication on boot. It seems that it serves as a guardrails where the vttablet will remember, even after a restart that it told to stop replication. This is the context I was able to grab from reading the code, but I would like to know if folks have more information on why this was added. I might be missing some context here. 

It seems that the intent of this feature is to protect from certain edge cases. From conversation with Peter in Slack, one of those edge cases is when a tablet restarts and there is an on-going EmergencyReparentShard. This feature prevents the vttablet that restarted to try to fix replication.

However, this adds some extra complexity to operators of Vitess. This is something that is very deep in the codebase and it's not obvious that Vitess is doing this. At Slack, we were completely unaware and it bite us in an unexpected way. 

For reasons that don't matter for this discussion, we had a shard that all the replicas had this file on disk. On this tablets the file was created six months ago. This seems like the feature is not working as expected in certain scenarios. However, the shard was healthy and replicating correctly. We were performing an operation that required to restart mysql. After doing this, none of these tablets came up replicating and it was not obvious why `vttablet` was not restarting replication. For context, we rely on this. We run mysql with `skip-slave-start`. 

We could invest time in making sure this is bullet proof, but I would like to argue that is not worth it. I think enforcing this in a way that is not best-effort, will be complicated. For instance, take this example:

1. One of the replicas is partitioned from vtctld when `EmergencyReparentShard`. In this case it will completely miss the signal to `StopReplicationAndGetStatus` and an operator will still have to intervene to fix that replica. 

So I think it is a fair expectation to operators that you have to monitor if a tablet is in a bad state. I think that should cover the cases that this trying to protect from. I think the most important invariant is that the old master is not going to take traffic and that vtgates won't route to it. I think Vitess already goes at great length to guarantee that. In my view that should be sufficient. 

So overall, to me it seems that keeping this simpler would be better for Vitess users.

### CODE REVIEW

**Comment by PrismaPhonic** [comment]
@rafael why do you want to remove this?

**Comment by rafael** [comment]
I don't know why CI is so unhappy though 😅

**Comment by enisoc** [comment]
> It seems that it serves as a guardrails where the vttablet will remember, even after a restart that it told to stop replication. This is the context I was able to grab from reading the code, but I would like to know if folks have more information on why this was added.

You are correct. We encountered this problem at YouTube, where a tablet restart mistakenly caused replication to resume. In that case, the tablet had been stopped by SplitDiff, so the resumption of replication caused the diff to fail. @deepthi Is the new VDiff also going to require a tablet with replication stopped for a long time?

As @PrismaPhonic mentioned, we are hoping to rely on this feature for the new, safer EmergencyReparentShard.

> One of the replicas is partitioned from vtctld when EmergencyReparentShard. In this case it will completely miss the signal to StopReplicationAndGetStatus and an operator will still have to intervene to fix that replica.

In this case, ERS will know to stop and do nothing, so it preserves the safety goal we defined: we should only take automatic action if we can guarantee we aren't going to be the cause of data loss. Otherwise we require user intervention to override the appropriate safety check.

> I think the most important invariant is that the old master is not going to take traffic and that vtgates won't route to it.

Ensuring replication is stopped everywhere is the key to our strategy for preventing a partitioned master from accepting writes. We configure the master to require at least one semi-sync ACK, and disallow fallback to async. If we can talk to all replicas and guarantee they are stopped, we can guarantee the master is not accepting writes, even if we can't talk to the master itself. If a replica we stopped might restart and resume replicating at any time, it defeats this protection and the master could begin accepted writes again on the other side of a partition from us, causing split brain.

**Comment by PrismaPhonic** [comment]
I agree with Anthony's points and would echo those. My sense is that it actually is a better approach for us to try to make this handle the edge case that caused the state your team experienced. I think there's still a very valid use for this feature existing, and we shouldn't throw the baby out with the bathwater.

I would agree that it is important for a human operator to monitor when a tablet is in a bad state - but that wouldn't necessarily provide the same level of protection. A tablet restarting in the middle of an ERS likely isn't something a human operator can catch quickly enough to handle, and this could cause unintended side effects with ERS that I think could be even worse than the alternative.

**Comment by rafael** [comment]
> Ensuring replication is stopped everywhere is the key to our strategy for preventing a partitioned master from accepting writes. We configure the master to require at least one semi-sync ACK, and disallow fallback to async.

This is true for as well. However, what I'm trying to understand is whether or not this feature will really help with that. It's seems to me that it's working on a best effort way and I'm not seeing a clear way to make it bullet proof with the current design. 

Could you share how this could protect from the scenario where ERS is in the process of stopping replication and the existent master comes back from being partitioned?  It seems that a split brain like the one described could occur as well. 

The other example I described seems to be an issue too (replica also being partitioned while ERS is running). 

My initial thoughts is that to really prevent from this, we would need to re-think the approach we are taking to solve this problem.

**Comment by rafael** [comment]
For context, this is what I refer to best effort: https://github.com/tinyspeck/vitess/blob/master/go/vt/wrangler/reparent.go#L910 

It doesn't seem to fail if  `StopSlave` fails there. However @sougou  mention to me that you all are in the process of rewriting all this. I think that might be the context I'm missing.

**Comment by enisoc** [comment]
> Could you share how this could protect from the scenario where ERS is in the process of stopping replication and the existent master comes back from being partitioned?

We won't assume the master is blocked from accepting writes until we finish stopping replication on all other tablets. As long as we can be sure no tablet we already stopped will restart on its own, we know that no one is left to ACK after this point.

> The other example I described seems to be an issue too (replica also being partitioned while ERS is running).

This is an issue for availability since it will prevent ERS from succeeding, but we don't believe it's an issue for consistency. We plan to have the new ERS prioritize consistency by default. Users will need to break glass (e.g. add override flags) to make ERS lose data if they choose to do so in the name of availability.

> My initial thoughts is that to really prevent from this, we would need to re-think the approach we are taking to solve this problem. [...] you all are in the process of rewriting all this. I think that might be the context I'm missing.

Sorry for not making this clear. We are indeed in the process of rewriting ERS (#6206). You're right that this edge case is not applicable to the current ERS because it is best-effort. The new ERS is designed with stronger guarantees, and we were planning to rely on this "do not replicate" feature to make that possible.

If a file is a bad way to go, maybe we should look into moving this to the tablet record?

**Comment by rafael** [comment]
@enisoc - Ah thanks for all this context. Given the stronger guarantees in the new design, this makes sense to me now. I agree with both of you, with those changes in mind, I think we should focus on making this more robust. 

I'm going to close this and bounce some ideas with y'all so we create an issue to just focus on that.

**Pull request closed without merging**
