### PR TITLE
using import (), remove redundant code

### PR DESCRIPTION
**Pull request by xichengliudui**

### CODE REVIEW

**Comment by sougou** [comment]
Unfortunately, this is generated code by the proto compiler. We can't change the formatting.
All files that are `.pb.go` are generated.

**Comment by xichengliudui** [comment]
ok，thanks

**Comment by deepthi** [comment]
The one change from this PR that can be done is to the doc / comments.
`// TUPLE specifies a a tuple. `
Any changes should go into the .proto file. For instance, the source for this go file is at `/vitess.io/vitess/proto/query/query.proto`. You would edit that, and run `make proto` from the root directory. That will regenerate the go file, and then you would put both files into your commit.

**Comment by xichengliudui** [comment]
@deepthi  Sorry, I did not find this absolute path, may I ask what is wrong? I want to fix them.

**Comment by deepthi** [comment]
> @deepthi Sorry, I did not find this absolute path, may I ask what is wrong? I want to fix them.
The file is at https://github.com/vitessio/vitess/blob/master/proto/query.proto

**Pull request closed without merging**
