### PR TITLE
Per workload TxThrottler metrics

### PR DESCRIPTION
**Pull request by ejortegau**
## Description
With these changes, TxThrottler metrics for requests received and requests throttled now include a label to identify workload associated with the request.

This allows to keep track of statistics about how much each individual workload gets throttled.

## Related Issue(s)

https://github.com/vitessio/vitess/issues/13524

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

## Deployment Notes

N/A

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
LGTM

**Comment by shlomi-noach** [comment]
Please elt me know when changes are complete so we can review in a single sweep 🙏

**Comment by shlomi-noach** [comment]
I can trigger any failing job - don't worry about it.

**Comment by ejortegau** [comment]
This PR is ready and all CI is passing. @shlomi-noach, you already approved, but perhaps want to take a second look? Other than that, I would love 👀  from one of the other reviewers so we can move forward with merging it.

**Review by GuptaManan100 — APPROVED** [review]
LGTM!

**Pull request merged**
