### PR TITLE
tracking failed check runs

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

This _meta_ PR adds a CI workflow that trakcs failed check runs, in an effort to get a hold on our flaky tests and crunch some numbers.

The flow is:

- every 10 minutes
- check GitHub API for failed job runs
- parse, formalize
- append to a file `.metrics/workflow-failures` in the `metrics` branch
- we can later analyze that file

Note that I chose to keep the information within this repo; this both simplifies a few things (like write credentials) as well as ensures the data is "ours". To this effect I created the "magic" branch `metrics`. This branch should not be merged or deleted. The specific file `.metrics/workflow-failures` is created empty and will be updated by the workflow job.

In a later PR we can further analyze the file and possibly get some graphs.

## Related Issue(s)

#7207 

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build 
- [ ]  VTAdmin

No component is affected. This is a meta change

### CODE REVIEW

**Comment by shlomi-noach** [comment]
This PR updates a file in the `metrics` branch of this (`vitessio/vitess`) repo. The file is `.metrics/workflow-failures`, which only exists in `metrics` branch.

Example generated file contents:
```
2021-01-05T18:16:41Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/464066047
2021-01-05T18:16:41Z,cluster_initial_sharding_multi,https://github.com/planetscale/vitess/actions/runs/464066044
2021-01-05T18:16:41Z,docker_test_1,https://github.com/planetscale/vitess/actions/runs/464066053
2021-01-05T18:16:41Z,endtoend,https://github.com/planetscale/vitess/actions/runs/464066050
2021-01-05T18:16:41Z,local_example,https://github.com/planetscale/vitess/actions/runs/464066057
2021-01-05T18:16:41Z,region_example,https://github.com/planetscale/vitess/actions/runs/464066052
2021-01-05T18:16:41Z,unit,https://github.com/planetscale/vitess/actions/runs/464066051
2021-01-05T18:16:41Z,unit_race,https://github.com/planetscale/vitess/actions/runs/464066048
2021-01-05T20:28:54Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/464338525
2021-01-06T07:23:56Z,golangci-lint,https://github.com/planetscale/vitess/actions/runs/465483001
2021-01-06T07:23:56Z,unit,https://github.com/planetscale/vitess/actions/runs/465482995
2021-01-06T07:23:56Z,unit_race,https://github.com/planetscale/vitess/actions/runs/465482996
2021-01-06T07:43:51Z,unit,https://github.com/planetscale/vitess/actions/runs/465517973
2021-01-06T07:43:51Z,unit_race,https://github.com/planetscale/vitess/actions/runs/465517976
2021-01-06T11:26:56Z,unit,https://github.com/planetscale/vitess/actions/runs/465956144
2021-01-06T11:26:56Z,unit_race,https://github.com/planetscale/vitess/actions/runs/465956141
2021-01-06T12:13:41Z,unit_race,https://github.com/planetscale/vitess/actions/runs/466047499
2021-01-06T12:13:41Z,Unit Test (percona56),https://github.com/planetscale/vitess/actions/runs/466047501
2021-01-06T12:49:53Z,docker_test_3,https://github.com/planetscale/vitess/actions/runs/466118431
2021-01-06T14:26:04Z,unit_race,https://github.com/planetscale/vitess/actions/runs/466317669
2021-01-06T17:07:23Z,unit_race,https://github.com/planetscale/vitess/actions/runs/466673883
2021-01-06T21:53:33Z,Unit Test (mariadb101),https://github.com/planetscale/vitess/actions/runs/467242973
2021-01-07T01:41:09Z,unit,https://github.com/planetscale/vitess/actions/runs/467647729
2021-01-07T02:23:16Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/467720488
2021-01-07T02:23:16Z,cluster_initial_sharding_multi,https://github.com/planetscale/vitess/actions/runs/467720514
2021-01-07T02:23:16Z,docker_test_1,https://github.com/planetscale/vitess/actions/runs/467720495
2021-01-07T02:23:16Z,docker_test_2,https://github.com/planetscale/vitess/actions/runs/467720484
2021-01-07T02:23:16Z,docker_test_3,https://github.com/planetscale/vitess/actions/runs/467720494
2021-01-07T02:23:16Z,e2e_race,https://github.com/planetscale/vitess/actions/runs/467720498
2021-01-07T02:23:16Z,endtoend,https://github.com/planetscale/vitess/actions/runs/467720493
2021-01-07T02:23:16Z,golangci-lint,https://github.com/planetscale/vitess/actions/runs/467720490
2021-01-07T02:23:16Z,local_example,https://github.com/planetscale/vitess/actions/runs/467720496
2021-01-07T02:23:16Z,local_example,https://github.com/planetscale/vitess/actions/runs/467720497
2021-01-07T02:23:16Z,region_example,https://github.com/planetscale/vitess/actions/runs/467720491
2021-01-07T02:23:16Z,unit,https://github.com/planetscale/vitess/actions/runs/467720500
2021-01-07T02:23:16Z,unit_race,https://github.com/planetscale/vitess/actions/runs/467720487
2021-01-07T06:30:33Z,endtoend,https://github.com/planetscale/vitess/actions/runs/468135237
2021-01-07T06:30:33Z,unit,https://github.com/planetscale/vitess/actions/runs/468135229
2021-01-07T06:30:33Z,unit_race,https://github.com/planetscale/vitess/actions/runs/468135227
2021-01-07T06:30:34Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/468135242
2021-01-07T07:40:48Z,unit_race,https://github.com/planetscale/vitess/actions/runs/468267597
2021-01-07T08:49:22Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/468401028
2021-01-07T08:49:22Z,e2e_race,https://github.com/planetscale/vitess/actions/runs/468401033
2021-01-07T08:49:22Z,unit,https://github.com/planetscale/vitess/actions/runs/468401026
2021-01-07T08:49:23Z,endtoend,https://github.com/planetscale/vitess/actions/runs/468401040
2021-01-07T08:49:23Z,unit_race,https://github.com/planetscale/vitess/actions/runs/468401035
2021-01-07T08:55:41Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/468413995
2021-01-07T08:55:41Z,e2e_race,https://github.com/planetscale/vitess/actions/runs/468414001
2021-01-07T08:55:41Z,endtoend,https://github.com/planetscale/vitess/actions/runs/468413997
2021-01-07T08:55:41Z,unit,https://github.com/planetscale/vitess/actions/runs/468414007
2021-01-07T08:55:41Z,unit_race,https://github.com/planetscale/vitess/actions/runs/468414006
2021-01-07T13:13:36Z,Cluster (11),https://github.com/planetscale/vitess/actions/runs/468954746
2021-01-07T13:13:36Z,Cluster (12),https://github.com/planetscale/vitess/actions/runs/468954722
2021-01-07T13:13:36Z,Cluster (13),https://github.com/planetscale/vitess/actions/runs/468954749
2021-01-07T13:13:36Z,Cluster (14),https://github.com/planetscale/vitess/actions/runs/468954736
2021-01-07T13:13:36Z,Cluster (15),https://github.com/planetscale/vitess/actions/runs/468954755
2021-01-07T13:13:36Z,Cluster (16),https://github.com/planetscale/vitess/actions/runs/468954727
2021-01-07T13:13:36Z,Cluster (17),https://github.com/planetscale/vitess/actions/runs/468954748
2021-01-07T13:13:36Z,Cluster (19),https://github.com/planetscale/vitess/actions/runs/468954729
2021-01-07T13:13:36Z,Cluster (20),https://github.com/planetscale/vitess/actions/runs/468954740
2021-01-07T13:13:36Z,Cluster (21),https://github.com/planetscale/vitess/actions/runs/468954744
2021-01-07T13:13:36Z,Cluster (22),https://github.com/planetscale/vitess/actions/runs/468954738
2021-01-07T13:13:36Z,Cluster (23),https://github.com/planetscale/vitess/actions/runs/468954756
2021-01-07T13:13:36Z,Cluster (24),https://github.com/planetscale/vitess/actions/runs/468954758
2021-01-07T13:13:36Z,Cluster (26),https://github.com/planetscale/vitess/actions/runs/468954742
2021-01-07T13:13:36Z,Cluster (27),https://github.com/planetscale/vitess/actions/runs/468954739
2021-01-07T13:13:36Z,Unit Test (mariadb101),https://github.com/planetscale/vitess/actions/runs/468954751
2021-01-07T13:13:36Z,Unit Test (mariadb102),https://github.com/planetscale/vitess/actions/runs/468954721
2021-01-07T13:13:36Z,Unit Test (mariadb103),https://github.com/planetscale/vitess/actions/runs/468954725
2021-01-07T13:13:36Z,Unit Test (mysql57),https://github.com/planetscale/vitess/actions/runs/468954745
2021-01-07T13:13:36Z,Unit Test (mysql80),https://github.com/planetscale/vitess/actions/runs/468954720
2021-01-07T13:13:36Z,Unit Test (percona56),https://github.com/planetscale/vitess/actions/runs/468954731
2021-01-07T15:04:04Z,unit,https://github.com/planetscale/vitess/actions/runs/469197754
2021-01-07T19:07:30Z,unit,https://github.com/planetscale/vitess/actions/runs/469740044
2021-01-08T07:56:29Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/471150052
2021-01-08T07:56:29Z,unit,https://github.com/planetscale/vitess/actions/runs/471150061
2021-01-08T07:56:29Z,unit_race,https://github.com/planetscale/vitess/actions/runs/471150060
2021-01-08T08:33:08Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/471220757
2021-01-08T08:33:08Z,unit,https://github.com/planetscale/vitess/actions/runs/471220756
2021-01-08T08:33:08Z,unit_race,https://github.com/planetscale/vitess/actions/runs/471220753
2021-01-08T08:52:19Z,unit,https://github.com/planetscale/vitess/actions/runs/471258933
2021-01-08T08:52:19Z,unit_race,https://github.com/planetscale/vitess/actions/runs/471258946
2021-01-08T09:31:45Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/471340763
2021-01-08T09:42:46Z,unit,https://github.com/planetscale/vitess/actions/runs/471364482
2021-01-08T09:42:46Z,unit_race,https://github.com/planetscale/vitess/actions/runs/471364497
2021-01-08T09:50:31Z,unit_race,https://github.com/planetscale/vitess/actions/runs/471380867
2021-01-08T11:28:18Z,unit_race,https://github.com/planetscale/vitess/actions/runs/471582988
2021-01-08T11:49:41Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/471625552
2021-01-08T11:49:41Z,unit,https://github.com/planetscale/vitess/actions/runs/471625554
2021-01-08T20:52:45Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/472774892
2021-01-09T07:09:10Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/473674418
2021-01-09T07:09:10Z,unit,https://github.com/planetscale/vitess/actions/runs/473674419
2021-01-09T09:46:18Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/473841876
2021-01-09T09:46:18Z,golangci-lint,https://github.com/planetscale/vitess/actions/runs/473841873
2021-01-09T10:48:49Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/473908904
2021-01-09T15:22:33Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/474212876
2021-01-09T16:24:10Z,unit,https://github.com/planetscale/vitess/actions/runs/474283096
2021-01-09T16:24:10Z,unit_race,https://github.com/planetscale/vitess/actions/runs/474283101
2021-01-10T10:44:16Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/475464895
2021-01-10T10:46:27Z,cluster_endtoend,https://github.com/planetscale/vitess/actions/runs/475467262
```

**Comment by shlomi-noach** [comment]
ready for review

**Comment by shlomi-noach** [comment]
cc @deepthi

**Review by deepthi — APPROVED** [review]
:100:

**Comment by shlomi-noach** [comment]
It's working! Check out https://github.com/vitessio/vitess/blob/metrics/.metrics/workflow-failures

Now, e.g. how to analyze most recent `100` failures:

```shell
$ curl -L -s 'https://github.com/vitessio/vitess/raw/metrics/.metrics/workflow-failures' | tail -100 | awk -F "," '{print $2}' | sort | uniq -c
      2 check_formatting
      2 check_make_parser
      2 check_make_visitor
      2 Cluster (11)
      4 Cluster (12)
      2 Cluster (13)
      3 Cluster (14)
      2 Cluster (15)
      2 Cluster (16)
      5 Cluster (17)
      2 Cluster (18)
      2 Cluster (19)
      2 Cluster (20)
      2 Cluster (21)
      2 Cluster (22)
      2 Cluster (23)
      2 Cluster (24)
      2 Cluster (26)
      2 Cluster (27)
      1 docker_test_3
      2 e2e_race
      2 endtoend
      2 golangci-lint
      4 local_example
      2 region_example
      7 unit_race
      6 Unit Test (mariadb101)
      6 Unit Test (mariadb102)
      6 Unit Test (mariadb103)
      6 Unit Test (mysql57)
      6 Unit Test (mysql80)
      6 Unit Test (percona56)
```

**Pull request merged**
