### PR TITLE
multishard autocommit should work for bypass routing

### PR DESCRIPTION
**Pull request by demmer**
## Description
Parse and extract the multishard autocommit query directive in the bypass routing plan builder. 

We (Slack) noticed that routing a DML to the keyrange target `[-]`, performance timings implied that the multishard autocommit query directive wasn't being honored when routing the query.

This change makes the query directive take effect when DMLs are force routed to a particular shard or keyrange.

## Checklist
- [x] Verified manually in our dev environment
- [x] Added tests for both the engine and the planner
- [x] Documentation is not required

## Deployment Notes
None

### CODE REVIEW

**Comment by rafael** [comment]
This change looks good to me. @demmer  could you look at the conflicts and push again?

Also, extra pair of eyes from @GuptaManan100  or @systay  would be great.

**Comment by demmer** [comment]
I fixed the conflicts and re-pushed. Not sure why all the CI is failing.

**Review by systay — APPROVED** [review]
LGTM

**Comment by systay** [comment]
> I fixed the conflicts and re-pushed. Not sure why all the CI is failing.

Guessing that was the "pr-labels" check that was failing. Manan added labels to the PR, so nothing to do 👍

**Review by harshit-gangal — APPROVED** [review]

**Pull request merged**
