### PR TITLE
Add timeout to all the contexts used for RPC calls in vtorc

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the bug described in https://github.com/vitessio/vitess/issues/15990. It adds the `RemoteOperationTimeout` to all the RPC calls.

## Related Issue(s)

- Fixes https://github.com/vitessio/vitess/issues/15990

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by mattlord — APPROVED** [review]
❤️ Thanks, @GuptaManan100 ! I double checked a few of the RPCs we're making with the new context and confirmed that we're checking to see if the context is done as we go up the call stack on the tmc server side.

Do we not also need to do it for other things like `LockShard()` ? That's making a topo call and we use `context.Background()` here: https://github.com/vitessio/vitess/blob/cf06f6033680d1e5141a915d2156e81f86230413/go/vt/vtorc/logic/topology_recovery.go#L490

If that hangs then it could block many other operations both within vtorc and without (at least until the lock's lease expired in the topo server). I didn't look at everything so that's just one of N other potential places where we should probably use a context with a timeout/deadline too. 

I also think it probably makes sense to create a context earlier/lower in the call stack at various points, which then gets passed along. For example here: https://github.com/vitessio/vitess/blob/cf06f6033680d1e5141a915d2156e81f86230413/go/vt/vtorc/logic/topology_recovery.go#L446

Or even lower in the call stack at `CheckAndRecover()`. That would then get passed on to `LockShard`, `RefreshKeyspaceShard`, and all the recovery functions. It could be `topo.RemoteOperationTimeout` * X or a fixed time of e.g. `60s` — whatever makes sense for the larger overall operation with functions up the stack like `tabletUndoDemotePrimary()` still able to create child contexts with shorter timeouts. 

We don't have to fix/improve everything all at once, but I think it's at least something worth looking into and considering. If you do feel up for a more exhaustive context examination and refactoring I'm happy to help if/as needed (certainly at least with the review).

**Comment by mattlord** [comment]
There also appears to be a data race in one of the new tests that we should address before merging:
```
2024-05-22T04:28:30.9053460Z ==================
2024-05-22T04:28:30.9053564Z WARNING: DATA RACE
2024-05-22T04:28:30.9053700Z Read at 0x000002d0e9e0 by goroutine 587:
2024-05-22T04:28:30.9054125Z   vitess.io/vitess/go/vt/vtctl/reparentutil.(*PlannedReparenter).performGracefulPromotion()
2024-05-22T04:28:30.9054645Z       /home/runner/work/vitess/vitess/go/vt/vtctl/reparentutil/planned_reparenter.go:302 +0xd64
2024-05-22T04:28:30.9055191Z   vitess.io/vitess/go/vt/vtctl/reparentutil.TestPlannedReparenter_performGracefulPromotion.func3()
2024-05-22T04:28:30.9055788Z       /home/runner/work/vitess/vitess/go/vt/vtctl/reparentutil/planned_reparenter_flaky_test.go:1709 +0xace
2024-05-22T04:28:30.9055906Z   testing.tRunner()
2024-05-22T04:28:30.9056320Z       /opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1689 +0x21e
2024-05-22T04:28:30.9056452Z   testing.(*T).Run.gowrap1()
2024-05-22T04:28:30.9056806Z       /opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1742 +0x44
2024-05-22T04:28:30.9056814Z 
2024-05-22T04:28:30.9056987Z Previous write at 0x000002d0e9e0 by goroutine 888:
2024-05-22T04:28:30.9057432Z   vitess.io/vitess/go/vt/vtctl/reparentutil.TestEmergencyReparenter_reparentReplicas.func1.1()
2024-05-22T04:28:30.9057994Z       /home/runner/work/vitess/vitess/go/vt/vtctl/reparentutil/emergency_reparenter_test.go:3475 +0x30
2024-05-22T04:28:30.9058119Z   runtime.deferreturn()
...

2024-05-22T04:28:30.9064675Z ==================
2024-05-22T04:28:30.9065077Z === NAME  TestPlannedReparenter_performGracefulPromotion/demotion_succeeds_but_parent_context_times_out
2024-05-22T04:28:30.9065334Z     testing.go:1398: race detected during execution of test
2024-05-22T04:28:30.9065626Z --- FAIL: TestPlannedReparenter_performGracefulPromotion (0.01s)
```

**Comment by GuptaManan100** [comment]
The data race actually got introduced in https://github.com/vitessio/vitess/pull/15934, I'll do a PR to fix it separately, that we can merge ASAP

**Comment by GuptaManan100** [comment]
@mattlord We don't need a timeout for LockShard because internally it adds the appropriate timeout - 
```go
func (l *Lock) internalLockShard(ctx context.Context, ts *Server, keyspace, shard string, isBlocking bool) (LockDescriptor, error) {
	log.Infof("Locking shard %v/%v for action %v", keyspace, shard, l.Action)

	ctx, cancel := context.WithTimeout(ctx, getLockTimeout())
	defer cancel()
```

Having a timeout at a higher level in CheckAndRecover is something that I'm considering. Not sure whether we'll add one or not, and if we do, what that timeout would be. In any case, like you said, adding timeouts to each RPC is still something we should do! ❤️

**Review by deepthi — APPROVED** [review]

**Pull request merged**
