### PR TITLE
v14 backport of two PRs: vreplication throttling info & vreplication endtoend flakiness fix

### PR DESCRIPTION
**Pull request by shlomi-noach**
This PR backports to `v14` both:

- https://github.com/vitessio/vitess/pull/10601
- https://github.com/vitessio/vitess/pull/10876

The intention was to just backport https://github.com/vitessio/vitess/pull/10876 to fix `onlineddl_vrepl` CI flakiness, but it then depends on #10601 so we're backporting that, too.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Ironically `onlineddl_vrepl` fails.

**Comment by deepthi** [comment]
#10601 is too big to back port to the release branch. we should back port as much of #10876 as we can, OR find an alternative way to fix the flakiness.

**Comment by shlomi-noach** [comment]
We;re good test-wise.

**Comment by deepthi** [comment]
> We;re good test-wise.

Meaning we can close this without merging?

**Comment by shlomi-noach** [comment]
> Meaning we can close this without merging?

Sorry, missed this comment. No - meaning the tests for this PR are green  ad fixed. This PR should be merged.

**Review by mattlord — APPROVED** [review]

**Pull request merged**
