### PR TITLE
Prometheus histogram improvements

### PR DESCRIPTION
**Pull request by demmer**
Make a couple of improvements to the prometheus metrics:

1. Add a customizable label string for stats.NewTimings rather than a hard coded label of "Histograms".
2. Add prometheus export for stats.NewHistogram.
3. Reorganize the prometheus backend code to put the constructor definitions next to the structs themselves.
4. Change the PromBackend singleton from a pointer to a singleton struct.

---
This change is [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3879)

### CODE REVIEW

**Comment by michael-berlin** [comment]
:lgtm:

Everything looks good to me. I have three small nitpicks which should be easy to address?

---

Reviewed 13 of 13 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/stats/histogram_test.go, line 26 at r2](https://reviewable.io/reviews/vitessio/vitess/3879#-LBNnSfY2RxCHmtkovoK:-LBNnSfY2RxCHmtkovoL:b-7v7f9h) ([raw file](https://github.com/vitessio/vitess/blob/066e88eabc8a3ed180651159fe3f1ce5736a403e/go/stats/histogram_test.go#L26)):*
> ```Go
> func TestHistogram(t *testing.T) {
> 	clear()
> 	h := NewHistogram("hist1", "desc1", []int64{1, 5})
> ```

nit: just "help" everywhere in the tests?

---

*[go/stats/timings.go, line 166 at r1](https://reviewable.io/reviews/vitessio/vitess/3879#-LBNl2Ek2RGcxFqdxeAW:-LBNl2Ek2RGcxFqdxeAX:bc9gk6h) ([raw file](https://github.com/vitessio/vitess/blob/504550ecefce91be6298ff7fafd8ef85d3bab8df/go/stats/timings.go#L166)):*
> ```Go
> 
> // LabelName returns the label name.
> func (t *Timings) LabelName() string {
> ```

For the counter I changed it to "Label" and "label" everywhere.

In any case, let's be consistent. Do you mind omitting "name" here everywhere?

---

*[go/stats/prometheusbackend/prometheusbackend.go, line 152 at r2](https://reviewable.io/reviews/vitessio/vitess/3879#-LBNo6zDCKDgxrc4jC-k:-LBNo6zDCKDgxrc4jC-l:bvmm5c2) ([raw file](https://github.com/vitessio/vitess/blob/066e88eabc8a3ed180651159fe3f1ce5736a403e/go/stats/prometheusbackend/prometheusbackend.go#L152)):*
> ```Go
> 	}
> 
> 	for i, val := range t.Cutoffs() {
> ```

nit: I personally prefer to build the requirements of an object first and then assemble the object. This way it's also clearer what depends on the object creation. i.e.

```go
        cutoffs := make([]float64, len(t.Cutoffs()))
	for i, val := range t.Cutoffs() {
		collector.cutoffs[i] = float64(val) / 1000000000
	}

	collector := &timingsCollector{
		t:       t,
		cutoffs: cutoffs,
		desc: prometheus.NewDesc(
			be.buildPromName(name),
			t.Help(),
			[]string{t.LabelName()},
			nil),
	}
 

```

Same comment below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3879#-:-LBNpdfq0XTYVJN7QlrI:b8szh0k)*

**Comment by demmer** [comment]
@michael-berlin Thanks for the quick feedback and all the good suggestions. Updated accordingly.

**Comment by michael-berlin** [comment]
Reviewed 1 of 1 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3879)*

**Comment by michael-berlin** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3879#-:-LBSJe6g7G18NJKBi3la:bnfp4nl)*

**Pull request merged**
