### PR TITLE
Online DDL: fix deadlock by releasing mutex before calling callback

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

Fixes https://github.com/vitessio/vitess/issues/12208

I mean, the code which https://github.com/vitessio/vitess/pull/12169 replaced, strictly said:

> // We wrap everything in a function because we want the mutex released. We will need to reaquire it later on
> // for other bookkeeping work.

So here we are. This PR re-introduces a similar function wrap, to release the mutex before running the callback.

## Related Issue(s)

- https://github.com/vitessio/vitess/issues/12208
- #6926

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by shlomi-noach** [comment]
The gitdiff does injustice to the change. Basically a new anonymous `func() error` wraps a big chunk of `submitCallbackIfNonConflicting()`, shifting right most of the text; on top of it, which is what confuses `git`, the function only returns an `error` type, so all `return` point look slightly different.

**Review by mattlord — APPROVED** [review]
I know that I'm probably annoying you to death regarding unit tests... but this may have been caught by the unit test race workflow (don't know for sure, it's just another benefit to having them).

**Comment by shlomi-noach** [comment]
@mattlord I came here to say that you explicitly asked me about test coverage.

**Comment by shlomi-noach** [comment]
Notes on testing:

- Looking at the `unit_race` test, there _was_ a failure, but unrelated: https://github.com/vitessio/vitess/actions/runs/4069075880/jobs/7008400822 (I promise I did not just hit the re-run before looking at the output)
- I was planning to add a "resubmit" test to test the deadlock -- and as it happens there already is one: https://github.com/vitessio/vitess/blob/4b3b37d41ec08130d162b5115904108cbb3dc14b/go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go#L772-L805 ; so evidently that test is not enough and I need to think of a stronger test.

**Comment by shlomi-noach** [comment]
All right, it needs to be a resubmission of a `failed` or `cancelled` migration, _and_ in either `--singleton` or `--singleton-context` strategy.

**Comment by shlomi-noach** [comment]
Added a test that validates lack of deadlock. The same test fails on current `main` code, on deadlock.

**Review by dbussink — APPROVED** [review]

**Pull request merged**
