### PR TITLE
generated proto files with gogoproto gofast

### PR DESCRIPTION
**Pull request by acharis**
opening this PR for travis data

Signed-off-by: Alex Charis <acharis@hubspot.com>

### CODE REVIEW

**Comment by acharis** [comment]
Travis is now passing, but I had to cheat to do it:
- i copied the proto directory to pyproto, which is used by python and java. this is obviously undesirable. i've got to find a way to, idk, conditionally have those lines in there.
- i have a patch file, which adjusts the output of the gogo code generator for the vtgate.proto. i've got to find a way to set gogo options correctly to get that output without having a patch file (but having those options in there will make the python+java parts less happy ... )

**Comment by derekperkins** [comment]
I'm not an expert, but I know that there are some interop issues with gogo, which I'm assuming is what led to your java/python hacks.
https://jbrandhorst.com/post/gogoproto/

Do we have any benchmarking tools in place to let us know how much value this adds?

**Comment by acharis** [comment]
i'm also far from an expert, but the interop issues sound like they're around reflection. that blog post (which i read already) you reference calls this out, so I've chosen to:
> If you use just the protoc-gen-gofast generator, which simply generates type specific marshalling and unmarshalling code, you’ll be fine. 

the hacks i introduced are at _build_ time. for the java side, i've found:
https://github.com/QubitProducts/gogoproto-java
for python, i'm not 
i'm not sure about any benchmarks we have that might shed light on improvements.

I've been emailing with the current gogo proto fellow to get some help here.

**Comment by acharis** [comment]
i've gotten python+java using the same proto files that gogo is using, so that's good.
but i've still got to do massaging of the generated sources, which i'm not happy about.
the only way i found to get the java side to work is to add another compilation module, which i'm not happy about at all, but seems like the way to do it.

the other thing i'll drop here so that i stop forgetting it is that my govendor knowledge is lacking a bit: i didn't set a version, and i grabbed everything:
`govendor fetch github.com/gogo/protobuf/...`
i'm not sure if there's a way to be more selective about what we pull in, and i'm also not sure if we're actually using all that stuff (but i doubt it). so if we care to slim down a bit, we could look there.

**Comment by acharis** [comment]
wooo! travis is passing!!

**Comment by acharis** [comment]
TODO:
- use gogo better so that we don't have to apply a patch
- tighten up the vendoring of gogo

**Comment by acharis** [comment]
@dkhenry any luck benchmarking this?

**Comment by acharis** [comment]
some sysbench results, happy to share more data.
```
grep -e transactions: -e avg: **/*.log
gogopr/0003/sysbench-read-write-khhtd.log:    transactions:                        1278957 (1420.75 per sec.)
gogopr/0003/sysbench-read-write-khhtd.log:         avg:                                  140.75
gogopr/0004/sysbench-read-write-2z2hb.log:    transactions:                        1279174 (1421.02 per sec.)
gogopr/0004/sysbench-read-write-2z2hb.log:         avg:                                  140.72
gogopr/0005/sysbench-read-write-7vpwk.log:    transactions:                        1297330 (1441.15 per sec.)
gogopr/0005/sysbench-read-write-7vpwk.log:         avg:                                  138.76

master/0002/sysbench-read-write-bjlkn.log:    transactions:                        1319202 (1465.40 per sec.)
master/0002/sysbench-read-write-bjlkn.log:         avg:                                  136.46
master/0006/sysbench-read-write-rh9z6.log:    transactions:                        1344424 (1493.43 per sec.)
master/0006/sysbench-read-write-rh9z6.log:         avg:                                  133.90
master/0007/sysbench-read-write-hx5bh.log:    transactions:                        1259760 (1399.18 per sec.)
master/0007/sysbench-read-write-hx5bh.log:         avg:                                  142.91

grep -e queries: -e avg: **/*.log    
gogopr/0003/sysbench-read-write-khhtd.log:    queries:                             20464012 (22732.84 per sec.)
gogopr/0003/sysbench-read-write-khhtd.log:         avg:                                  140.75
gogopr/0004/sysbench-read-write-2z2hb.log:    queries:                             20467484 (22737.03 per sec.)
gogopr/0004/sysbench-read-write-2z2hb.log:         avg:                                  140.72
gogopr/0005/sysbench-read-write-7vpwk.log:    queries:                             20757896 (23059.06 per sec.)
gogopr/0005/sysbench-read-write-7vpwk.log:         avg:                                  138.76

master/0002/sysbench-read-write-bjlkn.log:    queries:                             21108076 (23447.41 per sec.)
master/0002/sysbench-read-write-bjlkn.log:         avg:                                  136.46
master/0006/sysbench-read-write-rh9z6.log:    queries:                             21511663 (23895.91 per sec.)
master/0006/sysbench-read-write-rh9z6.log:         avg:                                  133.90
master/0007/sysbench-read-write-hx5bh.log:    queries:                             20156958 (22387.70 per sec.)
master/0007/sysbench-read-write-hx5bh.log:         avg:                                  142.91
```

**Comment by sougou** [comment]
What were the CPU usage numbers. That's where we're expecting differences.

**Comment by sougou** [comment]
Is this still in play?

**Comment by acharis** [comment]
benchmarks here were pretty disappointing. bummed that this went nowhere.

**Comment by derekperkins** [comment]
It's just as well that the benchmarks weren't great, gogo has basically been abandoned.

**Comment by sougou** [comment]
The new leading suspect for the CPU burn is HTTP2.

**Pull request closed without merging**
