### PR TITLE
Rename master to primary/source in web interface of vtorc

### LINKED ISSUE #9150: Missing inclusive naming in `web/orchestrator/public/js`
#### Overview of the Issue

The Orchestrator UI would not load after JSON data structure and API endpoint updates for [inclusive naming](https://github.com/vitessio/vitess/commit/339e4ed15fdcfc665c632aa31b89bf554b0f1e7b) or [disambiguation](https://github.com/vitessio/vitess/commit/d9a8525b2d6a18c756b1ee335209af53e5110782).

The vtorc Orchestrator JS files were missed in these updates.

#### Reproduction Steps

Deploy `vtorc`.
Have some problems to recover from in the clusters.
Browse to the "Dashboard"

##### Observe

Spinning progress wheel in menu bar
Blank dashboard
Console errors referring to "Hostname" unable to be referenced on undefined

#### Binary version

vitess/lite:v12.0.0

#### Pod with work-around to fix

Remove the `sed` in the init container and provide your own global topo server, clusters_to_watch and configuration Secret to observe the JS console errors.

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-vtorc-data
  namespace: vt-example
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    planetscale.com/cell: db
    planetscale.com/cluster: example
    planetscale.com/component: vtorc
    statefulset.kubernetes.io/pod-name: example-vtorc-0
  name: example-vtorc-0
  namespace: vt-example
spec:
  containers:
  - args:
    - --clusters_to_watch=example
    - --topo_global_root=/vitess/example/global
    - --topo_global_server_address=global-etcd:2379
    - --topo_implementation=etcd2
    - --logtostderr=true
    - --config=/var/secrets/vtorc/config.json
    - --orc_web_dir=/vtorc/web
    command:
    - /vt/bin/vtorc
    image: vitess/lite:v12.0.0
    livenessProbe:
      failureThreshold: 30
      httpGet:
        path: /web/clusters
        port: web
      initialDelaySeconds: 300
    name: vtorc
    ports:
    - containerPort: 3000
      name: web
    readinessProbe:
      httpGet:
        path: /web/clusters
        port: web
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
    securityContext:
      runAsUser: 999
    volumeMounts:
    - mountPath: /vtorc/web
      name: web
    - mountPath: /vtorc/data
      name: data
    - mountPath: /var/secrets/vtorc
      name: vtorc-config
      readOnly: true
  hostname: example-vtorc-0
  initContainers:
  - args:
    - |
      set -ex
      cp -Rp /vt/web/orchestrator/* /vtorc/web/
      sed -i "s/MasterKey/SourceKey/g" /vtorc/web/public/js/*.js
      sed -i "s/MasterUUID/SourceUUID/g" /vtorc/web/public/js/*.js
      sed -i "s/Master/Primary/g" /vtorc/web/public/js/*.js
      sed -i "s/master/primary/g" /vtorc/web/public/js/*.js
    command:
    - bash
    - -c
    image: vitess/lite:v12.0.0
    name: init-web
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      runAsUser: 999
    volumeMounts:
    - mountPath: /vtorc/web
      name: web
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-lthls
      readOnly: true
  preemptionPolicy: PreemptLowerPriority
  priority: 1000
  priorityClassName: vitess
  serviceAccountName: default
  subdomain: vtorc
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: example-vtorc-data
  - name: web
  - name: vtorc-config
    secret:
      defaultMode: 292
      items:
      - key: config.json
        path: config.json
      secretName: orchestrator
```

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description
As a part of the naming convention change in VtOrc, the change in the website files was missed. This caused the website to not work at all in release-12 since it didn't find the required fields and got stuck loading the initial page. This PR addresses this and renames constructs from `master` to `primary`/`source` in accordion with the remaining code-base

## Related Issue(s)

- #7110 
- Fixes #9150 

## Checklist
- [x] Should this PR be backported? Should be back-ported to 12.0
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

**Review by harshit-gangal — COMMENTED** [review]
LGTM.

It would be good to add a test for the bug fix.

**Review by deepthi — APPROVED** [review]
LGTM

**Comment by deepthi** [comment]
Re: backport, we avoid backporting non-critical fixes because they can themselves possibly cause additional regressions.
However, this code affects nothing but vtorc, so I won't object if you _really_ want to backport.

**Comment by deepthi** [comment]
> LGTM.
> 
> It would be good to add a test for the bug fix.

We discussed this earlier today. Since vtorc UI will be replaced by vtadmin, it is not worth creating a UI test framework for it.

**Pull request merged**
