### PR TITLE
Optimize `sqlutils.ToSqlite3Dialect` for queries + DML/DDLs

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

This PR adds some slight optimisations to `sqlutils.ToSqlite3Dialect`, a function we've noticed to take up a significant amount of CPU time in `vtorc` when it watches many instances, primarily due to large insert queries needing to be parsed by `regexp` filters

Profile SVG _(need to enlarge)_:
profile001

All this change does is assumes inserts happen more frequently than alter/create. Moving inserts to be checked sooner and separating read queries causes them to have to go through [fewer regex matches](https://github.com/vitessio/vitess/blob/main/go/vt/external/golib/sqlutils/sqlite_dialect.go) _(still a lot 🙈)_. The expense of queries that are not insert, alter or create is unchanged.

On Slack's `vtorc` instances this gave us about a 15-20% reduction in user-CPU used by `vtorc` vs the previous avg

In the benchmark I added in the PR the difference is more like 8-9% for big inserts and 18-19% for reads

#### Before
```bash
goos: darwin
goarch: amd64
pkg: vitess.io/vitess/go/vt/external/golib/sqlutils
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkToSqlite3Dialect_Insert1000
BenchmarkToSqlite3Dialect_Insert1000-16    	       1	1870643229 ns/op
BenchmarkToSqlite3Dialect_Select
BenchmarkToSqlite3Dialect_Select-16        	    3541	    330667 ns/op
PASS
ok  	vitess.io/vitess/go/vt/external/golib/sqlutils	4.660s
```

#### After
```bash
goos: darwin
goarch: amd64
pkg: vitess.io/vitess/go/vt/external/golib/sqlutils
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkToSqlite3Dialect_Insert1000
BenchmarkToSqlite3Dialect_Insert1000-16    	       1	1711349181 ns/op
BenchmarkToSqlite3Dialect_Select
BenchmarkToSqlite3Dialect_Select-16        	    4436	    270223 ns/op
PASS
ok  	vitess.io/vitess/go/vt/external/golib/sqlutils	4.528s
```

## Related Issue(s)

Resolves https://github.com/vitessio/vitess/issues/17114

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by mattlord** [comment]
@GuptaManan100 do we still need this library at all? `vtorc` only supports SQLite now so I would think that we would use the SQLite dialect everywhere.

**Comment by timvaillancourt** [comment]
> @GuptaManan100 do we still need this library at all? `vtorc` only supports SQLite now so I would think that we would use the SQLite dialect everywhere.

@mattlord his is what I asked/proposed [in this thread](https://vitess.slack.com/archives/C02GSRZ8XAN/p1730207109838589) 👍

I'm hoping we can remove dialect translation and just use sqlite dialect. Also I think `external/sqlutils` could be replaced with something a bit less crufty - there are similar projects that can reflect `database/sql` to map/structs for example. For now this is some duct tape

**Comment by dbussink** [comment]
> @mattlord this is what I asked/proposed [in this thread](https://vitess.slack.com/archives/C02GSRZ8XAN/p1730207109838589) 👍. I'm hoping we can remove dialect translation and just use sqlite dialect

I think removing the translation and writing queries directly that work with sqlite is a good idea indeed. It removes this whole layer of translation that doesn't really serve any purpose anymore.

> Also I think `external/sqlutils` could be replaced with something a bit less crufty - there are similar projects that can reflect `database/sql` to map/structs for example. For now this is some duct tape

I think it's a good idea to clean this up (also fine incrementally). It's all leftovers from how it was basically vendored but only parts have been modernized to match how other parts of Vitess work. So I think thinks kind of cleanup is also very welcome.

**Comment by GuptaManan100** [comment]
Yes, @timvaillancourt we can get rid of all other dialects other than sqlite. We don't allow any other backing database in VTOrc.

**Comment by timvaillancourt** [comment]
Closing in favour of https://github.com/vitessio/vitess/pull/17124 which removes the translation entirely

**Pull request closed without merging**
