### PR TITLE
sqlparser: fix canonical formatting for enums

### PR DESCRIPTION
**Pull request by vmg**
## Description

Fixes https://github.com/vitessio/vitess/issues/10143, requested by @shlomi-noach 

## Checklist

-   [ ] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by systay — APPROVED** [review]

**Review by shlomi-noach — APPROVED** [review]
yay!

**Review by GuptaManan100 — APPROVED** [review]

**Comment by shlomi-noach** [comment]
`Cluster (20)` doesn't want to complete. #rd round where it's just hanging for over 30-40min

**Comment by shlomi-noach** [comment]
`Cluster (20)` fails consistently for some 7-8 times now; but it does not seem to be related to this PR. Any thoughts?

**Comment by GuptaManan100** [comment]
Oh, that not a required test anymore. There was a new version released of XtraBackup which is breaking. Here is the open issue for it - https://github.com/vitessio/vitess/issues/10146. It was created yesterday, and for the time being the test is marked not required. It should be okay to merge 👍

**Pull request merged**
