### PR TITLE
Support for MySQL `MAX_EXECUTION_TIME` as query timeout method

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

This PR implements https://github.com/vitessio/vitess/issues/12518 by allowing the MySQL Optimizer Hint `MAX_EXECUTION_TIME(<millis>)`, based on the existing `vttablet` query timeout (seconds) to be automatically added to queries using when the new `--query-timeout-method` flag is set to `mysql` (default `vttablet`)

The `vttablet` will wait up to `--query-timeout-seconds` + `1` for MySQL to do this, before falling back to the existing behaviour that issues a MySQL `KILL` operation

Suggestions on how to make the PR more robust is appreciated 🙇 

## Related Issue(s)

https://github.com/vitessio/vitess/issues/12518

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by timvaillancourt** [comment]
Planning to get this ready to review shortly, some tweaks needed first

**Comment by timvaillancourt** [comment]
Bump, still planning to complete this

**Comment by timvaillancourt** [comment]
I plan to wrap this up once I can figure out a smart way to add optimizer hints on the `vttablet` level. It seems `vtgate` has logic to add optimizer hints but it's not clear in `vttablet`

I'm curious if @harshit-gangal has time for a quick chat about that detail?

**Comment by harshit-gangal** [comment]
> I plan to wrap this up once I can figure out a smart way to add optimizer hints on the `vttablet` level. It seems `vtgate` has logic to add optimizer hints but it's not clear in `vttablet`
> 
> I'm curious if @harshit-gangal has time for a quick chat about that detail?

VTGate and VTTablet already have a flag for query timeouts `query-timeout` and `queryserver-config-query-timeout`. 
Currently, the VTGate flag is used to set the context timeout eventually a `Kill` on MySQL and the VTTablet flag is used to execute the `Kill` on MySQL.
The current VTTablet flag can be used to repurpose it for `select` queries. We can modify the `Build` method in `go/vt/vttablet/tabletserver/planbuilder/plan.go` to add the optimizer hint.

**Pull request closed without merging**
