### PR TITLE
fixing flaky upgrade test

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description
endtoend/upgrade is yet again flaky. Looking into.

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [x]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Review by vmg — APPROVED** [review]

**Comment by shlomi-noach** [comment]
Added the CI/workflow patches to all non-auto-generated tests:
```
    - name: Tune the OS
      run: |
        echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range
    # TEMPORARY WHILE GITHUB FIXES THIS https://github.com/actions/virtual-environments/issues/3185
    - name: Add the current IP address, long hostname and short hostname record to /etc/hosts file
      run: |
        echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
    # DON'T FORGET TO REMOVE CODE ABOVE WHEN ISSUE IS ADRESSED!
```

**Comment by shlomi-noach** [comment]
`Upgrade` test consistently passes in this PR, but still consistently fails on other PRs which have incorporated the changes in this PR (namely https://github.com/vitessio/vitess/pull/7785)

**Comment by shlomi-noach** [comment]
vreplication_basic failure: https://github.com/vitessio/vitess/pull/7901/checks?check_run_id=2390417564

**Comment by shlomi-noach** [comment]
What this PR ended up doing is add the two patches: `/etc/hosts` and port-range, to all tests, especially those not auto-generated by `make generate_ci_workflows`.

**Pull request merged**
