### PR TITLE
[13.0] Cherry Pick: only use the special NoRoute handling mode when needed

### LINKED ISSUE #10301: Bug Report: select with where in on secondary vindex is not working
### Overview of the Issue

Runing `where in(...)` query with no sharding key on a secondary vindex (`consistent_lookup_unique`) is throwing an error.

```sql
select `username` from `users`  where `id` in ("test2", "test")
```

```
vttablet: rpc error: code = InvalidArgument desc = missing bind var __vals (CallerID: userData1)
```

### Reproduction Steps

1. Deploy the following `vschema`:

```json
{
   "sharded":true,
   "vindexes":{
      "unicode_loose_md5":{
         "type":"unicode_loose_md5"
      },
      "users_keyspace_id":{
         "type":"consistent_lookup_unique",
         "params":{
            "table":"commerce.users_keyspace_id",
            "from":"id",
            "to":"keyspace_id"
         },
         "owner":"users"
      }
   },
   "tables":{
      "users":{
         "column_vindexes":[
            {
               "column":"team_id",
               "name":"unicode_loose_md5"
            },
            {
               "column":"id",
               "name":"users_keyspace_id"
            }
         ]
      },
      "users_keyspace_id":{
         "column_vindexes":[
            {
               "column":"id",
               "name":"unicode_loose_md5"
            }
         ]
      }
   }
}
```

2. Deploy the following `schema`

```sql
create table users(id char(36), team_id char(36), username varchar(50), primary key(id));
```

3. Run the query
 
```sql
select `username` from `users`  where `id` in ("test2", "test")
```

5. View error

```
vttablet: rpc error: code = InvalidArgument desc = missing bind var __vals (CallerID: userData1)
```

Explain

```
Route	IN	user		UNKNOWN	select username from users where id in ::__vals
```

### Binary Version

```sh
Version: 14.0.0-SNAPSHOT (Git revision 209c5747c529b001ad71b5f9bed53f57c6f5fdeb branch 'main') built on Tue May  3 09:53:06 UTC 2022 by vitess@buildkitsandbox using go1.18.1 linux/amd64
```

### Operating System and Environment details

```sh
Docker
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Description
Cherry Pick of https://github.com/vitessio/vitess/pull/10422

In a recent change (#10152), we introduced a special mode handling when no routes are found for a query. 
This introduced an issue that was later fixed for gen4 (#10346), but here I missed fixing the same issue for v3.

## Related Issue(s)
#10152 Bug introduced
#10346 Bug fixed for Gen4
Fixes #10301

### CODE REVIEW

**Review by systay — APPROVED** [review]

**Comment by deepthi** [comment]
Looks like we need the same change for mariadb102 as we did for mariadb103 in #11017. I'll push another commit to that PR.

**Comment by harshit-gangal** [comment]
> Looks like we need the same change for mariadb102 as we did for mariadb103 in #11017. I'll push another commit to that PR.

I see that you are removing 10.1 and 10.2 in that PR

**Comment by harshit-gangal** [comment]
> Looks like we need the same change for mariadb102 as we did for mariadb103 in #11017. I'll push another commit to that PR.

I think we should still not block this PR for unrelated failure

**Comment by deepthi** [comment]
> > Looks like we need the same change for mariadb102 as we did for mariadb103 in #11017. I'll push another commit to that PR.
> 
> I see that you are removing 10.1 and 10.2 in that PR

Yes, but that is correct only on main. 13.0 needs to continue to work with mariadb 10.2

**Comment by deepthi** [comment]
> > Looks like we need the same change for mariadb102 as we did for mariadb103 in #11017. I'll push another commit to that PR.
> 
> I think we should still not block this PR for unrelated failure

How do we know that the mariadb102 test won't fail on this PR?
I'll answer that myself. Because I went and checked that the original PR actually passed the mariadb102 unit test, we can have a high degree of confidence that it won't fail in this PR either.
However, I did things by the book. That is, I fixed the mariadb102 test in #11017, merged that PR and then merged the release branch into this PR branch.
Once all tests pass, I can merge this PR too.

**Comment by deepthi** [comment]
Backup test failure is a transient http error. Since backups are truly unrelated to this PR, going ahead with the merge.

**Pull request merged**
