### PR TITLE
Embed vtctld assets

### PR DESCRIPTION
**Pull request by rohit-nayak-ps**
Part of #5502 

Embedded web/vtctld2 web application assets into vtctld using go.rice.
Hotfixed javascript to fix an issue where a polyfill was causing some versions of chrome not to load the application. 
Removed web/vtctld and related code (checked with Sugu, it has been deprecated for some time).
Removed web_dir/web_dir2 config parameters from examples/local/vtctld-up.sh

### CODE REVIEW

**Comment by morgo** [comment]
I checked out your branch. Just a couple of quick suggestions:

- Add the rice file to gitignore
- Add the embed_static to the build target.
- Change the rice command to be a go run command, so rice doesn't need to be installed first.

Here's a patch:

```
diff --git a/.gitignore b/.gitignore
index be8fe7275..a4095ee9d 100644
--- a/.gitignore
+++ b/.gitignore
@@ -85,3 +85,6 @@ releases
 /vthook/
 /bin/
 /vtdataroot/
+
+# Rice generated files
+/go/vt/vtctld/rice-box.go
diff --git a/Makefile b/Makefile
index 54fb5df29..2ec325966 100644
--- a/Makefile
+++ b/Makefile
@@ -39,7 +39,7 @@ endif
 
 embed_static: 
        cd go/vt/vtctld
-       rice embed-go
+       go run github.com/GeertJohan/go.rice/rice embed-go
        go build .
 
 build_web:
@@ -47,7 +47,7 @@ build_web:
        cd web/vtctld2 && ng build -prod
        cp -f web/vtctld2/src/{favicon.ico,plotly-latest.min.js,primeui-ng-all.min.css} web/vtctld2/dist/
 
-build:
+build: embed_static
 ifndef NOBANNER
        echo $$(date): Building source tree
 endif
```

Otherwise LGTM

**Comment by rohit-nayak-ps** [comment]
Adding embed_static to the build step causes the rice file to be rebuilt on every make and presumably vtctld and dependent packages get rebuilt too. Is it ok to add this overhead?

**Comment by morgo** [comment]
> Adding embed_static to the build step causes the rice file to be rebuilt on every make and presumably vtctld and dependent packages get rebuilt too. Is it ok to add this overhead?

I am okay with it - it didn't seem like it took that long. The alternative is that we commit the rice-boxes (remove from gitignore). The problem I can see with this approach is that there will very likely be merge conflicts if multiple users are editing the source files. @sougou or @deepthi did you have opinions?

**Comment by morgo** [comment]
I chatted with sougou and deepthi - lets go with how you have it (regen as a manual step). Make sure you commit the generated file /go/vt/vtctld/rice-box.go to the repo so that users won't have to generate it to build.

**Comment by morgo** [comment]
@rohit-nayak-ps still a conflict on go.mod/go.sum.

**Comment by guidoiaquinti** [comment]
Do we need to also remove the references from [1](https://github.com/vitessio/vitess/blob/a17d817/helm/vitess/templates/_vtctld.tpl#L93) and [2](https://github.com/vitessio/vitess/blob/16300d6/Makefile#L84)?

**Comment by morgo** [comment]
> Do we need to also remove the references from [1](https://github.com/vitessio/vitess/blob/a17d817/helm/vitess/templates/_vtctld.tpl#L93) and [2](https://github.com/vitessio/vitess/blob/16300d6/Makefile#L84)?

I believe we will during Vitess 6.0 development. We discovered compatibility issues by removing these options too soon, so the behavior was changed to parse-but-ignore.

**Pull request merged**
