### PR TITLE
[release-20.0] Replace ErrorContains checks with Error checks before running upgrade downgrade

### PR DESCRIPTION
**Pull request by GuptaManan100**
This PR is a backport of #16688

### CODE REVIEW

**Comment by rohit-nayak-ps** [comment]
@GuptaManan100, seeing some proto errors in the upgrade/downgrade dates only for the v20 backport. protobuf compiler version mismatch?

**Comment by GuptaManan100** [comment]
It could be because of https://github.com/vitessio/vitess/pull/16702. Once that is merged, I can restart CI checks to see if this fixes it.

**Review by rohit-nayak-ps — APPROVED** [review]

**Comment by deepthi** [comment]
Looks like tests are still failing, even though #16702 has been merged.

**Review by deepthi — APPROVED** [review]

**Comment by GuptaManan100** [comment]
The test will be fixed after https://github.com/vitessio/vitess/pull/16705 is merged.

**Pull request merged**
