### PR TITLE
LegacySplitCloneWorker is no longer used in any code paths

### PR DESCRIPTION
**Pull request by mattlord**
Signed-off-by: Matt Lord <mattalord@gmail.com>

## Description
Keeping things tidy...

## Related Issue(s)
https://github.com/vitessio/vitess/issues/4456

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

**Comment by rafael** [comment]
Wow - end of an era! Excited to see this go. For completeness, we should not allow `LegacySlitClone` as an option from [here](https://github.com/vitessio/vitess/blob/main/go/vt/workflow/resharding/workflow.go#L77). 

Also, we should delete the resharding workflow entirely. But that could be a different PR.

**Comment by mattlord** [comment]
> Wow - end of an era! Excited to see this go. For completeness, we should not allow `LegacySlitClone` as an option from [here](https://github.com/vitessio/vitess/blob/main/go/vt/workflow/resharding/workflow.go#L77).

I tried to remove the remaining references in https://github.com/vitessio/vitess/pull/8867/commits/bfcfcb9e53f2ecd3a77fc6f23cbfc3638af06568

Let me know if you had something else in mind. 
 
> Also, we should delete the resharding workflow entirely. But that could be a different PR.

I'm actually not sure what you mean here and how it's related. 

Thanks!

**Comment by mattlord** [comment]
> Also, we should delete the resharding workflow entirely. But that could be a different PR.

@Rafael Were you saying that we should remove the non-legacy `SplitClone` code too [now that you should be using `MoveTables` isntead now after 6.0](https://vitess.io/docs/user-guides/historical/vertical-split/)? If so, then I think we probably should but can be done in a separate PR.

**Review by rafael — APPROVED** [review]
LGTM

**Pull request merged**
