### PR TITLE
fix return database name

### PR DESCRIPTION
**Pull request by hellobob**
The client got the wrong database name

5DD4ECD4-E695-488B-BDCD-5BEA5B99F5C0

21B4F287-4858-472A-A3CE-79EA095065D4

### CODE REVIEW

**Comment by harshit-gangal** [comment]
@hellobob I think there should be a better way to provide database to sharding-jdbc. I have not looked into the details of this framework. But current approach looks hackish to me.

**Comment by sougou** [comment]
We need to find a longer and more stable solution for this problem. The `vt_` is itself a default that can be changed using `init_dbname_override`. We should look at prioritizing the project to move this metadata into the shard record.

**Comment by systay** [comment]
Issue #6753

**Comment by deepthi** [comment]
Superseded by #6791

**Pull request closed without merging**
