### PR TITLE
Add tablet-tags/`--init_tags` stats

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

This PR adds stats for the key/values set by `--init_tags` in `vttablet`. I assume it's unlikely that a tablet would have enough tags to generate too much metric cardinality

This allows a user to use this data to query/group tablets in observability tooling

Output example _(heavily redacted)_:
Screenshot 2024-09-02 at 20 34 27

## Related Issue(s)

Resolves https://github.com/vitessio/vitess/issues/16696

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Review by frouioui — APPROVED** [review]
This sounds good to me, the format in the /metrics output looks okay too.

**Comment by deepthi** [comment]
We don't seem to have any tests for tablet stats. Now may be a good time to add some.

**Comment by timvaillancourt** [comment]
@deepthi I moved the `.Set()` loop to `.exportStats()` after finding that. I've added a test that checks the stats that are ouputted, let me know what you think 🙇

**Review by deepthi — APPROVED** [review]
Nice!

**Pull request merged**
