### PR TITLE
VSchema DDL: Add grammar to accept qualified table names in Vindex option values

### PR DESCRIPTION
**Pull request by hkdsun**
## Description

In a similar spirit as #12519, we have run into another bug handling keyspace names with dashes `-` in them.

This time, while applying VSchema DDL statements such as:

```
ALTER VSCHEMA ON test2 
  ADD VINDEX test_lookup_fqn(c1,c2) 
  USING consistent_lookup_unique 
  WITH 
    owner=`test`, 
    from=`c1,c2`, 
    table=`test-keyspace`.`lookup-fqn`, 
    to=`keyspace_id`
```

Currently, the above is a syntax error, since everything after `WITH` is parsed as a `reserved_sql_id`/`STRING`/`INTEGRAL`.

This PR introduces `table_id '.' reserved_table_id` as valid syntax.

I chose this over a blanket `table_name` token since it's a narrower change, but I'm happy to go either way with it. We will be using fully-qualified table names with keyspace names.

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by hkdsun** [comment]
👋 This should not impact any reasonable existing usage of the VSchema DDL, and only fix a previously-broken syntax error. As such, I would like to kindly request a backport of this issue (similarly and perhaps bundle with #12519)

**Comment by hkdsun** [comment]
If not the upcoming `v15.0.3`, we would love to have this merged and released in the next minor version 🙏

**Comment by frouioui** [comment]
> If not the [upcoming `v15.0.3`](https://github.com/vitessio/vitess/issues/12696), we would love to have this merged and released in the next minor version 🙏

I think this should be part of the upcoming `v15.0.3` and `v16.0.1`.

**Review by frouioui — APPROVED** [review]
Looks good to me, but I'll let @GuptaManan100 manan have a final say on the parser change.

The GH UI is telling me that there are some conflicts though: `This branch has conflicts that must be resolved`, would you mind fixing those?

**Comment by hkdsun** [comment]
Good morning/afternoon, thanks for taking a look and including this in the upcoming release!

I have fixed the merge conflict on the codegen file.

🤞 for CI

**Pull request merged**
