### PR TITLE
Add Severity Labels document

### PR DESCRIPTION
**Pull request by askdba**
Signed-off-by: Alkin Tezuysal <alkin.tezuysal@gmail.com>

## Related Issue(s)

https://github.com/vitessio/vitess/issues/7485
- 

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [X] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin
- [x]  Documentation

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]

**Comment by deepthi** [comment]
We should update the issue templates with 
* A link to the severity doc. 
* A section asking people to assign a severity label.

**Review by deepthi — DISMISSED** [review]
We should update the issue templates with
* A link to the severity doc.
* A section asking people to assign a severity label.

**Comment by shlomi-noach** [comment]
> A section asking people to assign a severity label.

I don't think arbitrary users have the privilege of assigning labels.

**Comment by deepthi** [comment]
> > A section asking people to assign a severity label.
> 
> I don't think arbitrary users have the privilege of assigning labels.

Do you think that is something we should be assigning during triage instead of asking the Issue creator to do it?

**Comment by shlomi-noach** [comment]
> Do you think that is something we should be assigning during triage instead of asking the Issue creator to do it?

I think it's our only options.

**Comment by askdba** [comment]
I have rolled back the latest review suggestions by @deepthi and agree that we'll be assigning severity during the triage of issues.

**Pull request merged**
