### PR TITLE
Backup & Restore: vtctldclient to support PITR flags

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

`vtctldclient` now supports `--incremental-from-pos` in `Backup` command, and `--restore-to-pos` and `--dry-run` flags in `Restore` command.

Followup to https://github.com/vitessio/vitess/pull/11097, which only implemented PITR for `vtctl`.

### Tests

I've converted the existing `backup_pitr` tests to only use `vtctldclient`, hence now testing the new behavior. I think going forward there's little point in verifying anything that uses `vtctl` also works with `vtctldclient` and vice versa?

## Related Issue(s)

- Fixes https://github.com/vitessio/vitess/issues/13413
- Fixes https://github.com/vitessio/vitess/issues/13416
- RFC: https://github.com/vitessio/vitess/issues/11227

More work to be done once https://github.com/vitessio/vitess/pull/13270 is merged (introducing `--restore-to-timestamp` flag)

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Documentation TBD

**Review by ajm188 — APPROVED** [review]

**Comment by ajm188** [comment]
@shlomi-noach just FYI for the website docs, after merging you can go to the website repo and run

```
VITESS_DIR=/path/to/your/checkout VTCTLDCLIENT_VERSION_PAIRS="<git-ref>:<website version>,<git-ref 2>:<website version 2>,..." make vtctldclient-docs
```

so for example last time I ran: `VITESS_DIR=~/dev/vitess VTCTLDCLIENT_VERSION_PAIRS="main:18.0,release-17.0:17.0" make vtctldclient-docs`

**Comment by shlomi-noach** [comment]
I'll be merging https://github.com/vitessio/vitess/pull/13270 imminently, and so I'll use this PR to add a `vtctldclient` support for `--restore-to-timestamp`

**Comment by shlomi-noach** [comment]
Now supporting `vtctldclient RestoreFromBackup --restore-to-timestamp`

**Review by GuptaManan100 — APPROVED** [review]

**Comment by shlomi-noach** [comment]
Documentation: https://github.com/vitessio/website/pull/1546

**Pull request merged**
