### PR TITLE
Introducing new error counter in VTTablet 

### LINKED ISSUE #12265: Add `ErrorCode` dimension to VTTablet error counters
Just like Vtgate, we should have 'errorcode` dimension for error counter metric

### Current state
Currently during queryExecute we define error counter as 
```
qe.queryErrorCounts = env.Exporter().NewCountersWithMultiLabels("QueryErrorCounts", "query error counts", []string{"Table", "Plan"} 
```
this result in data generation like this 
```
"QueryErrorCounts": {"product.Insert": 1}
```

the problem with current structure is it does not tell us what was the error and we are not able to slice and dice with respect to error type. If we add `errorcode` as dimension this will give more meaning to error counter metric.

### Code changes
After adding `errorcode` our metric data will look like following

```
"QueryErrorCounts": {"product.Insert.RESOURCE_EXHAUSTED": 1,}
```

### PR DESCRIPTION
**Pull request by rsajwani**
Signed-off-by: Rameez Sajwani <rameezwazirali@hotmail.com>

## Description

We are introducing new error counter `QueryErrorCountsWithCode` for VTTablet. It is similar to existing [QueryErrorCounts](https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletserver/query_engine.go#L174) except it contains errorCode as additional dimension.
We will deprecate `QueryErrorCounts` in v18.

## Related Issue(s)

Fixes #12265

## Json Data
This is how data is looking like after the change.

### Empty dataset
Screen Shot 2023-02-15 at 3 40 26 PM

### Non-Empty dataset
Screen Shot 2023-03-08 at 3 44 42 PM

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by GuptaManan100 — APPROVED** [review]
LGTM

**Review by harshit-gangal — APPROVED** [review]

**Comment by deepthi** [comment]
@GuptaManan100 @harshit-gangal isn't this a breaking change? The labels are now different.

**Comment by deepthi** [comment]
> @GuptaManan100 @harshit-gangal isn't this a breaking change? The labels are now different.

Looks like the code has changed, but not the description. Once the description and screenshots are replaced with latest ones, we can merge this.

**Comment by harshit-gangal** [comment]
> @GuptaManan100 @harshit-gangal isn't this a breaking change? The labels are now different.

@rsajwani added a new metric for the change.

**Pull request merged**
