### PR TITLE
Add support for `MultiEqual` opcode for lookup vindexes.

### PR DESCRIPTION
**Pull request by arthurschreiber**
## Description

Seems like v18 and later can treat queries of the form `(col1 = ... AND col2 = ...) OR (col1 = ... AND col2 = ...) OR ...` the same way as `(col1, col2) IN ((..., ...), (..., ...), ...)`.

Both of these generate `MultiEqual` operations, which apparently were not supported for lookup vindexes.

## Related Issue(s)

Fixes https://github.com/vitessio/vitess/issues/16972.

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by harshit-gangal — COMMENTED** [review]
We should add little more test(unit test) around the change.
1. plan test to show `MultiEqual` opcode for vindexlookup primitive.
2. executor test to see how they are executed, queries send down to each shard, etc.

**Comment by arthurschreiber** [comment]
@harshit-gangal I added some planner tests. Where would be the best plan to add executor tests for this?

**Review by frouioui — APPROVED** [review]

**Comment by harshit-gangal** [comment]
> @harshit-gangal I added some planner tests. Where would be the best plan to add executor tests for this?

It will be in `executor_select_test.go`.

**Review by GuptaManan100 — APPROVED** [review]
LGTM!

**Pull request merged**
