### PR TITLE
Implement message methods in Java client

### PR DESCRIPTION
**Pull request by frew**
I've got maven to the point where checkstyle passes, but not sure what the best way is to get an environment setup to actually run the tests. Suggestions or doc pointers welcome!

### CODE REVIEW

**Comment by saifalharthi** [comment]
Thanks @frew , Please rebase and sign off your commits to pass the DCO check.

**Comment by sougou** [comment]
Looks like this needs re-rebasing because of the other change I merged.

**Comment by frew** [comment]
I'm planning on just using `STREAM * FROM` so planning to just close out this PR w/o merge. But if somebody particularly wants the client methods, also happy to rebase and push forward - just let me know.

**Comment by sougou** [comment]
Sounds good. No need to have more than one way to do things.

**Pull request closed without merging**
