### PR TITLE
Remove default install mysql data files from vitess-lite image

### LINKED ISSUE #5443: vitess/lite image has 122MB of unnecessary mysql data files
The `vitess/lite` Docker image has 122MB of unnecessary mysql data files:

```console
$ docker run -ti --rm -u root vitess/lite:latest du -sh /var/lib/mysql
122M    /var/lib/mysql
```

These probably come from the default database that gets initialized when we install mysql-server through a package manager. We should be able to avoid saving these if we delete them in the same `RUN` statement as the package installation.

### PR DESCRIPTION
**Pull request by J0**
Fix #5443 

image

Signed-off-by: Lee Yi Jie Joel <lee.yi.jie.joel@gmail.com>

### CODE REVIEW

**Comment by morgo** [comment]
@J0 may I suggest we just delete `/var/lib/mysql`? The remaining files are not so useful with these ones removed.

**Comment by morgo** [comment]
I understand why the test-suite is failing. It is not a problem you introduced, but an interaction between two PRs. I will fix it.

**Comment by J0** [comment]
Alright @morgo, will adjust accordingly. Thanks!

**Comment by morgo** [comment]
Master has been fixed. Please rebase and CI will pass :-)

**Comment by morgo** [comment]
@J0 failing on DCO

**Comment by J0** [comment]
I think the commit history is a little messy because I didn't sign a commit somewhere in the middle. Attempting the default fix suggested by DCO doesn't seem to work and I can't seem to find the unsigned commit in the  git log. I'm just going to close this PR and open a new one.

**Pull request closed without merging**
