### PR TITLE
[release-15.0] Remove Launchable in the workflows

### PR DESCRIPTION
**Pull request by frouioui**
## Description

This Pull Request is part of https://github.com/vitessio/vitess/issues/11243 and removes launchable from all the workflows.

## Related Issue(s)

- part of https://github.com/vitessio/vitess/issues/11243

## Checklist

-   [x] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by deepthi** [comment]
`mysql80` failure is this:
```
running tests for  vitess.io/vitess/go/test/endtoend/vtgate/mysql80/derived
[92](https://github.com/vitessio/vitess/actions/runs/3422180788/jobs/5699847133#step:9:93)
no required module provides package vitess.io/vitess/go/test/endtoend/vtgate/mysql80/derived; to add it:
[93](https://github.com/vitessio/vitess/actions/runs/3422180788/jobs/5699847133#step:9:94)
	go get vitess.io/vitess/go/test/endtoend/vtgate/mysql80/derived
```
Looks like something that isn't present on the branch at all.

**Comment by frouioui** [comment]
@deepthi yes, this is fixed on `main` by this Pull Request: https://github.com/vitessio/vitess/pull/11668. It will need to be backported to all the release branches.

**Review by deepthi — COMMENTED** [review]
#11712 has the fix for `vtgate_queries_derived`. We need that to merge before this.
Also Cluster(26) is pitrtls. @rsajwani you had fixed this as part of a larger PR (removing transform tests) on main, right? Is it possible to port just the fix for this onto this branch?

Once those are done and this

**Review by deepthi — APPROVED** [review]
I meant to approve, not just comment on the previous review.

**Pull request merged**
