### PR TITLE
Updating to golang 1.12

### PR DESCRIPTION
**Pull request by mpawliszyn**
Signed-off-by: Michael Pawliszyn <mikepaw@squareup.com>

### CODE REVIEW

**Comment by mpawliszyn** [comment]
The reason why I want this is to try out what should be better performance on TLS1.3 as well as there have been some general buffer and other changes to crypto/tls

**Comment by derekperkins** [comment]
Not sure if all these spots are relevant, but this was the PR for bumping to 1.11 https://github.com/vitessio/vitess/pull/4246/files

**Comment by mpawliszyn** [comment]
> Not sure if all these spots are relevant, but this was the PR for bumping to 1.11 https://github.com/vitessio/vitess/pull/4246/files

Ok I've added all the places from this PR too not

**Comment by sougou** [comment]
Conflicts need to be resolved.

**Comment by morgo** [comment]
The docs moved to `vitessio/website` -- these two `.md` files being here was just legacy. They've since been removed.

**Comment by mpawliszyn** [comment]
@sougou I think the conflicts have been fixed.

**Pull request merged**
