### PR TITLE
Embed mycnf files and init_db

### LINKED ISSUE #5502: Pack web files and mysql config files into binaries
#### Feature Description

The examples currently have to refer to VTROOT and VTTOP, because they need to know how to start vtctld while referencing the correct web files:
```
https://github.com/vitessio/vitess/blob/master/examples/local/env.sh#L21
..
export VTTOP=${VTTOP-$VTROOT/src/vitess.io/vitess}
```

And then:
```
https://github.com/vitessio/vitess/blob/master/examples/local/vtctld-up.sh#L39-L40
...
  -web_dir $VTTOP/web/vtctld \
  -web_dir2 $VTTOP/web/vtctld2/app \
```

There are several technologies that allow you to embed web files and produce a single binary. We should look at doing this for both the web files, and `config/mycnf/*` and `config/init_db.sql`.

This will simplify the installation, similar to how MySQL switched from `mysql_install_db` bootstrapping the server to `mysqld --initialize` (embedded in the server).

#### Use Case(s)

Simplified distribution and configuration. This will soon be the only reason that VTTOP and VTROOT need to be specified outside of compile time.

### PR DESCRIPTION
**Pull request by morgo**
Fixes #5502

This embeds the my.cnf files for a MySQL flavor, as well as the init_db.sql file. 

The examples have also been modified to search for vitess binaries in the PATH, and no longer specify an init-db file. They can now completely standalone from the vitess root, as long as the binaries are in the path:

```
$ mv examples/local ~/vitess-examples
$ cd ~/vitess-examples/
$ ./101_initial_cluster.sh 
add /vitess/global
add /vitess/zone1
add zone1 CellInfo
etcd start done...
Starting vtctld...
Access vtctld web UI at http://ryzen:15000
Send commands with: vtctlclient -server ryzen:15999 ...
Starting MySQL for tablet zone1-0000000100...
Starting MySQL for tablet zone1-0000000101...
Starting MySQL for tablet zone1-0000000102...
Starting vttablet for zone1-0000000100...
Access tablet zone1-0000000100 at http://ryzen:15100/debug/status
Starting vttablet for zone1-0000000101...
Access tablet zone1-0000000101 at http://ryzen:15101/debug/status
Starting vttablet for zone1-0000000102...
Access tablet zone1-0000000102 at http://ryzen:15102/debug/status
Waiting for tablets to be listening...
HTTP/1.1 200 OK
Date: Fri, 03 Jan 2020 23:45:04 GMT
Content-Type: text/html; charset=utf-8

HTTP/1.1 200 OK
Date: Fri, 03 Jan 2020 23:45:04 GMT
Content-Type: text/html; charset=utf-8

HTTP/1.1 200 OK
Date: Fri, 03 Jan 2020 23:45:04 GMT
Content-Type: text/html; charset=utf-8

Tablets up!
W0103 16:45:04.720428   19305 main.go:64] W0103 23:45:04.719741 reparent.go:185] master-elect tablet zone1-0000000100 is not the shard master, proceeding anyway as -force was used
W0103 16:45:04.720616   19305 main.go:64] W0103 23:45:04.720030 reparent.go:191] master-elect tablet zone1-0000000100 is not a master in the shard, proceeding anyway as -force was used
New VSchema object:
{
  "tables": {
    "corder": {

    },
    "customer": {

    },
    "product": {

    }
  }
}
If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).
Waiting for vtgate to be up...
vtgate is up!
Access vtgate at http://ryzen:15001/debug/status
```

The linter also reported that the contains function and mycnfTemplateFile variable of mysqld.go are unused.

I introduced DefaultVtRoot so that there will not be an error if `VTROOT` is not defined. This means that if you want to use hooks, you will need to set a `VTROOT`, unless you are okay with the default of `/usr/local/vitess/vthook` (eventually I'd like to move binary instructions to use /usr/local/vitess as the install PATH similar to how golang installs.. it's not important to switch right now, and I could have equally specified /dev/null.)

In #5502 @enisoc commented that he was concerned that embedding init_db.sql creates a security risk. In this implementation, it is still possible to overwrite with a new init_db.sql file.. so it is possible to deploy securely. 

Signed-off-by: Morgan Tocker <tocker@gmail.com>

### CODE REVIEW

**Comment by sougou** [comment]
Shouldn't there be a generated file somewhere, like rice-box.go?

**Comment by morgo** [comment]
> Shouldn't there be a generated file somewhere, like rice-box.go?

It is produced in the Makefile on build, and added to gitignore. I took this direction because there are not many config files (vs. web files), and the generation time is quick.

**Comment by sougou** [comment]
Go recommends that all generated files be pre-generated and be part of the repo. The main goal is that you should be able to just `go get` whatever binary you need.

**Comment by morgo** [comment]
@sougou makes sense. Feedback addressed.

**Pull request merged**
