### PR TITLE
vrepl endtoend flakiness fix via schema versioning

### PR DESCRIPTION
**Pull request by shlomi-noach**
This is another take (see https://github.com/vitessio/vitess/pull/10797) at fixing `onlineddl_vrepl` flakiness. This PR attempts enabling schema versioning, looking to see if that reloads schema properly.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
huh the tests are not running at all

**Comment by shlomi-noach** [comment]
grrrrr the tests won't even queue. Why?

**Comment by shlomi-noach** [comment]
`onlineddl_vrepl` tests pass reliably and consistently. The fix looks good! Let's merge this to un-flaky the tests. On my roadmap to look for alternatives to this flag.

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Pull request merged**
