### PR TITLE
Add percona-toolkit (for pt-osc/pt-online-schema-change) to the docker/lite images

### LINKED ISSUE #7602: Add pt-osc (pt-online-schema-change) to the vitess/lite images
We already bundle `gh-ost` with Vitess as an embedded binary.  However, the Online DDL feature can use `pt-osc`/`pt-online-schema-change` as well.  Unfortunately, it is difficult to embed the Percona toolkit into Vitess, because of the dependencies that the toolkit requires (perl, libdbd, etc.).  As a result, the user is then expected to provide an install of the toolkit if the user wants to use the Online DDL `pt-osc` option.   This is normally fine, but if the user is running the Vitess operator, or just using the vitess/lite container images, things are not that simple.

As a result, we should probably just bundle the percona-toolkit package, which includes `pt-online-schema-change` (and other tools) into the vitess/lite container image.  The package is very small, and some of the dependencies are already present in the vitess/lite container, so the overall image size will only grow by a few percent.

### PR DESCRIPTION
**Pull request by aquarapid**
Fixes #7602 

Signed-off-by: Jacques Grove <aquarapid@gmail.com>

### CODE REVIEW

**Review by shlomi-noach — COMMENTED** [review]
I believe you need `libdbi` and `libdbd-mysql` as dependencies.

**Comment by dkhenry** [comment]
@aquarapid what does this do to image size ? If its a large increase I think it would be better to just have a flavor that includes the files.

**Comment by aquarapid** [comment]
> I believe you need `libdbi` and `libdbd-mysql` as dependencies.

Adding the percona-toolkit package pulls in the necessary deps, both on debian and UBI (redhat).

**Comment by aquarapid** [comment]
> @aquarapid what does this do to image size ? If its a large increase I think it would be better to just have a flavor that includes the files.

@dkhenry About 3.5% increase in image (uncompressed);  I expect it to be a bit less compressed, since the new files are mostly perl and compresses well.

**Comment by dkhenry** [comment]
Thats very acceptable. 🚢

**Review by shlomi-noach — APPROVED** [review]
:camel:

**Pull request merged**
