### PR TITLE
Remove vtqueryserver

### LINKED ISSUE #5531: failing unit test: vtqueryserver on debian10/mariadb 10.3
I am getting a consistently failing unit test when running the tests in the included MariaDB 10.3 in Debian 10:

```
ok  	vitess.io/vitess/go/vt/vtgate/vtgateconn	0.003s
--- FAIL: TestPassthroughDMLs (0.02s)
    endtoend_test.go:228: expected error but got: <nil>
--- FAIL: TestTransactions (0.00s)
    endtoend_test.go:258: error: Duplicate entry '1' for key 'PRIMARY' (errno 1062) (sqlstate 23000) (CallerID: userData1): Sql: "insert into test(id, val) values (:vtp1, :vtp2)", BindVars: {#maxLimit: "type:INT64 value:\"10001\" "vtp1: "type:INT64 value:\"1\" "vtp2: "type:VARBINARY value:\"hello\" "} (errno 1062) (sqlstate 23000) during query: insert into test (id, val) values(1, 'hello')
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbc8724]

goroutine 109 [running]:
testing.tRunner.func1(0xc000209200)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0xcb73c0, 0x1720750)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
vitess.io/vitess/go/vt/vtqueryserver.testDML(0xc000209200, 0xc00017b500, 0xe08139, 0x2d, 0x1, 0x1)
	/home/morgo/vitess/go/vt/vtqueryserver/endtoend_test.go:160 +0x194
vitess.io/vitess/go/vt/vtqueryserver.TestTransactions(0xc000209200)
	/home/morgo/vitess/go/vt/vtqueryserver/endtoend_test.go:258 +0x1ad
testing.tRunner(0xc000209200, 0xe2aa50)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
FAIL	vitess.io/vitess/go/vt/vtqueryserver	3.086s
ok  	vitess.io/vitess/go/vt/vttablet/customrule/filecustomrule	0.009s
```

Because this relates to vtqueryserver, per @gedgar 's comment in https://github.com/vitessio/vitess/issues/5421 we should probably remove this utility and test rather than fix it.

### PR DESCRIPTION
**Pull request by morgo**
Fixes #5531 

This PR proposes that we remove vtqueryserver, which [per this discussion](https://vitess.slack.com/archives/C0PQY0PTK/p1566760326343400?thread_ts=1566598055.316900&cid=C0PQY0PTK) is not being used.

The tool was never documented on vitess.io, so my understanding is that there is no current usage. But if reviewers feel otherwise, I am happy to change the PR to remove the tests and then add a note to the 5.0 release notes saying it is deprecated.

The motivation for removing this, is that it was failing unit test when using MariaDB as the mysql flavor. It is not the only test that breaks, but it is easier to remove rather than fix it. I originally had this in the PR https://github.com/vitessio/vitess/pull/5559 ; but have now forked it to a separate PR.

Signed-off-by: Morgan Tocker <tocker@gmail.com>

### CODE REVIEW

**Comment by derekperkins** [comment]
Kill it

**Comment by guidoiaquinti** [comment]
cc @demmer

**Comment by sougou** [comment]
Need to resolve conflicts.

**Comment by demmer** [comment]
👍 I'm ok to remove this.

It was an interesting experiment originally, but I agree it's not worth the code bloat to keep it around. If a use case comes up again we can resurrect.

**Pull request merged**
