### PR TITLE
delete deprecated flags

### PR DESCRIPTION
**Pull request by deepthi**
Signed-off-by: deepthi <deepthi@planetscale.com>

### CODE REVIEW

**Comment by morgo** [comment]
@deepthi LGTM, but would you mind if we postponed merging this until ~January 28th? We should try and contain removals and refactorings to the first part of the development cycle.

**Comment by deepthi** [comment]
> @deepthi LGTM, but would you mind if we postponed merging this until ~January 28th? We should try and contain removals and refactorings to the first part of the development cycle.

Good point. We can wait.

**Comment by systay** [comment]
@morgo Cool to merge now?

**Comment by morgo** [comment]
> @morgo Cool to merge now?

I just gave #developers a heads up now, I will branch tomorrow. We can merge this straight after.

**Pull request merged**
