### PR TITLE
Switch ApplySchema `--sql` argument to be `StringArray` instead of `StringSlice`

### LINKED ISSUE #11785: Operator Examples: Add `commerce` sequences with vtctldclient fails on parsing
### Overview of the Issue

When running the operator example, at the third step (resharding), we are asked to add the vitess sequences to the `commerce` keyspace using `vtctldclient` using the following commands:
```
vtctldclient ApplySchema --sql="$(cat create_commerce_seq.sql)" commerce
vtctldclient ApplyVSchema --vschema="$(cat vschema_commerce_seq.json)" commerce
```

However, the first command fails with a parsing error on the first line of the `create_commerce_seq.sql` file. The file is well written:

```sql
create table customer_seq(id int, next_id bigint, cache bigint, primary key(id)) comment 'vitess_sequence';
insert into customer_seq(id, next_id, cache) values(0, 1000, 100);
create table order_seq(id int, next_id bigint, cache bigint, primary key(id)) comment 'vitess_sequence';
insert into order_seq(id, next_id, cache) values(0, 1000, 100);
```

It seems that the first line of the file is always the issue. If I commend the first two lines and executes, it passes without an issue. If I add a comment before the 4 existing line and execute, it passes well.

My current workaround is to simply add one line of comment at the beginning of the file.

### Reproduction Steps

Run the local examples until the resharding phase.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
OSX
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by ajm188**
## Description

See [this comment](https://github.com/vitessio/vitess/issues/11785#issuecomment-1323641942) for an explanation.

## Related Issue(s)

Fixes #11785.

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by dbussink — APPROVED** [review]
Is there a way we can easily add a test for this?

**Comment by ajm188** [comment]
> Is there a way we can easily add a test for this?

@dbussink done. this test fails on `vitessio:main`, with:

```
        	Error:      	Received unexpected error:
        	            	invalid argument "\"CREATE TABLE foo(id int not null primary key, name varchar(255)); CREATE TABLE bar (id int not null primary key, foo_id int not null);" for "--sql" flag: parse error on line 1, column 136: extraneous or missing " in quoted-field
        	Test:       	TestApplySchema
```

and passes with my changes

**Review by deepthi — COMMENTED** [review]
What about the other commands where we are using `StringSliceVar`? I see at least `GetSchema` and `ApplyVSchema`.

**Review by frouioui — APPROVED** [review]
This is great. Thank you for fixing this!

**Comment by ajm188** [comment]
> What about the other commands where we are using `StringSliceVar`? I see at least `GetSchema` and `ApplyVSchema`.

in most cases, `StringSliceVar` is what you want (ie. you're taking input of multiple names of "things", and it saves you the hassle of taking a raw string and doing `strings.Split(input, ",")` on it). this is one of the few exceptions, since the input itself can (and _especially_ in the case of sql statements, _almost always_) correctly contain commas, so they can't be considered separators.

**Pull request merged**
