### PR TITLE
Test Vitess against django queries

### PR DESCRIPTION
**Pull request by J0**
Relevant issue: #5166 

As per discussion with @morgo and @saifalharthi, I've written a sample test for queries which came from django. I've currently hardcoded the source file path for the log file, need to find out where to store the set of `.txt` logs which @saifalharthi has passed to me

Signed-off-by: j0 <lee.yi.jie.joel@gmail.com>

### CODE REVIEW

**Comment by deepthi** [comment]
You can create a directory called testdata under sqlparser to store .txt files.
I recommend creating a separate file for these new testcases rather than adding them to parse_test.go.

**Comment by saifalharthi** [comment]
@deepthi I think this is still a work in progress. Some logs are too big to check in the main repo. I will discuss with @J0 about what to do next.

**Comment by deepthi** [comment]
> @deepthi I think this is still a work in progress. Some logs are too big to check in the main repo. I will discuss with @J0 about what to do next.

Once you run the generated list of queries against vitess and discover which ones didn't work and needed code changes, then you can checkin files with only those queries.

**Comment by sougou** [comment]
Tests are failing because `django_queries.txt` is missing.

**Comment by J0** [comment]
Hi @sougou noted. We've opted not to push the log files such as  `django_queries.txt` up to Github as they're quite large. We're currently looking into a solution which doesn't involve using the text files directly or looking to see if we can do without the dependency on the txt file entirely.

**Comment by morgo** [comment]
@J0 how about de-duplicating the queries with `pt-query-digest`? The resulting file should be small enough.

**Pull request merged**
