### PR TITLE
Remove license headers from files

### PR DESCRIPTION
**Pull request by systay**
## Description
My understanding of the ALv2 is that it is not necessary to add a license header to every single file - it's enough to clearly state the license in the repository once.

This according to: https://infra.apache.org/apply-license.html#copy-per-file

Since we have a license file already in [LICENSE](https://github.com/vitessio/vitess/blob/main/LICENSE), I don't think we need to list the license in all the files.

### CODE REVIEW

**Review by vmg — APPROVED** [review]
This PR crashed my browser.

**Comment by deepthi** [comment]
Do we retain external authors' copyrights? For example, some code was copied from `gh-ost` and modified for Vitess.

**Comment by deepthi** [comment]
Let's hold off on merging any license changes until after 13.0 is out the door (Feb 22).

**Comment by mattlord** [comment]
I am not a lawyer, but as far as I understand things:
License and copyright are not the same thing. I don't have a strong opinion on the license per file part, although I would ask why (?), but copyright is separate. License is about acceptable use while copyright is about lineage and ownership (and it's sharable, transferrable, etc.). This is my work and these are the restrictions I place on its use.

**Comment by deepthi** [comment]
We had actually checked with CNCF a while ago and this is what we were told:

> The general response is here: https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices
>
> We do recommend a simple notice for every file, it could be just as simple as a one line "Copyright Vitess Authors, SPDX-License-Identifier: Apache-2.0"

If you follow the link, they recommend exactly what they told us in this response. No year required.
The exception is that if we copy code from some other open source repo we have to preserve whatever copyright they come with. Hence my comment/question about `gh-ost`.

**Comment by mattlord** [comment]
Sharing my related comment on another ticket: https://github.com/vitessio/vitess/issues/9629#issuecomment-1049122484

**Comment by mattlord** [comment]
Can we close this? 

You can see more details here: https://github.com/vitessio/vitess/issues/9629#issuecomment-1049122484

But in short I think you're confusing a license *header* with the actual *license text*. I think that merging this would be a serious mistake, violating FOSS norms and practices in general, along with what both the Apache Foundation and CNCF recommend. Then there's the copyright issue noted, in addition to the license header.

**Comment by deepthi** [comment]
I agree with @mattlord that this cannot be merged in its current form.
We need _at least_ a "short" copyright header in each file AND we need to preserve the copyright headers on files copied from other OSS project.
Closing for now, we can open another PR if we want to replace the existing notice with a shorter one.

**Pull request closed without merging**
