### PR TITLE
Fix schema engine reload so it accounts for swapped tables during online DDL

### LINKED ISSUE #9287: Schema engine does not reload schema correctly after online DDL
#### Overview of the Issue

 I'm seeing an issue with stale schema on the PRIMARY tablet (can be seen via localhost:19000/schemaz) after an Online DDL (vreplication-based) has successfully completed. I tried to debug this and I think I know where the bug is but I would like someone else to double check my thinking.

 * Schema Engine does a reload of schema on the tablet. There is an optimization in this code where it first gets the current list of tables from MySQL and if the table's creation-time reported by MySQL is older than the last-successful-reload-time.
 * When we do OnlineDDL cutovers, we swap tables (eg: `RENAME TABLE sbtest2 TO _swap_0f881eb64c9e11eca5ca0696249e414f, _df3be650_4c9d_11ec_ae52_0aefae84596b_20211123204229_vrepl TO sbtest2,_swap_0f881eb64c9e11eca5ca0696249e414f TO _df3be650_4c9d_11ec_ae52_0aefae84596b_20211123204229_vrepl`).
 * But the problem is that after the swap, Schema Engine reload will still not realize that the table's schema has changed because technically all we did was to swap 2 tables. So the table's creation-times have not changed according to MySQL. So Schema Engine refuses to reload the table schema even if you explicitly send a ReloadSchemaShard command via vtctlclient.

#### Reproduction Steps

1. Create a new keyspace and create a new table.

```
vtctlclient ApplySchema -sql='
CREATE TABLE sbtest1(
  id INTEGER NOT NULL,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT "c" NOT NULL,
  pad CHAR(60) DEFAULT "p" NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;
' devmvhks20

mysql> show create table sbtest1;
+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                                                                                                                                                                       |
+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sbtest1 | CREATE TABLE `sbtest1` (
  `id` int NOT NULL,
  `k` int NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT 'c',
  `pad` char(60) NOT NULL DEFAULT 'p',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

ApplyVSchema -vschema='
> {
>   "sharded": true,
>   "vindexes": {
>     "hash": {
>       "type": "hash"
>     }
>   },
>   "tables": {
>     "sbtest1": {
>       "column_vindexes": [
>         {
>           "column": "id",
>           "name": "hash"
>         }
>       ]
>     }
>   }
> }
> ' devmvhks20
```

2. Insert some rows into the new table from vtgate

```
mysql> INSERT INTO sbtest1 (id) values (1),(2);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0
```

3. Run an online DDL via vtgate to add new column to the table

```
mysql> alter table sbtest1 ADD COLUMN home_phone VARCHAR(15) DEFAULT NULL;
+--------------------------------------+
| uuid                                 |
+--------------------------------------+
| c74acc03_4d49_11ec_ae52_0aefae84596b |
+--------------------------------------+
1 row in set (0.01 sec)
```

In the primary vttablet logs, you would see the schema being reloaded.

```
[2021-11-24 17:13:02.433767] I1124 17:13:02.433596 2214408 rpc_schema.go:57] ReloadSchema requested via RPC
[2021-11-24 17:13:02.439768] I1124 17:13:02.439634 2214408 engine.go:395] schema engine created [_c74acc03_4d49_11ec_ae52_0aefae84596b_20211124171302_vrepl], altered [], dropped []
```

4. Immediately reload the schema on the shard again via vtctlclient.

```
vtctlclient ReloadSchemaShard devmvhks20/0
```

**IMPORTANT**: For this repro to work, this needs to be done before OnlineDDL cutover phase begins on the tablet. Since there is almost no data in this table, it will happen within a matter of seconds. But it should give you enough time to quickly run the `ReloadSchemaShard` command before cutover begins.

You will see the primary tablet would have reloaded schema again.

```
[2021-11-24 17:13:04.021800] I1124 17:13:04.021679 2214408 rpc_schema.go:57] ReloadSchema requested via RPC
[2021-11-24 17:13:04.027182] I1124 17:13:04.027042 2214408 engine.go:395] schema engine created [], altered [_c74acc03_4d49_11ec_ae52_0aefae84596b_20211124171302_vrepl], dropped []
```

5. Now wait for OnlineDDL cutover to finish and the schema migration workflow to complete.
6. Now insert some new rows into the table.

```
mysql> INSERT INTO sbtest1 (id) values (7),(8);
Query OK, 2 rows affected (0.00 sec)
```

Almost instantly you will see errors in vttablet logs. 

```
[2021-11-24 17:13:39.029228] I1124 17:13:39.029045 2214408 historian.go:228] Schema not found in cache for sbtest1 with pos 8189eb4a-024b-4dff-bf85-b0e37b9d105c:1-1305
[2021-11-24 17:13:39.029331] I1124 17:13:39.029085 2214408 vstreamer.go:713] Cannot determine columns for table sbtest1
[2021-11-24 17:13:39.029466] E1124 17:13:39.029290 2214408 vstreamer.go:939] stream (at source tablet) error @ 8189eb4a-024b-4dff-bf85-b0e37b9d105c:1-1305: cannot determine table columns for sbtest1: event has [3 3 254 254 15 15], schema as [name:"id" type:INT32 table:"sbtest1" org_table:"sbtest1" database:"vt_devmvhks20" org_name:"id" column_length:11 charset:63 flags:53251 name:"k" type:INT32 table:"sbtest1" org_table:"sbtest1" database:"vt_devmvhks20" org_name:"k" column_length:11 charset:63 flags:32769 name:"c" type:CHAR table:"sbtest1" org_table:"sbtest1" database:"vt_devmvhks20" org_name:"c" column_length:480 charset:45 flags:1 name:"pad" type:CHAR table:"sbtest1" org_table:"sbtest1" database:"vt_devmvhks20" org_name:"pad" column_length:240 charset:45 flags:1 name:"cell_phone" type:VARCHAR table:"sbtest1" org_table:"sbtest1" database:"vt_devmvhks20" org_name:"cell_phone" column_length:60 charset:45]
```

7. Now run another online DDL on the same table

```
mysql> alter table sbtest1 ADD COLUMN zipcode VARCHAR(15) DEFAULT NULL;
+--------------------------------------+
| uuid                                 |
+--------------------------------------+
| 3b5cd60a_4d4a_11ec_ae52_0aefae84596b |
+--------------------------------------+
1 row in set (0.01 sec)
```

Again you should see new errors in vttablet log

```
[2021-11-24 17:17:48.028220] I1124 17:17:48.028098 2214408 vcopier.go:201] Copying table _3b5cd60a_4d4a_11ec_ae52_0aefae84596b_20211124171617_vrepl, lastpk: <nil>
[2021-11-24 17:17:48.034872] E1124 17:17:48.034705 2214408 dbclient.go:107] error in stream 3, retrying after 5s: vttablet: rpc error: code = Unknown desc = column home_phone not found in table sbtest1
```

If you query the workflow status, it should report an error
```
vtctlclient Workflow devmvhks20.3b5cd60a_4d4a_11ec_ae52_0aefae84596b show
{
	"Workflow": "3b5cd60a_4d4a_11ec_ae52_0aefae84596b",
	"SourceLocation": {
		"Keyspace": "devmvhks20",
		"Shards": [
			"0"
		]
	},
	"TargetLocation": {
		"Keyspace": "devmvhks20",
		"Shards": [
			"0"
		]
	},
	"MaxVReplicationLag": 81,
	"ShardStatuses": {
		"0/northwest-0000130527": {
			"PrimaryReplicationStatuses": [
				{
					"Shard": "0",
					"Tablet": "northwest-0000130527",
					"ID": 3,
					"Bls": {
						"keyspace": "devmvhks20",
						"shard": "0",
						"filter": {
							"rules": [
								{
									"match": "_3b5cd60a_4d4a_11ec_ae52_0aefae84596b_20211124171617_vrepl",
									"filter": "select `id` as `id`, `k` as `k`, `c` as `c`, `pad` as `pad`, `cell_phone` as `cell_phone`, `home_phone` as `home_phone` from `sbtest1`",
									"source_unique_key_columns": "id",
									"target_unique_key_columns": "id",
									"source_unique_key_target_columns": "id"
								}
							]
						}
					},
					"Pos": "",
					"StopPos": "",
					"State": "Error",
					"DBName": "vt_devmvhks20",
					"TransactionTimestamp": 0,
					"TimeUpdated": 1637774177,
					"Message": "vttablet: rpc error: code = Unknown desc = column home_phone not found in table sbtest1",
					"Tags": "",
					"CopyState": [
						{
							"Table": "_3b5cd60a_4d4a_11ec_ae52_0aefae84596b_20211124171617_vrepl",
							"LastPK": ""
						}
					]
				}
			],
			"TabletControls": null,
			"PrimaryIsServing": true
		}
	}
}
```

If you look at the schema for the "sbtest1" table from the vttablet admin website http://localhost:19000/schemaz, you will also observe that it doesn't have the new column that we added earlier.

### PR DESCRIPTION
**Pull request by mvh-stripe**
## Description

This PR addresses the following bug in schema engine reload process:
 * The schema engine depends on the `information_schema.tables create_time` field to tell when a table is updated. Unlike the name might indicate, this field is updated when a structural DDL is performed on a table (e.g. a column add/delete).
 * As an optimization, the schema engine keeps track of the last time it loaded (reloaded) the schema, and saves this timestamp (called `lastChange`).
 * When reloading schema, for each table we then check the `create_time` for that table against this saved timestamp, and if it's older, we skip examining the table further for changes.
 * Vitess online DDL swaps the tables, and a table swap does not affect the `create_time` timestamp for the table (it remains the original timestamp of when online DDL created the temporary table). If after this, but before the online DDL is done and the tables are swapped, a schema reload is run (in any of the various ways), we will record all the changes in schema at that point, and save the current time in the schema engine's `lastChange` field.
 * Now, after the online DDL completes, a schema reload is internally signaled:
   * For the table we are interested in (the one that was just DDL-ed), the `create_time` field is now older than the schema engine `lastChange` field. We therefore do not update the schema engine's view of this table's schema.

Changes:
 * Instead of keeping track of the `lastChange` time in schema engine, we track the `create_time` of every table explicitly. On a subsequent refresh, if we find the `create_time` of the table reported by MySQL differs from what we have cached in-memory, then we will assume the table has changed and reload its schema.
 * This will address the issue with tables being swapped during OnlineDDL without the `create_time` being modified.

## Related Issue(s)
Fixes #9287 

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

**Comment by mvh-stripe** [comment]
@rohit-nayak-ps @deepthi any feedback on this PR? Also I noticed a lot of the CI checks failed but they look unrelated to my change. Are some of these checks flaky?

**Comment by rohit-nayak-ps** [comment]
The change made to use `tbl.CreateTime` rather than `se.lastChange` to refresh a table's schema caused a bunch of side-effects in the unit tests. The main reason was that schema changes made in a test were not applied because they occurred in the same second as a previous test. This resulted in differing errors in multiple vplayer, rowstreamer, vstreamer and vcopier tests: tables or columns not found, incorrect schema in the FieldEvents etc. I changed the schema reloading logic between tests to decouple the tests from each other.

For some reason I have not yet understood the VSchema watcher also needed to be reinitialized in vschema-related tests. 

Anyway as of now I have got the unit_tests working locally. I will clean it up and test it some more tomorrow and push a commit to this PR's branch and check how it behaves in CI.

**Comment by rohit-nayak-ps** [comment]
> @rohit-nayak-ps @deepthi any feedback on this PR? Also I noticed a lot of the CI checks failed but they look unrelated to my change. Are some of these checks flaky?

The new approach and code changes look good, but I was distracted by all the failing tests and will review again once the tests run in CI.

**Comment by rohit-nayak-ps** [comment]
Since I couldn't push to the mvh repo, I created https://github.com/vitessio/vitess/pull/9324 based off of the commit in this PR. Key changes:
* bring back the `se.lastChange` logic to handle DDLs on the same table within a second. Otherwise the `tbl.CreateTime` matches that in the information_schema and the later DDLs are not reflected in the cached schema
* reload schema in unit tests to decouple sql changes from changes made in previous tests. Since we use a singleton schema engine, schema changes made in a test within a second of schema changes in a previous test can get ignored. Also when tablets get created/deleted we were not explicitly reloading the schema.

All tests pass in that PR. Please review my commit and cherry-pick it if you agree with the changes.

**Comment by rohit-nayak-ps** [comment]
Replaced by https://github.com/vitessio/vitess/pull/9324.

**Pull request closed without merging**
