### PR TITLE
update vite base to respect absolute path

### PR DESCRIPTION
**Pull request by pbibra**
<!--
  Thank you for your contribution to the Vitess project.
  How to contribute: https://vitess.io/docs/contributing/
  Please first make sure there is an open Issue to discuss the feature/fix suggested in this PR.
  If this is a new feature, please mark the Issue as "RFC".
 -->

<!-- if this PR is Work in Progress please create it as a Draft Pull Request -->

## Description

This PR fixes the asset paths for VTAdmin so that we can open schema/shard pages in new tabs

`index.html` before

```
[build] cat index.html                                                                                                                                                                                                                    22:45:37  ☁  main ☀
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="./favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <link rel="apple-touch-icon" href="/logo192.png" />
    <link rel="manifest" href="./manifest.json" />
    <script src="./config/config.js"></script>
...
    <!-- See also the useDocumentTitle hook, which sets document.title dynamically. -->
    <title>VTAdmin</title>
    <script type="module" crossorigin src="./assets/index-49a95637.js"></script>
    <link rel="stylesheet" href="./assets/index-ef40fbc9.css">
  </head>
...
</html>
```

`index.html` after

```
vitess/web/vtadmin/build$ cat index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <link rel="apple-touch-icon" href="/logo192.png" />
    <link rel="manifest" href="/manifest.json" />
    <script src="/config/config.js"></script>
...
    <!-- See also the useDocumentTitle hook, which sets document.title dynamically. -->
    <title>VTAdmin</title>
    <script type="module" crossorigin src="/assets/index-8e9973e7.js"></script>
    <link rel="stylesheet" href="/assets/index-ce497355.css">
  </head>
...
</html>
```

**Note that the "." in front of the asset hrefs are gone**
## Related Issue(s)

https://github.com/vitessio/vitess/issues/13109

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

## Deployment Notes

<!-- Notes regarding deployment of the contained body of work. These should note any db migrations, etc. -->

### CODE REVIEW

**Review by deepthi — APPROVED** [review]
LGTM
@pbibra did you click around on other pages to make sure this doesn't break anything?

**Comment by notfelineit** [comment]
I'll help test this tomorrow as well. Thank you for your contribution!

**Comment by pbibra** [comment]
> LGTM @pbibra did you click around on other pages to make sure this doesn't break anything?

yes! Things look good on our end. Tablet debug pages open correctly, things in new tabs are rendering now, gates, tablets, shard pages all load as normal

**Comment by notfelineit** [comment]
@pbibra would you mind sharing some screenshots or gifs on this PR of it working?

**Comment by pbibra** [comment]
> @pbibra would you mind sharing some screenshots or gifs on this PR of it working?

posted!

**Review by notfelineit — APPROVED** [review]

**Pull request merged**
