### PR TITLE
Allow override of build git env in docker/base builds

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

This PR allows `BUILD_GIT_BRANCH` and `BUILD_GIT_REV` to be passed-into docker builds using `Dockerfile`s from `docker/base`. Currently it is [possible to override `CGO_ENABLED` and `BUILD_NUMBER`](https://github.com/vitessio/vitess/blob/main/docker/base/Dockerfile#L29-L33), but not these git-related vars

Specifically, this is useful when [the `BUILD_GIT_BRANCH` default](https://github.com/vitessio/vitess/blob/main/tools/build_version_flags.sh#L24-L31) is not useful _(`HEAD`)_ and an override from your CI is needed
```bash
$ curl -s localhost:15000/debug/vars|jq .BuildGitBranch
"HEAD"
```

If possible, please backport to v14+ 🙏 

## Related Issue(s)

Resolves https://github.com/vitessio/vitess/issues/11967

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by deepthi** [comment]
@frouioui can you take a look? Also seems like we aren't keeping the bootstrap_version up to date in the `vitess/base` Dockerfiles. Not sure how those are working right now with such an old bootstrap_version.
Separately, we should probably add you and @GuptaManan100 as code owners for docker files.

**Comment by frouioui** [comment]
> Separately, we should probably add you and @GuptaManan100 as code owners for docker files.

@deepthi, done in https://github.com/vitessio/vitess/pull/11981.

**Review by frouioui — APPROVED** [review]
This change is looking good to me. I am assuming you are doing manual build of `vitess/bootstrap` and `vitess/base` on your own and require the git revision to not be `HEAD`.

**Comment by frouioui** [comment]
> Also seems like we aren't keeping the bootstrap_version up to date in the vitess/base Dockerfiles. Not sure how those are working right now with such an old bootstrap_version.

@deepthi - The bootstrap version used by `vitess/base` is in sync with the one used to build `vitess/bootstrap`. The branch was just not up-to-date with `main`. I merged `main` onto that branch.

**Comment by timvaillancourt** [comment]
> I am assuming you are doing manual build of vitess/bootstrap and vitess/base on your own and require the git revision to not be HEAD.

@frouioui yes, that is correct. I haven't figured out why `git` returns `HEAD` but overriding the var with `$GIT_BRANCH` from Jenkins fixes it. Some googling suggests it's due to a detached-head state in `git` 🤷‍♂️

**Review by mattlord — APPROVED** [review]
Thanks! ❤️

**Pull request merged**
