### PR TITLE
Refactor: Remove unused ExecuteBatch and BeginExecuteBatch from vttablet

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Description

This PR removes unused ExecuteBatch and BeginExecuteBatch. It is not used in queryservice.

## Related Issue(s)

- https://github.com/vitessio/vitess/issues/6407

## Checklist
- [X] Tests were added or are not required
- [X] Documentation was added or is not required

### CODE REVIEW

**Review by deepthi — COMMENTED** [review]
Even though we no longer call these from vtgate, they are a public API.
I'm not certain that it is safe / ok to delete these without going through a deprecation cycle.

**Comment by harshit-gangal** [comment]
The deprecation was announced in 7.0 release. This is more of code cleanup now.

**Comment by deepthi** [comment]
> The deprecation was announced in 7.0 release. This is more of code cleanup now.

The linked RFC says "deprecate calls in vtgate". Did we find out from the community that no one uses the vttablet query service API directly so it's ok to remove things from there?

**Review by GuptaManan100 — APPROVED** [review]
Everything else LGTM, but do we need to go through a deprecation cycle where we log a deprecation warning before removing it from a public API?

**Comment by GuptaManan100** [comment]
Oh I see that was already brought up by @deepthi

**Comment by harshit-gangal** [comment]
> > The deprecation was announced in 7.0 release. This is more of code cleanup now.
> 
> The linked RFC says "deprecate calls in vtgate". Did we find out from the community that no one uses the vttablet query service API directly so it's ok to remove things from there?

That is the general expectation that no one will use queryservice API directly as this would require managing connections and session by the caller. I will post on slack to see if there is any feedback.

**Review by deepthi — APPROVED** [review]

**Pull request merged**
