### PR TITLE
Fix order of DeleteKeyspace operations, to delete deeper nodes first

### PR DESCRIPTION
**Pull request by teejae**
Signed-off-by: Toliver Jue <toliver@planetscale.com>

### CODE REVIEW

**Comment by sougou** [comment]
This makes sense. @rafael can you confirm this is good?

**Comment by deepthi** [comment]
> This makes sense. @rafael can you confirm this is good?

@rafael this looks like the same error we were looking at last week.
@teejae this is awesome. Can you add a unit test?

**Comment by rafael** [comment]
@teejae - Thanks for this contribution. 

Agreed with @deepthi, if we could add a test that would be great.

**Comment by sougou** [comment]
@teejae ping

**Comment by teejae** [comment]
i don't have time to write a test for this right now. i believe @deepthi mentioned she might take this on.

**Comment by teejae** [comment]
abandoning PR

**Pull request closed without merging**
