### PR TITLE
Add read-only token permissions to GitHub Action workflows

### LINKED ISSUE #12717: Set read-only token permissions for all workflows
By default, GitHub workflows run with write-all permissions. This is dangerous, since it opens `vitess` up to supply-chain attacks. [GitHub itself](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets) recommends ensuring all workflows run with minimal permissions.

As far as I can tell, `vitess`' workflows are mainly used for testingand therefore don't need such broad permissions.

This issue can be solved in two ways:

- add top-level read-only permissions to all workflows, and then give additional job-level permissions as necessary; and/or
- set the default token permissions to read-only in the repo settings.

I have a PR ready with the workflow changes (and to their templates), if you're interested.

If you instead (or also) wish to modify the default token permissions:

1. Open the repo settings
2. Go to [Actions > General](https://github.com/vitessio/vitess/settings/actions)
3. Under "Workflow permissions", set them to "Read repository contents and packages permissions"

If you wish to only modify the default token permissions, know that you'll need to modify any workflows that require additional permissions.

---

**Disclosure**: My name is Pedro and I work with Google and the Linux Foundation's [Open Source Security Foundation (OpenSSF)](https://www.openssf.org/) to improve the supply-chain security of the open-source ecosystem.

### PR DESCRIPTION
**Pull request by pnacht**
## Description

As described in the issue below, this PR adds read-only token permissions to all GitHub Action workflows, including their respective templates.

`close_stale_pull_requests.yml` needs `pull_request: write` permissions, so those were granted at the job level, ensuring that any future jobs added to the workflow don't have that permission unnecessarily.

## Related Issue(s)

Fixes #12717 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by frouioui — COMMENTED** [review]
Hello Pedro and thank you for your first contribution. This looks good to me. However, I'll apply your change to even more workflows in a subsequent commit.

**Review by frouioui — APPROVED** [review]

**Review by GuptaManan100 — APPROVED** [review]
LGTM

**Comment by pnacht** [comment]
@frouioui thanks for the additional changes! I can't believe I missed so many workflows!

One question, though: why did you grant `create_release.yml` write-all permissions? Is it for the `csexton/release-asset-action`? Given that it authenticates using a secret token (not the workflow's normal token), I don't think that's necessary.

**Comment by frouioui** [comment]
> One question, though: why did you grant create_release.yml write-all permissions? Is it for the csexton/release-asset-action? Given that it authenticates using a secret token (not the workflow's normal token), I don't think that's necessary.

Hello @pnacht! It seems like we are using the auto-generated GitHub Token that Actions gives us.

**Comment by frouioui** [comment]
Merging this now, we can always modify `create_release.yaml` in a subsequent Pull Request if we are not agreeing.

**Comment by frouioui** [comment]
> Also, [`create_release.yml`](https://github.com/vitessio/vitess/blob/e1b79bee46265926bf23d129dfa30186496c37ec/.github/workflows/create_release.yml#L28-L32) has the following:
> 
> ```yaml
>     # TEMPORARY WHILE GITHUB FIXES THIS https://github.com/actions/virtual-environments/issues/3185
>     - name: Add the current IP address, long hostname and short hostname record to /etc/hosts file
>       run: |
>         echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
>     # DON'T FORGET TO REMOVE CODE ABOVE WHEN ISSUE IS ADRESSED!
> ```
> 
> The linked issue has been fixed.

I'll open a PR now to remove this unnecessary bit of code.

**Pull request merged**
