### PR TITLE
Add a Go client for messaging

### PR DESCRIPTION
**Pull request by derekperkins**

### CODE REVIEW

**Comment by derekperkins** [comment]
@sougou Can you take a look at this and let me know if you agree with the direction I'm taking? If so, I'll go ahead and add tests. Other than relying on hardcoded column ordering, I really like the way it shaped up.

**Comment by sougou** [comment]
First reaction: I didn't expect to see so much scaffolding on the client side for messages. The original idea is that messages should look like a normal SQL table:
* To create a message, you issue a normal `insert`.
* To read, you `stream` instead of `select`.
* To ack, you `update`. I think this part can be improved.

The high level question: is there something missing in the messages abstraction that is requiring you to build all this? If so, we should identify those gaps and fill them.

Otherwise, what you've built in Go, we have to build for all other languages.

If this is mostly a convenience wrapper, then I see the value of it, which is more parallel to an OR mapper, but one that also understands some higher level functions of messages. Is this what you had in mind?

**Comment by derekperkins** [comment]
This is just a convenience wrapper to allow for clients to interact with Vitess messages in a similar fashion to other message queues.

The only things not supported yet by Vitess messaging are:
- failed message status, which I work around here by setting the next time to the max value
- the ability to `Nack` a message, which I just left out to be handled by timeouts

Now that custom fields are supported, is `message` a required field or is it treated simply as a custom field?

**Comment by derekperkins** [comment]
Also, I started writing this internally before deciding to check if it made sense to contribute. If you don't feel like it belongs upstream in the main Vitess project, we'll just use it ourselves and my feelings won't be hurt. :)

**Comment by sougou** [comment]
We should work on getting those functionalities in as DMLs. I think you've already filed bugs for them?

BTW, the code looks pretty nice. So, I'd recommend adding it to contribs :).

I'll see if I can whip up a demo by hacking examples/demo/run.py, and I'll paste the results in here in a few mins.

**Comment by sougou** [comment]
So, I wasn't able to show the demo because of some vtgate buffering issue, which I'll fix. Essentially, the answer is that there is no requirement about a `message` field in a message table. You can add any number of columns to it just like a regular table, and they will all be returned when you issue a `stream * from message`, similar to a `select *`.

For example, if you created a message table like this:
```
create table message(
        time_scheduled bigint,
        id bigint,
        time_next bigint,
        epoch bigint,
        time_created bigint,
        time_acked bigint,
        val1 bigint,
        val2 varchar(128),
        primary key(time_scheduled, id),
        unique index id_idx(id),
        index next_idx(time_next, epoch))
comment 'vitess_message,vt_ack_wait=1,vt_purge_after=3,vt_batch_size=2,vt_cache_size=10,vt_poller_interval=1'
```

After you issue an insert of this form:
```
insert into message(id, val1, val2) values(1, 10, 'derek');
```

A `stream * from message` will return something like this:
```
+----+---------------------+------+-------+
| id | time_scheduled      | val1 | val2  |
+----+---------------------+------+-------+
|  1 | 1519104656110214096 |   10 | derek |
+----+---------------------+------+-------+
```

**Comment by bbeaudreault** [comment]
My 2 cents here:

Vitess is a DB sharding system, not a message queueing system. IMO it should never have been baked into vitess but that ship sailed last year. So adding code to the main codebase of vitess in order to "allow for clients to interact with Vitess messages in a similar fashion to other message queues" just stands to pollute the codebase.

I like the idea of having an ecosystem of "vitess-native" apps like message queues. But it should live outside of the main vitess repo. To that end, IMO any client code should go into the upcoming vitessio organization, under a different repo therein. Ideally all code for message queues would be eventually ripped out of vitess and put there. That may not be possible due to how it was implemented, but maybe as hooks are added over time it may eventually be possible. Until then we can avoid adding more message queues support code in the main repo.

**Comment by derekperkins** [comment]
@bbeaudreault I totally agree on building out the Vitess ecosystem, and that this belongs in a separate repo. While we're waiting for that migration, this code is currently pushed into a new top level `contrib` folder to keep it separated from the core code.

While I understand your reticence towards adding the core messaging functionality, I think there is a lot of precedent and value in including in the Vitess. If the messaging component ran separately from vtgate, it seems like it would be near impossible to include messages alongside data commits. Many people, including @sjmudd, use MySQL as a backing store for queues, and this enhances the experience. Other queues, including the Google Task Queue / Datastore provide similar transactional guarantees, where a message is only enqueued on a successful data write. The fact that Vitess is a DB sharding system is what truly enables efficient message queuing.

That being said, if there were a way to pull it out of the core without compromising the transactional capabilities, I wouldn't oppose it.

> Would be a good start to a vitessio/message-queue-client repo

Would you envision that as a repo that would contain clients for all languages, or would you have separate repos for those, e.g. `message-queue-client-go` `message-queue-client-java`, etc? I lean towards multiple repos. It will be very interesting to see how the Vitess ecosystem progresses.

**Comment by bbeaudreault** [comment]
@derekperkins sorry yea just to be clear I don't want to hamstring the queues features. I think it would be great for vitess to build out the necessary plugin integration points such that one could install message queues as a plugin and get everything nice that comes with it. Not sure how possible that is, but may a future improvement.

In terms of multiple repos I'm not sure.  I can see two good options: 

1) `vitessio/vitess-queues`.  Includes the core server plugin (future) and all the clients. Similar to how the existing java client exists within the main vitess repo.

2) hyper granular repos -- so a separate repo for each component and each client.

There is probably a middle ground too, but from those I think I would personally prefer the first option.  Not sure if there's a technical reason to do either, or if it will just come down to taste.

**Comment by sougou** [comment]
Personally, messages were a pleasant distraction for me. I'm actually surprised that the investment is paying off (two users already).

Having said that, although it's theoretically possible to have built it outside or on top of vitess, I don't think it could be as efficient as it is right now. In fact, this is what inspired us to build it inside. YouTube had so many custom implementations, and each of them had made impractical trade-offs leading to bottlenecks or scalability problems.

It's also true that every database vendor has been forced by their customers to come up with a queuing solution. It's almost like anyone that uses an RDBMS also wants queuing functionality. The vendors seem to have implemented it as a separate service, though. But then, maybe they shouldn't have. Our gut feel made us think that this will pay off in the long run. Only time will tell.

**Comment by bbeaudreault** [comment]
My main concern and a reason for keeping it separate is that it's not a great precedent to set as the community grows. There is some benefit in having focus, especially for a database (imo). It adds binary and configuration bloat for those that don't want it, and is a thing vitess developers always need to keep in mind now as changes are made to vitess core. That's probably why most vendors have kept it separate, potentially at the cost of performance. 

Ideally there would be a first-class coprocessor framework which enables queues as well as other novel implementations/apps down the road, by providing hooks in the critical places for such features. This allows each coprocessor to have its own focused owners with their own codebase, and to allow the core vitess developers to focus on building a great DB as well as maintaining a robust coprocessor framework.

Anyway, sorry to distract from the main issue at hand. I think this is the right long term path, but may be wrong, and either way perhaps doesn't need to be decided now.

**Comment by derekperkins** [comment]
No worries, I don't think it's distracting. This is a conversation that needs to be had at some point, and I hope that I'm not coming across defensive. There should always be pushback, since that leads to better outcomes.

**Comment by derekperkins** [comment]
@sougou Presumably you already have access to the `vitessio` GitHub organization. If we're not planning on ever committing this to the main Vitess project, should we go ahead and create `vitessio/messages` and push this code over there?

**Comment by sougou** [comment]
Let's wait till vitess is moved. Want to avoid any complications until that's done :).

**Comment by derekperkins** [comment]
@sougou This is ready for review.

**Comment by alainjobart** [comment]
So you're going to add tests next, right? I won't merge just yet then.

**Comment by derekperkins** [comment]
Moved to https://github.com/vitessio/messages

**Pull request closed without merging**
