### PR TITLE
Run vdiff concurrently per-table

### PR DESCRIPTION
**Pull request by ajm188**
Signed-off-by: Andrew Mason <amason@slack-corp.com>

## Description

This follows the original implementation, in that we fail everything on the first error encountered.

Finally fixed my local setup to sanity check against the local example:

```
❯ vtctlclient -server "localhost:15999" VDiff customer.cust2cust
Summary for customer: {ProcessedRows:0 MatchingRows:0 MismatchedRows:0 ExtraRowsSource:0 ExtraRowsTarget:0}
Summary for corder: {ProcessedRows:0 MatchingRows:0 MismatchedRows:0 ExtraRowsSource:0 ExtraRowsTarget:0}
```

## Related Issue(s)

- 

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [x]  VReplication
- [x]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Comment by ajm188** [comment]
So on the one hand I am seeing this in the failure logs:

```
E0413 01:04:25.654791   28153 vdiff.go:367] one or more tables provided are not present in the workflow: [t1 t2 t3 t5], map[t1:0xc000098a80 t2:0xc000098d80 t3:0xc000098e00]
```

but on the other hand there are a lot of dial errors and timeouts connecting to tablets and to the topo, and tests all fail like this one:

```
--- FAIL: TestMoveTablesV2Partial (0.00s)
    fake_tablet_test.go:114: 
        	Error Trace:	fake_tablet_test.go:114
        	            				traffic_switcher_env_test.go:100
        	            				traffic_switcher_env_test.go:85
        	            				workflow_test.go:271
        	Error:      	Received unexpected error:
        	            	FullyQualifiedHostname: failed to reverse lookup this machine's local IP (10.1.0.25): lookup 10.1.0.25: Name or service not known
        	Test:       	TestMoveTablesV2Partial
```

going to kick it once more and hope this is "weird networking/CI issues"

**Comment by rafael** [comment]
Ah sorry, I did not look at this earlier. This TODO is more complicated. Inside each of the diffTable calls, there is some synchronization work that needs to happen across the streams involved in the diff.  I don't think this approach will work here unfortunately.

**Comment by rohit-nayak-ps** [comment]
Should we close this?

**Comment by ajm188** [comment]
ya, closing!

**Pull request closed without merging**
