### PR TITLE
Perform Fast Shutdowns

### PR DESCRIPTION
**Pull request by mattlord**
## Problem
There are various times -- most notably when performing a [`PlannedReparentShard`](https://vitess.io/docs/reference/programs/vtctl/shards/#plannedreparentshard) operation for planned maintenance -- that you want the tablet to shutdown as quickly as possible. You should be able to get this by [passing the immediate flag to `TxEngine.shutdown()`](https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/tabletserver/tx_engine.go#L374-L380) or when doing a shutdown and [having hit the `transaction_shutdown_grace_period`](https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/tabletserver/tx_engine.go#L408-L417).

Today, in both cases we _do not_ immediately shutdown as one might expect. Instead [we attempt to _explicitly_ rollback all transactions via a `rollback` statement](https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/tabletserver/tx_pool.go#L115-L122). On busy systems with potentially long running multi-statement transactions and transactional statements, the current behavior causes reparents to fail. So we unnecessarily fail to complete the requested operation and cause a period of downtime -- where the master tablet for this shard is not serving any traffic while demoted as part of the reparent attempt -- in the process.

## Solution
When immediate shutdown has been requested or we have hit the defined `transaction_shutdown_grace_period` we should implicitly rollback the transactions by closing the connections. This patch attempts to do that.

### CODE REVIEW

**Comment by mattlord** [comment]
This branch passes my specific test case, which is this:
Setup: `mysql --socket=/tmp/test_shard_1a.sock -u root -e "create database if not exists test; create table if not exists test.test (id bigint unsigned not null auto_increment primary key, company varchar(100) default 'LordCo', email varchar(100), index(email)); insert into test.test (email) values ('matt@lordco.com'), ('faith@lordco.com'), ('sid@lordco.com'), ('lily@lordco.com'), ('snickers@lordco.com');"`

Test:
```
while true; do echo "Before: "; vtctl $TOPOLOGY_FLAGS ListAllTablets 2>/dev/null;
    mysql --protocol=tcp --port=16306 -u test-rw -ptest -D test_shard/-7f -e "start transaction; select * from test.test; select sleep(30); insert into test.test (company, email) values ('acme', 'bob@acme.com'); select sleep(20); insert into test.test (company, email) values ('acme', 'faith@acme.com'); select sleep(20); insert into test.test (company, email) values ('acme', 'sid@acme.com'); select sleep(20);" & \
    mysql --protocol=tcp --port=16306 -u test-rw -ptest -D test_shard/-7f -e "update test.test set email='matt@lordco.com' where email='mlord@lordco.com'; set workload='olap'; select sleep(30);" & \
    sleep 5 && \
    vtctl $TOPOLOGY_FLAGS -alsologtostderr PlannedReparentShard -keyspace_shard=test_shard/-7f -wait_slave_timeout 6.0s;
    echo -e "\nAfter: "; vtctl $TOPOLOGY_FLAGS ListAllTablets 2>/dev/null;
    mysql --protocol=tcp --port=16306 -u test-rw -ptest -D test_shard/-7f -e "select * from test.test"; sleep 60;
done
```

I'd love to know what thoughts people have on the solution proposed here, what additional tests I should create and/or run, etc. 

Thanks!

**Comment by harshit-gangal** [comment]
I think the approach looks fine to me.
The unit test I would like to see is on tx_engine. That for an on-going transaction we receive a commit and that commit failed because PRS closed all the connection and released back to pool. 
The Commit failure should not release additional connection back to pool. 

https://github.com/vitessio/vitess/blob/fddb82a0daf57fea9238beb63c7696bb20031a58/go/vt/vttablet/tabletserver/tx_engine.go#L283 - this call should fail in the unit test.

**Comment by harshit-gangal** [comment]
@deepthi - PTAL

**Comment by harshit-gangal** [comment]
@mattlord is there any blocker? Are you able to make progress?

**Comment by mattlord** [comment]
> @mattlord is there any blocker? Are you able to make progress?

No blockers, just been busy with project work on my side. I will try and dive into the tests more this week.

**Comment by mattlord** [comment]
@harshit-gangal would this not be enough? https://github.com/vitessio/vitess/pull/6645/commits/3dd8ecb0db7f7c3cd0331960f6bf2297c6ec957e

**Comment by mattlord** [comment]
@harshit-gangal would this not be enough? https://github.com/vitessio/vitess/pull/6645/commits/3acaa71da6e372185889aa8ad7e53c6ea8a210d7

**Comment by mattlord** [comment]
We can now see these unit test failures:
```
--- FAIL: TestTabletServerMasterToReplica (0.00s)
##[error]    tabletserver_test.go:114: ch should not fire
```

[As the test is assuming we're NOT doing a fast shutdown where we close all connections](https://github.com/mattlord/vitess/blob/fast_shutdown/go/vt/vttablet/tabletserver/tabletserver_test.go#L110-L117).

**Comment by mattlord** [comment]
@harshit-gangal there seems to be assumptions throughout the tests that even when doing an "immediate" shutdown that certain non-immediate / graceful shutdown behavior occurs. I'm not sure what you think the best approach is. Should we update all of these tests to NOT use `tx_engine.shutdown(true)` for an immediate shutdown of the tx engine when they expect graceful behavior? But the tests seem to expect slightly different behavior still when passing true vs. false to `tx_engine.shutdown()`: 
  - **true**: attempt to issue an explicit `rollback` statement in each connection on the demoted master once the currently active statement finishes
  - **false**: do nothing and wait for all ongoing transactions to complete (`commit` or `rollback`) or we hit the remote operation timeout (or some other context timeout) and rollback the master demotion  

So I'm not sure if we want to maintain the distinction between an actual immediate shutdown by closing the connections vs. explicitly rolling back the transactions ASAP? IMO, the notion of an immediate shutdown that waits for any long running statement to finish so that it an issue an explicit rollback statement is not immediate -- and that is the crux of the issue. But I also have no doubt that there were good reasons for things being the way they are. Can you offer any guidance here?

Thanks!

**Comment by harshit-gangal** [comment]
I do not have options around keeping rollback, may be I am not fully aware when that will be useful. To me closing connection is equivalent to rollback. Option 1 and 2 kind of look same to me. Only thing that additional happens in Option 2 is not touch any in use connection to be rolled back.

@deepthi has more understanding of these process. I will let her take this decision.

**Comment by sougou** [comment]
This took some convoluted race analysis to figure out the best course of action. Here's the TL;DR:

The connections that are in the pool are lock-free. This is because there are higher level control mechanisms that ensure that only one goroutine accesses them. So, invoking `InTransaction` or `Releasef` on those connections will result in data race. Also, `Releasef` is not idempotent. The goroutinge that holds the connection may eventually end up invoking `Releasef`, which will end up returning an extra connection to the pool and will mess up the accounting.

Either we have to add mutexes to the connection and make Releasef idempotent, or we have to solve this problem within the context of existing mutexes. We're going to look at the latter approach.

The call-stack on shutdown is as follows:
* TxEngine.shutdown
* TxEngine.rollbackTransactions
* TxPool.RollbackNonBusy
* StatefulConnectionPool.GetOutdated
* Numbered.GetOutdated

What we know:
* TxEngine has no mutex
* TxPool has no mutex
* StatefulConnectionPool has no mutex
* Numbered is at the lowest level and does have a mutex.

We have to essentially rewrite `rollbackTransactions` to achieve the above two objectives without causing a data race. This can be done as follows:
* TxEngine.rollbackTransactions will invoke TxPool.RollbackAll instead of TxPool.RollbackNonBusy
* TxPool.RollbackAll will invoke StatefulConnectionPool.GetOutdated like before and rollback the connections that are not in use.
* TxPool.RollbackAll will then invoke a new StatefulConnectionPool.FetchAndReleaseAll.
* StatefulConnectionPool.FetchAndReleaseAll will invoke Numbered.FetchAndUnregisterAll.
* Numbered.FetchAndUnregisterAll will use the mutex to atomically forget and return all current resources.

* TxPool.RollbackAll: upon return from StatefulConnectionPool.FetchAndReleaseAll, it will Close all those connections and Release a corresponding empty connection to the TxPool.

Eventually, the goroutine that was stuck executing a query will return. At that point, it will attempt to unlock that connection: https://github.com/vitessio/vitess/blob/64c2c54d18b71163e950175b9a8f38b042caad96/go/vt/vttablet/tabletserver/query_executor.go#L119. The unlock will fortunately fail to add the connection back to Numbered pool because it has now been cleared (by  Numbered.FetchAndUnregisterAll), and that number will never be reused again.

Race conditions:
* After StatefulConnectionPool.GetOutdated gets invoked, and before StatefulConnectionPool.FetchAndReleaseAll gets called, a connection could be unlocked, returned to the numbered pool. If so, Numbered.FetchAndUnregisterAll will still catch it.
* It is also possible that the connection was Released through a commit or rollback. If so, the numbered pool will not have the connection, but that connection would have gone back to the StatefulConnectionPool.
* This is the tricky one. It is possible that a Releasef by a request to commit or rollback a transaction after a successful pool close. If so, we have to prevent that Releasef from adding an extra connection to the pool. We can prevent this by adding conditional code here https://github.com/vitessio/vitess/blob/64c2c54d18b71163e950175b9a8f38b042caad96/go/vt/vttablet/tabletserver/stateful_connection.go#L153-L154.

if pool.unregister returns a failure, then you should skip invoking `sc.dbConn.Recycle`. In all the other cases, the accounting is expected to be consistent.

**Comment by sougou** [comment]
Reading back at my own comments, maybe we should explore adding a mutex to StatefulConnection and see how deep that rabbit hole goes.

**Comment by sougou** [comment]
I looked at the approach to add a mutex to StatefulConnection. But that brought in its own complications. The changes would be more localized, but there are many functions in that connection, and they would all have to cooperate with each other on concurrency.

So, here's a proposal for a third approach:

Change `ResourcePool` and `Numbered` to be more forgiving:
* ResourcePool: If a connection is returned and it's already full, it currently panics. Instead, it will just close the resource and throw it away.
* Numbered: if a connection is returned, and it's not on its list, it currently ignores the request. Instead, it will close the resource and throw it away.

Change TxPool.WaitForEmpty call to TxPoolAbandonInUseConnections: This will change the Numbered pool to forget all its ids, and fill back the Conn Pool with the number of nil connections that are in use.

The queries that are currently executing will eventually return. When they are put back into the Numbered pool, they will be closed. If they were in use during a commit or rollback, that code will try to put them back into the conn pool, and that will also cause those connections to be closed.

Race condition:
After we switch to NonMaster mode, someone can start a read-only transaction. At this point, an older connection can be returned. But this is ok. It just means that the read-only connection will eventually be discarded instead of the old one. These are almost impossible corner cases, but it's good to know that the system will still handle them correctly if they happened.

This change feels much simpler. The only downside is that the queries that currently executing will not be killed. A small price to pay.

**Comment by harshit-gangal** [comment]
I was also thinking about the last approach. I do understand why we cannot kill the inUse connection? I think if we just discard any extra connection returned to pool. It should be ok to even kill the inUse connection.

**Comment by sougou** [comment]
> I was also thinking about the last approach. I do understand why we cannot kill the inUse connection? I think if we just discard any extra connection returned to pool. It should be ok to even kill the inUse connection.

You'll introduce one or two data races if you try to kill the inUse connection. This is because, the `Close` function accesses `dbConn`.

**Comment by deepthi** [comment]
@mattlord shall we close this? Since @sougou is working on #6982?

**Comment by mattlord** [comment]
Closing this in favor of the WiP upstream PR: #6982

**Comment by sougou** [comment]
You can also follow along here https://github.com/planetscale/vitess/tree/ss-fs2-fast-shutdown

**Pull request closed without merging**
