### PR TITLE
Rebase #3450 Use destination master for comparison during split clone

### PR DESCRIPTION
**Pull request by deepthi**
After rebase, made the following changes:
1. set attempt := 1 in nextWithRetries
2. change worker test to stop master while the copy is running instead of before starting SplitClone
3. Fix bug in cancelVerticalResharding that was causing vertical_split tests to fail with this change

@tirsen Please review

### CODE REVIEW

**Comment by systay** [comment]
LGTM 👍

**Comment by sougou** [comment]
@rafael @tirsen: @deepthi has fixed up this old PR.
Can you eyeball this before I merge?

**Comment by tirsen** [comment]
@mpawliszyn Can you have a look too. I think you've been working on the retries here as well right?

**Comment by tirsen** [comment]
I'm guessing you've only changed test code not production code? In that case LGTM, otherwise could you point to any production code you changed?

**Comment by deepthi** [comment]
@tirsen 
here are the changes from your PR:
1. restartable_result_reader.go:nextWithRetries
`attempt := 1`. You had changed this to `attempt := 0`
2.  executor.go:checkError	
      ` - case errNo == "2002" || errNo == "2006" || errNo == "2013":
       +case errNo == "2002" || errNo == "2006" || errNo == "2013" || errNo == "1053":`
This is to allow mysql going down and coming back up while SplitClone is running

**Pull request merged**
