### PR TITLE
txthrottler: add metrics for topoWatcher and healthCheckStreamer

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

This PR adds additional metrics to `go/vt/vttablet/tabletserver/txthrottler` in order to understand:
1. How many topo watchers are opened by `txthrottler`
    - `TransactionThrottlerTopoWatchers` with `cell` label
2. How many healthchecks are read and recorded by `txthrottler`
    - `TransactionThrottlerHealthchecksRead` with `cell` + `DbType` label
    - `TransactionThrottlerHealthchecksRecorded` with `cell` + `DbType` label
3. Adds a code cleanup suggestion in `.StatsUpdate()` from @shlomi-noach (on earlier PR)

## Related Issue(s)

Relates to issue: https://github.com/vitessio/vitess/issues/13068. This PR will help gauge the effectiveness of https://github.com/vitessio/vitess/pull/13062

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
LGTM. I don't think there's any concurrency issues since both newly introduced maps are only populated on init time, right?

**Comment by timvaillancourt** [comment]
> LGTM. I don't think there's any concurrency issues since both newly introduced maps are only populated on init time, right?

@shlomi-noach yes, this is populated at init only (at least for now) 👍

**Comment by timvaillancourt** [comment]
Bump to keep this open

**Review by GuptaManan100 — APPROVED** [review]
LGTM

**Comment by GuptaManan100** [comment]
@timvaillancourt Could you merge main once inorder to fix up the CI?

**Comment by shlomi-noach** [comment]
@timvaillancourt we'll also need a docs update. We realize there's actually no TxThrottler doc right now on https://vitess.io/, so not going to block this PR on that. However, I thought I might persuade you to put up a brief page to explain what the TxThrottler is. The docs repo is https://github.com/vitessio/website/ and we'll be looking for a page under [features](https://github.com/vitessio/website/tree/prod/content/en/docs/18.0/reference/features)

**Comment by shlomi-noach** [comment]
@timvaillancourt https://github.com/vitessio/vitess/pull/13153#issuecomment-1641856392

**Comment by timvaillancourt** [comment]
> @timvaillancourt Could you merge main once inorder to fix up the CI?

@GuptaManan100 / @shlomi-noach sorry I missed this part, I've updated the branch 👍

**Pull request merged**
