### PR TITLE
Remaining JDBC zero-timestamp config values

### LINKED ISSUE #2135: java: Zero DATETIME value gets mangled
MySQL allows a special [zero value](http://dev.mysql.com/doc/refman/5.7/en/datetime.html) (`0000-00-00 00:00:00`) as an exception to the rule that DATE and DATETIME values must otherwise be valid dates.

In `java.sql.Timestamp`, an attempt to parse the zero value throws an `IllegalArgumentException`.

In [Connector/J](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html), the `zeroDateTimeBehavior` setting can be used to specify `exception`, `round`, or `convertToNull`. The default behavior is `exception`.

In contrast to these two, [our Java client](https://github.com/youtube/vitess/blob/master/java/client/src/main/java/com/youtube/vitess/mysql/DateTime.java) converts the zero DATETIME value to something around `0002-11-30 00:00:00` (depending on the time zone).

We should either support the `zeroDateTimeBehavior` property, or at least pick a default behavior that matches one of those options.

### PR DESCRIPTION
**Pull request by kivikakk**
Fixes #2135.

More or less just familiarising myself with more of the codebase. I'm not super familiar with Java so my style might be out.

### CODE REVIEW

**Comment by harshit-gangal** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java, line 820 at r1](https://reviewable.io/reviews/vitessio/vitess/3902#-LCDECKIBC7CeKc2ty2e:-LCDECKIBC7CeKc2ty2f:b-urkfxx) ([raw file](https://github.com/vitessio/vitess/blob/6c45165be92db246401d70b36e0855fce113cdf6/java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java#L820)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>         switch (this.vitessStatement.getConnection().getZeroDateTimeBehavior()) {
>         case CONVERTTONULL:
>             return NullDateTime.NULL;
>         case EXCEPTION:
>             throw new SQLException(
>                 Constants.SQLExceptionMessages.ZERO_TIMESTAMP + ": " + columnIndex);
>         case ROUND:
>             return NullDateTime.ROUND;
>         case GARBLE:
>         default:
>             return NullDateTime.NO_CHANGE;
>         }
>     }
> ```
</details>


nit: format this part of the code.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java, line 838 at r1](https://reviewable.io/reviews/vitessio/vitess/3902#-LCDENOy6OGWaXE8RaAz:-LCDENOy6OGWaXE8RaB-:b-x3kyx6) ([raw file](https://github.com/vitessio/vitess/blob/6c45165be92db246401d70b36e0855fce113cdf6/java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java#L838)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>         switch (nullDateTime) {
>         case NULL:
>             return null;
>         case ROUND:
>             return new Date(-1900, 0, 1);
>         case NO_CHANGE:
>         default:
>             if (cal == null) {
>                 return this.row.getDate(columnIndex);
>             } else {
>                 return this.row.getDate(columnIndex, cal);
>             }
>         }
> ```
</details>

nit: format this part of the code.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3902)*

**Comment by harshit-gangal** [comment]
*[java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java, line 735 at r1](https://reviewable.io/reviews/vitessio/vitess/3902#-LCDFE4t3JnICza0euGH:-LCDFE4t3JnICza0euGI:bon6enp) ([raw file](https://github.com/vitessio/vitess/blob/6c45165be92db246401d70b36e0855fce113cdf6/java/jdbc/src/main/java/io/vitess/jdbc/VitessResultSet.java#L735)):*
> ```Java
> 
>         NullDateTime nullDateTime = getNullDateTime(columnIndex);
>         return getNullableDate(columnIndex, nullDateTime, null);
> ```

getNullableDate method should be called with Calendar cal than being null.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3902)*

**Comment by harshit-gangal** [comment]
@kivikakk - Can you take care of the review comments, so that it can be released with 2.2. Let us know if you want us to take care of it.

**Comment by kivikakk** [comment]
Hi @harshit-gangal, thanks so much for your review. I'm on holiday at the moment, so if you would be able to take care of it, that would be super ideal for me! Thank you.

**Pull request merged**
