### PR TITLE
Implementation of K8s secrets for Mysql Authentication

### PR DESCRIPTION
**Pull request by avaidyanatha**
### Main Changes
- Created new AuthServer implementation: k8s
- Allows for the usage of Kubernetes secrets for Mysql authentication
- Currently only uses MysqlNativePassword

Signed-off-by: avaidyanatha <avaidyanatha@ucsb.edu>

### CODE REVIEW

**Comment by derekperkins** [comment]
The k8s client-go library is notoriously difficult to compile and loads a substantial number of dependencies, which can significantly increase binary size (last I checked it was ~50 MB or so). This feels overly heavy for a pretty simple operation.

What if instead of communicating with k8s directly, the flag simply pointed at a filename or environment variable that contained the necessary files? That's how Google handles credentials https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable, and AWS/Azure do something similar.

**Comment by dkhenry** [comment]
the client-go library is in fact a mess, but we wanted to be able to support rotating secrets which is only supported by directly accessing the API.

**Comment by derekperkins** [comment]
You could still achieve the same thing with a file watcher on the mounted secret, and that would provide benefits for anyone configuring Vitess.

> When a secret being already consumed in a volume is updated, projected keys are eventually updated as well. Kubelet is checking whether the mounted secret is fresh on every periodic sync.
https://kubernetes.io/docs/concepts/configuration/secret/

If you really want direct integration, I've heard good things about this client https://github.com/ericchiang/k8s.

**Comment by derekperkins** [comment]
I'm not sure what your specific use case is, but for rotating secrets, I'm super interested in seeing Vitess integrate with Vault. https://www.vaultproject.io/docs/secrets/databases/mysql-maria.html

**Comment by dkhenry** [comment]
Integrating with vault is the kind of thing we want to support. The k8s integration was the first since its the lowest hanging fruit. Also I took out the client-go library and I am working on directly using the REST Api. That should reduce the overhead of what we need to pull in

**Comment by sougou** [comment]
This was submitted in contrib because of the binary bloat. Closing this.

**Pull request closed without merging**
