### PR TITLE
skip dbddl plugin test

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Description

The creation of database from vitess with a use of plugin was done as experimental. The recent changes to vttablet has let to consistent failure of this test. Marking this as skipped and removing from the CI run. We can revive it based on the interest.

## Checklist

-   [X] Tests were added or are not required

### CODE REVIEW

**Review by GuptaManan100 — COMMENTED** [review]
When did we break this? Was it intentional? Why didn't the CI catch it? Do we intend to fix it?

**Comment by harshit-gangal** [comment]
> When did we break this? Was it intentional? Why didn't the CI catch it? Do we intend to fix it?

I am not sure, but mostly when sidecar db work was done the delay got increased. Currently I do not see a reason to fix it as it is an unused feature.

**Review by frouioui — APPROVED** [review]
Agreed with @GuptaManan100, it is odd that this did not fail on CI in the past. Approving this PR to unblock you.

**Comment by frouioui** [comment]
Also @harshit-gangal if DBDDL plugin is an unused feature, can we remove it altogether?

**Comment by harshit-gangal** [comment]
> Also @harshit-gangal if DBDDL plugin is an unused feature, can we remove it altogether?

cc: @deepthi 
I am fine with removing the plugin work.

**Comment by harshit-gangal** [comment]
@deepthi is this acceptable to do at this point? We can revive and see what failed when we want to go in this direction.

**Pull request closed without merging**
