### PR TITLE
Fixes vtgate which throws an error in case of empty statements

### LINKED ISSUE #6644: `1105 (HY000): vtgate: [...]: empty statement` with Rust sqlx
#### Overview of the Issue
While most MySQL clients (at least, ones I've tested) seem to strip trailing semicolons from queries, sqlx is not one of them.  They appear to have spun their own implementation from the wire protocol up, and it does not strip trailing semicolons from queries.  This highlighted a vtgate issue where having a trailing semicolon _followed by whitespace_ on a query fails with error 1105, "empty statement".

#### Reproduction Steps
1. Install Rust toolchain
2. `cargo install --version=0.1.0-beta.1 sqlx-cli`
3. `export PATH="${PATH}:${HOME}/.cargo/bin"`
4. `git clone https://github.com/launchbadge/sqlx.git`
5. `cd sqlx/examples/mysql/todos`
6. `sqlx migrate run`

If you want `sqlx` to print every query as it runs them, the following patch will enable that:
```diff
diff --git a/sqlx-core/src/mysql/connection/executor.rs b/sqlx-core/src/mysql/connection/executor.rs
index 509ab0d1..2298ba7d 100644
--- a/sqlx-core/src/mysql/connection/executor.rs
+++ b/sqlx-core/src/mysql/connection/executor.rs
@@ -89,6 +89,7 @@ impl MySqlConnection {
         arguments: Option<MySqlArguments>,
         persistent: bool,
     ) -> Result<impl Stream<Item = Result<Either<MySqlDone, MySqlRow>, Error>> + 'e, Error> {
+        println!("run(): {}", sql);
         let mut logger = QueryLogger::new(sql);
 
         self.stream.wait_until_ready().await?;
```

Applying either of the following two patches, then `cd`ing into `/sqlx-core` in the root of the repo, running `cargo build`, and putting the binary in `~/.cargo/bin/` will resolve it.
```diff
diff --git a/sqlx-core/src/mysql/migrate.rs b/sqlx-core/src/mysql/migrate.rs
index 1476ef04..37b46836 100644
--- a/sqlx-core/src/mysql/migrate.rs
+++ b/sqlx-core/src/mysql/migrate.rs
@@ -88,8 +88,7 @@ CREATE TABLE IF NOT EXISTS _sqlx_migrations (
     success BOOLEAN NOT NULL,
     checksum BLOB NOT NULL,
     execution_time BIGINT NOT NULL
-);
-                "#,
+);"#,
             )
             .await?;
```
```diff
diff --git a/sqlx-core/src/mysql/migrate.rs b/sqlx-core/src/mysql/migrate.rs
index 1476ef04..2ccb9a95 100644
--- a/sqlx-core/src/mysql/migrate.rs
+++ b/sqlx-core/src/mysql/migrate.rs
@@ -88,7 +88,7 @@ CREATE TABLE IF NOT EXISTS _sqlx_migrations (
     success BOOLEAN NOT NULL,
     checksum BLOB NOT NULL,
     execution_time BIGINT NOT NULL
-);
+)
                 "#,
             )
             .await?;
```

#### Binary version
```
Version: f315cb35e (Git branch 'master') built on Fri Aug 28 13:21:19 UTC 2020
```

#### Operating system and Environment details
In the vtgate container:
```sh
vitess@mc-test1-mc1local-vtgate-afe64d24-747ddd7f88-fhwrb:/$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
vitess@mc-test1-mc1local-vtgate-afe64d24-747ddd7f88-fhwrb:/$ uname -sr
Linux 4.19.107
vitess@mc-test1-mc1local-vtgate-afe64d24-747ddd7f88-fhwrb:/$ uname -m
x86_64
```

On the host, where I'm running the client:
```sh
[mc@mc-thinkpad todos]$ cat /etc/os-release 
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;2;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
[mc@mc-thinkpad todos]$ uname -sr
Linux 5.6.16-1-MANJARO
[mc@mc-thinkpad todos]$ uname -m
x86_64
```

#### Log Fragments
I get the following log messages each time I run an unpatched `sqlx migrate run`:
```
I0828 17:49:48.430018       1 set.go:250] Ignored inapplicable SET time_zone = '+00:00'
E0828 17:49:48.436744       1 vtgate.go:452] Execute: empty statement, request: map[BindVariables:map[] Session:shard_sessions:<target:<keyspace:"test1" shard:"-" tablet_type:MASTER > tablet_alias:<cell:"mc1local" uid:1662884826 > reserved_id:1598629919380903914 > autocommit:true target_string:"test1" options:<included_fields:ALL client_found_rows:true > system_variables:<key:"sql_mode" value:"'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ENGINE_SUBSTITUTION'" > row_count:-1 in_reserved_conn:true Sql:]
```

### PR DESCRIPTION
**Pull request by GuptaManan100**
Vtgate currently throws an error in case an empty statement is passed. For example on running "insert into t1(c1, c2, c3, c4) values (300,100,300,'abc'); ;;" we see the following error -

E1026 12:53:24.191128   40177 vtgate.go:454] Execute: empty statement, request: map[BindVariables:map[] Session:autocommit:true options:<included_fields:ALL > found_rows:1 row_count:-1 Sql:]

Fixes #6644

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
I'm not sure if we ever created a coding guideline; I prefer avoiding `break loop` statements, but that's perhaps for another discussion.

**Review by harshit-gangal — COMMENTED** [review]
Can you explain the test better? I am not able to understand the expectation.

**Comment by systay** [comment]
@shlomi-noach I agree 💯 % about the `break`ing of loops. Not on my watch. ;)

However... Our tokeniser is the one place where I can understand that it makes sense to use this abominable language feature.

**Review by systay — APPROVED** [review]

**Comment by GuptaManan100** [comment]
> Can you explain the test better? I am not able to understand the expectation.

Done in the latest commit

**Pull request merged**
