### PR TITLE
Remove deprecated flags

### PR DESCRIPTION
**Pull request by systay**

### CODE REVIEW

**Comment by deepthi** [comment]
If something was deprecated after 3.0, we will need to keep it in 4.0 but can remove it right after the release branch is created.

**Comment by systay** [comment]
Let's revisit after releasing 4.0

**Comment by morgo** [comment]
I've made a note in the release notes:
> The backup configuration flags timeout, replication_timeout, gcs_backup_storage_project and lock_timeout have been deprecated and will be removed in the next release of Vitess.

**Comment by deepthi** [comment]
Let's remove refs to timeout and replication_timeout. They were introduced after 3.0 and deprecated within a short time, so there's no need to document them.

**Pull request closed without merging**
