### PR TITLE
Optimised Images

### PR DESCRIPTION
**Pull request by agarwalutkarsh554**
## Related Issue(s)

- 

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build/CI
- [x]  VTAdmin

### CODE REVIEW

**Comment by deepthi** [comment]
Thank you for the contribution! Can you describe the motivation for this PR and quantify the size reductions?
I'll leave it to @doeg and @ajm188 to decide whether we want to merge this.

**Comment by agarwalutkarsh554** [comment]
The size of the images have been reduced by at least  60%

**Comment by ajm188** [comment]
> The size of the images have been reduced by at least 60%

Including for vtadmin? Can you show the before/after image sizes?

**Comment by doeg** [comment]
Going through old branches; going to close this one out since it's over a year old and has merge conflicts.

**Pull request closed without merging**
