### PR TITLE
Handle auth method string.

### PR DESCRIPTION
**Pull request by dcadevil**
The JDBC driver sends the auth method string behind a Null byte when you don't specify a database name in the connection string. 
We should ignore the Null byte to get the auth method string.

image

Signed-off-by: dcadevil <dcadevil@126.com>

### CODE REVIEW

**Comment by alainjobart** [comment]
This doesn't look right, the database name is specified if the flag is set, and read a few lines before in the code. Are you sure this is the proper fix?

**Comment by dcadevil** [comment]
Does not read the byte before in the code because the byte isn't null when the database name is specified if the flag is set.
If we don't make changes, we won't get the correct auth method string when the database name is not specified.
@alainjobart

**Comment by alainjobart** [comment]
OK I've been scratching my head on this for a while now, I can't see what's happening. I fell like we need to understand what's going on instead of going for the quick fix here. Note there is something wrong with the Vitess code before your change, as we get an empty plugin auth string, instead of reading it properly, so I'm not saying this change is not useful, I'd just like to know where that extra 0 is from...

More info:
* first the official documentation for the packet:
https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse
In that one, it's clear the 00 that's in the packet you mention shouldn't be there.
* Some random mysql server code:
http://www.iskm.org/mysql56/sql__acl_8cc_source.html
line 10479 does the exact same parsing the go code does, before this change.
* The MySQL Connector-J source code that I thin is responsible for this:
https://github.com/mysql/mysql-connector-j/blob/release/5.1/src/com/mysql/jdbc/MysqlIO.java#L1864
note the connectorJ code also has a bunch of other parts where it sends the database, like in line 1804, but it seems like that code is for some other packet, not the initial handshake.

Do you have more information on what you see here? is the packet you're linking the first auth packet sent by the client?

What's also confusing me is the program you're using to show the packet source knows how to unpack and display the packet, and correctly skips that '00' in there. What program is that? Can we find the source code for that?

**Comment by alainjobart** [comment]
Ah one slight correction, the program you're using to decode the packet also gets confused: it says:
Client Auth Plugin:
and then nothing, and then is confused by the extra bytes.

The JDBC driver you're using is Connector J, right?

**Comment by dcadevil** [comment]
Yes, I use mysql-connector-java-5.1.40.jar.

**Comment by alainjobart** [comment]
I'm still scratching my head on even which code path is generating that packet. The only place I see is the line I linked in my previous comment, and it cannot add just '00' for the database. Are you compiling your own driver? Could you add some logging in some key places to see where that extra 00 comes from?

**Comment by dcadevil** [comment]
I found it. This is a bug in the old version of the mysql connector and it has been fixed in the new version.
image

**Comment by dcadevil** [comment]
Are we not going to be compatible with older versions of the mysql connector j which without fixing the bug?

**Comment by alainjobart** [comment]
I'd look at it the other way: if you want to use any other auth method than the default with connector J, you have to upgrade to a version without the bug. The current behavior we have is exactly what MySQL already does (finding 0 for the auth method, and reverting to default). I don't really want to have special handling for client bugs when there is an easy workaround...

Does that make sense?

**Pull request closed without merging**
