### PR TITLE
VReplication: Gather source positions once we know all writes are done during traffic switch

### PR DESCRIPTION
**Pull request by mattlord**
## Description

This PR addresses a logic bug when switching traffic:
  - We gathered the replication position on migration sources immediately after stopping writes there, then stopped other streams, did `LOCK TABLES` rounds to ensure that there are no in flight writes on the tables we're migrating, then we ensure that the migration targets' replication position is at least where the migration source was.
  - Logically we should get the replication source positions AFTER all of the other work is done and just before we ensure that the targets are caught up with that position.

I have not been able to trigger any actual bug/issue (lost writes during a traffic switch) through extensive manual testing and nobody has seen or reported an issue around this, but it's clearly a logical bug.

We address this here in a way that causes no additional work or overhead by simply moving the position gathering work from the `stopSourceWrites` step/function to its own step/function that we call immediately before the `waitForCatchup` step/function.

## Related Issue(s)

  - Fixes: https://github.com/vitessio/vitess/issues/16563

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by deepthi — APPROVED** [review]
Can you amend the last paragraph of the PR description, given that you have included a unit test?
Rest LGTM

**Review by rohit-nayak-ps — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
I think this issue may have been introduced by https://github.com/vitessio/vitess/pull/13015, which is why many people have not run into this yet, as it only affects v18 and later. I didn't dig into this in much detail at all, but if I'm right, is this PR worth backporting?

**Comment by mattlord** [comment]
@GrahamCampbell no, that is the same in the wrangler package which `vtctlclient` uses.

**Comment by mattlord** [comment]
> I think this issue may have been introduced by https://github.com/vitessio/vitess/pull/13015

@GrahamCampbell no, this aspect is the same in the `wrangler` package which `vtctlclient` uses. I didn't change the wrangler because it's been deprecated — via the `vtctlclient` or "legacy client" deprecation — since v18 and we want to remove it entirely soon.

> which is why many people have not run into this yet, as it only affects v18 and later.

Exactly nobody has reported it. It's not that "many people have not". The issue reported was from going through the code for the distributed transactions work, not because somebody encountered a problem.

**Pull request merged**
