### PR TITLE
Add `-full_flush` parameter for vtbackup, which performs

### PR DESCRIPTION
**Pull request by aquarapid**
a clean MySQL shutdown & startup cycle to work around xtrabackup
DDL bugs (see https://jira.percona.com/browse/PXB-2205).  xtrabackup
`-lock-ddl` (which is the default) is not sufficient to fix this, and we
have run into this in real-world scenarios.  See #8610 

Signed-off-by: Jacques Grove <aquarapid@gmail.com>

### CODE REVIEW

**Comment by deepthi** [comment]
vtbackup can be run with either `builtin` or `xtrabackup` backup engine. A better place for this flag and functionality is in the xtrabackup backup engine code. That gives us two benefits:
- This functionality will become available to all uses of xtrabackup, not just via vtbackup.
- Someone using builtin backup method won't be able to make the mistake of stopping and restarting mysql twice using this flag.

**Comment by aquarapid** [comment]
Not sure I agree with this;  limiting this to vtbackup only avoids someone doing the wrong thing when running xtrabackup against a live instance, and killing MySQL

**Comment by deepthi** [comment]
> Not sure I agree with this; limiting this to vtbackup only avoids someone doing the wrong thing when running xtrabackup against a live instance, and killing MySQL

They would have to start vttablets with the flag for that to happen. We would still default it to false.

**Review by deepthi — COMMENTED** [review]
Based on an offline discussion, I'm ok with adding this flag just to vtbackup and not vttablet.
The reasoning is that for anyone using vitess-operator, there's currently no way to pass differing xtrabackup flags through vtbackup than the standard vttablet ones;  so you wouldn't be able to vary this flag depending on whether you take an offline (vtbackup) backup or an online one (vttablet). We can revisit a vttablet flag when someone is able to make that change in concert with a vitess-operator change.

@aquarapid Can you rename the flag to reflect that we are doing a stop/start and not actually executing any `FLUSH` statements?

**Review by deepthi — APPROVED** [review]
LGTM

**Pull request merged**
