### PR TITLE
Run plan tests in end to end configuration

### PR DESCRIPTION
**Pull request by systay**
## Description
We’ve frequently encountered planner tests that assert faulty query plans, which would crash if executed directly on MySQL. This PR enhances testing by running these queries, with data, against both MySQL and Vitess, ensuring the results are consistent and correct across both systems.

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by arthurschreiber** [comment]
Nice! This will be a great help in making sure we catch planner issues earlier. 👍

**Comment by systay** [comment]
Thank you @harshit-gangal for picking this up and running with it. It looks great now. I can't accept my own PR, but if I could, I would! 👍

**Review by frouioui — APPROVED** [review]
This is good! Any plan on running more plan tests in E2E?

**Comment by harshit-gangal** [comment]
> This is good! Any plan on running more plan tests in E2E?

This should be done as and when a the planner is modified.

**Review by harshit-gangal — APPROVED** [review]

**Pull request merged**
