### PR TITLE
adds optional over clause to aggregate functions in sqlparser

### PR DESCRIPTION
**Pull request by CoreyWinkelmann**
(#5852)

## Description

This adds additional functionality to the sqlparser to support window functions associated to aggregate functions. #4099 new window function capabilities was added but it seemed to miss adding it to aggregate functions like COUNT, SUM, AVG, etc. This will add the [OVER CLAUSE](https://dev.mysql.com/doc/refman/8.0/en/window-functions-usage.html) associated to existing aggregate functions. 

### ADDED AGGREGATE FUNCTIONS

```
AVG()
BIT_AND()
BIT_OR()
BIT_XOR()
COUNT()
MAX()
MIN()
STDDEV_POP(), STDDEV(), STD()
STDDEV_SAMP()
SUM()
VAR_POP(), VARIANCE()
VAR_SAMP()
```

This **does not** implement `JSON_ARRAYAGG()` or `JSON_OBJECTAGG()` and the related over clause that can be added to them.

## Related Issue(s)

#4099 
#5852

## Checklist

-   [ X ] "Backport to:" labels have been added if this change should be back-ported
-   [ X ] Tests were added or are not required
-   [ X ] Did the new or modified tests pass consistently locally and on the CI
-   [ X ] Documentation was added or is not required

### CODE REVIEW

**Comment by edwardsainsbury** [comment]
I believe this is still an issue, has it been superseded by a change I haven't spotted?

**Comment by CoreyWinkelmann** [comment]
> I believe this is still an issue, has it been superseded by a change I haven't spotted? Thoughts @harshit-gangal @systay @GuptaManan100

Not sure, I think it is still needed. Unsure why it would be closed or if I need to do something. Is there anyone that can speak to if this is needed or if someone else added this functionality?

**Comment by harshit-gangal** [comment]
It was closed as there was no activity on the PR. You can reopen the PR and seek review for the same.

**Review by GuptaManan100 — APPROVED** [review]

**Comment by GuptaManan100** [comment]
@GrahamCampbell done

**Pull request merged**
