### PR TITLE
vindex ddl statements

### PR DESCRIPTION
**Pull request by demmer**
## Overview
Implement support for DDL statements to modify the vschema as described in #3459.

### Syntax
This adds support for all the following statements:

- [x] `CREATE VINDEX <name> USING <type> [WITH params]`
- [ ] ~`DROP VINDEX <name>`~
- [x] `ALTER TABLE <table> ADD VINDEX <name>`
- [x] `ALTER TABLE <table> ADD VINDEX <name> USING <type> [WITH params]`
- [x] `ALTER TABLE <table> DROP VINDEX <name>`

I decided not to implement `DROP VINDEX` as a standalone statement since it would require verifying that the vindex isn't in use by any tables. If this becomes important we can always do this in a separate PR.

### Topology Changes
In the original PR we proposed having vtgate call out to vtctld to make the requested topo changes. However since there is currently no linkage between vtgate and a vtctld instance, I instead made changes in the srvtopo interfaces so the vtgate can make the requested changes directly.

This assumes that any environment where this feature is used allows vtgate to talk to all topo servers (including those in other cells).

I also created a new `srvtopo.VSchemaServer` interface, implemented that within ResilientServer and pass both that and the original `srvtopo.Server` interface down into the vtgate. 

### Access Control
To restrict which users can make vindex changes using DDLs, I added a very simple access control mechanism. A new flag `-vschema_ddl_authorized_users` contains a comma separated list of usernames or "%" to represent all users, and the caller ID is compared to this list of usernames when executing the DDL statements.

### CODE REVIEW

**Comment by alainjobart** [comment]
This is really cool. At some point, it will be nice to have all DB schemas (regular MySQL schemas and vindexes) consistently created by just running SQL statements. Then we can control everything with our regular schema management tools...

**Comment by demmer** [comment]
@alainjobart / @sougou I spent some time over the last couple days dusting off and polishing up this PR.

I updated the descriptions here and in #3459 to reflect the new syntax and implementation.

**Comment by alainjobart** [comment]
On the srvtopo.Server split, @demmer and I talked for a bit about it, and we agreed it was a bit confusing. srvtopo.Server is supposed to be a read-only access to the local topo, and topo.Server is the place to have read-write methods. The new vschema manager was using bits and pieces of each, and it is confusing.

So we agreed to, instead:
- add a method GetTopoServer() *topo.Server to the srvtopo.Server interface. That way it's easy from a srvtopo.Server to gets its underlying topo.Server.
- in all places where we pass both, now just pass srvtopo.Server.
- call the read-write methods, when needed, on the topo.Server.

**Comment by demmer** [comment]
@alainjobart / @sougou I finally got a bit of time to revive this PR.

I've rebased against upstream and adapted to the change that we agreed on in #3740. This should be ready for final review and then we can get it in!

The biggest implication of this is that I ended up needing to change sandboxTopo so that it implements watches using a real memorytopo server. To minimize the impact of this, I made this optional since it does depend on consistency in the set of cells used in the tests. See 21df434 for the detailed changes.

**Pull request merged**
