### PR TITLE
Move some commas around in README.md :)

### PR DESCRIPTION
**Pull request by doeg**
## Description
Just shuffling punctuation around 😄 

## Related Issue(s)

N/A

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Deployment Notes

N/A 

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Review by rohit-nayak-ps — APPROVED** [review]
l,g,t,m!

**Comment by rohit-nayak-ps** [comment]
looks like this is missing the DCO. Also for some reason it has queued twice the number of tests, not sure why.

**Comment by doeg** [comment]
Haha oh no... let me fix the DCO signoff, one sec.

**Comment by doeg** [comment]
I edited the README in the browser -- neglected to remember the DCO signoff. Maybe that's why it queued 2x as many tests, also. 🤔

**Comment by deepthi** [comment]
> I edited the README in the browser -- neglected to remember the DCO signoff. Maybe that's why it queued 2x as many tests, also.

We get 2x tests if you create a branch on the main repo instead of doing it on a fork.

**Pull request merged**
