### PR TITLE
Fix type coercion between the sides of an UNION

### PR DESCRIPTION
**Pull request by systay**
## Description

For the following SQL query, Vitess doesn't return the same results as MySQL:

```sql
select email, max(col) as max_col from user group by email union select email, avg(col) as avg_col from user group by email order by email desc
```

```
Vitess Results:
[VARCHAR("test") DECIMAL(2)]
[VARCHAR("test") DECIMAL(1.5000)]
[VARCHAR("d") DECIMAL(2.0000)]
[VARCHAR("d") DECIMAL(2)]
[VARCHAR("c3") DECIMAL(4.0000)]
[VARCHAR("c3") DECIMAL(4)]
[VARCHAR("c") DECIMAL(4)]
[VARCHAR("c") DECIMAL(4.0000)]
[VARCHAR("b") DECIMAL(3.0000)]
[VARCHAR("b") DECIMAL(3)]
[VARCHAR("Abc") DECIMAL(2.0000)]
[VARCHAR("Abc") DECIMAL(2)]
[VARCHAR("a") DECIMAL(1.5000)]
[VARCHAR("a") DECIMAL(2)]


MySQL Results:
[VARCHAR("test") DECIMAL(2.0000)]
[VARCHAR("test") DECIMAL(1.5000)]
[VARCHAR("d") DECIMAL(2.0000)]
[VARCHAR("c3") DECIMAL(4.0000)]
[VARCHAR("c") DECIMAL(4.0000)]
[VARCHAR("b") DECIMAL(3.0000)]
[VARCHAR("Abc") DECIMAL(2.0000)]
[VARCHAR("a") DECIMAL(2.0000)]
[VARCHAR("a") DECIMAL(1.5000)]
```

Fixing this bug was way more involved than we initially expected! Basically, we were not properly performing type aggregation nor coercion between the two sides of UNION queries. The results for queries like that were only correct when the two sides of the union have the same types (something which is quite common, which is why we hadn't found out yet), but with different types the results are off.

To fix the issue, this PR:

- Implements proper type coercion in the `evalengine`, including changing the precision of `DECIMAL` when casting from a decimal with a smaller precision.
    - as part of this implementation, the old type coercion API has been removed, and with it several arithmetic APIs that were the only remaining user of the API and that have been superseded by the arithmetic aggregation operators we shipped in Vitess 19. :fire:  
- Implements a new API for incremental type aggregation, instead of the previous API that required collecting all the types to be aggregated in a slice upfront.
- Implements a new API to convert between `evalengine.Type` and `querypb.Field` without losing information
- Wires up these two new APIs to the `UNION`/`DISTINCT` engine primitives, so that we're properly aggregating the types between the two sides of the union.

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Are there similar issues with group by, or is this just an issue with distinct?

**Comment by vmg** [comment]
@systay OK here's a more-or-less working fix for this (which includes several related cleanups, particularly removing evalengine APIs which we don't need anymore). You'll see that some plans have changed: we're not asking for `weight_string` to MySQL in several union cases. I think that's a good thing but I'd like to review it with you next week.

**Review by vmg — APPROVED** [review]

**Comment by vmg** [comment]
Fixing this bug was way more involved than we initially expected! The PR is green now and the planner changes have been reviewed with @systay. Basically, we were not properly performing type aggregation nor coercion between the two sides of `UNION` queries. The results for queries like that were only correct when the two sides of the union have the same types (something which is quite common, which is why we hadn't found out yet), but with different types the results are off.

**Review by GuptaManan100 — APPROVED** [review]
The title and the description need an update

**Comment by vmg** [comment]
Updated title and description with an actual list of changes for this PR. :sparkle:

**Comment by systay** [comment]
> Are there similar issues with group by, or is this just an issue with distinct?

We didn't find any such issues, but you are correct in suspecting `DISTINCT`. It also needs to compare values. `ORDER BY` that is performed on the vtgate side would also be exposed to the same underlying problem.

This fix solved the issue in the underlying evalengine component, so it should apply to DISTINCT, GROUP BY and ORDER BY.

**Comment by vmg** [comment]
@GrahamCampbell :point_up: what @systay said -- sorry I missed your question! The GitHub UI collapsed it. :sweat_smile:

**Comment by dbussink** [comment]
> Needs backporting to 18.0 and 19.0, presumably? Caused by #15192?

This is not related to those changes and I don't think we need to backport here.

**Comment by vmg** [comment]
Aye this is unrelated to any previous issue, and it's not blocking any users or customers afaict. The report was filed by @systay itself and he found the problem by fuzzing.

**Pull request merged**
