### PR TITLE
vtctl: add new BackupShard cmd

### PR DESCRIPTION
**Pull request by derekperkins**
This chooses the most up to date tablet in a shard to run a backup on.

### CODE REVIEW

**Comment by rafael** [comment]
One question. Now that: 
```
			{"Backup", commandBackup,
				"[-concurrency=4] <tablet alias>",
				"Stops mysqld and uses the BackupStorage service to store a new backup. This function also remembers if the tablet was replicating so that it can restore the same state after the backup completes."},
```

Is registered in ` go/vt/vtctl/backup.go`, should we remove from `go/vt/vtctl/vtctl.go`?

**Comment by derekperkins** [comment]
I moved it in the second commit.

**Comment by derekperkins** [comment]
... or at least I thought I did. Just a sec

**Comment by derekperkins** [comment]
Ok, it's now not double registered anymore.

**Comment by sougou** [comment]
The more I thought about this, the more I like this.

**Pull request merged**
