### PR TITLE
BugFix: Keep predicates in join when pushing new ones

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the bug found in https://github.com/vitessio/vitess/issues/10713. 
The plan for the query found there with Gen4 using the vschema provided was - 
```json
{
  "QueryType": "SELECT",
  "Original": "select user.id, team.id from user join team_member on user.id = team_member.user join team on team_member.team = team.id where user.email = 'alice@gmail.com'",
  "Instructions": {
    "OperatorType": "Join",
    "Variant": "Join",
    "JoinColumnIndexes": "L:0,R:0",
    "JoinVars": {
      "user_id": 0
    },
    "TableName": "`user`_team, team_member",
    "Inputs": [
      {
        "OperatorType": "Route",
        "Variant": "EqualUnique",
        "Keyspace": {
          "Name": "customer",
          "Sharded": true
        },
        "FieldQuery": "select `user`.id from `user` where 1 != 1",
        "Query": "select `user`.id from `user` where `user`.email = 'alice@gmail.com'",
        "Table": "`user`",
        "Values": [
          "VARCHAR(\"alice@gmail.com\")"
        ],
        "Vindex": "email_user_map"
      },
      {
        "OperatorType": "Route",
        "Variant": "Scatter",
        "Keyspace": {
          "Name": "customer",
          "Sharded": true
        },
        "FieldQuery": "select team.id from team_member, team where 1 != 1",
        "Query": "select team.id from team_member, team where team_member.`user` = :user_id",
        "Table": "team, team_member"
      }
    ]
  }
}
```

In the plan, it is clearly visible that the predicate `team_member.team = team.id` is not applied anywhere. This results in extra rows being returned due to insufficient filtering as reported by the user.

After the changes in the PR, the plan looks like 
```json
{
  "QueryType": "SELECT",
  "Original": "select user.id, team.id from user join team_member on user.id = team_member.user join team on team_member.team = team.id where user.email = 'alice@gmail.com'",
  "Instructions": {
    "OperatorType": "Join",
    "Variant": "Join",
    "JoinColumnIndexes": "L:0,R:0",
    "JoinVars": {
      "user_id": 0
    },
    "TableName": "`user`_team, team_member",
    "Inputs": [
      {
        "OperatorType": "Route",
        "Variant": "EqualUnique",
        "Keyspace": {
          "Name": "customer",
          "Sharded": true
        },
        "FieldQuery": "select `user`.id from `user` where 1 != 1",
        "Query": "select `user`.id from `user` where `user`.email = 'alice@gmail.com'",
        "Table": "`user`",
        "Values": [
          "VARCHAR(\"alice@gmail.com\")"
        ],
        "Vindex": "email_user_map"
      },
      {
        "OperatorType": "Route",
        "Variant": "Scatter",
        "Keyspace": {
          "Name": "customer",
          "Sharded": true
        },
        "FieldQuery": "select team.id from team_member, team where 1 != 1",
        "Query": "select team.id from team_member, team where team_member.`user` = :user_id and team_member.team = team.id",
        "Table": "team, team_member"
      }
    ]
  }
}
```
Now, the predicate is found in the last route.

The earliest release affected by the bug is 13.0 and as such, the PR should be backported to both release-14.0 and release-13.0

## Related Issue(s)

- https://github.com/vitessio/vitess/issues/10713

## Checklist

-   [x] "Backport me!" label has been added if this change should be backported - Both to release-13.0 and release-14.0
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by harshit-gangal** [comment]
The changes looks good.
Can you add an e2e test as well?

I’m not sure about v13 backport as Gen4 was experimental on that.

**Review by frouioui — APPROVED** [review]
the fix looks good to me

**Comment by GuptaManan100** [comment]
@harshit-gangal I and @frouioui think we should backport to 13.0 too since the bug is making Gen4 give incorrect results. We wouldn't have backported if the bug was an unsupported query or failing with an error, but incorrect results even in v13 is not a good user experience. They won't know that the query is giving incorrect results and it will be hard for us to document which kind of queries won't work. WDYT?

**Comment by harshit-gangal** [comment]
> @harshit-gangal I and @frouioui think we should backport to 13.0 too since the bug is making Gen4 give incorrect results. We wouldn't have backported if the bug was an unsupported query or failing with an error, but incorrect results even in v13 is not a good user experience. They won't know that the query is giving incorrect results and it will be hard for us to document which kind of queries won't work. WDYT?

we can keep correctness over experimental feature :+1:

**Review by harshit-gangal — APPROVED** [review]

**Review by systay — APPROVED** [review]

**Comment by systay** [comment]
if it's easy to backport to r13, why not just do it, right?

**Comment by frouioui** [comment]
> if it's easy to backport to r13, why not just do it, right?

That's what @GuptaManan100 and I were thinking 👍🏻

**Pull request merged**
