### PR TITLE
Upgrade go minimum to 1.15

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Description
This bumps the minimum golang version to 1.15. For prior art, the PR to bump to 1.12 was #5017 and for 1.13 was #5943.

```
➜  vitess git:(master) grep -l -RF 1.13 .
./go/vt/vtctld/rice-box.go
./go/vt/orchestrator/external/raft/LICENSE
./web/vtctld2/app/plotly-latest.min.js
./web/vtctld2/package-lock.json
./web/vtctld2/src/plotly-latest.min.js
./go.sum
./.github/workflows/docker_test_2.yml
./doc/releasenotes/7_0_0_release_notes.md
```
Once this is approved and merged I'll open a similar PR for the `vitessio/website` repo like https://github.com/vitessio/website/pull/419

## Why

Go 1.14 release _"improves the performance of most uses of defer to incur almost zero overhead compared to calling the deferred function directly. As a result, defer can now be used in performance-critical code without overhead concerns"._

Go 1.15 release _"includes substantial improvements to the linker, improves allocation for small objects at high core counts [...]"._

### CODE REVIEW

**Comment by guidoiaquinti** [comment]
Not very familiar with the new CI but are those tests failing because they rely on Docker images (built on 1.13)?

**Comment by deepthi** [comment]
> Not very familiar with the new CI but are those tests failing because they rely on Docker images (built on 1.13)?

Some of them yes, but some seem to be compile errors in test code: 
```
Error: go/vt/vtgate/vcursor_impl_test.go:280:9: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```
You should be able to click through to `Details` on each of the CI checks. This one is from unit and unit_race.

**Comment by derekperkins** [comment]
I forgot that we hadn't upgraded. I think there are some significant gains to be had with the new defer optimizations.

**Comment by deepthi** [comment]
@derekperkins @dkhenry what are the steps needed to get the tests passing? build bootstrap images off this PR and push them to dockerhub? That will break other open PRs until this PR is merged, correct?

**Comment by deepthi** [comment]
I have merged #6800. A merge/rebase should get unit tests passing on this PR.

**Comment by derekperkins** [comment]
@deepthi I wouldn't expect this to break other open PRs unless they're hitting some strange edge cases.

**Comment by guidoiaquinti** [comment]
All the CI tests still failing are due to:
```
ERROR: Go version reported: go version go1.13.15 linux/amd64. Version 1.15+ required. See https://vitess.io/contributing/build-from-source for install instructions.
```

This is because we run the test using pre-built images (like `vitess/bootstrap:mysql57`) instead of rebuilding those against `master` before launching the suite.

**Comment by guidoiaquinti** [comment]
Also, I missed that there’s no official go 1.15 docker image for Debian Stretch so for the upgrade we also need to move to Debian Buster. This is not super straight forward as there are major deprecations, package name changes and so on. 

@morgo worked on the Debian upgrade in #6129 but it was never pushed to the finish line. I'll see if I can revamp his PR but till it's merged I think we can consider this PR blocked. Feedback/ideas are welcome.

**Comment by dkhenry** [comment]
Just doing some sanity tests before we do this merge

### Go 1.14.3 
TPCC - 2972.80

### Go 1.15.3
TPCC -  2906.25

So we are in the same ballpark ( we know theses tests have been giving 20% variance between runs ). I am going to continue to test to see if I can get definitive numbers, but this should be clear to merge once the new bootstraps get pushed and the CI builds pass

@guidoiaquinti do you need me to push up new bootstrap images ?

**Review by dkhenry — APPROVED** [review]

**Comment by guidoiaquinti** [comment]
> Just doing some sanity tests before we do this merge
> 
> ### Go 1.14.3
> TPCC - 2972.80
> 
> ### Go 1.15.3
> TPCC - 2906.25
> 
> So we are in the same ballpark ( we know theses tests have been giving 20% variance between runs ). I am going to continue to test to see if I can get definitive numbers, but this should be clear to merge once the new bootstraps get pushed and the CI builds pass
> 
> @guidoiaquinti do you need me to push up new bootstrap images ?

Hey @dkhenry, thanks for your comment. Were you doing your tests against this branch? Because I think we need #6833 before merging this as there are no go 1.15 docker image for Debian Stretch.

Let me know if I've missed anything. Thanks!

**Comment by deepthi** [comment]
replaced with #7204

**Pull request closed without merging**
