### PR TITLE
Fixing flaky endtoend/tablegc tests

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description
Fixes https://github.com/vitessio/vitess/issues/7878

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [x]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Example for failed test: https://github.com/vitessio/vitess/runs/2421562090?check_suite_focus=true (shard named `27` now renamed in this PR to `tabletmanager_tablegc`):

```
== RUN   TestPopulateTable
--- PASS: TestPopulateTable (0.02s)
=== RUN   TestHold
--- PASS: TestHold (15.03s)
=== RUN   TestEvac
--- PASS: TestEvac (20.03s)
=== RUN   TestDrop
--- PASS: TestDrop (20.03s)
=== RUN   TestPurge
    tablegc_test.go:331: 
        	Error Trace:	tablegc_test.go:331
        	Error:      	Should be false
        	Test:       	TestPurge
    tablegc_test.go:337: 
        	Error Trace:	tablegc_test.go:337
        	Error:      	Should be true
        	Test:       	TestPurge
    tablegc_test.go:123: 
        	Error Trace:	tablegc_test.go:123
        	            				tablegc_test.go:338
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestPurge
--- FAIL: TestPurge (65.03s)
FAIL
FAIL	vitess.io/vitess/go/test/endtoend/tabletmanager/tablegc	146.848s
FAIL
```

**Comment by shlomi-noach** [comment]
This should be good to go. Basically just incrmented some sleep time to let the mechnism do its expected work.

**Comment by harshit-gangal** [comment]
I think this needs to be removed "Run endtoend tests on Cluster (27) Expected — Waiting for status to be reported"

**Review by harshit-gangal — APPROVED** [review]

**Comment by shlomi-noach** [comment]
> I think this needs to be removed "Run endtoend tests on Cluster (27) Expected — Waiting for status to be reported"

Indeed. Thank you!

**Comment by shlomi-noach** [comment]
Removed `Run endtoend tests on Cluster (27)` from being `Required`. Merging and then adding `tabletmanager_tablegc` as `Required`.

**Pull request merged**
