### PR TITLE
Add option to log queries only when rows returned/affected >= X

### PR DESCRIPTION
**Pull request by aquarapid**

### CODE REVIEW

**Comment by sougou** [comment]
The idea behind the querylog was that you could do the filtering on the client side on various criteria using a tool like awk; The fields are tab separated. Is there a use case where this would not work?

**Comment by aquarapid** [comment]
Where you just have too many queries to log;  as multiple Vitess users have shared...?

**Comment by deepthi** [comment]
@sougou ping. Is the reasoning behind this PR acceptable?

**Review by sougou — APPROVED** [review]
Can you do a rebase (or anything else to retrigger the hung tests)? Once it passes, we can merge.

**Comment by aquarapid** [comment]
Things have changed underneath a bit, I'm just going to redo this PR.

**Pull request closed without merging**
