### PR TITLE
Add Dockerfile.mariadb-arm64v8 to support arm64

### PR DESCRIPTION
**Pull request by jiameixie**
Install correct maridb and xtrabackup for aarch64.

Change-Id: I58b1750f78b667842bbc172d65f6dca0c6beb81d
Signed-off-by: Jiamei.Xie <Jiamei.Xie@arm.com>

### CODE REVIEW

**Comment by jiameixie** [comment]
@dkhenry I add Dockerfile.mariadb-arm64v8 to support arm64. Would you help me review it? Thx.

**Comment by jiameixie** [comment]
@dkhenry @derekperkins Could you please review it ? Thanks.

**Comment by grooverdan** [comment]
recommend using debian:buster so at least then there is mariadb-backup (https://packages.debian.org/buster/mariadb-backup). This is significantly better than using percona's xtrabackup as its more closely related/tested withh mariadb. Or alternatley use MariaDB's repos and then any base contain could be used.

**Comment by dkhenry** [comment]
@grooverdan we wouldn't be able to incorporate mariadb-backup without adding the supporting code in Vitess. Right now there are only two backup engines available ( `builtin` and `xtrabackup` )

**Review by dkhenry — CHANGES_REQUESTED** [review]

**Comment by grooverdan** [comment]
mariadb-backup is a fork. Its command line and behaviour are the same.

Allowing the changing of https://github.com/vitessio/vitess/blob/3e8a9265879d38589012fa052309d6a4371d9aa2/go/vt/mysqlctl/xtrabackupengine.go#L70-L72 constants `xtrabackup` -> `mariabackup` and `xbstream` -> `mbstream` is sufficient to support it.

Changes in the MariaDB on disk storage format for innodb means that Percona's xtrabackup won't work on it. mariabackup is part of the MariaDB-10.1 onwards.

**Comment by dkhenry** [comment]
@grooverdan that being the case it would still need a corresponding change to enable the new backup engine, and if that is that case ( that xtrabackup doesn't work with mariadb 10.1+) then this Dockerfile should change to use the working backup engine. 

Also if it is interface compatible then perhaps the best short term solution would be to install mariabackup and symlink the binary names to prevent needing an update to Vitess.

**Comment by deepthi** [comment]
> @grooverdan that being the case it would still need a corresponding change to enable the new backup engine, and if that is that case ( that xtrabackup doesn't work with mariadb 10.1+) then this Dockerfile should change to use the working backup engine.
> 
> Also if it is interface compatible then perhaps the best short term solution would be to install mariabackup and symlink the binary names to prevent needing an update to Vitess.

Agree with what @dkhenry is saying here.

**Comment by systay** [comment]
Let's re-open if this is still interesting to add

**Pull request closed without merging**
