### PR TITLE
Fixing code quality issues

### PR DESCRIPTION
**Pull request by de-sh**
## Backport
YES

## Status
**READY**

## Description
I am opening this PR to fix a few [interesting code quality issues](https://deepsource.io/gh/de-sh/vitess) detected on static analysis with DeepSource. It is a code review automation tool that detects problems in contributions and helps developers automatically fix some of them.

The fixes made in this PR include:

- Remove unnecessary imports
- Remove unnecessary return statements
- Refactor conditional statement with `in`
- Perform identity check instead of equality comparison
- Correct print syntax
- Added a DeepSource config

## Related Issue(s)
List related PRs against other branches:

## Todos
- [x] Tests
- [ ] Documentation

## Deployment Notes
Notes regarding deployment of the contained body of work.  These should note any
db migrations, etc.

## Impacted Areas in Vitess
List general components of the application that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build

### CODE REVIEW

**Review by shlomi-noach — CHANGES_REQUESTED** [review]
Thank you for this contribution! We appreciate your time and effort.

Personally I'm not familiar with `deepsource`. I see it's a commercial linter. And while the actual code changes made to this PR seem legit, I'd prefer that this OSS project standardizes on OSS linters. Granted, we have invested a lot more about linting our `golang` code than in the small amount of `python` code, and it's great that you've highlighted the need for that!

Thank you again.

**Comment by de-sh** [comment]
Hey @shlomi-noach, that's fine. You want the `.deepsource.toml` removed right?

**Comment by shlomi-noach** [comment]
@de-sh I suggest we close this PR, and later can work on using one of the open source python linters and see what it has to suggest.

**Comment by de-sh** [comment]
Ok, I shall do that

**Pull request closed without merging**
