### PR TITLE
Basic support for -stats_backend opentsdb

### PR DESCRIPTION
**Pull request by dweitzman**
Signed-off-by: David Weitzman <dweitzman@pinterest.com>

### CODE REVIEW

**Comment by sougou** [comment]
If I understand correctly, opentsdb is an alternative to prometheus right? If so, we have two choices:
1. Support only one by default, but allow the default to be replaced. This is the plugin approach. If this is the case, we should choose between opentsdb and prometheus.
2. Allow choosing of the monitoring plugin through the command line. This is the lockserver approach where we build all, but register only what is chosen at runtime.

I'm ok with either. If it's option 1, we should remove the `plugin_*` files, and they can be added by whoever wants to use something else. The opentsdb code can still be there to make it easy for the swap.

If it's option 2, we should remove the plugins for opentsdb as well as prometheus, and do what we did for the lockservers.

@demmer @zmagg thoughts?

**Comment by dweitzman** [comment]
I think it's already the case that you can choose either prometheus or
influxdb using different command line arguments, although the distinction
between push vs pull backends allows that configuration to be less
consistent than the topo service options

**Comment by zmagg** [comment]
It's a mix of approaches today:

InfluxDB uses [approach no. 2](https://github.com/vitessio/vitess/blob/master/go/stats/export.go#L44) and Prometheus uses approach no. 1. We should just standardize on one of them. I don't have a super strong preference, but providing a default (approach no. 1) seems slightly nicer for new users getting started.

**Comment by derekperkins** [comment]
There have been 5 releases of OpenCensus since we last discussed it in #3644, and the linked issues have been seemingly resolved. Has it gotten to a place where we could use it for abstractions rather than reimplementing?

cc @alainjobart @rakyll

_I just checked and it doesn't support OpenTSDB yet, so this is probably premature_

**Comment by demmer** [comment]
@derekperkins This core issue was technically resolved but in a way that marks it as "controversial" and not in a way that seems to address the desire for callback based pull systems:
https://github.com/census-instrumentation/opencensus-go/issues/372

OpenTSDB support notwithstanding it really just seems to me like OpenCensus has a ways to go before it can cover the requirements we have for Vitess.

**Comment by dweitzman** [comment]
This code only pushes stats if you set the opentsdb URI, the push stats
interval, and select "opentsdb" as the stats backend on the command line.

It only registers /debug/opentsdb when you set the opentsdb URI on the
command line

**Comment by dweitzman** [comment]
Actually, I think there's a default push stats interval, so setting that
may be unnecessary as long as you set -stats_backend opentsdb

**Pull request merged**
