### PR TITLE
schemadiff: constraint name diff hints strategies

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

This PR adds `ConstraintNamesStrategy` to `DiffHint`. The hint tells `schemadiff` how to diff two constraints (this applies to both `FOREIGN KEY` and `CHECK` constraints in the same way); specifically, what to do if their names are different. Possible values are:

- `ConstraintNamesIgnoreVitess` (default): ignore if names are identical after stripping vitess special prefix (see shortly)
- `ConstraintNamesIgnoreAll`: completely ignore constraint names, consider two are equal solely based on their actual content
- `ConstraintNamesStrict`: names must be identical.

#### Why

In MySQL, `check` or `foreign key` constraints names are unique in the schema. This means that two tables, that are otherwise identical, cannot possibly have identical constraint names. See https://github.com/vitessio/vitess/pull/10369 for a bit more discussion.

However, in `schemadiff` we may want to ignore those name diffs. Specifically, in a Vitess Online DDL flow, any migration will rename constraints name in a predictable way (see https://github.com/planetscale/vitess-private/pull/721#issuecomment-1140388649), e.g. :
```sql
CONSTRAINT `chk_04a5b01db9d15e218979970c23bfc13a_check1` CHECK ((`test` >= 0))
```

**UPDATE** format has changed, see followup comment.

So the initial and main objective of this PR is to diff these two tables, with an empty diff result:
```sql
CREATE TABLE `t1` (
  `id` int NOT NULL,
  `test` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `chk_04a5b01db9d15e218979970c23bfc13a_check1` CHECK ((`test` >= 0)),
  CONSTRAINT `chk_2dbf8418af7250d783beb208344ae16b_check5` CHECK ((`test` < 5)),
  CONSTRAINT `chk_353c799af3d858eb99b87d6419133d5c_check2` CHECK ((`test` >= 0)),
  CONSTRAINT `chk_5b7f19d3521f59bd85045742d6d95913_check3` CHECK ((`test` >= 0)),
  CONSTRAINT `chk_d3ea4658fb83587f9beae3064c354041_check4` CHECK ((`test` <> 4))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `t2` (
  `id` int NOT NULL,
  `test` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `chk_326258d255a154229107a02402b2b6f1_check1` CHECK ((`test` >= 0)),
  CONSTRAINT `chk_74954dcba13f5deda55006e52b1d5004_check5` CHECK ((`test` < 5)),
  CONSTRAINT `chk_87ef2bbaac825426a5f9ff8ad88d8b4a_check3` CHECK ((`test` >= 0)),
  CONSTRAINT `chk_9148a507c23d5275845b208a7eb52a57_check4` CHECK ((`test` <> 4)),
  CONSTRAINT `chk_d77103119cf35487aa954c488f66f736_check2` CHECK ((`test` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```
Notice how in the above both name and ordering change, but the original name and the content of the checks remain unchanged. This is what `ConstraintNamesIgnoreVitess` means, and given the fact Vitess _always_ modifies constraint names during migration, and uses these conventions, `ConstraintNamesIgnoreVitess` is `schemadiff`'s default strategy.

Tests are added for all strategy variations.

## Related Issue(s)

- https://github.com/vitessio/vitess/pull/10369
- #6926 
- #10203 

## Checklist

-   [ ] "Backport me!" label has been added if this change should be backported
-   [ ] Tests were added or are not required
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by shlomi-noach** [comment]
# Change of constraint name format

To allow more character space for original names, and to maintain original name order, the new constraint name format is:

`<original name>_[0-9a-z]{25}`

The checksum is a `128` bit (`UUIDv5` based on `SHA256`) encoded in `base36`, which is `25` characters (down from `32`). We remove `chk_` or `fk_` because those are superfluous to the constraint definition.

### Example:

original table:
```sql
CREATE TABLE `t` (
  `id` int NOT NULL,
  `test` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `check1` CHECK ((`test` >= 0)),
  CONSTRAINT `check2` CHECK ((`test` >= 0)),
  CONSTRAINT `check3` CHECK ((`test` >= 0)),
  CONSTRAINT `check4` CHECK ((`test` <> 4)),
  CONSTRAINT `check5` CHECK ((`test` < 5))
)
```

modified once:

```sql
CREATE TABLE `t` (
  `id` int NOT NULL,
  `test` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `check1_19l09s37kbhj4axnzmi10e18k` CHECK ((`test` >= 0)),
  CONSTRAINT `check2_cukwabxd742sgycn96xj7n87g` CHECK ((`test` >= 0)),
  CONSTRAINT `check3_d9ict50651cj9qzlzmqxjrerq` CHECK ((`test` >= 0)),
  CONSTRAINT `check4_0j5zhr7pheqtftoc6jyib997o` CHECK ((`test` <> 4)),
  CONSTRAINT `check5_ccqceb4vzonxgy9plzynofyr3` CHECK ((`test` < 5))
)
```

modified again:

```sql
CREATE TABLE `t` (
  `id` int NOT NULL,
  `test` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `check1_cps1okb4uafunfqusi2lp22u3` CHECK ((`test` >= 0)),
  CONSTRAINT `check2_atleezf4dlbjvon55mflylhjb` CHECK ((`test` >= 0)),
  CONSTRAINT `check3_8nj6a51pszqbtbycrm18qri0n` CHECK ((`test` >= 0)),
  CONSTRAINT `check4_dvc5bs03r4twlyo2a5i76ll8k` CHECK ((`test` <> 4)),
  CONSTRAINT `check5_b7c76z82dbqpp90bv3ywokzqo` CHECK ((`test` < 5))
)
```

You may see how original names are clearer, and constraint names consistently sorted by original names.

**Review by dbussink — APPROVED** [review]
Nice user experience improvement.

**Comment by shlomi-noach** [comment]
Thanks @dbussink for suggesting the change

**Comment by shlomi-noach** [comment]
Some of the `Upgrade Dowgrade Testing` CI tests are taking forever. I'm gonna wait a bit longer, but ultimately merge this PR irrespective of their results, given runtime, flakiness, and irrelevance of changes in this PR.

**Pull request merged**
