### PR TITLE
Use a truly random Destination for DestinationAnyShard

### PR DESCRIPTION
**Pull request by eeSeeGee**
Signed-off-by: Aaron Young <young@squareup.com>

### CODE REVIEW

**Comment by rafael** [comment]
However, tests are going to fail because they are expecting to be in shard one. One approach that we discussed to address this is that the shard "picker" should be an interface. That way we can use random in the real one, but a mocked one that always picks the first shard that is used in the context of the tests.

**Comment by xhh1989** [comment]
We JDer use this function for pined table that pined to the first shard.

**Comment by eeSeeGee** [comment]
> We JDer use this function for pined table that pined to the first shard.

That's... weird? Why not use a separate keyspace?

**Comment by sougou** [comment]
@xhh1989 Can you confirm that you have the code I pointed at? If so, this change should not affect you.

**Pull request merged**
