### PR TITLE
update go.mod file 

### PR DESCRIPTION
**Pull request by tanjunchen**

### CODE REVIEW

**Comment by tanjunchen** [comment]
@deepthi

**Comment by tanjunchen** [comment]
@sougou

**Comment by sougou** [comment]
You need to resolve the merge conflict

**Comment by tanjunchen** [comment]
> You need to resolve the merge conflict

Should we update the mod file?

**Comment by tanjunchen** [comment]
@sougou

**Comment by sougou** [comment]
There seems to be an issue with the go.mod file. It seems to be inconsistent. It's better not to aggressively change it right now. Closing this PR.

**Pull request closed without merging**
