### PR TITLE
Vitess mixin improvements

### PR DESCRIPTION
**Pull request by manfontan**
## Description

This PR Draft includes a number of improvements to the vitess-mixin:
1. New dashboards to the vitess-mixin. Including:
    - `vtgate-host-view`
    - `vttablet-host-view`
    - `vtgate-overview`
 1. `keyspace-overview` dashboard has been deprecated since it was dependant on custom Prometheus Tags. This change may impact upstream users.
 1. Performance improvements to existing dashboards.
 1. Recording rules to support many of the panels.
 1. An alpha version of end to end testing.
 1. Improvements to the make targets.
 1. Refactor of the dashboard resources:
     - Add helper libraries to isolate grafonnet code from configuration files.
     - Add additional structure to organise the resources by groups (vtgate, vttablet, mysql, os...)
 
 Given the significant amount of changes included. I am opening this as a Draft looking for feedback.

## Related Issue(s)
N/A

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Deployment Notes
N/A

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [x]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Comment by guidoiaquinti** [comment]
LGTM in general. 

Nit: we probably need to remove the label `$region` or make it more clear in the doc that is a label that needs to be set via Prometheus config as Vitess doesn't expose it natively.

**Comment by manfontan** [comment]
> LGTM in general.
> 
> Nit: we probably need to remove the label `$region` or make it more clear in the doc that is a label that needs to be set via Prometheus config as Vitess doesn't expose it natively.

Good catch. I will remove it.

**Comment by guidoiaquinti** [comment]
Once we verify that this version works clean on a vanilla Vitess installation: :shipit:

**Comment by maZahaca** [comment]
Hello guys, do you have any timeline for releasing a new version of mixins?

**Comment by maZahaca** [comment]
@manfontan @guidoiaquinti Do you guys have a proper configuration for Prometheus scrape configuration?
I've spent few days trying to build it on my own, but it seems that apart from port `15000` it also tries to scrapes `15999`, `3306` which is not really expected. So, in fact, many prometheus targets are shown as `Down` and retried every 10s.

Here is what I use: 
```
- job_name: vitess-vtgate
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - vitess
    selectors:
    - role: pod
      label: planetscale.com/component=vtgate
- job_name: vitess-vttablet
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - vitess
    selectors:
    - role: pod
      label: planetscale.com/component=vttablet
- job_name: vitess-vtctld
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - vitess
    selectors:
    - role: pod
      label: planetscale.com/component=vtctld
- job_name: vitess-vtworker
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - vitess
    selectors:
    - role: pod
      label: planetscale.com/component=vtworker
```

**Comment by maZahaca** [comment]
Ok, I found out another way.

**Comment by manfontan** [comment]
@maZahaca sorry for the delay in my response. 

With my latest commit it is now possible to test the mixin with vanilla vitess using compose. However the prometheus configuration is just a mock to allow local testing. It will scrape metrics from Vitess, Node exporter and Mysql exporter.

We use custom labels for keyspace and shard in a number of metrics. But those are not included in this PR. The idea is to include them in future PRs. 

Instructions on how to test using docker can be found at `vitess-mixin-quickstart.md`.

This is a gif of the Cluster Overview Dashboard

cluster_overview

**Comment by deepthi** [comment]
@guidoiaquinti can you approve if this  looks good to you? Then we can merge it.

**Comment by guidoiaquinti** [comment]
I've synced with @manfontan and I think this PR still need a bit of work. He will provide an update once it's ready to be merged.

**Comment by manfontan** [comment]
@guidoiaquinti  The PR should be ready now. Looks like one test is failing. But seems to be unrelated to the mixin. Please let me know the best way to proceed.

**Comment by manfontan** [comment]
@deepthi this should be ready to merge. I believe the failing test is totally unrelated to this PR. 
Could you please let me know the best way to proceed here?

**Comment by deepthi** [comment]
> @deepthi this should be ready to merge. I believe the failing test is totally unrelated to this PR.
> Could you please let me know the best way to proceed here?

We can override the failing test, but I'm waiting for @guidoiaquinti to approve.

**Review by deepthi — APPROVED** [review]
Approving based on this out-of-band note from @guidoiaquinti 
"The PR looks good to me overall."

**Comment by deepthi** [comment]
@manfontan `tools.go` is failing `go fmt`. Can you make a PR to fix that?

**Comment by ajm188** [comment]
I'll take care of it!

**Pull request merged**
