### PR TITLE
vreplication: Run all appropriate tests

### PR DESCRIPTION
**Pull request by dbussink**
This is on top of #12861 but showcases a bunch of tests are broken. We never noticed since we were never running these tests even when we should. It means either the tests are broken or the underlying code is broken.

## Related Issue(s)

Uncovered in due to the work in #12861

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by dbussink** [comment]
@rohit-nayak-ps @mattlord @shlomi-noach I suspect that one of you would know best if this is a tests problem or an underlying issue then.

**Comment by rohit-nayak-ps** [comment]
> @rohit-nayak-ps @mattlord @shlomi-noach I suspect that one of you would know best if this is a tests problem or an underlying issue then.

Ouch, thanks for finding. I will take a look later today. The initial errors in the unit test failure logs are to do with the test setup: expected queries in the mock db are not setup correctly. Once those are fixed we will know for sure if the generated column functionality is broken or not.

**Comment by rohit-nayak-ps** [comment]
> @rohit-nayak-ps @mattlord @shlomi-noach I suspect that one of you would know best if this is a tests problem or an underlying issue then.

Had to only fix the tests.

**Comment by dbussink** [comment]
> Had to only fix the tests.

Ah, good that it's only broken tests then!

**Review by frouioui — APPROVED** [review]

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Pull request merged**
