### PR TITLE
VStreams: Rotate Binary Log For Snapshot Connections

### PR DESCRIPTION
**Pull request by mattlord**
## Description

Rotate the binary logs as needed in order to limit the GTID auto positioning overhead when starting a results/row stream from a given GTID set/position in VStreams. This is needed as the currently open binary log (which can be up to 1G in size by default) will need to be scanned and empty GTID events will be streamed for those GTIDs in the log that we are skipping. In total, this can add a lot of overhead on both the mysqld instance and the tablet. It can also cause a significant delay — particularly on connections with higher latency such as when the source and target are communicating over the internet with TLS — for otherwise fast actions such as VDiff on relatively small tables. Rotating the log ensures that we are processing a fresh binary log that will be minimal in size and GTID events.

> **Note**
>  We only rotate the binary log if it's > 64MiB in size by default. This avoids unnecessary flushes when there are many vstreams running  concurrently and/or there's very little write activity happening.

We had previously discovered this behavior during other events which require syncing with a GTID position/set, specifically during reparents, and used the same solution. See related issue and its links below.

## Related Issue(s)

  - Fixes: https://github.com/vitessio/vitess/issues/11345
  - Related to: https://github.com/vitessio/vitess/issues/4161

## Checklist

-   [x] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added
-   [x] Documentation: https://github.com/vitessio/website/pull/1153

### CODE REVIEW

**Review by aquarapid — COMMENTED** [review]
Shouldn't this just ignore/log if it fails?  E.g. if we don't have the RELOAD privilege, or are doing the snapshot from a replica?

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm, this is nice!

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Review by aquarapid — COMMENTED** [review]
LGTM!  Only other thing I could suggest is to test the error path (e.g. if the show binary logs fails because of lack of RELOAD privs)

**Comment by mattlord** [comment]
> LGTM! Only other thing I could suggest is to test the error path (e.g. if the show binary logs fails because of lack of RELOAD privs)

I assume you mean for the log message here: https://github.com/vitessio/vitess/pull/11344/files#diff-efb6bf2b0113d05b4466e1c54f4abf7ccad01637cc8ad1f01ceb2bb916dd67fdR81-R82

If so, we log the error info we get back from MySQL which is pretty explanatory IMO:
```
ERROR 1227 (42000): Access denied; you need (at least one of) the RELOAD privilege(s) for this operation
```

Please let me know if you had something else in mind though. Thanks!

**Pull request merged**
