### PR TITLE
Add `-db_connect_timeout_ms` for timing out mysqld conns.

### PR DESCRIPTION
**Pull request by adsr**
While testing vttablet-mysqld over TCP, we noticed `mysql.Connect`
sometimes blocks forever if the backend mysqld hit max conns. This
patch adds a timeout to this codepath. It defaults to 0 (no timeout)
for back compatibility.

Signed-off-by: Adam Saponara <as@php.net>

### CODE REVIEW

**Comment by adsr** [comment]
Sample stack trace illustrating stuck `mysql.Connect`:

```
goroutine 16446281 [IO wait, 318 minutes]:
internal/poll.runtime_pollWait(0x7f066421d458, 0x72, 0xc005f78880)
	/usr/local/go/1.11.4/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc001cb6598, 0x72, 0xffffffffffffff00, 0x14807a0, 0x1e0c7c0)
	/usr/local/go/1.11.4/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc001cb6598, 0xc003fc0000, 0x4000, 0x4000)
	/usr/local/go/1.11.4/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc001cb6580, 0xc003fc0000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/usr/local/go/1.11.4/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc001cb6580, 0xc003fc0000, 0x4000, 0x4000, 0x0, 0x0, 0xc0001e44a0)
	/usr/local/go/1.11.4/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0001e44a0, 0xc003fc0000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/usr/local/go/1.11.4/src/net/net.go:177 +0x68
bufio.(*Reader).Read(0xc005b243c0, 0xc004769be8, 0x4, 0x4, 0x4, 0x0, 0x0)
	/usr/local/go/1.11.4/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x147d1e0, 0xc005b243c0, 0xc004769be8, 0x4, 0x4, 0x4, 0x1095a40, 0xc001cb6501, 0xc004769be8)
	/usr/local/go/1.11.4/src/io/io.go:310 +0x88
io.ReadFull(0x147d1e0, 0xc005b243c0, 0xc004769be8, 0x4, 0x4, 0x0, 0x48f666, 0x5da369da)
	/usr/local/go/1.11.4/src/io/io.go:329 +0x58
vitess.io/vitess/go/mysql.(*Conn).readHeaderFrom(0xc00707f5e0, 0x147d1e0, 0xc005b243c0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/mysql/conn.go:261 +0x7e
vitess.io/vitess/go/mysql.(*Conn).readOnePacket(0xc00707f5e0, 0x0, 0xc0015fe0f0, 0xc005f78d38, 0x586aba, 0xc001cb6500)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/mysql/conn.go:400 +0x6b
vitess.io/vitess/go/mysql.(*Conn).readPacket(0xc00707f5e0, 0xc00707f5e0, 0xc005f78cd0, 0x40d493, 0x7f06545a4a58, 0x0)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/mysql/conn.go:422 +0x32
vitess.io/vitess/go/mysql.(*Conn).clientHandshake(0xc00707f5e0, 0xc005f78f2d, 0xc0043a00e0, 0xe, 0x149a660)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/mysql/client.go:224 +0x43
vitess.io/vitess/go/mysql.Connect.func1(0xc000c30180, 0x14930c0, 0xc00003e0a0, 0x12e19fa, 0x3, 0xc002734150, 0xe, 0xc00007142d, 0xc0043a00e0)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/mysql/client.go:118 +0x465
created by vitess.io/vitess/go/mysql.Connect
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/mysql/client.go:72 +0x13f

goroutine 16448536 [select, 318 minutes]:
vitess.io/vitess/go/mysql.Connect(0x14930c0, 0xc00003e0a0, 0xc008c9ad20, 0x0, 0x7, 0xbf60f85636d80987)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/mysql/client.go:153 +0x302
vitess.io/vitess/go/vt/dbconnpool.NewDBConnection(0xc000cde7e0, 0xc0002c58c0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/dbconnpool/connection.go:127 +0xf5
vitess.io/vitess/go/vt/vttablet/tabletserver/connpool.(*DBConn).reconnect(0xc005675200, 0xc0021823c0, 0xc0050eed00)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/vttablet/tabletserver/connpool/dbconn.go:348 +0x53
vitess.io/vitess/go/vt/vttablet/tabletserver/connpool.(*DBConn).Stream(0xc005675200, 0x1493140, 0xc0050eed80, 0xc007b88440, 0x12, 0xc004fc1560, 0x8000, 0xc000000002, 0x0, 0x0)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/vttablet/tabletserver/connpool/dbconn.go:205 +0x29c
vitess.io/vitess/go/vt/vttablet/tabletserver.(*QueryExecutor).execStreamSQL(0xc003561920, 0xc005675200, 0xc007b88440, 0x12, 0xc004fc1540, 0x0, 0xc007b88440)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/vttablet/tabletserver/query_executor.go:954 +0x1b7
vitess.io/vitess/go/vt/vttablet/tabletserver.(*QueryExecutor).streamFetch(0xc003561920, 0xc005675200, 0xc0048aaed0, 0xc0050eedb0, 0x0, 0x0, 0xc004fc1540, 0x12, 0x0)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/vttablet/tabletserver/query_executor.go:893 +0xce
vitess.io/vitess/go/vt/vttablet/tabletserver.(*QueryExecutor).Stream(0xc003561920, 0xc004fc1540, 0x0, 0x0)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/vttablet/tabletserver/query_executor.go:239 +0x26c
vitess.io/vitess/go/vt/vttablet/tabletserver.(*TabletServer).StreamExecute.func1(0x1493140, 0xc0050eed80, 0xc001355c20, 0xc0001c0340, 0x1493100)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:1094 +0x226
vitess.io/vitess/go/vt/vttablet/tabletserver.(*TabletServer).execRequest(0xc0001c0340, 0x1493140, 0xc0050eed80, 0x0, 0x12ec9ce, 0xd, 0xc007b883c0, 0x12, 0x0, 0xc004d0f4a0, ...)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:1511 +0x34b
vitess.io/vitess/go/vt/vttablet/tabletserver.(*TabletServer).StreamExecute(0xc0001c0340, 0x1493140, 0xc0050eed80, 0xc004d0f4a0, 0xc007b883c0, 0x12, 0xc0050eedb0, 0x0, 0xc00216fa90, 0xc004fc1540, ...)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:1070 +0x146
vitess.io/vitess/go/vt/vttablet/grpcqueryservice.(*query).StreamExecute(0xc0001a8090, 0xc00216f9a0, 0x1499340, 0xc009dd95e0, 0xc0001a8090, 0xc004fc1500)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/vttablet/grpcqueryservice/server.go:79 +0x1be
vitess.io/vitess/go/vt/proto/queryservice._Query_StreamExecute_Handler(0x129e1e0, 0xc0001a8090, 0x1497f60, 0xc004fc1500, 0x21, 0x1493140)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/proto/queryservice/queryservice.pb.go:550 +0x10c
vitess.io/vitess/go/vt/servenv.authenticatingStreamInterceptor(0x129e1e0, 0xc0001a8090, 0x1497a80, 0xc005eea540, 0xc004fc14a0, 0x1359668, 0xc0026f14a0, 0x40e1a8)
	/builddir/build/BUILD/vt/go/src/vitess.io/vitess/go/vt/servenv/grpc_server.go:260 +0xfc
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000ed2600, 0x149b560, 0xc001c86180, 0xc00841dc00, 0xc00016ce70, 0x1fc6c40, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/vt/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1209 +0x488
google.golang.org/grpc.(*Server).handleStream(0xc000ed2600, 0x149b560, 0xc001c86180, 0xc00841dc00, 0x0)
	/builddir/build/BUILD/vt/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1282 +0xd9b
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000f42170, 0xc000ed2600, 0x149b560, 0xc001c86180, 0xc00841dc00)
	/builddir/build/BUILD/vt/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/builddir/build/BUILD/vt/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1
```

**Comment by sougou** [comment]
@rafael noticed that connections hung on a different type of failure. So, I think there's a deeper problem in the connect code. I want to see if we can get to the root cause and report the actual error. Otherwise, this timeout will mask all of that.

**Comment by sougou** [comment]
Can you resolve the conflicts? Given that we haven't had time to find the root cause, it's better to get this submitted.

**Comment by adsr** [comment]
Opened a new PR https://github.com/vitessio/vitess/pull/5832

**Pull request closed without merging**
