### PR TITLE
unit_race: attempt to fix flaky mysql/server_test

### LINKED ISSUE #5631: unit_race test flakyness in vitess/go/mysql
```
2019-12-31T17:01:51.5814048Z ok  	vitess.io/vitess/go/memcache	1.009s
2019-12-31T17:01:58.4099659Z W1231 17:01:54.983007   18121 auth_server_static.go:202] Config parsed using legacy configuration. Please update to the latest format: {"user":[{"Password": "xxx"}, ...]}
2019-12-31T17:01:58.4101424Z E1231 17:01:54.985027   18121 server.go:325] Cannot read post-SSL client handshake response from client 1 ([::1]:37946): tls: client didn't provide a certificate
2019-12-31T17:01:58.4102657Z io.ReadFull(header size) failed
2019-12-31T17:01:58.4103325Z E1231 17:01:57.044655   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4103686Z E1231 17:01:57.047185   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4103979Z E1231 17:01:57.488260   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4104279Z E1231 17:01:57.489453   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4104560Z E1231 17:01:57.490707   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4106028Z W1231 17:01:57.491574   18121 server.go:368] Error authenticating user using MySQL native password: Access denied for user 'user1' (errno 1045) (sqlstate 28000)
2019-12-31T17:01:58.4106372Z E1231 17:01:57.491917   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4106911Z W1231 17:01:57.492699   18121 server.go:368] Error authenticating user using MySQL native password: Access denied for user 'user1' (errno 1045) (sqlstate 28000)
2019-12-31T17:01:58.4107198Z E1231 17:01:57.493028   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4107421Z E1231 17:01:57.493921   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4107625Z E1231 17:01:57.495589   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4107841Z E1231 17:01:57.497278   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4108307Z W1231 17:01:57.503602   18121 server.go:456] Slow connection from client 1 (127.0.0.1:43410): 369.3Âµs
2019-12-31T17:01:58.4108821Z E1231 17:01:57.510653   18121 server.go:278] mysql_server caught panic:
2019-12-31T17:01:58.4109032Z test panic attack!
2019-12-31T17:01:58.4109278Z /home/runner/work/vitess/vitess/go/mysql/server_test.go:127 (0xb16c4c)
2019-12-31T17:01:58.4109761Z 	io/vitess/go/mysql.(*testHandler).ComQuery: panic("test panic attack!")
2019-12-31T17:01:58.4110060Z /home/runner/work/vitess/vitess/go/mysql/conn.go:1070 (0xa8f11b)
2019-12-31T17:01:58.4110315Z 	io/vitess/go/mysql.(*Conn).execQuery: err := handler.ComQuery(c, query, func(qr *sqltypes.Result) error {
2019-12-31T17:01:58.4110569Z /home/runner/work/vitess/vitess/go/mysql/conn.go:771 (0xa8e6ea)
2019-12-31T17:01:58.4110806Z 	io/vitess/go/mysql.(*Conn).handleNextCommand: if err := c.execQuery(sql, handler, more); err != nil {
2019-12-31T17:01:58.4111079Z /home/runner/work/vitess/vitess/go/mysql/server.go:463 (0xabd38c)
2019-12-31T17:01:58.4111301Z 	io/vitess/go/mysql.(*Listener).handle: err := c.handleNextCommand(l.handler)
2019-12-31T17:01:58.4111602Z /opt/hostedtoolcache/go/1.12.14/x64/src/runtime/asm_amd64.s:1337 (0x488010)
2019-12-31T17:01:58.4112386Z 	goexit: BYTE	$0x90	// NOP
2019-12-31T17:01:58.4112735Z E1231 17:01:57.527611   18121 conn.go:1117] Error in the middle of a stream to client 5 (127.0.0.1:43418): forced error after send (errno 1047) (sqlstate 08S01)
2019-12-31T17:01:58.4113472Z W1231 17:01:57.555525   18121 server.go:368] Error authenticating user using MySQL native password: Access denied for user 'user1' (errno 1045) (sqlstate 28000)
2019-12-31T17:01:58.4114196Z W1231 17:01:57.560827   18121 server.go:368] Error authenticating user using MySQL native password: Access denied for user 'user2' (errno 1045) (sqlstate 28000)
2019-12-31T17:01:58.4114725Z --- FAIL: TestServer (0.06s)
2019-12-31T17:01:58.4116412Z ##[error]    server_test.go:238: listening on address '127.0.0.1' port 46285
2019-12-31T17:01:58.4142022Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e error -h 127.0.0.1 -P 46285 -u user1 -ppassword1]
2019-12-31T17:01:58.4143163Z ##[error]    server_test.go:602: Expected ConnCount=0, got 1
2019-12-31T17:01:58.4144723Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e panic -h 127.0.0.1 -P 46285 -u user1 -ppassword1]
2019-12-31T17:01:58.4146711Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e select rows -h 127.0.0.1 -P 46285 -u user1 -ppassword1]
2019-12-31T17:01:58.4148196Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e select rows -h 127.0.0.1 -P 46285 -u user1 -ppassword1]
2019-12-31T17:01:58.4149620Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e error after send -h 127.0.0.1 -P 46285 -u user1 -ppassword1]
2019-12-31T17:01:58.4150817Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e insert -h 127.0.0.1 -P 46285 -u user1 -ppassword1]
2019-12-31T17:01:58.4153056Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e schema echo -h 127.0.0.1 -P 46285 -u user1 -ppassword1 -D XXXfancyXXX]
2019-12-31T17:01:58.4154544Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e ssl echo -h 127.0.0.1 -P 46285 -u user1 -ppassword1 -D XXXfancyXXX]
2019-12-31T17:01:58.4156284Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e userData echo -h 127.0.0.1 -P 46285 -u user1 -ppassword1 -D XXXfancyXXX]
2019-12-31T17:01:58.4157526Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e select rows -h 127.0.0.1 -P 46285 -u user1 -pbad -D XXXfancyXXX]
2019-12-31T17:01:58.4158646Z ##[error]    server_test.go:1249: Running mysql command: /usr/bin/mysql [-v -v -v -e select rows -h 127.0.0.1 -P 46285 -u user2 -ppassword1 -D XXXfancyXXX]
2019-12-31T17:01:58.4159217Z E1231 17:01:57.561630   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4159723Z E1231 17:01:57.586110   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4160019Z E1231 17:01:57.592197   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4160394Z E1231 17:01:58.005498   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4160912Z E1231 17:01:58.398741   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4161204Z E1231 17:01:58.400935   18121 auth_server_static.go:142] Error parsing auth server config: EOF
2019-12-31T17:01:58.4161462Z FAIL
2019-12-31T17:01:58.4161723Z FAIL	vitess.io/vitess/go/mysql	3.821s
2019-12-31T17:01:58.4162596Z ok  	vitess.io/vitess/go/mysql/ldapauthserver	1.018s
```

### PR DESCRIPTION
**Pull request by deepthi**
Since the gauges are global, it is possible that some other test is incrementing connCount.
Check the delta instead.
Might fix #5631 

Signed-off-by: deepthi <deepthi@planetscale.com>

### CODE REVIEW

**Comment by deepthi** [comment]
Well, this didn't help.
I don't think there's any way to get a deterministic value for connCount.

**Comment by sougou** [comment]
> Well, this didn't help.
> I don't think there's any way to get a deterministic value for connCount.

The error implies that the initialConnCount was 1, which is strange. But what may generally be happening is that the error is sent to the client before the function returns, So, it's possible that the client checks the connCount before that function returns.
So, adding a short sleep (which I don't like), is likely to deflake this test.

**Comment by morgo** [comment]
@deepthi while we are waiting on a longer term fix, did you want to change this PR to rename the test to include _flaky_ in the filename so it will retry 3 times?

**Comment by sougou** [comment]
The test is still too flaky (or will always fail with mariadb102). I'm thinking we should look at using our on mysql client instead.

It probably made sense in the initial implementation to validate against a mysql's client. But now that we have bootstrapped and have confidence in our own client, there's no need to test against mysql's tools any more.

**Comment by deepthi** [comment]
> The test is still too flaky (or will always fail with mariadb102). I'm thinking we should look at using our on mysql client instead.
> 
> It probably made sense in the initial implementation to validate against a mysql's client. But now that we have bootstrapped and have confidence in our own client, there's no need to test against mysql's tools any more.

I'm going to close this for now. Changing the test to use our own client is a non-trivial rewrite of the test.

**Pull request closed without merging**
