### PR TITLE
correct gofmt of vtctld and re-sync go.mod

### PR DESCRIPTION
**Pull request by jmhodges**
This addresses symptoms, but not causes, discussed in #5755 and #5756

Signed-off-by: Jeff Hodges <jeff@somethingsimilar.com>

### CODE REVIEW

**Comment by jmhodges** [comment]
This failed because of some remote apt repo failing. Could I get a re-run?

**Comment by morgo** [comment]
I've triggered a rebuild.

**Comment by jmhodges** [comment]
Weird panic in the cluster_end / build (15) run that doesn't seem related?

**Comment by deepthi** [comment]
@sougou @morgo travis actually ran successfully but the status :point_up: didn't get updated.
One of you needs to override to merge this PR.

**Pull request merged**
