### PR TITLE
Upgrade to `go1.19.1`

### PR DESCRIPTION
**Pull request by frouioui**
## Description

This PR upgrades the go version to `go1.19.1`.

## Checklist

-   [x] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by deepthi — COMMENTED** [review]
What is the motivation for upgrading right now?
We should do version upgrades early in a release cycle versus late. Ideally we should also benchmark before we merge.

**Comment by mattlord** [comment]
Assuming we plan to merge this after the RC cutoff, then I like it! 🙂 Was that the plan?

**Comment by frouioui** [comment]
Removing the `Benchmark Me` label until we have upgraded the Golang version to `1.19.1` on arewefastyet too. Otherwise it will just create a bunch of failing benchmarks.

**Comment by deepthi** [comment]
@frouioui do you want to continue this PR or create a new one? We do want to upgrade on main.

**Comment by frouioui** [comment]
> @frouioui do you want to continue this PR or create a new one? We do want to upgrade on main.

I will use this Pull Request @deepthi

**Comment by frouioui** [comment]
> > @frouioui do you want to continue this PR or create a new one? We do want to upgrade on main.
> 
> I will use this Pull Request @deepthi

Nevermind, it was simpler to create a new Pull Request. Here is the new one: https://github.com/vitessio/vitess/pull/11655

**Pull request closed without merging**
