### PR TITLE
VReplication: throttle on target tablet

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

With this PR Vreplication throttles on writing to _target_ tablet. This applied to both table-copy writes and binlog events writes.

The VReplication Engine throttles by using the standard `check`, which assumes the backend is a shard's primary tablet, and which throttles by shard's lag.

I'm not sure if there's a scenario where the target is a replica? If so, we can certainly _also add_ `check-self` to the throttler's consideration.

## Related Issue(s)

- Tracking issue: #7362 
- Extends #7324 (which in turn extends #7319)

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [x]  VReplication
- [ ]  Cluster Management
- [ ]  Build 
- [ ]  VTAdmin

Because this PR extends #7324 it only makes sense to fully review it once #7324 is merged. Having said that, check out the specific changes under `go/vt/vttablet/tabletmanager/vreplication/`
cc @rohit-nayak-ps

### CODE REVIEW

**Comment by shlomi-noach** [comment]
This PR is ready; however, it does extend #7324 so it's best to first review that.

**Comment by rohit-nayak-ps** [comment]
What do you think of  extracting the  throttleStatusOK/throttle functions and related lagThrottler/lastSuccessfulThrottleCheck properties which are repeated in tableGC/vstreamer/vreplication into its own "class"?

**Comment by shlomi-noach** [comment]
> What do you think of extracting the throttleStatusOK/throttle functions

Yes, let me look into it. One hidden but important difference in the two implementations is that source side calls `CheckSelf` and target side calls `Check` for throttling.

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Comment by shlomi-noach** [comment]
@rohit-nayak-ps I will refactor this PR a bit to consolidate the calls for throttle checks; will request an additional review afterwards.

**Comment by shlomi-noach** [comment]
@rohit-nayak-ps I've created a new `throttler.Client` which is used by:

- vstreamer Engine
- replicator Engine
- tablegc

and which offers the functionality of checking the throttler and backing off with sleep as necessary.

**Pull request merged**
