### PR TITLE
actions: set ephemeral port range to include more ports

### PR DESCRIPTION
**Pull request by skottler**
## Description

This change aims to test whether ephemeral port exhaustion plays a role in intermittently failing tests.

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [x]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Comment by shlomi-noach** [comment]
I checked and current value is:
```
net.ipv4.ip_local_port_range = 32768	60999
```

does this PR decrease the existing value?

**Comment by shlomi-noach** [comment]
Silly me. No! It increases the range. I'm reading number wrong.

**Review by shlomi-noach — APPROVED** [review]

**Comment by skottler** [comment]
Replaced by https://github.com/vitessio/vitess/pull/7850.

**Comment by shlomi-noach** [comment]
Thank you @skottler ! This seems to solve `local_example` tests issues.

**Pull request closed without merging**
