### PR TITLE
Fix Online DDL Revert flakiness

### PR DESCRIPTION
**Pull request by frouioui**
## Description

This Pull Request fixes the flakiness induced by schema tracking in Online DDL Revert tests.

The interval at which vttablet sends schema updates has been lowered to `0.1` second instead of `5` seconds.

## Related Issue(s)

- fix https://github.com/vitessio/vitess/issues/10674
- Part of https://github.com/vitessio/vitess/issues/10620

## Checklist

-   [x] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by frouioui** [comment]
@shlomi-noach 👋🏻 After the last commit on this Pull Request (46129cd), all the OnlineDDL workflows passed on the first try, except for `Cluster (onlineddl_scheduler)`, which I believe failed pretty randomly after a short time:

```
I0712 14:58:59.048989   15320 vtgate_process.go:110] Running vtgate with command: vtgate --topo_implementation etcd2 --topo_global_server_address localhost:16002 --topo_global_root /vitess/global --log_dir /tmp/vt_3840535655/vtroot_16001/tmp_16003 --log_queries_to_file /tmp/vt_3840535655/vtroot_16001/tmp_16003/vtgate_querylog.txt --port 16010 --grpc_port 16011 --mysql_server_port 16012 --mysql_server_socket_path /tmp/vt_3840535655/vtroot_16001/tmp_16003/mysql.sock --cell zone1 --cells_to_watch zone1 --tablet_types_to_wait PRIMARY,REPLICA --service_map grpc-tabletmanager,grpc-throttler,grpc-queryservice,grpc-updatestream,grpc-vtctl,grpc-vtgateservice --mysql_auth_server_impl none --planner-version Gen4CompareV3
process 'vtgate' exited prematurely (err: exit status 1)
```

I feel confident rolling this out to `main` and seeing how it affects other Pull Requests.

**Comment by frouioui** [comment]
@shlomi-noach, do you think we should backport this to release-14?

**Review by shlomi-noach — APPROVED** [review]
Awesome, thank you!

**Comment by shlomi-noach** [comment]
@frouioui definitely, let's backport this!

**Pull request merged**
