### PR TITLE
[WIP]Support DESC and DESCRIBE for qualified tables

### LINKED ISSUE #5907: Unqualified DESC fails
#### Overview of the Issue
Unqualified `DESC` query fails on Vitess/vtgate while works on MySQL

#### Reproduction Steps

This works fine in MySQL:
```
mysql> DESC vt_db_name.table_name;
+------------------------+---------------------+------+-----+----------------------+--------------------------------+
| Field                  | Type                | Null | Key | Default              | Extra                          |
+------------------------+---------------------+------+-----+----------------------+--------------------------------+
....
```

This doesn't work in Vitess:
```
mysql> DESC db_name.table_name;
ERROR 1105 (HY000): vtgate: http://xxx/: no keyspace in database name specified. Supported database name format (items in <> are optional): keyspace<:shard><@type> or keyspace<[range]><@type>
```

### PR DESCRIPTION
**Pull request by saifalharthi**
closes #5907 
Basically re-write and re-route `DESC` or `DESCRIBE` as SHOW queries.
Signed-off-by: Saif Alharthi <saif@saifalharthi.me>

### CODE REVIEW

**Comment by harshit-gangal** [comment]
desc|describe|explain are synonyms. So, if you are implementing the partial support for former i.e. table and column, you can add partial support for explain as well.

https://dev.mysql.com/doc/refman/5.7/en/describe.html

{EXPLAIN | DESCRIBE | DESC}
    tbl_name [col_name | wild]

**Comment by sougou** [comment]
If `explain` is a synonym of `describe`, then it allows for other constructs like `explain select...`. So, I don't think we can restrict its syntax to just table names.

We'll have to look at expanding the ast to accommodate the other constructs.

**Comment by saifalharthi** [comment]
@sougou Correct, I knew EXPLAIN would be used in queries. but wasnt sure about Describe. I will expand the AST and do handles for it.

**Comment by saifalharthi** [comment]
Closing this PR in favor of refactoring the executor.

**Pull request closed without merging**
