### PR TITLE
Make `Durabler` interface methods public

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

This PR implements [an open RFC](https://github.com/vitessio/vitess/issues/15544) for moving the `Durabler` interface from the `reparentutil` package to public methods so it is easier to integrate Durability Policies from external packages 

## Related Issue(s)

RFC: https://github.com/vitessio/vitess/issues/15544

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by deepthi — APPROVED** [review]
LGTM. We also need approval from @GuptaManan100 as the primary author/maintainer of these files.

**Comment by deepthi** [comment]
@GuptaManan100 should we add this to the release notes for v20?

**Review by GuptaManan100 — COMMENTED** [review]
Yes! The changes look good to me, but we do need to add a section describing this change to the interface in `changelog/20.0/20.0.0/summary.md`

**Comment by timvaillancourt** [comment]
> Yes! The changes look good to me, but we do need to add a section describing this change to the interface in `changelog/20.0/20.0.0/summary.md`

@GuptaManan100 / @deepthi sounds good, changelog added 👍. Edits are appreciated

**Review by GuptaManan100 — APPROVED** [review]

**Pull request merged**
