### PR TITLE
Online DDL: revert considerations for migrations with foreign key constraints

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

This PR maps what kind of migrations, that deal with foreign keys, have revertibility risks.

As an obvious example: imagine `DROP`ping a FK child table. Then, as the parent has no children, you `DELETE` all rows from the parent. Then, you revert the `DROP`. The child table re-appears with rows that have no compatible rows in the parent.

This is but one example and this PR investigates the potential of other types of migrations to cause FK violation.

It should be noteworthy that FK violation in MySQL is generally in the user's hands. It is always possible, in MySQL, to `SET FOREIGN_KEY_CHECKS=0` and introduce violations. The server does not blow up, it's just that enforcement is suspended.

## Related Issue(s)

- #11975 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Up to https://github.com/vitessio/vitess/pull/14368/commits/7cee6d31f18e1fb368d27fa590cebb053520e369, we've deal with two situations that are actually manifestations of the same concept: dropping a foreign key.

When you drop a foreign key, you drop a constraint. When a constraint is dropped, your data becomes less constrained, and it is then possible for the data to take forms it could not, before. This is why reverting the drop of a foreign key is a problem: you reintroduce a constraint, and the data may already disagree with the constraint.

Moving on:

- Adding a FK constraint should not be an issue for the immediate revert. Of course, if you revert-the-revert then you're back in the "re-introduce a FK" problem. So in general, we don't need to worry about a `CREATE TABLE`.
- In MySQL, there's no `ALTER`ing a constraint. A constraint can be created or dropped. So we don't need to sorry about modifying a constraint (`ALTER CONSTRAINT ... ENFORCE` is outside the scope of this discussion).
- In MySQL, it is impossible to change the data type of a column covered by a foreign key (!). Vitess might actually want to offer this functionality in the long term, and in this case the `revert` can be impacted by the expansion of the data type scope (e.g. `int` to `bigint`). The impact for foreign keys exists, but the scenario is already covered outside the scope of foreign keys.
- This leaves us with "normal" `ALTER TABLE` statements. Can there be a scenario where an `ALTER TABLE` does not add/drop foreign keys, does not change data type, and still has revertibility issues? What could be such scenarios?
  - An immediate suspect is a change to `GENERATED` column, but thankfully MySQL's foreign keys do not allow use of `GENERATED` columns neither in parent nor child.
  - There can be an issue if a FK covered column is impacted by a change to a `CHECK` constraint. This is actually outside the scope of FK. This is really complex because the `CHECK` constraint expression may be complex and we cannot anticipate exactly how it might limit/expand the possible values.

More thinking to come.

**Comment by shlomi-noach** [comment]
Noteworthy: at this time Vitess does not prevent the scenario where a FK parent table is `DROP`ped. That is, it allows it. As reminder, in Online DDL tables aren't actually immediately dropped. 

First, they are `RENAME`d. Children's FK will migrate with the renamed table. What happens from that point on depends on whether [this MySQL patch](https://github.com/planetscale/mysql-server/commit/bb777e3e86387571c044fb4a2beb4f8c60462ced) is used or not. If used, then then effective immediately these FK constraints are ignored by InnoDB.
Then, at some point later on, the table is actually dropped. Again, with said patch, children tables still ignore that fact and continue to live happily. But the schema becomes inconsistent, and a logical backup+restore will fail.

So _at this time_ this is not being handled, and we assume that a child table gets dropped (or its foreign key constraints are dropped), before the parent table is dropped.

**Comment by shlomi-noach** [comment]
At this time I'm only able to see risks with all things removing-a-foreign-key. To that effect, I'm making this PR ready to review. We can iterate in the future in case we meet new scenarios.

**Review by notfelineit — APPROVED** [review]
this was a great read! Thank you 🙏

**Review by dbussink — APPROVED** [review]

**Pull request merged**
