### PR TITLE
Turn off percona 5.6 tests

### PR DESCRIPTION
**Pull request by systay**
## Description
Turns off percona 5.6 tests, since the binaries for it are no longer available.

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Comment by deepthi** [comment]
How is CI passing on the main branch? We still seem to have percona56 tests there.
https://github.com/vitessio/vitess/blob/main/.github/workflows/unit_test_percona56.yml

**Review by deepthi — CHANGES_REQUESTED** [review]
Needs further investigation as to why these tests pass on main.

**Comment by harshit-gangal** [comment]
This change is not required, breaking the CI workflows and using ubuntu-18.04 is sufficient to unlock the other PR merged.
https://github.com/vitessio/vitess/pull/8361

**Pull request closed without merging**
