### PR TITLE
Add support for the MySQL prepare command protocol

### PR DESCRIPTION
**Pull request by dcadevil**

### CODE REVIEW

**Comment by dcadevil** [comment]
image
I tested it and it works correctly.

**Comment by sougou** [comment]
Ahh ok. I see now. Github didn't show me all the changes...
This is very good work. However, we need more tests, lots more. All the conversion and protocol code needs to be covered. If you look at the tests for the regular protocol, equal amount is needed for the prepared statement protocol.

**Comment by dcadevil** [comment]
OK, I'll add test case.

**Comment by linuxgood1230** [comment]
Waiting for you merge to master
I want test.

**Comment by dcadevil** [comment]
@linuxgood1230  I'm very busy recently. After a few days I'll write test case. Thanks for your attention.

**Comment by deepthi** [comment]
Tests to be added:
1. go/mysql/query_test.go
   - TestComPrepare
   - TestComStmtExecute
   - TestStmtSendLongData
   - TestComStmtReset
   - TestComStmtClose
   
2. go/mysql/server_test.go
   - ComPrepare
   - ComStmtExecute

3. go/vt/vtgate/executor_test.go

4. go/vt/vtgate/plugin_mysql_server_test.go
   - ComPrepare
   - ComStmtExecute

5. go/vt/vtqueryserver/plugin_mysql_server_test.go
   - ComPrepare
   - ComStmtExecute

6. go/vt/vtgate/vtgate_test.go

7. go/vt/vtgate/endtoend

**Comment by deepthi** [comment]
@dcadevil I'm planning to write the testcases so that we can get this PR merged.

**Comment by dcadevil** [comment]
@deepthi Thank you very much, if you need any help, please let me know.

**Comment by deepthi** [comment]
> @deepthi Thank you very much, if you need any help, please let me know.

hi @dcadevil, can you put in some examples of how this feature is intended to be used?
basically example syntax of prepare statement, and execute statement with bind variables.

**Comment by dcadevil** [comment]
hi, @deepthi, the MySQL prepare protocol implemented here is not the prepare in the SQL syntax. 
You can refer to the this link: https://dev.mysql.com/doc/internals/en/prepared-statements.html

You can use java's jdbc driver client (note: useServerPrepStmts=true), or golang's go-mysql-driver(https://github.com/go-sql-driver/mysql) to test.

The basically example by golang can be found here: https://github.com/go-sql-driver/mysql/wiki/Examples

**Comment by saifalharthi** [comment]
@dcadevil I am writing the unit tests for this PR and I am learning more about the MySQL protocol. I am trying to write tests for:

* TestComStmtExecute
* TestComStmtReset
in `go/mysql/query_test.go`

and I am following the pattern of the tests. I noticed there are parse functions associated with them but write functions. I am not very familiar with MySQL protocol but is there an example you can give to help test those functions properly?

**Comment by dcadevil** [comment]
@saifalharthi, writeBinaryRows function can be regarded as the write function of parseComStmtExecute function. In fact, this function is used to transform the execution result into MySQL protocol format result after ComStmtExecute execution.

In addition, it should be noted that the parameters of the parseComStmtExecute function contain a map of prepareData, the key of which is the statementID, which contains the statement and the number of parameters. So to use the parseComStmtExecute function, you need to set up the map.

The setting of another data parameter is rather complicated. I recommend using JDBC or golang's MySQL client driver to execute prepared statement program to get it. Of course, it is a bit cumbersome and complicated to do so.

**Comment by tirsen** [comment]
I think this might solve our long standing issue with using the JDBC MySQL driver and Vitess: https://github.com/vitessio/vitess/issues/4100

Packet 20/0x16 is COM_PREPARE_STMT which is what that complains about. I think the MySQL JDBC driver always uses prepare statements.

Checking now.

**Comment by tirsen** [comment]
This is really amazing and thanks for all the effort you've put into this.

I'm trying this out in one of our apps and I'm running into this issue:
https://github.com/vitessio/vitess/issues/5075

Something wrong with the string encoding?

**Pull request merged**
