### PR TITLE
Inclusive Naming: TabletType + Misc Changes 

### PR DESCRIPTION
**Pull request by rohit-nayak-ps**
## Description
Part of the inclusive naming initiative. 

Changed various properties, protos, enums and strings to switch terminology from master to primary. Some key items that  changed:

* TabletType proto
* Shard proto
* topodatapb.TabletType_MASTER
* si.MasterAlias
* MasterTermStartTime
* GetIsMasterServing
* IsMasterServing
* checkIsMasterServing
* checkMastership

### Backward Compatibility
* MASTER has been kept as a synonym in tablet types
* Both  vtctlclient commands /vstream API continue to accept master 
* `use @master` will continue to work
* flags that use string values will accept both PRIMARY and MASTER
* Existing vreplication workflows that use MASTER as tablet_type will continue to work

## Breaking Changes
vtctl commands that output the tablet type, one or more the `master_term_start_time`, `master_alias` and/or `is_master_serving` attributes will now use primary instead of master. Thus any scripts or code that looks for these strings will need to be updated.

In particular:
#### tablet type master
* ListAllTablets
* ListTablets
* TopoCat
* Workflow Show
* VReplicationExec and VExec queries that return the `tablet_types` column

#### attributes `master_term_start_time`, `master_alias` and/or `is_master_serving`
* GetTablet
* GetShard
* FindAllShardsInKeyspace
* TopoCat
* Workflow Show

Signed-off-by: Rohit Nayak <rohit@planetscale.com>

## Related Issue(s)

#7113 
#7114

### CODE REVIEW

**Comment by deepthi** [comment]
Some things to check:
* `use @master`
* for flags that use tablet_type e.g. vtgate flag `tablet_types_to_wait`, vttablet flag `vreplication_tablet_type`, will we continue to accept `MASTER` as a valid value?

**Comment by rohit-nayak-ps** [comment]
Since all of these use `topodata.ParseTabletType` they all accept MASTER. 
> * `use @master`
> * for flags that use tablet_type will we continue to accept `MASTER` as a valid value?
>   * vtgate: `tablet_types_to_wait`, `allowed_tablet_types`, `default_tablet_type`

>   * vttablet flag `vreplication_tablet_type`, `init_tablet_type`, `throttle_tablet_types`
(`init_tablet_type` cannot be MASTER, as per current code)

>   * maybe time to remove `-demote_master_type` flag

Removed

**Review by deepthi — APPROVED** [review]
LGTM

**Comment by rohit-nayak-ps** [comment]
That made a dent, approx halved the references to master ...
```
rohit@rohit-ubuntu:~/vitess-ps$ git checkout release-11.0
Switched to branch 'release-11.0'
rohit@rohit-ubuntu:~/vitess-ps$ git grep -i master | wc -l
11524
rohit@rohit-ubuntu:~/vitess-ps$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'upstream/main'.
rohit@rohit-ubuntu:~/vitess-ps$ git grep -i master | wc -l
5750
```

**Pull request merged**
