### PR TITLE
WIP Running CI workflows on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

Resubmission of https://github.com/vitessio/vitess/pull/7613 (which went a bit stale). This is an attempt to see whether ubuntu-latest (`20.04` at this time) reduces CI flakiness.
## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [x]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Percona Server `5.6` is not available in Ubuntu `20.04`, so `Unit Test (percona56)` cannot be expected to run.

**Comment by shlomi-noach** [comment]
`PASSWORD` function no longer available in MySQL 8.0, so we replace it with its equivalent, `CONCAT('*', UPPER(SHA1(UNHEX(SHA1('<clear-text>')))))`

**Review by skottler — APPROVED** [review]
the procfs change looks good to me

**Comment by shlomi-noach** [comment]
At least the good news, seeing all those failed tests, is that these failures seem just flaky. I'm not sure either has to do with ubuntu 20.04

**Comment by shlomi-noach** [comment]
`percona56` test pinned to `ubuntu 18.04`

**Comment by shlomi-noach** [comment]
`cluster (17)` and `cluster (20)` continue to fail.

**Comment by shlomi-noach** [comment]
keeps failing: [cluster 17](https://github.com/vitessio/vitess/pull/7850/checks?check_run_id=2538047393), [cluster 20](https://github.com/vitessio/vitess/pull/7850/checks?check_run_id=2538047428)

**Comment by askdba** [comment]
@shlomi-noach is this still failing or ready to merge?

**Comment by shlomi-noach** [comment]
@askdba seems to pass now, but then again, looks like `main` already has a `.Ubuntu20` flag? Not sure how it works?

**Pull request closed without merging**
