### PR TITLE
Changed master to primary

### PR DESCRIPTION
**Pull request by arvind-murty**
## Description

Changed master to primary.

## Related Issue(s)

#8618 

## Checklist
- [ ] Should this PR be backported?
- [X] Tests were added or are not required
- [X] Documentation was added or is not required

### CODE REVIEW

**Comment by deepthi** [comment]
@jawabuu @arthurnn @eeSeeGee would any of you like to review these changes before they are merged?

**Comment by jawabuu** [comment]
@deepthi Sure.
@arvind-murty Have you tested a local compose run with the changes?

**Comment by arvind-murty** [comment]
> @arvind-murty Have you tested a local compose run with the changes?

I tested using `docker-compose.beginners.yml` and went through the steps in the `README`.
I did not try the custom config generation using `vtcompose.go`.

**Comment by deepthi** [comment]
@jawabuu nudge

**Comment by jawabuu** [comment]
@deepthi I'll complete this today

**Comment by jawabuu** [comment]
@deepthi  LGTM from initial tests.
If there is an edge case I missed we could have a follow-up PR.

**Comment by deepthi** [comment]
> @deepthi LGTM from initial tests.
> If there is an edge case I missed we could have a follow-up PR.

Thanks! that sounds good.

**Review by deepthi — APPROVED** [review]
Approving based on review from @jawabuu

**Pull request merged**
