### PR TITLE
Updates and Corrections to v9 Release Notes

### PR DESCRIPTION
**Pull request by askdba**
Signed-off-by: Alkin Tezuysal <alkin.tezuysal@gmail.com>

## Description
This pull request addresses issues with the Version 9 Release Notes. 

## Related Issue(s)
https://github.com/vitessio/vitess/issues/8212

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

**Comment by askdba** [comment]
Please do not merge until @systay approves.

**Review by frouioui — CHANGES_REQUESTED** [review]
Deletions are good for me. In the additions, the following PRs are missing: #6816, #6823, #6831, #6869, #6965, #7340

**Review by frouioui — APPROVED** [review]
Looks good!

**Comment by systay** [comment]
We need to move this to the `release-9.0` branch

**Pull request merged**
