### PR TITLE
Upgrade mysqld memory limits to 1024Mi

### PR DESCRIPTION
**Pull request by vinimdocarmo**
## Description

Current k8s resources for the operator example aren't enough in the current version. See more details here: https://github.com/vitessio/vitess/issues/13118

This PR is related: https://github.com/vitessio/website/pull/1477

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

## Deployment Notes

N/A

### CODE REVIEW

**Review by frouioui — APPROVED** [review]
LGTM, thank you!

**Comment by vinimdocarmo** [comment]
Hi @frouioui. Please check [this](https://github.com/vitessio/vitess/issues/13118#issuecomment-1558505244) out. Apparently another approach was discussed. I'm waiting for confirmations there to know how to proceed.

**Comment by frouioui** [comment]
> Hi @frouioui. Please check [this](https://github.com/vitessio/vitess/issues/13118#issuecomment-1558505244) out. Apparently another approach was discussed. I'm waiting for confirmations there to know how to proceed.

Let's hold on until @GuptaManan100 answers your comment.

**Comment by vinimdocarmo** [comment]
@frouioui, the other approach didn't work. We can go ahead with this one.

https://github.com/vitessio/vitess/issues/13118#issuecomment-1568694328

**Review by GuptaManan100 — APPROVED** [review]

**Pull request merged**
