### PR TITLE
resharding: CancelResharding

### PR DESCRIPTION
**Pull request by sougou**
CancelResharding works for horizontal and vertical resharding
as long as migration hasn't started.

Signed-off-by: Sugu Sougoumarane <ssougou@gmail.com>

### CODE REVIEW

**Comment by rafael** [comment]
Nice. This is very handy and we've found ourselves starting from scratch a split in a shard because we didn't have a clean way to do this. 

Should we add this functions to the docs so they get shown here: https://vitess.io/reference/vtctl/?

**Comment by tirsen** [comment]
Oh man we've needed this so many times. Doing it by hand is so painful. :-)

**Comment by tirsen** [comment]
Oh man we've needed this so many times. Doing it by hand is so painful. :-)

**Comment by rafael** [comment]
LGTM +1

**Pull request merged**
