### PR TITLE
go mod tidy

### PR DESCRIPTION
**Pull request by systay**

### CODE REVIEW

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm. need to fix conflict ...

**Comment by derekperkins** [comment]
We should add a CI check that fails the build if go mod tidy isn't clean. This is what we have in our config.

```
go mod tidy
output=$(git status -s) && if [ ${#output} -eq 0 ]; then exit 0; else echo "$output"; exit 1; fi
```

**Comment by deepthi** [comment]
> We should add a CI check that fails the build if go mod tidy isn't clean. This is what we have in our config.
> 
> ```
> go mod tidy
> output=$(git status -s) && if [ ${#output} -eq 0 ]; then exit 0; else echo "$output"; exit 1; fi
> ```

Good point.
@askdba can you please create an issue for this?

**Comment by askdba** [comment]
> > We should add a CI check that fails the build if go mod tidy isn't clean. This is what we have in our config.
> > ```
> > go mod tidy
> > output=$(git status -s) && if [ ${#output} -eq 0 ]; then exit 0; else echo "$output"; exit 1; fi
> > ```
> 
> Good point.
> @askdba can you please create an issue for this?

https://github.com/vitessio/vitess/issues/7154

**Pull request merged**
