### PR TITLE
trigger pr-labels workflow when labels added/removed from PR

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

followup to #8147 
the workflow doesn't seem to kick when labels are added to a PR. This PR attempts to fix this.
 
## Related Issue(s)

#8146 

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

**Comment by shlomi-noach** [comment]
hmmm, `pr-labels` didn't even trigger when this PR wa sopened.

**Comment by shlomi-noach** [comment]
`pr-labels` is not even here right now.

**Comment by shlomi-noach** [comment]
OK good. Adding a label now triggers `pr-labels`

**Comment by shlomi-noach** [comment]
this should be good to merge once all tests are green.

**Comment by systay** [comment]
beautiful!

**Review by systay — APPROVED** [review]

**Pull request merged**
