### PR TITLE
Vitess.io logo update

### PR DESCRIPTION
**Pull request by raunaqgupta**
* Updating Vitess logo
* Updating brand colors
* Adding Pinterest logo in the adopters list

### CODE REVIEW

**Comment by skinnylatte** [comment]
Hey @raunaqgupta - we are good to go except for this one small thing.

When you click any of the menu items and go into any of the pages: /overview, /user-guide/introduction, /reference/vitess-api, the spacing for the title becomes lost.

Like this:

screenshot 2018-08-30 20 50 23

If you can fix this, we can publish this rightaway.

**Comment by skinnylatte** [comment]
@raunaqgupta - please also explore another color, other than brown. I do agree with @derekperkins, brown makes it look a little dull.

**Comment by raunaqgupta** [comment]
The spacing issue seems to be a build issue as a lot of styles are not being applied in the `publish-site` version which work fine in the `preview-site` version in `site.scss`. Does anyone know what's the cause of that?

**Comment by skinnylatte** [comment]
@raunaqgupta i like this color. thoughts, @derekperkins, @jvaidya, @sougou?

Also, need your eyes on Raunaq's question about the styling issue [above](https://github.com/vitessio/vitess/pull/4158#issuecomment-417826384).

**Comment by raunaqgupta** [comment]
screenshot_2018-09-05 vitess - database clustering system for horizontal scaling of mysql

**Comment by derekperkins** [comment]
How does that look on the subpages title bars?

**Comment by raunaqgupta** [comment]
screenshot_2018-09-11 vitess user guide - introduction

**Comment by derekperkins** [comment]
I think that should match the same schema as the homepage, with a gray background at the top and a white/off-white title. I don't mind the orange hyperlinks, but I don't like orange in the other tones.

I'd also like to see the white/off-white in the menu lose the orange tint and go back to the original shade (#E0F7FA).

Thanks for your patience @raunaqgupta, I'm not trying to be difficult. IMO, orange is a difficult color to weave through a site, hence so many companies going with blue color schemes. Also, I'm not the only person with a say in how the site looks, so feel free to get feedback from others too. :)

**Comment by sougou** [comment]
Looks like the root cause of the font issue hasn't been found. I'm going to submit this PR with the hope that may it will be fine. If not, we'll revert it.

**Pull request closed without merging**
