### PR TITLE
[release-17.0] Upgrade go from 1.20.13 to 1.20.14

### PR DESCRIPTION
**Pull request by GrahamCampbell**
## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by systay** [comment]
Thanks for this @GrahamCampbell!

You need to sign the commit for this to go through. That's what the DCO CI step is complaining about.

```
git commit --amend --no-edit -s
```

and the `git push -f`

**Comment by shlomi-noach** [comment]
@GrahamCampbell thank you -- can you please clarify the specific purpose of this version upgrade? As mentioned in https://github.com/vitessio/vitess/pull/15650#issuecomment-2036792589 the `golang` security fix was not made in `1.20`. So I'm just checking, other than the good practice of staying up-to-date, is there a particular thing to look out for in this upgrade?

**Comment by dbussink** [comment]
> There was a security fix, but not the same fix from this month. It was a fix from the round of golang releases before that.

Right, we still need to look into if we need to upgrade to Go 1.21 here for example to address the latest issues.

**Comment by dbussink** [comment]
This also doesn't update the base images which is a separate process, so it's not going to be complete.

**Review by frouioui — CHANGES_REQUESTED** [review]
Hello @GrahamCampbell, thank you for taking the time to think about doing this and creating the PR. We are still unsure whether or not to merge this or to directly upgrade to `go1.21`, we are going to talk about it.

In the meantime, upgrading the Golang version is little bit more involved than that. Refer to https://github.com/vitessio/vitess/pull/15639 to see an example of how it is done. We need to bump the golang version used by `vitess/bootstrap` (as you did), and increment the minor version of the `vitess/bootstrap` by one, and then build and push the docker image.

Won't approve this for now as we are still reviewing with the rest of the maintainers.

**Comment by GrahamCampbell** [comment]
> and increment the minor version of the vitess/bootstrap by one, and then build and push the docker image.

Right. That's not something I can do. ;)

**Comment by frouioui** [comment]
> Right. That's not something I can do. ;)

You could change the `bootstrap_version` though.

**Comment by frouioui** [comment]
I am closing this Pull Request in favor of https://github.com/vitessio/vitess/pull/15669, which upgrades to the next minor version of Go.

Thank you @GrahamCampbell 🙇🏻

**Pull request closed without merging**
