### PR TITLE
vtctl: add workflow commands

### PR DESCRIPTION
**Pull request by demmer**
Add two new vtctl commands WorkflowShow and WorkflowNames which expose the contents of running workflows to the CLI.

This is based on #3382. Will rebase once that merges but I wanted to get initial thoughts.

### CODE REVIEW

**Comment by arthurnn** [comment]
can `vtctlclient` do this already?

**Comment by demmer** [comment]
@arthurnn Ha! Apropos to the conversation in Slack I just learned about `vtctlclient`.

The changes in #3382 look like they're completely unnecessary in a `vtctlclient` world because they'd already be registered in vtctld and thereby exposed through vtctlclient.

These two are new commands however and would be exposed through both clients.

**Comment by sougou** [comment]
tests need fixing.

**Comment by demmer** [comment]
@sougou This has now passed travis and is ready for review.

I again disagree with the CodeClimate complaints.

**Comment by sougou** [comment]
Can you write tests that prove that this works? You should be able to piggy-back on an existing flow, and show that these commands print out the necessary info.

**Comment by sougou** [comment]
This has been lingering. Did you still want to push this through? If so, conflicts need resolving, and tests needed.

**Comment by demmer** [comment]
Yeah I know — this isn’t actually important for us any more as we’ve stopped using Workflow. 

I’d be fine to just close it and we can always reopen if someone finds the desire to pick it up.

**Pull request closed without merging**
