### PR TITLE
VReplication: more unrecoverable error codes

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

followup to #9973, #10390, #10394

Adding error codes related to `DATETIME` value conversion/truncation. This will fail a `VReplication` workflow, and specifically an Online DDL `vitess` migration, immediately upon receipt of such error.

## Related Issue(s)

#6926 

## Checklist

-   [ ] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by dbussink** [comment]
@shlomi-noach as a bugfix, would this also be eligible to backport to the 14 release branch as well?

**Comment by shlomi-noach** [comment]
> would this also be eligible to backport to the 14 release branch as well?

I think so!

**Comment by shlomi-noach** [comment]
> but I see some onlineddl workflows are failing.

yes, there is increased flakiness lately, which I don't have good explanation for, yet.

**Comment by shlomi-noach** [comment]
Ohhhh. The `vrepl` tests are failing because I accidentally committed a temp directory into the test suite. Removing it.

**Pull request merged**
