### PR TITLE
Upgrade to `go1.18.9`

### PR DESCRIPTION
**Pull request by frouioui**
## Description

This Pull Request upgrades the go version used on `release-15.0` to `go1.18.9`.

### CODE REVIEW

**Review by deepthi — CHANGES_REQUESTED** [review]
We should not do major golang version upgrades on release branches. We should only be doing security patch upgrades.

**Review by deepthi — APPROVED** [review]

**Comment by rsajwani** [comment]
does go upgrade always result in upgrade in bootstrap version or is it just you did both as part of same PR to save CI cycle.?
Rest looks good to me.

**Review by GuptaManan100 — APPROVED** [review]
Approval for after answering Rameez's comment.

**Comment by frouioui** [comment]
> does go upgrade always result in upgrade in bootstrap version or is it just you did both as part of same PR to save CI cycle.?
Rest looks good to me.
Also its would be good if you can mention bootstrap version upgrade in description as well.

Hello @rsajwani, we always bump the bootstrap version when upgrading the Go version. When we upgrade the Go version on a release branch, we bump the bootstrap version by `0.1`. On `main`, we bump the version by `1.0`.

**Pull request merged**
