### PR TITLE
add option to disable lookup read lock

### PR DESCRIPTION
**Pull request by maxenglander**
## Description

(This PR is based on [this other PR](https://github.com/vitessio/vitess/pull/11313). Once that PR is merged, will refresh this one and take out of draft state. See [here for accurate diff](https://github.com/maxenglander/vitess/compare/jg-maxeng-noverify...maxenglander:vitess:maxeng-opt-disable-locking-read?expand=1).)

DML to lookup VIndexes unconditionally takes a row lock on rows in the lookup VIndex backing table. Add an option to optionally elide this lock for cases where we know via business logic that the row will not be deleted, nor the lookup column changed.

## Related Issue(s)

Fixes https://github.com/vitessio/vitess/issues/11612

## Checklist

-   [ ] "Backport me!" label has been added if this change should be backported
-   [ ] Tests were added or are not required
-   [x] Documentation was added or is not required:
     * https://github.com/vitessio/website/pull/1193

### CODE REVIEW

**Comment by harshit-gangal** [comment]
This would need website documentation.

**Comment by maxenglander** [comment]
Thanks @harshit-gangal will follow-up here once the PRs for `no_verify` get merged.

**Comment by deepthi** [comment]
@maxenglander while we wait for re-review from harshit, do you mind creating a `Feature Request` issue for this and linking it in?
Something like `Option to optimize locking for lookup Vindexes...` or whatever you think is best.

**Comment by maxenglander** [comment]
@deepthi will do, thank you!

**Review by harshit-gangal — APPROVED** [review]
LGTM

**Pull request merged**
