### PR TITLE
Allow sending back stale shard name data if requested,…

### LINKED ISSUE #5038: SHOW VITESS_SHARDS intermittently returns an empty list of shards
`SHOW VITESS_SHARDS` intermittently returns an empty list of shards

I think the issue can be traced down to these lines of code at `go/vt/vtgate/executor.go:800`:
```
			_, _, shards, err := e.resolver.resolver.GetKeyspaceShards(ctx, keyspace, destTabletType)
			if err != nil {
				// There might be a misconfigured keyspace or no shards in the keyspace.
				// Skip any errors and move on.
				continue
			}
```

As you can see errors are ignored. So if there is for example an intermittent connectivity problem with the topology server then we would return an empty list rather than signaling an error.

I think the correct solution is to catch and ignore specific errors but in general pass the errors on.

### PR DESCRIPTION
**Pull request by aquarapid**
… instead of zeroing it out.
Fixes #5038

### CODE REVIEW

**Comment by deepthi** [comment]
Welcome @aquarapid! We tend to not list the issue in the PR title, preferring a line like `Fixes #0000` in the description. That will ensure that when this PR is merged, the issue will automatically be closed.

**Comment by sougou** [comment]
Need to fix DCO. Also, the build broke. Looks like some interfaces may need to be updated.

**Comment by deepthi** [comment]
@aquarapid ping
can you fix the DCO?

**Comment by aquarapid** [comment]
@deepthi @sougou this is ready for review.  As a stress test, I ran the script mentioned here https://github.com/vitessio/vitess/issues/5038#issuecomment-530153284 but with a million iterations against a vtgate instance, and did not see a single error.

**Comment by deepthi** [comment]
LGTM
@tirsen @sougou can you also review?

**Comment by deepthi** [comment]
Trying to kick CI.

**Pull request merged**
