### PR TITLE
change -mysql_server_bind_address

### PR DESCRIPTION
**Pull request by lokune**
More info in this thread https://vitess.slack.com/archives/C0PQY0PTK/p1571783731198400

Signed-off-by: lokune <laban.okune@ma3route.com>

### CODE REVIEW

**Comment by morgo** [comment]
@enisoc do you know if there are any security consequences here, or is this straight forward to merge?

**Comment by enisoc** [comment]
I would prefer to make this passed in as an option, with the default still being `localhost` since that's more secure. Would that still work for your use case @lokune?

**Comment by lokune** [comment]
@enisoc, I was thinking of the same, and yes it will still work for my use case but I assumed it should be fine as is since this is the test module?

**Comment by enisoc** [comment]
I was thinking that we wouldn't want people to run something as a test and unintentionally expose a server over the network.

**Comment by lokune** [comment]
Makes sense... Seems like there has to be changes in `vttest/run_local_database.py`, `local_database.py` and `vttest/vt_processes.py`. Would you like to take over from here? I can also try if you are busy but I would prefer someone more experienced with Vitess codebase.

**Comment by lokune** [comment]
@enisoc, I decided to give it a shot and made the changes as per your suggestion. Let me know what you think. cc @morgo

**Pull request merged**
