### PR TITLE
Refactor `InitShardMaster` checks so that `InitShardMaster` can be called on a brand new shard without using `--force`

### PR DESCRIPTION
**Pull request by zmagg**
## Description

An initial step to work on #4110 . I think it'd be better to have a new shard automatically elect a master as part of setting up a new shard and its tablets, but this is an incremental improvement to make things safer for us as we continue splitting keyspaces in the next week.

Refactor `InitShardMaster` checks so that we can call `InitShardMaster` on a brand new shard without using `--force`.

Adds a sanity check that keyspace / shard match the keyspace / shard of the chosen elected master tablet. 

## Testing

- [x] Test in our dev environment. Verify able to `InitShardMaster` on a brand new shard without using `--force`
- [ ] Need to add unit tests around the new checks.

### CODE REVIEW

**Comment by sougou** [comment]
I think this is unsafe. The absence of a master doesn't necessarily mean that we're bringing up empty databases. It's quite possible that someone has brought up a brand new cluster against an already running set of mysqls. If so, they should not be allowed to `InitShardMaster`, and should have to use `TabletExternallyReparented` instead.

The safer thing would be to not require ISM at all. The first tablet that comes up for a keyspace-shard, if empty, should declare itself to be the master.

The part that I'm still not sure about is: what do we do about the replica? If it's empty, there are two paths:
1. Restore from backup and then point to the master.
2. If no backups are present, assume it's a new cluster, and directly point to master.

Option 2 has some minor risk for the case where it's actually not a new cluster. There must be a way to be sure we're new. Can't think of one right now.

**Comment by sougou** [comment]
I thought about this some more. There is no good way to be 100% sure about the second case.

So, we should make this a formal property of a shard:
* Add a new field `initialized` to the shard record.
* If vttablet creates it implicitly, it will be set to `false`.
* `ISM` can then check this flag. If it's `false`, then `-force` is not required. If `ISM` succeeds, it will set this flag to `true`.
* `CreateShard` will default this to true. We'll need to add an override for those who want to create an unitialized shard.
* We'll also need a way to turn this flag on/off in case a shard was incorrectly created.
* Currently, a vttablet that comes up against an empty mysql spams the logs with errors. If the flag is false, it can instead quietly wait till `ISM` does its thing.

The flag will still be useful if we eventually make `ISM` implicit (automatically coordinated by the vttablets).

Thoughts?

**Comment by zmagg** [comment]
@sougou I like it! It makes sense to add a flag to differentiate externally-managed MySQL clusters and fully Vitess-managed MySQL clusters. 

One thing I'm wondering is if the shard record is the right place to store that information. Would it make sense to store that information globally instead of shard record by shard record? I'm not super sure about the use cases for externally-managed clusters, as Slack lets Vitess do all the `CreateShard`-style management.

I'm in training all day today/tomorrow, so I'll be slow to respond and get started on this, but I like this approach to solve this problem and I can take on the coding of it this week.

**Comment by zmagg** [comment]
@sougou Realistically....no. Been dragged away to other things and this is lower priority for us. Closing for now.

**Pull request closed without merging**
