### PR TITLE
add mysql native password to login

### PR DESCRIPTION
**Pull request by yangxuanjia**
Signed-off-by: yangxuanjia <yangxuanjia@jd.com>

"mysql_user": [
     {
      "MysqlNativePassword": "*9E128DA0C64A6FCCCDCFBDD0FC0A2C967C6DB36F",
       "Password": "mysql_password",
       "UserData": "mysql_user"
     }
   ],
  "mysql_user2": [
    {
      "Password": "mysql_password",
      "UserData": "mysql_user"
    }
  ],
 "mysql_user3": [
    {
      "MysqlNativePassword": "*9E128DA0C64A6FCCCDCFBDD0FC0A2C967C6DB36F",
      "UserData": "mysql_user"
  }
  ],

### CODE REVIEW

**Comment by yangxuanjia** [comment]
The error message does not have anything to do with the code I submitted

**Comment by alainjobart** [comment]
Thanks, that looks good.

Can you please add a unit test or two in server_test.go, around line 234, that would exercise the new code? TestConnectionWithoutSourceHost can be duplicated, replacing Password with MysqlNativePassword...

**Comment by yangxuanjia** [comment]
Thanks.
I have some company work today,  I will add UT next week.

**Comment by yangxuanjia** [comment]
@alainjobart , I add one UT ,  sorry for late.

**Pull request merged**
