### PR TITLE
Online DDL:  ddl_type column

### PR DESCRIPTION
**Pull request by shlomi-noach**
Context: #6926 
This PR extends https://github.com/vitessio/vitess/pull/7083

Given #7083 adds support for `CREATE` and `DROP` in online DDL, this PR adds a new column, `ddl_action`, to the backend `schema_migrations` table.

Values of this column are necessarily one of:

- `create`
- `alter`
- `drop`

which are the three supported online DDL types.

This column gets populated via `vtctld` and is communicated via `vtctl OnlineDDL show ...` command.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Only review after https://github.com/vitessio/vitess/pull/7083 is merged.

**Comment by shlomi-noach** [comment]
Documentation PR: https://github.com/vitessio/website/pull/623

**Comment by shlomi-noach** [comment]
:pray:  @vitessio/ps-vitess  request for review

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Comment by shlomi-noach** [comment]
Will resolve conflict after merging #7083

**Pull request merged**
