### PR TITLE
Add flags to allow PITR binlog client TLS support

### PR DESCRIPTION
**Pull request by aquarapid**
Fix bug where password was never passed.

Signed-off-by: Jacques Grove <aquarapid@gmail.com>

### CODE REVIEW

**Comment by aquarapid** [comment]
I cannot easily modify the endtoend tests to test the TLS support;  they need to be changed to (also) pull binlogs from an upstream mysql server.  This will take some time;  we can review the rest in the meanwhile.

**Comment by aquarapid** [comment]
I have added an e2e test for this (TestTLSPITRRecovery).  It has a few issues:
 * It does not test mTLS (client certs)
 * It is distinct from the current binlog tests, so it adds significant testing time to the e2e tests (4-5 mins).  May be possible to integrate them to cut this down a bit

I am not planning to fix these issues in this PR.

**Review by deepthi — APPROVED** [review]
LGTM

**Comment by deepthi** [comment]
@arindamnayak this looked fine to me, but can you please take a look also?
If there's any feedback it can be addressed as a separate PR.

**Pull request merged**
