### PR TITLE
Fix all occurrences of `fmt.Sprint(x)` where x is `int`

### PR DESCRIPTION
**Pull request by ajm188**
## Description

What it says in the title. Also reorder some imports to follow the "stdlib/3rdparty+vitess/proto" pattern.

## Related Issue(s)

- From [this discussion](https://github.com/vitessio/vitess/pull/7240#discussion_r551208289)

## Checklist
- [ ] Should this PR be backported? **No**
- [ ] Tests were added or are not required **N/A**
- [ ] Documentation was added or is not required **N/A**

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build

### CODE REVIEW

**Comment by ajm188** [comment]
@shlomi-noach I believe this also fixes some of the goimports issues you were discussing in #7235

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Review by shlomi-noach — APPROVED** [review]
lgtm; personal preference to keep `printf` behavior, and change to `fmt.Sprintf("%d", <the-value>)` instead of `strconv.FormatInt(<the-value>, 10)` but it's fine as it is.

**Review by deepthi — APPROVED** [review]

**Comment by ajm188** [comment]
fwiw `fmt.Sprintf` and `fmt.Sprint` have the same performance characteristics, which was the original motivation for this change.

**Comment by shlomi-noach** [comment]
> have the same performance characteristics, which was the original motivation for this change

I see. I thought this was about a linter issue.

**Pull request merged**
