### PR TITLE
Add support for parsing the 'CONSTRAINT' keyword within the create table definition

### PR DESCRIPTION
**Pull request by bramp**

### CODE REVIEW

**Comment by sougou** [comment]
Need to `commit -s` for DCO. Also need codeclimate fix.

**Comment by bramp** [comment]
ah sorry ok. Will fix shortly.

**Comment by nebril** [comment]
Seems like this was added via 24eca5fed19ab3274ad5a95e01bac3c2f1b71b10, should this PR be closed?

**Comment by derekperkins** [comment]
`CONSTRAINT` works for me. Feel free to reopen this if need be.

**Pull request closed without merging**
