### PR TITLE
Modify ETCD_BINDIR for aarch64

### PR DESCRIPTION
**Pull request by jiameixie**
Modify ETCD_BINDIR in local example env script for aarch64

Change-Id: I1a9d6591316b60f1c7672f4c0eb4906f6dc65de7
Signed-off-by: Jiamei.Xie <Jiamei.Xie@arm.com>

### CODE REVIEW

**Comment by morgo** [comment]
Hi @jiameixie - I have another PR I just opened which should make this one obsolete: https://github.com/vitessio/vitess/pull/5427

Do you mind reviewing it to confirm?

(The advantage of the PR I have open is that it can get Vitess in a state of no longer shipping etcd.)

**Comment by jiameixie** [comment]
> Hi @jiameixie - I have another PR I just opened which should make this one obsolete: #5427
> 
> Do you mind reviewing it to confirm?
> 
> (The advantage of the PR I have open is that it can get Vitess in a state of no longer shipping etcd.)

Yes, it's true. It will be obsolete after #5427 merged. I'll change it according to #5427

**Comment by jiameixie** [comment]
I added a condition to check if directory "${VTROOT}/dist/etcd" exists as below. Is this ok? 
   if [ -d "${VTROOT}/dist/etcd" -a "$(arch)" == aarch64 ];then
            ETCD_BINDIR="${VTROOT}/dist/etcd/etcd-${ETCD_VERSION}-${etcd_platform}-arm64/"
    else
            ETCD_BINDIR="${VTROOT}/dist/etcd/etcd-${ETCD_VERSION}-${etcd_platform}-amd64/"
    fi

**Comment by morgo** [comment]
> Hi @morgo - I added a condition to check if directory "${VTROOT}/dist/etcd" exists as below. Is this ok?
> if [ -d "${VTROOT}/dist/etcd" ];then
> if [ "$(arch)" == aarch64 ];then
> ETCD_BINDIR="${VTROOT}/dist/etcd/etcd-${ETCD_VERSION}-${etcd_platform}-arm64/"
> else
> ETCD_BINDIR="${VTROOT}/dist/etcd/etcd-${ETCD_VERSION}-${etcd_platform}-amd64/"
> fi
> else
> ETCD_BINDIR=$(dirname `which etcd`)
> fi

I think we can totally remove this, and just rely on `$PATH` :-) The current solution is a problem, because it is implying that we ship etcd in the Vitess packages.

**Comment by jiameixie** [comment]
> > Hi @morgo - I added a condition to check if directory "${VTROOT}/dist/etcd" exists as below. Is this ok?
> > if [ -d "${VTROOT}/dist/etcd" ];then
> > if [ "$(arch)" == aarch64 ];then
> > ETCD_BINDIR="${VTROOT}/dist/etcd/etcd-${ETCD_VERSION}-${etcd_platform}-arm64/"
> > else
> > ETCD_BINDIR="${VTROOT}/dist/etcd/etcd-${ETCD_VERSION}-${etcd_platform}-amd64/"
> > fi
> > else
> > ETCD_BINDIR=$(dirname `which etcd`)
> > fi
> 
> I think we can totally remove this, and just rely on `$PATH` :-) The current solution is a problem, because it is implying that we ship etcd in the Vitess packages.

Got it. I'll close this request.

**Pull request closed without merging**
