### PR TITLE
refac: Remove duplicate `forAllShards` methods from `vt/vtctl/workflow`

### PR DESCRIPTION
**Pull request by beingnoble03**
## Description
This PR removes some duplicate code from `vt/vtctl/workflow`
- Removes multiple `forAllShards` methods
- Moves `validateSourceTablesExist` from server.go to utils.go removing the method receiver.
- Adds unit tests for `validateSourceTablesExist`

## Related Issue(s)
- #16499

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by mattlord** [comment]
Just FYI, there are also some unit tests that cover the workflow package in rpc_vreplication_test.go as well. That is needed to test the tablet side (the database queries) of the work where we’ve replaced vexec usage with specific RPCs.

**Comment by beingnoble03** [comment]
@mattlord thanks for letting me know. I don't we need unit tests added here then.

**Review by mattlord — APPROVED** [review]
Thanks, @beingnoble03 !

**Review by rohit-nayak-ps — APPROVED** [review]
Nice refactor, thanks!

**Pull request merged**
