### PR TITLE
Removing Linux/amd64 specific subdependencies

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

Reported by @systay, the merging of https://github.com/vitessio/vitess/pull/7725 introduced a subdependency `github.com/moby/term` which does not build on MacOS:

```
> make build
Tue Apr 6 14:14:12 CEST 2021: Building source tree
# github.com/moby/term
../go/pkg/mod/github.com/moby/term@v0.0.0-20200429084858-129dac9f73f6/tc.go:13:28: undefined: unix.SYS_IOCTL
../go/pkg/mod/github.com/moby/term@v0.0.0-20200429084858-129dac9f73f6/tc.go:18:28: undefined: unix.SYS_IOCTL
../go/pkg/mod/github.com/moby/term@v0.0.0-20200429084858-129dac9f73f6/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
../go/pkg/mod/github.com/moby/term@v0.0.0-20200429084858-129dac9f73f6/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
make: *** [build] Error 2
```

This is a subdependency of `github.com/fsouza/go-dockerclient`, which is in itself a dependency of `tengo`.

We already user our own [fork](https://github.com/planetscale/tengo) of `tengo`. I've submitted and merged https://github.com/planetscale/tengo/pull/5, which removes any `docker` references, none of which we use. This removes the dependencies  on aforementioned libraries. I tagged as `v0.9.6-ps.v2`

This PR instructs `go.mod` to use `v0.9.6-ps.v2`.

## Checklist
- [x] Should this PR be backported? (to `v10`)
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [x]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Review by systay — APPROVED** [review]

**Comment by deepthi** [comment]
@gedgar created #7787 yesterday to fix the same issue. However, I'm not sure if that will stick because the `go mod tidy` test is failing right now on it.
cc @shlomi-noach

**Comment by shlomi-noach** [comment]
I ran `go mod tidy` and committed to https://github.com/vitessio/vitess/pull/7787. If https://github.com/vitessio/vitess/pull/7787 works, then I prefer that https://github.com/vitessio/vitess/pull/7787 is merged over this PR, because this PR requires us to edit our fork of `tengo` and this causes maintainership pains.

**Comment by shlomi-noach** [comment]
closing since https://github.com/vitessio/vitess/pull/7787 fixed the problem in a different way.

**Comment by shlomi-noach** [comment]
Again, dropped `docker` code from `planetscale/tengo`, and this removes dependency modules that are giving us some pains.

**Pull request merged**
