### PR TITLE
Flush binlogs after reparent

### PR DESCRIPTION
**Pull request by rafael**
### Desc

Addresses #4161 

### Test

I tested this in our dev environment.  @sougou  do you think we should add some sort of integration/unit tests for this? Not sure how to go about it. Do you have ideas on that regard?

### CODE REVIEW

**Comment by rafael** [comment]
We deployed this change to our production env. We got 0 errors after this during a full fleet `PlannedReparent` !!

**Comment by demmer** [comment]
IMO this is a great change and as @rafael said it has a lot of benefits for Slack's environment.

I would however like to get an outside perspective before merging this as it does have some production implications for the number of binlogs produced.

**Comment by sougou** [comment]
To avoid the painful introduction of another TabletManager API call, we could just add the `FLUSH` invocation to `PromoteSlave`: https://github.com/vitessio/vitess/blob/master/go/vt/mysqlctl/reparent.go#L117

**Comment by rafael** [comment]
@sougou  - At first, I did not want to do it like that because I thought I was overloading `PromoteSlave` and I was leaning towards being more explicit. However, I did not know about the dumb client policy.  Given that, adding this to `PromoteSlave` seems good to me. I'll update.

**Comment by sougou** [comment]
Closing this in favor of #4179

**Pull request closed without merging**
