### PR TITLE
CI: Correct etcd and ncurses package names for Ubuntu 24.04

### PR DESCRIPTION
**Pull request by mattlord**
## Description

In Ubuntu 24.04 — [which is currently what is used for `ubuntu-latest` in GitHub Actions](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) — the [`etcd` package was split into `etcd-client` and `etcd-server`](https://packages.ubuntu.com/search?keywords=etcd&searchon=names&suite=noble&section=all) and [it includes libncurses6](https://packages.ubuntu.com/search?keywords=libncurses&searchon=names&suite=noble&section=all).

> [!NOTE]
> This is not needed today (the driver for opening this seems to have been fixed in Actions) — so there must be package helpers in 24.04 that help bridge the gap and cover the transition, but these may go away in 26.04. Since these *are* the correct package names, there's no reason not to make the change.

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Might it be prudent to pin to ubuntu-22.04, rather than latest (in particular for the versions older than Vitess 22), so things don't break from under us?

**Comment by mattlord** [comment]
> Might it be prudent to pin to ubuntu-22.04, rather than latest (in particular for the versions older than Vitess 22), so things don't break from under us?

Yeah, it looks like we'll probably need to do that.

**Review by arthurschreiber — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
> Yeah, it looks like we'll probably need to do that.

Or at least, pin to 24.04, so the next upgrade to 26.04 will be explicit.

**Review by arthurschreiber — APPROVED** [review]

**Review by frouioui — APPROVED** [review]

**Comment by dbussink** [comment]
> Might it be prudent to pin to ubuntu-22.04, rather than latest (in particular for the versions older than Vitess 22), so things don't break from under us?

We had everything pinned, but that was changed in https://github.com/vitessio/vitess/pull/16714. @frouioui Was that done out of necessity there? I know we pinned it explicitly before to avoid upgrade problems.

**Pull request merged**
