### PR TITLE
backport: upgrade tests vs v9

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

Backport of https://github.com/vitessio/vitess/pull/7848, test upgrade vs. v9

## Checklist
- [x] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [x]  Build/CI
- [ ]  VTAdmin

cc @askdba @deepthi

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Currently GitHub/workflows CI has a DNS resolution issue, described in https://github.com/actions/virtual-environments/issues/3185

I'm using this PR to also backport the patch suggested in said issue, which was proven to work well via #7847

**Review by askdba — APPROVED** [review]
LGTM

**Comment by deepthi** [comment]
The port-range and DNS fixes need to go into unit_race.yml, local_example.yml and region_example.yml. These aren't failing on the main branch right now because there we started running them in docker.

**Comment by shlomi-noach** [comment]
Added the DNS+prt range patches to aforementioned tests plus other tests I thought may be relevant.

**Comment by shlomi-noach** [comment]
Ahhhh it's finally green! I'm good to merge this, keeping this open for a few more hours then merging

**Pull request merged**
