### PR TITLE
Add in stats counters for ExecuteOptions_DBA inuse and total transactions.

### PR DESCRIPTION
**Pull request by makmanalp**
A step towards tackling #4197 - tracking DBA transactions that are running but have been idle. The idea is that as long as we have external visibility over this number, we can alert and handle the scenario where leaky transactions are growing for some reason.

Apologies, it's my first time contributing and:

1) I'm not sure I've gotten the terminology correct re: Active / Idle / Persistent, etc.
2) I'm not sure what should go into `numbered.go` vs `tx_pool.go` - I could have e.g. had `GetPersistent` return just a number, but I tried to not put highly tx_pool specific stuff into the more generic Numbered struct.
3) I'm not sure of the approach of using a Gauge function and counting the thing on-demand instead of having an `sync2.AtomicInt64` (like `tx_pool.go:waiters`) and incrementing / decrementing it manually in each appropriate spot - seemed like that approach had many more edge cases and this was simpler.
4) I'm not sure if there are any gaps - any other numbers we'd like to add in while we're at it.

Happy to make any changes.

### CODE REVIEW

**Comment by sougou** [comment]
This looks good. Can you add a test for this here: https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/endtoend/transaction_test.go#L316.

Also, how about the idea enforcing transaction timeouts for these connections?

**Comment by makmanalp** [comment]
Hey Sugu - I'm working on adding tests but it took a bit longer because I had a bit of trouble figuring out how to test the in-use transaction counter in a non-gross and slow way, but it seems like perhaps calling `select sleep(5);` in a goroutine might be the best way to go - let me know if you agree.

In the meantime I have to finish integrating this on our end to unblock some other folks, but I'll get back to this soon.

Re: enforcing transaction timeouts for these connections, I think this is a good idea and we had some good discussion about this. I'm thinking of opening up a separate issue with all the ideas so we can track things there instead of piggybacking this PR.

**Comment by sougou** [comment]
Oh. No need to test the non-kill part. Just up to the point where we verify that the dba count went up to 1. So, you can delete the rest, and we can get this submitted.

**Comment by sougou** [comment]
Looks like you've already added the tests that verify stats. Can you remove the TODOs? Then this is good to go.

**Comment by sougou** [comment]
Reminder. You just need to delete the TODO lines to get this submitted.

**Comment by sougou** [comment]
@makmanalp ping

**Comment by morgo** [comment]
@makmanalp I am going to close this PR due to staleness, but please feel free to re-open if you would like to bring it back to life. Thanks!

**Pull request closed without merging**
