### PR TITLE
Open vtadmin-api port in docker-local example to enable vtadmin access

### PR DESCRIPTION
**Pull request by andylim-duo**
## Description
This PR adds a port to enable access to the vtadmin API for the local docker image. This will enable [Local Install via Docker](https://vitess.io/docs/16.0/get-started/local-docker/) to work correctly. 

## Related Issue(s)
No related issue was open for this PR, but I'm happy to create one if you all think it is required.

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported - _not added._
-   [x] Tests were added or are not required - _No test were added, but manual verification was done see below_
-   [x] Did the new or modified tests pass consistently locally and on the CI - _Manual testing passed_
-   [x] Documentation was added or is not required - _website should be updated to include `vtadmin` access port. I will submit a separate PR against the website_. The website [PR is #1393](https://github.com/vitessio/website/pull/1393) for the website repository. 

## Deployment Notes
No deployment updates

## Testing
I manually verified that vtadmin is now accessible from the local docker installation of vitess.

commerce-local-VTAdmin

### CODE REVIEW

**Review by mattlord — APPROVED** [review]
Thanks again, @andylim-duo ! ❤️

**Comment by mattlord** [comment]
@andylim-duo I think we need to add the vtadmin-api and vtadmin-web ports here for all the doc versions: https://vitess.io/docs/16.0/get-started/local-docker/#run-the-docker-image

Is that what you were planning to open a docs PR for?

**Comment by andylim-duo** [comment]
> @andylim-duo I think we need to add the `vtadmin-api` and `vtadmin-web` ports here for all the doc versions: https://vitess.io/docs/16.0/get-started/local-docker/#run-the-docker-image
> 
> Is that what you were planning to open a docs PR for?

Yup, I put up a PR for the website repository - https://github.com/vitessio/website/pull/1393

**Review by deepthi — APPROVED** [review]
Thank you for the contribution!

**Comment by deepthi** [comment]
> No related issue was open for this PR, but I'm happy to create one if you all think it is required.

I did not require a new issue, since this is a followup to #12382 and can be considered part of fixing #12310

**Pull request merged**
