### PR TITLE
Allow version to be accessible via the -v shorthand

### PR DESCRIPTION
**Pull request by ajm188**
## Description

Before/after adding my absurdly "I am very annoyed by computers right now" lengthily-named function:

```
➜  vitess git:(vmain) ✗ vttablet -v
unable to redefine 'v' shorthand in "vttablet" flagset: it's already used for "version" flagpanic: unable to redefine 'v' shorthand in "vttablet" flagset: it's already used for "version" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0x140001ae100, 0x1400099a000)
        github.com/spf13/pflag@v1.0.5/flag.go:874 +0x3a8
github.com/spf13/pflag.(*FlagSet).AddGoFlag(0x140001ae100, 0x140000c62c0)
        github.com/spf13/pflag@v1.0.5/golangflag.go:90 +0x80
github.com/spf13/pflag.(*FlagSet).AddGoFlagSet.func1(0x140000acde0?)
        github.com/spf13/pflag@v1.0.5/golangflag.go:99 +0x2c
flag.(*FlagSet).VisitAll(0xf?, 0x140008bfd08)
        flag/flag.go:394 +0x50
github.com/spf13/pflag.(*FlagSet).AddGoFlagSet(0x140001ae100, 0x140000c4300)
        github.com/spf13/pflag@v1.0.5/golangflag.go:98 +0x48
vitess.io/vitess/go/internal/flag.Parse(0x140001ae100)
        vitess.io/vitess/go/internal/flag/flag.go:47 +0x38
vitess.io/vitess/go/vt/servenv.ParseFlags({0x105b071dc, 0x8})
        vitess.io/vitess/go/vt/servenv/servenv.go:310 +0x30
main.main()
        vitess.io/vitess/go/cmd/vttablet/vttablet.go:83 +0x50
➜  vitess git:(vmain) ✗ make
Fri Oct 14 20:10:52 EDT 2022: Building source tree
➜  vitess git:(vmain) ✗ vttablet -v
Version: 16.0.0-SNAPSHOT (Git revision b942dc3378f433278e4a4b22fb9bd86a0b63efd4 branch 'vmain') built on Fri Oct 14 20:10:52 EDT 2022 by andrew@<a computer> using go1.18.6 darwin/arm64
```

## Related Issue(s)

https://github.com/rohit-nayak-ps/vreplication-docs/pull/2#discussion_r995542326

## Checklist

-   [x] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by deepthi** [comment]
Thank you!
Unit tests are failing 
```
go.vt.vtadmin flag redefined: v
[94](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:95)
panic: go.vt.vtadmin flag redefined: v
[95](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:96)

[96](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:97)
goroutine 1 [running]:
[97](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:98)
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0000a5100, 0xc000133ea0)
[98](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:99)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x5e6
[99](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:100)
vitess.io/vitess/go/internal/flag.preventGlogVFlagFromClobberingVersionFlagShorthand(0xc00011c120?)
[100](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:101)
	/home/runner/work/vitess/vitess/go/internal/flag/flag.go:118 +0x85
[101](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:102)
vitess.io/vitess/go/internal/flag.ParseFlagsForTest()
[102](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:103)
	/home/runner/work/vitess/vitess/go/internal/flag/flag.go:161 +0x346
[103](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:104)
vitess.io/vitess/go/vt/vtadmin.TestMain(0xcccb11?)
[104](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:105)
	/home/runner/work/vitess/vitess/go/vt/vtadmin/api_test.go:63 +0x1e
[105](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:106)
main.main()
[106](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:107)
	_testmain.go:167 +0x1d3
[107](https://github.com/vitessio/vitess/actions/runs/3255913954/jobs/5346107107#step:9:108)
FAIL	vitess.io/vitess/go/vt/vtadmin	0.024s
```

**Comment by ajm188** [comment]
> Thank you! Unit tests are failing
> 
> ```
> go.vt.vtadmin flag redefined: v
> panic: go.vt.vtadmin flag redefined: v
> goroutine 1 [running]:
> github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0000a5100, 0xc000133ea0)
> 	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x5e6
> vitess.io/vitess/go/internal/flag.preventGlogVFlagFromClobberingVersionFlagShorthand(0xc00011c120?)
> 	/home/runner/work/vitess/vitess/go/internal/flag/flag.go:118 +0x85
> vitess.io/vitess/go/internal/flag.ParseFlagsForTest()
> 	/home/runner/work/vitess/vitess/go/internal/flag/flag.go:161 +0x346
> vitess.io/vitess/go/vt/vtadmin.TestMain(0xcccb11?)
> 	/home/runner/work/vitess/vitess/go/vt/vtadmin/api_test.go:63 +0x1e
> main.main()
> 	_testmain.go:167 +0x1d3
> FAIL	vitess.io/vitess/go/vt/vtadmin	0.024s
> ```

ah, my shim is non-idempotent, which only matters in tests

(sorry, i meant to quote reply and I somehow edited your comment instead!)

**Comment by deepthi** [comment]
Upgrade/downgrade tests don't depend on `--version` so overriding.
The failures are because we upgraded golang on release-15 to 1.18.7.

**Comment by ajm188** [comment]
manually back porting this one, hold tight

**Pull request merged**
