### PR TITLE
[vtadmin] add to local example

### LINKED ISSUE #7598: Add vtadmin to the local example
#### Feature Description

Update 101_initial_cluster.sh to start up a local vtadmin installation, pointed at the local cluster.

#### Use Case(s)

Manual testing during vtadmin development, and demonstration of working features in PRs

### PR DESCRIPTION
**Pull request by ajm188**
## Description

This PR does two things:
* Remove our poorly-and-not-actually-supported TLS based grpc connections, by always specifying `grpc.WithInsecure` when dialing vtctlds and vtgates. We'll come back around to make this more robust and flexible.
* Add scripts to run vtadmin-{api,web}, with the local example.

To run, `cd examples/local; ./101_initial_cluster.sh; ./vtadmin-up.sh`, and ctrl-C at any point to tear down the vtadmin components. `401_teardown.sh` is still used to tear down the other components, as per usual.

Example: 
Screen Shot 2021-03-16 at 2 24 14 PM

## Related Issue(s)

- Closes #7598 

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build/CI
- [x]  VTAdmin

### CODE REVIEW

**Review by doeg — APPROVED** [review]
This looks good to me! 

... Caveat that I haven't run it though. My local machine is, uh... very much not set up to run Vitess outside of Docker. (I was... experimenting... at one point. 😊 ) 

I think there's a couple minor changes we'll need to the local Docker flow to get VTAdmin working there, too, but I can do those later on! I don't think we should block this on that, personally. :)

**Comment by rohit-nayak-ps** [comment]
Get this error when I ran it locally (followed your instructions above). npm install seems to have worked fine, error was while starting the development server.
```
Failed to compile.

./src/components/App.module.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-7-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-7-4!./src/components/App.module.scss)
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1

```

**Comment by doeg** [comment]
Bah... node-sass is notoriously inflexible across node versions + platforms since it depends heavily on [gyp](https://www.npmjs.com/package/node-sass#install), my nemesis. 

@rohit-nayak-ps when you get a chance, could you send me the output of the following?

```
npm -v              
node -v
node -p process.versions
node -p process.platform
node -p process.arch
```

For reference, here's my node/npm versions:

```
🍕~/workspace/vitess/web/vtadmin $ npm -v 
6.14.9
🍕~/workspace/vitess/web/vtadmin $ node -v
v14.15.3
```

I've been testing vtadmin-web against LTS only (node v.14.16.... looks like I'm already behind 😤) so that would be my first guess! 

Would also recommend an `rm -rf web/vtadmin/node_modules` if you haven't done so. :)

**Comment by rohit-nayak-ps** [comment]
> Would also recommend an `rm -rf web/vtadmin/node_modules` if you haven't done so. :)

This didn't help. Output of those commands:
```
$ npm -v              
7.0.3

$ node -v
v15.0.1
 
$ node -p process.versions
{
  node: '15.0.1',
  v8: '8.6.395.17-node.15',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '88',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
 
$ node -p process.platform
linux
 
$ node -p process.arch
x64
```

**Comment by doeg** [comment]
@rohit-nayak-ps ah ok, looks like your node version is newer than VTAdmin supports. :) 

VTAdmin targets LTS (v14.x), and an unfortunate trade-off with our node-sass dependency is that we lose portability between node versions. That said! If PlanetScale is already on node v.15, I can prioritize updating VTAdmin's version to the same.

In the meantime, if you want to run this locally, I personally really like using [nvm](https://github.com/nvm-sh/nvm) for managing multiple node versions.

**Comment by rohit-nayak-ps** [comment]
> VTAdmin targets LTS (v14.x), and an unfortunate trade-off with our node-sass dependency is that we lose portability between node versions. That said! If PlanetScale is already on node v.15, I can prioritize updating VTAdmin's version to the same.

Cool. Installed 14.0.0 with nvm and it works fine :-)

**Comment by rohit-nayak-ps** [comment]
This is really awesome to have vtadmin within local example!!

**Pull request merged**
