### PR TITLE
OnlineDDL: cleanup cancelled migration artifacts; support `--retain-artifacts=<duration>` DDL strategy flag

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

This PR first and foremost fixes https://github.com/vitessio/vitess/issues/14022, by ensuring to collect `cancelled` migrations artifacts for cleanup. The change is in `onlineddl/schema.go`, a mere SQL query modification.

As a bonus, it also fixes https://github.com/vitessio/vitess/issues/14024, introducing `--retain-artifacts=<duration>` DDL strategy flag, which now allows a per-migration setting for artifact retention. This flag came useful when designing the `endtoend` tests for collecting `cancelled` migration artifacts.

## Related Issue(s)

Fixes https://github.com/vitessio/vitess/issues/14022
Fixes https://github.com/vitessio/vitess/issues/14024

Docs: https://github.com/vitessio/website/pull/1590

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Docs PR: https://github.com/vitessio/website/pull/1590

**Review by deepthi — COMMENTED** [review]
The bug fix looks fine to me, but I'm wondering if there's a cleaner way to handle the flag.
@ajm188 thoughts?

**Review by ajm188 — APPROVED** [review]
LGTM

**Comment by ajm188** [comment]
> The bug fix looks fine to me, but I'm wondering if there's a cleaner way to handle the flag. @ajm188 thoughts?

not particularly, not without overhauling how `ddl-strategy` is parsed. imo it's fine to keep things this way

**Review by deepthi — APPROVED** [review]

**Comment by shlomi-noach** [comment]
We can always iterate later on how these flags are parsed...

**Comment by ajm188** [comment]
> We can always iterate later on how these flags are parsed...

if we were, the direction i have in mind is similar to how vtadmin subcomponents parse their flags https://github.com/vitessio/vitess/blob/main/go/vt/vtadmin/vtsql/config.go#L83-L109 and https://github.com/vitessio/vitess/blob/main/go/vt/vtadmin/vtctldclient/config.go#L81-L100

**Pull request merged**
