### PR TITLE
vtgate sql: enforce a max row count limit

### PR DESCRIPTION
**Pull request by sougou**
I've been claiming that vtgate had a max row count limit.
It turns out that I never actually implemented it.
So, here's the implementation.

Signed-off-by: Sugu Sougoumarane <ssougou@gmail.com>

### CODE REVIEW

**Comment by sougou** [comment]
This was loosely based the fact hat vttablets already limit the max count to 10K. Are there workloads that pull under 10K from each vttablet, that still add up to over 30K?

**Comment by zmagg** [comment]
> This was loosely based the fact hat vttablets already limit the max count to 10K. Are there workloads that pull under 10K from each vttablet, that still add up to over 30K?

 Definitely. We have some scatter queries that absolutely hit that. I just checked. :)

**Comment by sougou** [comment]
Can you check if they were using OLTP, and not OLAP? Note that it's a bad idea to do it this way. We've always said that one should use OLAP if fetching more than 10K rows.

The main motivation behind this limit is to prevent site-wide outage from a rogue query. If it pulls too many rows, it can OOM all the vtgates. Ideally, we should have a global limit. But that's hard to track and enforce. So, this is some kind of a start.

Will 100K be reasonable?

**Comment by demmer** [comment]
Slack doesn't use OLAP anywhere.

Yes we realize there are probably better ways to do this... but in the global scheme of tradeoffs what we have is the least-bad.

**Pull request merged**
