### PR TITLE
naming: deprecate old flags and create new ones (master->primary)

### PR DESCRIPTION
**Pull request by deepthi**
## Description

Deprecate vtctl command flags that contain `master` and introduce replacements that use `primary` instead.
Full list is documented in linked issue.
Along the way I needed to make changes in `wranger/testlib` so I went through and cleaned up all references in that package.

## Related Issue(s)

#7114 

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required (will be added to https://github.com/vitessio/website/pull/786)

## Deployment Notes

All changes are fully backwards-compatible and will remain so in release 12. Old flags will be removed in release 13, so users are advised to change their scripts and tooling before then.

### CODE REVIEW

**Review by ajm188 — APPROVED** [review]
lgtm

**Comment by deepthi** [comment]
@ajm188 noted that it would be nice to add a big `DEPRECATED` to the flag help as well. Right now it looks like this:
```
$ vtctlclient PlannedReparentShard --help
Usage: PlannedReparentShard -keyspace_shard=<keyspace/shard> [-new_primary=<tablet alias>] [-avoid_tablet=<tablet alias>] [-wait_replicas_timeout=<duration>]

Reparents the shard to the new primary, or away from old primary. Both old and new primary need to be up and running.

  -avoid_master string
    	alias of a tablet that should not be the master, i.e. reparent to any other tablet if this one is the master
  -avoid_tablet string
    	alias of a tablet that should not be the primary, i.e. reparent to any other tablet if this one is the primary
  -keyspace_shard string
    	keyspace/shard of the shard that needs to be reparented
  -new_master string
    	alias of a tablet that should be the new master
  -new_primary string
    	alias of a tablet that should be the new primary
  -wait_replicas_timeout duration
    	time to wait for replicas to catch up on replication before and after reparenting (default 30s)
```
which can be very confusing.
I will change the flag help for all deprecated flags before merging this.

**Review by deepthi — COMMENTED** [review]
TODO: update flag help with `DEPRECATED`.

**Comment by deepthi** [comment]
Sample help output after fixing the flag docs. Manually verified each of the 8 commands changed in this PR.
```
$ vtctlclient PlannedReparentShard --help
Usage: PlannedReparentShard -keyspace_shard=<keyspace/shard> [-new_primary=<tablet alias>] [-avoid_tablet=<tablet alias>] [-wait_replicas_timeout=<duration>]

Reparents the shard to the new primary, or away from old primary. Both old and new primary need to be up and running.

  -avoid_master string
    	DEPRECATED. Use -avoid_tablet instead
  -avoid_tablet string
    	alias of a tablet that should not be the primary, i.e. reparent to any other tablet if this one is the primary
  -keyspace_shard string
    	keyspace/shard of the shard that needs to be reparented
  -new_master string
    	DEPRECATED. Use -new_primary instead
  -new_primary string
    	alias of a tablet that should be the new primary
  -wait_replicas_timeout duration
    	time to wait for replicas to catch up on replication before and after reparenting (default 30s)
```

**Pull request merged**
