### PR TITLE
Adding file storage backup support for helm based deployment

### PR DESCRIPTION
**Pull request by lokanadham100**

### CODE REVIEW

**Comment by sougou** [comment]
This has been lingering. Can we move to a resolution?
@derekperkins @dkhenry

**Comment by mayurthakur29** [comment]
are this changes verified .

**Comment by dkhenry** [comment]
The implementation looks fine. This will need to be rebased and tested.

**Comment by sougou** [comment]
Looks like this has gone stale. Closing.

**Pull request closed without merging**
