### PR TITLE
change bad handshake logging to INFO

### PR DESCRIPTION
**Pull request by drogart**
Addresses https://github.com/vitessio/vitess/issues/5191

This changes logging of bad handshakes from error to info.  It also adds a bit of detail to the log message to indicate it may be from a non-mysql connection attempt.

/cc @morgo

### CODE REVIEW

**Comment by sougou** [comment]
Can you update the commit with `git commit -s`?

**Comment by drogart** [comment]
> Can you update the commit with `git commit -s`?

Done [here](https://github.com/vitessio/vitess/pull/5208/commits/1ec86fadf9f6d5e22796ddc4eff75c007cb953c6).  Thanks!

**Comment by sougou** [comment]
DCO is still not green. Looks like the old commit without the signature is still part of the PR.

**Comment by enisoc** [comment]
drogart?

obiwan

**Comment by drogart** [comment]
Eh, I'm just gonna spin a new PR with proper signoff because I'm still learning rebasing etc.

**Pull request closed without merging**
