### PR TITLE
Remove additional unused Dockerfile entries

### PR DESCRIPTION
**Pull request by dbussink**
The `docker/k8s` directory also seems to trace back to when Helm was still a thing. It also doesn't actually have a `vtorc` container which indicates it's not actually used since `vtorc` is actually required these days.

From the looks of it, the same applies to `docker/mini` and that is unused as well.

## Related Issue(s)

Found when looking at pending comments for #3553

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by derekperkins** [comment]
The k8s images are very much in use, not sure about docker/mini, I didn't know it even existed

image

https://hub.docker.com/orgs/vitess/insights

**Comment by dbussink** [comment]
> The k8s images are very much in use, not sure about docker/mini, I didn't know it even existed

Ah, I don't have access to those Docker stats.

**Comment by dbussink** [comment]
Closing this as we do seem to publish `docker/k8s` (but need to dig more where it comes from and how we tag this, since we build from `stable-slim` for Debian but I see different base version tags :confused:).

**Comment by dbussink** [comment]
Opened https://github.com/vitessio/vitess/pull/13347 for the cleanup TODO that we can fix now.

**Pull request closed without merging**
