### PR TITLE
Flakes: Handle Non-Determinstic Shard Ordering in VGTID

### PR DESCRIPTION
**Pull request by mattlord**
## Description

I've noticed that the `TestVStreamCopyResume` test has been flaky lately in the endtoend workflow since we merged https://github.com/vitessio/vitess/pull/12623. You can see an example of it failing 4 times in a row here: https://github.com/vitessio/vitess/actions/runs/4432838267

After investigating the failures, the reason for them is that the order of the shards in the VGTID event is non-deterministic and thus so is which one has the `table_p_ks` field: https://github.com/vitessio/vitess/blob/7afc6e1e1816a820baba841fd4dc38901d40e5a3/go/vt/vtgate/endtoend/vstream_test.go#L483-L488

The regexp would fail if the 80- shard was first in the output. This PR alters the regexp so that it matches regardless of the shard order in the output. 

The test was failing in the CI ~ 50% of the time. With the changes in this PR, it has passed XX times in a row: https://github.com/vitessio/vitess/actions/runs/4434033059/jobs/7779619850

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Comment by vmg** [comment]
Definitely can see this flake. Can you un-draft the PR, @mattlord ?

**Comment by dbussink** [comment]
Going to merge as it's causing friction in other places as well.

**Comment by mattlord** [comment]
The regex was still slightly off. Going to open a new PR.

**Pull request merged**
