### PR TITLE
Fixes for local docker environment

### LINKED ISSUE #12310: Bug Report: "npm: command not found" when following Vitess 14 Local Install.
### Overview of the Issue

When running "Local Install" on CentOs 8 {1}...

{1}: https://vitess.io/docs/14.0/get-started/local/

...I am getting "npm: command not found" when running `101_initial_cluster.sh`:
```
[...]
vtgate is up!
Access vtgate at http://<my hostname>:15001/debug/status
vtadmin-api is running!
  - API: http://localhost:14200
  - Logs: /home/$USER/my-vitess-example/vtdataroot/tmp/vtadmin-api.out
  - PID: 5455

./scripts/vtadmin-up.sh: line 38: npm: command not found
./scripts/vtadmin-up.sh: line 40: npm: command not found
vtadmin-web is running!
[...]
```

### Reproduction Steps

```
./scripts/vtadmin-up.sh: line 38: npm: command not found
./scripts/vtadmin-up.sh: line 40: npm: command not found
```

### Binary Version

```sh
vitess-14.0.4-7fafc94
```

### Operating System and Environment details

```sh
$ cat /etc/centos-release
CentOS Stream release 8
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by andylim-duo**
## Description
This pull request fixes a couple of current problems with the local docker installation container. While following the Getting Started guide for [Local Install via Docker](https://vitess.io/docs/16.0/get-started/local-docker/),  I ran into a couple of errors. These two errors included:
* `npm` command not found
   ```
    Waiting for vtgate to be up...
    vtgate is up!
    Access vtgate at http://f992a1293646:15001/debug/status
    vtadmin-api is running!
    - API: http://localhost:14200/
    - Logs: /vt/vtdataroot/tmp/vtadmin-api.out
    - PID: 2456
    
    ../common/scripts/vtadmin-up.sh: line 39: npm: command not found
    ../common/scripts/vtadmin-up.sh: line 41: npm: command not found
   ```
*  The **vtadmin** web application was not installed in the correct location
   ```
   Error: EACCES: permission denied, mkdir '/web'
   TypeError: Cannot read property 'get' of undefined
      at errorHandler (/usr/share/npm/lib/utils/error-handler.js:208:18)
      at /usr/share/npm/bin/npm-cli.js:85:20
      at cb (/usr/share/npm/lib/npm.js:224:22)
      at /usr/share/npm/lib/npm.js:262:24
      at /usr/share/npm/lib/config/core.js:81:7
      at Array.forEach (<anonymous>)
      at /usr/share/npm/lib/config/core.js:80:13
      at f (/usr/lib/nodejs/once/once.js:25:25)
      at afterExtras (/usr/share/npm/lib/config/core.js:178:20)
      at Conf.<anonymous> (/usr/share/npm/lib/config/core.js:234:20)
   ```
For more details, see our discussion in the Vitess Slack Channel [here](https://vitess.slack.com/archives/C02JQQ88Z1C/p1676408775552939).

## Related Issue(s)

Fixes #12310 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported - **No backport**
-   [x] Tests were added or are not required - **See Manual Test below**
-   [x] Documentation was added or is not required - **No documentation updates required**

## Manual Test
I manually verified the two make commands - `make docker_local` and `make docker_run_local`. The output for each command is shown below:

`make docker_local` output:
```
$ make docker_local    
Building vitess/local
Building docker using straight docker build
[+] Building 465.0s (23/23) FINISHED                                                                                      
 => [internal] load build definition from Dockerfile                                                                 0.1s
 => => transferring dockerfile: 1.31kB                                                                               0.0s
 => [internal] load .dockerignore                                                                                    0.0s
 => => transferring context: 35B                                                                                     0.0s
 => [internal] load metadata for docker.io/vitess/bootstrap:14-common                                                3.1s
 => [auth] vitess/bootstrap:pull token for registry-1.docker.io                                                      0.0s
 => [ 1/17] FROM docker.io/vitess/bootstrap:14-common@sha256:e853ecc1ac68a9e6efec60e74865d31de2d5b35256041b78b75973  0.0s
 => [internal] load build context                                                                                    2.5s
 => => transferring context: 312.25kB                                                                                2.5s
 => CACHED [ 2/17] RUN apt-get update                                                                                0.0s
 => CACHED [ 3/17] RUN apt-get install -y sudo curl vim jq                                                           0.0s
 => CACHED [ 4/17] COPY docker/lite/install_dependencies.sh /vt/dist/install_dependencies.sh                         0.0s
 => CACHED [ 5/17] RUN /vt/dist/install_dependencies.sh mysql57                                                      0.0s
 => [ 6/17] COPY docker/local/install_local_dependencies.sh /vt/dist/install_local_dependencies.sh                   0.1s
 => [ 7/17] RUN /vt/dist/install_local_dependencies.sh                                                              29.6s
 => [ 8/17] RUN echo "source /vt/common/env.sh" >> /etc/bash.bashrc                                                  0.5s
 => [ 9/17] COPY --chown=vitess:vitess . /vt/src/vitess.io/vitess                                                   12.4s 
 => [10/17] WORKDIR /vt/src/vitess.io/vitess                                                                         0.0s 
 => [11/17] RUN make install PREFIX=/vt/install                                                                    351.9s 
 => [12/17] RUN mkdir /vt/local                                                                                      0.6s 
 => [13/17] COPY examples/local /vt/local                                                                            0.1s 
 => [14/17] COPY --chown=vitess:vitess web /web                                                                      0.2s 
 => [15/17] RUN npm install /web/vtadmin                                                                            21.4s 
 => [16/17] RUN mkdir /vt/common                                                                                     0.4s 
 => [17/17] COPY examples/common /vt/common                                                                          0.0s 
 => exporting to image                                                                                              41.8s 
 => => exporting layers                                                                                             41.7s 
 => => writing image sha256:00c46d7153146d72e77f44353d14d5c6a019fae8662694e5d639e84cabd784d8                         0.0s 
 => => naming to docker.io/vitess/local  
```

`make docker_run_local` output:
```
$ make docker_run_local
add /vitess/global
add /vitess/zone1
add zone1 CellInfo
ERROR: logging before flag.Parse: E0216 16:45:46.722920      36 syslogger.go:149] can't connect to syslog
W0216 16:45:46.776995      36 vtctl.go:124] cannot connect to syslog: Unix syslog delivery error
Created cell: zone1
etcd start done...
Starting vtctld...
Starting MySQL for tablet zone1-0000000100...
ERROR: logging before flag.Parse: E0216 16:45:46.947522      79 syslogger.go:149] can't connect to syslog
Starting vttablet for zone1-0000000100...
HTTP/1.1 200 OK
Date: Thu, 16 Feb 2023 16:45:53 GMT
Content-Type: text/html; charset=utf-8

Starting MySQL for tablet zone1-0000000101...
ERROR: logging before flag.Parse: E0216 16:45:53.602676     709 syslogger.go:149] can't connect to syslog
Starting vttablet for zone1-0000000101...
HTTP/1.1 200 OK
Date: Thu, 16 Feb 2023 16:46:01 GMT
Content-Type: text/html; charset=utf-8

Starting MySQL for tablet zone1-0000000102...
ERROR: logging before flag.Parse: E0216 16:46:01.663308    1331 syslogger.go:149] can't connect to syslog
Starting vttablet for zone1-0000000102...
HTTP/1.1 200 OK
Date: Thu, 16 Feb 2023 16:46:08 GMT
Content-Type: text/html; charset=utf-8

ERROR: logging before flag.Parse: E0216 16:46:08.586354    1947 syslogger.go:149] can't connect to syslog
{
  "keyspace": {
    "served_froms": [],
    "keyspace_type": 0,
    "base_keyspace": "",
    "snapshot_time": null,
    "durability_policy": "semi_sync"
  }
}
vtorc is running!
  - UI: http://localhost:16000
  - Logs: /vt/vtdataroot/tmp/vtorc.out
  - PID: 1964

ERROR: logging before flag.Parse: E0216 16:46:08.720700    1969 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:08.783777    1989 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:08.857961    2011 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:09.962662    2034 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:11.069568    2054 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:12.159739    2072 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:13.261536    2092 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:14.355732    2111 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:15.510334    2130 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:16.622632    2151 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:17.724237    2169 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:18.880600    2190 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:19.980265    2209 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:21.119616    2227 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:22.225939    2246 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:23.322896    2265 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:24.423544    2318 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:25.527348    2350 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:25.632250    2368 syslogger.go:149] can't connect to syslog
ERROR: logging before flag.Parse: E0216 16:46:25.718558    2381 syslogger.go:149] can't connect to syslog

ERROR: logging before flag.Parse: E0216 16:46:26.398628    2400 syslogger.go:149] can't connect to syslog
New VSchema object:
{
  "sharded": false,
  "vindexes": {},
  "tables": {
    "corder": {
      "type": "",
      "column_vindexes": [],
      "auto_increment": null,
      "columns": [],
      "pinned": "",
      "column_list_authoritative": false,
      "source": ""
    },
    "customer": {
      "type": "",
      "column_vindexes": [],
      "auto_increment": null,
      "columns": [],
      "pinned": "",
      "column_list_authoritative": false,
      "source": ""
    },
    "product": {
      "type": "",
      "column_vindexes": [],
      "auto_increment": null,
      "columns": [],
      "pinned": "",
      "column_list_authoritative": false,
      "source": ""
    }
  },
  "require_explicit_routing": false
}
If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).
Waiting for vtgate to be up...
vtgate is up!
Access vtgate at http://1c16740ecb0b:15001/debug/status
vtadmin-api is running!
  - API: http://localhost:14200
  - Logs: /vt/vtdataroot/tmp/vtadmin-api.out
  - PID: 2458


> vtadmin@0.1.0 build
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  451.01 kB  build/static/js/main.eb19b1b9.js
  16.11 kB   build/static/css/main.4982d801.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

vtadmin-web is running!
  - Browser: http://localhost:14201
  - Logs: /vt/vtdataroot/tmp/vtadmin-web.out
  - PID: 2560

vitess@1c16740ecb0b:/vt/local$ 
```

**vtadmin seemed to start alright**:

Schemas-VTAdmin

## Deployment Notes

This PR only affects the local Docker deployment.

### CODE REVIEW

**Review by notfelineit — APPROVED** [review]
🥳 thanks!

**Comment by GuptaManan100** [comment]
@andylim-duo The DCO check is failing. Would you mind re-committing your change with `-s` flag and then force pushing.

**Review by GuptaManan100 — APPROVED** [review]
The changes themselves look good to me!

**Review by frouioui — APPROVED** [review]
The change looks good to me. I allowed myself to change the description of the PR in order to close https://github.com/vitessio/vitess/issues/12310 once this PR is merged.

Thank you for your first contribution! ❤️

**Comment by andylim-duo** [comment]
> @andylim-duo The DCO check is failing. Would you mind re-committing your change with `-s` flag and then force pushing.

Fixed the DCO check based on the linked documentation that was very helpful. Thanks.

**Pull request merged**
