### PR TITLE
add vstream to java grpc client

### PR DESCRIPTION
**Pull request by pH14**
Adds the shiny, new VStream RPC to the Java GRPC client.

Signed-off-by: Paul Hemberger <phemberger@hubspot.com>

cc @leoxlin

### CODE REVIEW

**Comment by leoxlin** [comment]
LGTM on the java side

**Comment by harshit-gangal** [comment]
I think the vstream method should be added to [VTGateConnection.java](https://github.com/vitessio/vitess/blob/master/java/client/src/main/java/io/vitess/client/VTGateConnection.java)

**Comment by sougou** [comment]
Oops. Missed @harshit-gangal's comment. Can you add this in a separate PR?

**Comment by pH14** [comment]
I'll try to get to that this week

**Pull request merged**
