### PR TITLE
docker/mini: remove refs to orc configs

### PR DESCRIPTION
**Pull request by yields**
Signed-off-by: Amir Abushareb <yields@icloud.com>

## Description

During the cleanup in https://github.com/vitessio/vitess/pull/13327 seems like we removed some files but didn't update `docker/mini/Dockerfile`.

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by deepthi — APPROVED** [review]
Changes look fine to me, but this brings up the question of whether this example is even useful, and whether we should delete it.
@yields were you trying to run this as your local test?

**Comment by deepthi** [comment]
For future reference, please use a fork to create the PRs instead of creating a branch on the main repo. PRs created from branches on the vitess repo consume twice as much of CI resources.
Ref: https://vitess.io/docs/contributing/
and https://vitess.io/docs/contributing/github-workflow/

**Comment by yields** [comment]
> For future reference, please use a fork to create the PRs instead of creating a branch on the main repo. PRs created from branches on the vitess repo consume twice as much of CI resources.
> 
> Ref: https://vitess.io/docs/contributing/
> 
> and https://vitess.io/docs/contributing/github-workflow/

Ah sorry will do!

And yeah I ran this example locally, is there a different image that I should run?

**Review by frouioui — APPROVED** [review]

**Comment by deepthi** [comment]
> And yeah I ran this example locally, is there a different image that I should run?

Most of us run the example from `examples/local` and there is some debate about whether this `docker/mini` example is useful to anyone at all.

**Pull request merged**
