### PR TITLE
[13.0] Backport Add support for non aggregated columns in `OrderedAggregate`

### PR DESCRIPTION
**Pull request by frouioui**
## Description

This pull request is a backport of #10139. Among the changes backported from #10139, the changes done in #10163 are also backported (2682ecb561010ca55d20e41a9c6411718cdc44ef), they were required to successfully implement #10139.

## Related Issue(s)

- Fixes https://github.com/vitessio/vitess/issues/9889 on release-13

## Checklist

-   [x] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by frouioui** [comment]
@rohit-nayak-ps, I will investigate why `local.vtgate_reserved_conn3` is failing.

**Comment by frouioui** [comment]
[d038c39](https://github.com/vitessio/vitess/pull/10324/commits/d038c3906abf35ee37f0d737cbd07348bc1d2e76) fixes the flakiness observed in `TestMysqlDownServingChange`

**Review by systay — APPROVED** [review]

**Comment by GuptaManan100** [comment]
@frouioui It has been a month since this PR was created. Do we want to merge it or close it?

**Comment by frouioui** [comment]
@GuptaManan100, we are still looking at it.

**Pull request closed without merging**
