### PR TITLE
Add flags to limit `consultopo` connections

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

This PR addresses https://github.com/vitessio/vitess/issues/13678 by providing flags to tune the `consultopo` connection pool. This has mitigated/resolved a serious `vtctld` crash we're seeing in Production

While I expect/hope to stop using `consultopo` in our Production by the time we're on v18+ (where this PR would land), this crash could seriously impact users still using `consul`, which is why I propose this fix

## Related Issue(s)

Resolves https://github.com/vitessio/vitess/issues/13678

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by mattlord — COMMENTED** [review]
Thank you, @timvaillancourt !

Are you using the proposed flag default values in your cluster(s)? I'm curious if these new defaults could potentially cause unwanted side effects on upgrade.

In general, I think that this is fine. We should add some tests for it though. Are you up for writing some unit and/or e2e tests for this? I can help if needed.

Thanks again!

**Comment by timvaillancourt** [comment]
> Are you using the proposed flag default values in your cluster(s)? I'm curious if these new defaults could potentially cause unwanted side effects on upgrade.

@mattlord we're setting the new max-connections flag to `250` in our production and it has resolved the crashes we were seeing. The idle connection defaults seemed to work well, so we've left those at default values for now but it is nice they can be tuned in the future

This question has made me realise that this PR still uses the same `0` default as the consul driver, meaning no one is protected from the crash we saw unless they know to define this flag with a non-zero value

Due to this, I think we should set a non-zero default in Vitess. Perhaps `250`-`500` 🤔. Any thoughts there?

> In general, I think that this is fine. We should add some tests for it though. Are you up for writing some unit and/or e2e tests for this? I can help if needed.

Yes, I can give that a shot! Would the goal of this unit test be to validate that the maximum connection limit is respected? I saw `toxiproxy` is used somewhere, so that could be used to "stall" consul connections but I'm not sure how we'd know if the limit was respected, short of running something like `netstat` 🤔

**Comment by mattlord** [comment]
> > Are you using the proposed flag default values in your cluster(s)? I'm curious if these new defaults could potentially cause unwanted side effects on upgrade.
> 
> @mattlord we're setting the new max-connections flag to `250` in our production and it has resolved the crashes we were seeing. The idle connection defaults seemed to work well, so we've left those at default values for now but it is nice they can be tuned in the future
> 
> This question has made me realise that this PR still uses the same `0` default as the consul driver, meaning no one is protected from the crash we saw unless they know to define this flag with a non-zero value
> 
> Due to this, I think we should set a non-zero default in Vitess. Perhaps `250`-`500` 🤔. Any thoughts there?

500 seems like a pretty safe defaults change to me.

> > In general, I think that this is fine. We should add some tests for it though. Are you up for writing some unit and/or e2e tests for this? I can help if needed.
> 
> Yes, I can give that a shot! Would the goal of this unit test be to validate that the maximum connection limit is respected? I saw `toxiproxy` is used somewhere, so that could be used to "stall" consul connections but I'm not sure how we'd know if the limit was respected, short of running something like `netstat` 🤔

Unit tests would confirm intended behavior at the code level. Probably not applicable here (unless we start an actual consul process). 

For endtoend tests, yeah we could do something like what you described. It doesn't have to be that complicated either, we could e.g. just modify the default flag values so that it's easier to test, and then e.g. open up enough connections to test the behavior. Just something to confirm the expected/desired behavior and potentially suss out any unintended side effects.

Thanks!

**Comment by timvaillancourt** [comment]
Bump to avoid stale close

**Pull request closed without merging**
