### PR TITLE
Wrong length creating the buffer needed to ask for full auth

### PR DESCRIPTION
**Pull request by ofiriluz**
## Description
Minor bug fix where in the full auth flow of caching sha2 the buffer created has the wrong length to write 1 byte instead of 2, causing a panic

## Related Issue(s)

https://github.com/vitessio/vitess/issues/10769

## Checklist

-   [x] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by frouioui** [comment]
Hello @ofiriluz, thank you for your first contribution. Can you create an issue to describe the bug more in-depth and how to reproduce it?

**Comment by ofiriluz** [comment]
> Hello @ofiriluz, thank you for your first contribution. Can you create an issue to describe the bug more in-depth and how to reproduce it?

Done, https://github.com/vitessio/vitess/issues/10769

**Comment by dbussink** [comment]
@ofiriluz If you ensure you rebase onto latest `main`, the linter error in CI would also be fixed. 

Separately, would you be able to add a test for this?

**Comment by dbussink** [comment]
I think we still want this fix, but would be good to have a test for this.

**Review by dbussink — APPROVED** [review]
I have added a test here to ensure we cover the fallback path now through the auth server logic.

**Review by harshit-gangal — APPROVED** [review]

**Pull request merged**
