### PR TITLE
bugfix: Columns alias expanding

### LINKED ISSUE #14869: query planner regression: Invalid use of group function
### Overview of the Issue

We have a query that was using the v3 query planner comment directive that broke when upgrading to v18, with that removal. Vitess isn't handling an ambiguous column alias in the `ORDER BY` clause the same way MySQL does.

`vttablet: rpc error: code = InvalidArgument desc = Invalid use of group function (errno 1111) (sqlstate HY000)`

Possibly related issue:
- https://github.com/vitessio/vitess/issues/11641

### Reproduction Steps

1. Unsharded keyspace
```sql
create table tbl1(id bigint, group_id bigint, deadline_at timestamp, primary key(id));
```

2.
```sql
select /*vt+ PLANNER=v3 */
  group_id,
  from_unixtime(min(deadline_at)) as deadline_at
from tbl1
group by group_id
order by min(deadline_at)
limit 100;
```

The query above works if you change the column alias to `deadline_at2` or anything that doesn't shadow the original column name.

### Binary Version

```sh
All components v18.0.2
```

### Operating System and Environment details

```sh
GKE v1.27
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by systay**
## Description
We were not rewriting column aliases correctly. The rules that MySQL 8.0.x follows are not well documented, and in some cases we have found that the manual is not agreeing with our experiments.

This PR changes the alias rewriting rules to make sure to rewrite aliases early in the planning process, and removes the complex column lookup logic, which is no longer needed.

## Related Issue(s)
Fixes #14869

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by systay** [comment]
The codecov report doesn't seem to take into account the unit tests we have in the `planbuilder`  package, that also cover the `planbuilder/operators` package 🤷

**Review by harshit-gangal — COMMENTED** [review]
what is the expectation where order by and group by has alias referencing to a subquery

**Comment by harshit-gangal** [comment]
found a wrong plan output
```json
{
          "QueryType": "SELECT",
          "Original": "select 1, (select -1 from main.user) a from music order by a",
          "Instructions": {
            "OperatorType": "UncorrelatedSubquery",
            "Variant": "PulloutValue",
            "PulloutVars": [
              "__sq1"
            ],
            "Inputs": [
              {
                "InputName": "SubQuery",
                "OperatorType": "Route",
                "Variant": "Unsharded",
                "Keyspace": {
                  "Name": "main",
                  "Sharded": false
                },
                "FieldQuery": "select -1 from `user` where 1 != 1",
                "Query": "select -1 from `user`",
                "Table": "`user`"
              },
              {
                "InputName": "Outer",
                "OperatorType": "Route",
                "Variant": "Scatter",
                "Keyspace": {
                  "Name": "user",
                  "Sharded": true
                },
                "FieldQuery": "select 1, :__sq1 as a, weight_string(:__sq1) from music where 1 != 1",
                "OrderBy": "(1|2) ASC",
                "Query": "select 1, :__sq1 as a, weight_string(:__sq1) from music order by (select -1 from main.`user`) asc",
                "ResultColumns": 2,
                "Table": "music"
              }
            ]
          },
          "TablesUsed": [
            "main.user",
            "user.music"
          ]
        }
```

**Comment by harshit-gangal** [comment]
> found a wrong plan output
> 
> ```json
> {
>           "QueryType": "SELECT",
>           "Original": "select 1, (select -1 from main.user) a from music order by a",
>           "Instructions": {
>             "OperatorType": "UncorrelatedSubquery",
>             "Variant": "PulloutValue",
>             "PulloutVars": [
>               "__sq1"
>             ],
>             "Inputs": [
>               {
>                 "InputName": "SubQuery",
>                 "OperatorType": "Route",
>                 "Variant": "Unsharded",
>                 "Keyspace": {
>                   "Name": "main",
>                   "Sharded": false
>                 },
>                 "FieldQuery": "select -1 from `user` where 1 != 1",
>                 "Query": "select -1 from `user`",
>                 "Table": "`user`"
>               },
>               {
>                 "InputName": "Outer",
>                 "OperatorType": "Route",
>                 "Variant": "Scatter",
>                 "Keyspace": {
>                   "Name": "user",
>                   "Sharded": true
>                 },
>                 "FieldQuery": "select 1, :__sq1 as a, weight_string(:__sq1) from music where 1 != 1",
>                 "OrderBy": "(1|2) ASC",
>                 "Query": "select 1, :__sq1 as a, weight_string(:__sq1) from music order by (select -1 from main.`user`) asc",
>                 "ResultColumns": 2,
>                 "Table": "music"
>               }
>             ]
>           },
>           "TablesUsed": [
>             "main.user",
>             "user.music"
>           ]
>         }
> ```

this could be unrelated to your changes, did not check the `main` branch.

**Review by harshit-gangal — APPROVED** [review]

**Comment by systay** [comment]
> > found a wrong plan output

me and @harshit-gangal looked at this, and it's a real issue, but unrelated to these changes. I'll work on fixing this separately: https://github.com/vitessio/vitess/issues/14950

**Comment by frouioui** [comment]
> The codecov report doesn't seem to take into account the unit tests we have in the `planbuilder` package, that also cover the `planbuilder/operators` package 🤷

We should look into that @mattlord. I can see the base branch reports `0.00%` of coverage for these paths.

**Review by frouioui — APPROVED** [review]

**Pull request merged**
