### PR TITLE
style(grpc_codec): use switch-case

### PR DESCRIPTION
**Pull request by maxbrunet**
## Description

Hello! :wave:

Just a fly-by PR, I am coming from [planetscale/vtprotobuf#mixing-protobuf-implementations-with-grpc](https://github.com/planetscale/vtprotobuf#mixing-protobuf-implementations-with-grpc), `switch-case` seems appropriate and more readable here, but if it's a bad idea, I'd love to know why. :slightly_smiling_face:

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by ajm188 — COMMENTED** [review]
i don't think it's a _bad_ idea, but at the same time i don't find the previous version particularly _un_readable .. readability is pretty subjective, so i am somewhat concerned what happens when six months later someone else undoes this "to make things more clear [to them]"

**Comment by maxbrunet** [comment]
> i don't think it's a _bad_ idea, but at the same time i don't find the previous version particularly _un_readable .. readability is pretty subjective, so i am somewhat concerned what happens when six months later someone else undoes this "to make things more clear [to them]"

Thank you for your feedback, it makes sense to me, no problem if you'd prefer to refuse the PR

Asking @vmg (original author and vtprotobuf maintainer) for a review too :slightly_smiling_face:

**Review by vmg — APPROVED** [review]
This seems suspicious to me... I think the code was originally written like this because a Message could implement more than one interface at once and we wanted to prioritize `vtproto`. But you can do the same with a `switch`! Hm. Maybe this was just an oversight.

**Comment by vmg** [comment]
I think this is fine. I gave a look at the two interfaces and they don't really overlap (I don't think they ever did), so a type switch should be safe. Thanks @maxbrunet!

**Review by ajm188 — APPROVED** [review]
LGTM!

**Comment by dbussink** [comment]
@maxbrunet The test failure here is fixed on `main` so if you rebase, that's probably the easiest way to get this green.

**Review by harshit-gangal — APPROVED** [review]

**Pull request merged**
