### PR TITLE
bug: fix slice init length

### PR DESCRIPTION
**Pull request by longhutianjie**
## Description

fix slice init length

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Doesn't this also highlight that there's insufficient test coverage here?

**Comment by deepthi** [comment]
> Doesn't this also highlight that there's insufficient test coverage here?

What would a unit test for this look like?
An alternative idea is to see if we can lint for such usages. No idea whether `golangci-lint` (which is what we use) has a rule that would work for this.

**Review by deepthi — APPROVED** [review]

**Comment by deepthi** [comment]
I noticed a minute too late that the DCO check is failing. @longhutianjie you will need to fix that. The current CI workflows are going to be a waste, they will run again once you push a commit to fix the DCO aka sign-off.

**Comment by Sajjon** [comment]
@GrahamCampbell @deepthi 
> [!CAUTION]
> GH user `longhutianjie` is performing a supply chain attack!
> 🚫 BLOCK user immediatly and report him to Github 🚫
>
> The first step is getting rid of "first time contributor" status.
>
> The user has manually added the message "Signed-off-by: <USER>" to make the commit 
look more trust worthy. User has opened similar PRs in all these other
> repos in within the same hour:

- https://github.com/c9s/bbgo/pull/1731
- https://github.com/crypto-org-chain/cronos/pull/1566
- https://github.com/ethereumclassic/ethereumclassic.github.io/pull/1579
- https://github.com/stellar/go/pull/5453
- https://github.com/ory/hydra/pull/3831
- https://github.com/dfinity/ic/pull/1309
- https://github.com/lightningnetwork/lnd/pull/9064
- https://github.com/near/nearcore/pull/12036
- https://github.com/stellar/stellar-core/pull/4450
- https://github.com/fetchai/uAgents/pull/525
- https://github.com/vitessio/vitess/pull/16708


Furthermore I'm pretty sure this is the same person or group as github.com/vivoxfold3,
who tried performing the attack against these repos, with the exact same style:
Manually adding the message "Signed-off-by: <USER>" and making trivial contributions
to many crypto libs within the same hour:

- https://github.com/radixdlt/babylon-wallet-ios/pull/1321
- https://github.com/DeFiCh/ain/pull/3031
- https://github.com/beefyfinance/beefy-api/pull/1546
- https://github.com/fluencelabs/cli/pull/1022
- https://github.com/hoprnet/hoprnet/pull/6482
- https://github.com/ResearchHub/researchhub-web/pull/1825
- https://github.com/Taraxa-project/taraxa-node/pull/2846

**Pull request closed without merging**
