### PR TITLE
Managed DROP TABLE

### PR DESCRIPTION
**Pull request by shlomi-noach**
Tracking issue: https://github.com/vitessio/vitess/issues/6689

Implementing a `TableGC` (garbage collector) component as part of `TabletServer`, which periodically checks for tables in various table-drop states, transitions the tables between those states, purges data from the tables, or drops them altogether.

At this time this PR is not concerned with user facing `DROP` statements.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
This PR is now ready for review. Still TODO:

- endtoend tests
- accompanying documentation

**Comment by shlomi-noach** [comment]
Please note this PR requires, and is based on, #6668 . It is best if we first merge #6668. Reviewing this PR will become easier.

**Comment by shlomi-noach** [comment]
This PR implements _most of_ the `DROP TABLE` logic in #6689 : it runs the table lifecycle behind the scenes, down to dropping the table. The only part it does _not_ implement is the user facing `DROP IN '24h' TABLE my_table` syntax. This will be taken care of by a followup PR.

This PR is enough to run table garbage collection, if only the user/app know how to RENAME their table into the correct magic form. That's easy to do if you use the mechanisms `go/vt/schema`. And this is exactly what #6547 (or one of its followups) will do at the end of migration, for the artifact tables.

**Comment by shlomi-noach** [comment]
`endtoend` tests now added

**Comment by shlomi-noach** [comment]
This PR is in good shape the way I see it. It works through a table's lifecycle to eventually drop it; it only works on tables with "magic" names like `_vt_HOLD_6ace8bcef73211ea87e9f875a4d24e90_20200915120410`.

It does not offer a `DROP TABLE` syntax -- that's for a different PR. 

So, this PR only introduces a new behavior for very special tables, which will be immediately put to use by #6547 .

**Comment by shlomi-noach** [comment]
I'm ready to have this PR reviewed and merged.

**Review by deepthi — APPROVED** [review]
Looks fine to me.
We can merge after the conflicts are resolved and tests pass.

**Comment by shlomi-noach** [comment]
conflicts resolved, tests pass. Per review, I'm now merging (!)

**Pull request merged**
