### PR TITLE
fix backup goroutine leak

### LINKED ISSUE #15409: Bug Report: builtin backup leaks goroutine when it fails
### Overview of the Issue

When a backup on a tablet fails, it leaves behind the progress reporting goroutine.

### Reproduction Steps

Run a backup using vtctldclient and kill it using Ctrl+C before it completes. The context will get canceled, and the tablet on which the backup is running will go back into its previous state (usually REPLICA). Examine the goroutines on the tablet and see it is still running something like
```
vitess.io/vitess/go/vt/mysqlctl.(*backupPipe).ReportProgress+0xec	
vitess.io/vitess/go/vt/mysqlctl/builtinbackupengine.go:687
```
tablet will continue to repeatedly log the exact same message even though the backup has completed with a failure message.

### Binary Version

```sh
at least v16 and all later versions
```

### Operating System and Environment details

```sh
any
```

### Log Fragments

```sh
I0305 07:45:32.804549       1 builtinbackupengine.go:697] Backup "my_test_db/my_table.ibd": 11.02% (11753472.00/106676224.00kb)
```

### PR DESCRIPTION
**Pull request by deepthi**
## Description
Close the reader and writer in a defer func. This ensures that the progress goroutine receives a message on the done channel and returns.

Note that the golangci-lint hook broke after the go1.22 upgrade, so I've updated it to the latest version.

## Related Issue(s)
Fixes #15409 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by deepthi** [comment]
For reference, here's the stack trace from the old version of golangci-lint
```
ERRO [runner] Panic: SA1027: package "mysqlctl" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference: goroutine 9849 [running]:
runtime/debug.Stack()
	/Users/deepthi/.gvm/gos/go1.22.1/src/runtime/debug/stack.go:24 +0x64
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/golangci/golangci-lint@v1.51.2/pkg/golinters/goanalysis/runner_action.go:102 +0x108
panic({0x10194be20?, 0x102255290?})
	/Users/deepthi/.gvm/gos/go1.22.1/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x101aafc90, 0x10226ca80})
	/Users/deepthi/.gvm/gos/go1.22.1/src/go/types/sizes.go:228 +0x314
honnef.co/go/tools/staticcheck.checkAtomicAlignmentImpl(0x1400dc681e0)
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/honnef.co/go/tools@v0.4.2/staticcheck/lint.go:773 +0x64
honnef.co/go/tools/staticcheck.checkCalls.func1(0x102261330?, {0x101ac4750, 0x14003882b00}, 0x14002c0b540)
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/honnef.co/go/tools@v0.4.2/staticcheck/lint.go:3279 +0x298
honnef.co/go/tools/staticcheck.eachCall(0x1400c9257c0, 0x1400b1cdcd8)
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/honnef.co/go/tools@v0.4.2/staticcheck/lint.go:2648 +0x190
honnef.co/go/tools/staticcheck.checkCalls(0x14001839d18?, 0x100fbfb24?)
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/honnef.co/go/tools@v0.4.2/staticcheck/lint.go:3320 +0x90
honnef.co/go/tools/staticcheck.init.makeCallCheckerAnalyzer.callChecker.func64(0x101938a80?)
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/honnef.co/go/tools@v0.4.2/staticcheck/lint.go:3247 +0x20
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0x140017ba4a0)
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/golangci/golangci-lint@v1.51.2/pkg/golinters/goanalysis/runner_action.go:188 +0x8b8
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/golangci/golangci-lint@v1.51.2/pkg/golinters/goanalysis/runner_action.go:106 +0x20
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0x140016e6690, {0x1015947aa, 0x6}, 0x14001839f30)
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/golangci/golangci-lint@v1.51.2/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0x100fc2150?)
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/golangci/golangci-lint@v1.51.2/pkg/golinters/goanalysis/runner_action.go:105 +0x78
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0x140017ba4a0)
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/golangci/golangci-lint@v1.51.2/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb0
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 9
	/Users/deepthi/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/golangci/golangci-lint@v1.51.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x170
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: SA1027: package "mysqlctl" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference
ERRO Running error: 1 error occurred:
	* can't run linter goanalysis_metalinter: goanalysis_metalinter: SA1027: package "mysqlctl" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference
```

**Comment by deepthi** [comment]
CI is running with
```
run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.0
```

**Review by aybabtme — APPROVED** [review]

**Review by frouioui — APPROVED** [review]

**Review by mdlayher — APPROVED** [review]
LGTM!

**Comment by deepthi** [comment]
I don't think it's really necessary to backport to older releases. We can do it if someone asks.

**Pull request merged**
