### PR TITLE
RefreshMaster on both source and target before turning off query service on source during splitting

### PR DESCRIPTION
**Pull request by figocia**
Motivation:

I'm Yufei from Square Cash and we are using Vitess to scale our database.
We encountered an issues during a split this Monday. Basically we saw the source shard stopped taking traffic but the two target shards didn't pick up the traffic, and that leads to a downtime..

@tirsen helped us identified why the split stuck. It's because we found that our zookeeper can't refreshState on the source shard for some reason, it stuck there when running the command. 

So creating this PR to make sure we do not turn off the query service on the source if we found there is problem with either refreshState on the source or refreshState on the target

Question:
1: How to test this, i couldn't figure out how to mock the failure behavior by looking at the existing test
2: Is it worth writing a test for this?

### CODE REVIEW

**Comment by sougou** [comment]
Can you recreate this PR with DCO fixed: recreate the commit with `git commit -s`.

**Comment by deepthi** [comment]
> Can you recreate this PR with DCO fixed: recreate the commit with `git commit -s`.

Or you can amend and force-push using instructions here:
https://github.com/vitessio/vitess/pull/5165/checks?check_run_id=213965913

**Comment by sougou** [comment]
You can try. But amend doesn't update the DCO status.

**Comment by figocia** [comment]
@sougou @deepthi   Thanks! I did the amend thing, looks like the DCO is green now :)

**Pull request merged**
