### PR TITLE
vstreamer to throttle on source endpoint

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

VReplication works by hooking to a `source` tablet, pulling data as a replica as well as scanning tables, then to be applied on a `target` tablet.

On `source`, VReplication (via `vstreamer`) can cause a high load by aggressively pulling data, such that:

- if `source` is a replica, it can start lagging
- if `source` is a primary, it becomes sluggish

With this PR, `vstreamer` throttles based on `check-self`, introduced in #7319 , which is a throttle endpoint that tests the health of a specific tablet, the `source` tablet in our scenario. Right now, as described in #7319, whether replica or primary, we test for replication lag, which is an actual indicator on primary, too.

## Related Issue(s)

Tracking issue: https://github.com/vitessio/vitess/issues/7362

This PR extends and depends on https://github.com/vitessio/vitess/pull/7319

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [x]  VReplication
- [ ]  Cluster Management
- [ ]  Build 
- [ ]  VTAdmin

### CODE REVIEW

**Comment by shlomi-noach** [comment]
@rohit-nayak-ps please see my recent changes. On `vstreamer.go`, I only throttle on the `events` channel, so that I'm not blocking `venets` and `ctx.Done()` and `timer.C`.

Otherwise, added throttling in rowstreamer and resultstreamer.

**Comment by shlomi-noach** [comment]
Next up, I'l create an `endtoend` test

**Comment by shlomi-noach** [comment]
I've moved `rowstreamer` and `resultstreamer` throttling inside their main loops, where throttling is more granular. In my understanding, where we initially placed throttling (at beginning of `Stream()` function) was a one time check at the point of initially setting up the streaming.

**Comment by shlomi-noach** [comment]
Ready for review! Tests are now good.

Reminder that this PR extends https://github.com/vitessio/vitess/pull/7319, so it's best to first merge https://github.com/vitessio/vitess/pull/7319

**Comment by rohit-nayak-ps** [comment]
The new workflow yaml file for the e2e test should be created by updating the `test/ci_workflow_gen.go` script by. Otherwise any updates to the cluster template file will not reflect in this yaml.

**Review by rohit-nayak-ps — APPROVED** [review]
looks great!
test script / e2e workflow yaml needs to be updated as per comment.

**Comment by shlomi-noach** [comment]
> The new workflow yaml file for the e2e test should be created by updating the test/ci_workflow_gen.go codegen script 

Oh, I completely missed this!

**Comment by shlomi-noach** [comment]
because this PR introduced a named endtoend shard (`vreplication_basic`), I took it to now normalize all shards to be strings, not numbers. So, for example, shard `22` is now shard `"22"`.

**Pull request merged**
