### PR TITLE
fix query panic when fields and row length is not matching

### PR DESCRIPTION
**Pull request by inolddays**
Signed-off-by: JohnnyThree <whereshallyoube@gmail.com>

## Description

when you execute ddl on one shard's master mysql directly : 
```shell
mysql> desc sbtest3;
+-------+-----------+------+-----+---------+----------------+
| Field | Type      | Null | Key | Default | Extra          |
+-------+-----------+------+-----+---------+----------------+
| id    | int(11)   | NO   | PRI | NULL    | auto_increment |
| k     | int(11)   | NO   |     | 0       |                |
| c     | char(120) | NO   |     |         |                |
| pad   | char(60)  | NO   |     |         |                |
+-------+-----------+------+-----+---------+----------------+
4 rows in set (0.00 sec)

mysql> alter table sbtest3 add column d int(5) default 0;
Query OK, 0 rows affected (0.07 sec)
Records: 0  Duplicates: 0  Warnings: 0
```
then you select * from table (assume all shards has data already), you will get error like this:
```shell
mysql> select * from sbtest3 limit 1;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (61)
ERROR:
Can't connect to the server
```
and also vtgate crashes

this pr give a error hint and will not crash under this situation:
```shell
mysql> select * from sbtest3 ;
ERROR 1054 (42S22): vtgate: http://localhost:15001/: target: commerce.-80.master, used tablet: zone1-100 (localhost): query like 'select *' may encounter this problem, cause fields length cached in tablet & row length are not compatible, it may work again when tablet reload schema timely, try to ReloadSchema manually (errno 1054) (sqlstate 42S22)
```

## Related Issue(s)

#7046
- 

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [x]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build 
- [ ]  VTAdmin

### CODE REVIEW

**Comment by deepthi** [comment]
I believe it may be better to return `ER_BAD_FIELD_ERROR` as suggested in #4660.

**Comment by Johnny-Three** [comment]
> I believe it may be better to return `ER_BAD_FIELD_ERROR` as suggested in #4660.
done

**Comment by shlomi-noach** [comment]
As a special request, let's please paste codeblocks rather than screenshots, as screenshots are non-searchable for content. :pray: :bow:

**Comment by Johnny-Three** [comment]
ah. see, understood.  will fix .

Shlomi Noach <notifications@github.com> 于2021年1月21日周四 下午2:05写道：

**Comment by shlomi-noach** [comment]
Thank you so much, this is so much better!

**Comment by shlomi-noach** [comment]
@Johnny-Three I would like to sidetrack this issue and encourage you to try out the new Online DDL, as per https://vitess.io/docs/user-guides/schema-changes/managed-online-schema-changes/

With this new functionality, you do not need to migrate directly on the backend servers. You will simply run this **on vtgate**:
```
mysql> set @@ddl_strategy='gh-ost';
mysql> alter table sbtest3 add column d int(5) default 0;
```

This will kick an asynchronous `gh-ost` migration which you will be able to track, cancel, retry, and will run on the relevant shards/severs without requiring intervention from you.

While this feature exists in `8.0` I advise to use `9.0` (release next week) or current `master` branch, as we've made incompatible changes with `8.0` all things Online DDL (while the feature was "experimental").

Please let me know if you try this.

**Comment by Johnny-Three** [comment]
> @Johnny-Three I would like to sidetrack this issue and encourage you to try out the new Online DDL, as per https://vitess.io/docs/user-guides/schema-changes/managed-online-schema-changes/
> 
> With this new functionality, you do not need to migrate directly on the backend servers. You will simply run this **on vtgate**:
> 
> ```
> mysql> set @@ddl_strategy='gh-ost';
> mysql> alter table sbtest3 add column d int(5) default 0;
> ```
> 
> This will kick an asynchronous `gh-ost` migration which you will be able to track, cancel, retry, and will run on the relevant shards/severs without requiring intervention from you.
> 
> While this feature exists in `8.0` I advise to use `9.0` (release next week) or current `master` branch, as we've made incompatible changes with `8.0` all things Online DDL (while the feature was "experimental").
> 
> Please let me know if you try this.

cool , sounds great !
we have not catched up to 8.0 yet .
But gh-ost integrated into vitess is really exciting , i will have a try :)

**Comment by systay** [comment]
Instead of doing a big recover, did you consider checking the slice lengths and returning an error instead?

**Comment by Johnny-Three** [comment]
> Instead of doing a big recover, did you consider checking the slice lengths and returning an error instead?



> Instead of doing a big recover, did you consider checking the slice lengths and returning an error instead?

hi , thanks for suggestion. you mean in the function MakeRowTrusted ?  i have been considering this ,  MakeRowTrusted is a low-level function method, and  there are other functions also depend on this method, but this kind of mismatch is a small probability time and only occurs under certain circumstances, so I think it may proper to put the judgement in “Defer”. Because i am a bit worrying if  checking & comparing the slice lengths will take much cpu cost ? what is your opinion ?

**Comment by systay** [comment]
My concern is that we are catching panics that are caused by something else, and this ends up hiding other issues for us. How about this - let's benchmark it. We are already checking the length of one slice, so maybe checking the size of the other one does not cost much more.

We would need to change `MakeRowTrusted` so that it can return an error, and then check errors everywhere this is used. Is this something you feel comfortable doing?

**Comment by Johnny-Three** [comment]
I think you may right. This PR seems to only temporarily solve the problem, but  may hiding other sources of errors, but Modify ‘MakeRowTrusted' the underlying changes may affect some further operations such as vreplication and resharding. I think it may better for official to solve this . just for more careful to verify the correctness of the modification. BTW , Do you think this discussion should be reserved? Or should I close this PR first and let the new PR associate the related ISSUE?

**Comment by indera-shsp** [comment]
Does anybody know if this issue is not happening when these two flags are enabled?

```
-watch_replication_stream
-track_schema_versions
```

https://vitess.io/docs/design-docs/vreplication/vstream/tracker/

**Comment by Johnny-Three** [comment]
> Does anybody know if this issue is not happening when these two flags are enabled?
> 
> ```
> -watch_replication_stream
> -track_schema_versions
> ```
> 
> https://vitess.io/docs/design-docs/vreplication/vstream/tracker/

it won't help. if execute DDL directly to mysql and then query plan cache will not adapt with the real one.

**Pull request closed without merging**
