### PR TITLE
Do vschema_customer_sharded.json before create_customer_sharded.sql.

### PR DESCRIPTION
**Pull request by jfg956**
When doing create_customer_sharded.sql (removing auto-increments) before vschema_customer_sharded.json (applying VIndex), there is a short period of time where INSERTs in the customer and corder tables would fail if the customer_id or order_id is not set.  Doing vschema_customer_sharded.json before create_customer_sharded.sql remove this failure possibility.

### CODE REVIEW

**Comment by jfg956** [comment]
Related: https://github.com/vitessio/website/pull/647

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm
nice catch

**Comment by rohit-nayak-ps** [comment]
@shlomi-noach , before merging this just wanted to check with you about this failing test: https://github.com/vitessio/vitess/pull/7210/checks?check_run_id=1591367702. Is this related to your internal post this morning about the failing docker test?

**Comment by shlomi-noach** [comment]
> Is this related to your internal post this morning

It is. Just merged `upstream/master` into that branch and will follow up to confirm the test passes.

**Comment by shlomi-noach** [comment]
@rohit-nayak-ps tests now pass. I'll also keep an eye for other PRs. Merging this one.

**Pull request merged**
