### PR TITLE
Replace the native gzip implementation with the pure Go impl

### PR DESCRIPTION
**Pull request by tirsen**
This makes it possible to build Vitess cross platform which is great if
you code on a Mac and run Linux in production.

Signed-off-by: Jon Tirsen <jontirsen@squareup.com>

### CODE REVIEW

**Comment by alainjobart** [comment]
I understand the motivation, but I'm a bit sad to see it go... :)
At some point we said we would make it a plugin, and not compile / use cgzip on Mac. Not sure how much work that is.

**Comment by derekperkins** [comment]
What are the performance implications?

**Comment by demmer** [comment]
Does `GOOS=linux go build` not do the trick?

**Comment by derekperkins** [comment]
@demmer That works for native Go code, but anything using CGo has to be compiled in the same environment.

**Comment by dweitzman** [comment]
Related: https://github.com/vitessio/vitess/issues/3632

**Comment by dweitzman** [comment]
It seems like it's actually possible for a pure and cgo version to co-exist in the same codebase using build tags / build constraints (https://golang.org/pkg/go/build/#hdr-Build_Constraints), which is a golang feature I've only just discovered

I haven't actually tried this, but I think the idea is that you could put annotations in a file like these:

// +build !cgo
// +build cgo

And then at compilation time, choose whether to build a cgo or pure version like this:

CGO_ENABLED=0 go build ...

**Comment by sougou** [comment]
Closing this due to #4008

**Pull request closed without merging**
