### PR TITLE
Support for REVERT VITESS_MIGRATION statement

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

This PR adds support for a new type of query:

```
REVERT VITESS_MIGRATION 'cc89c799_817b_11eb_9baf_f875a4d24e90'
```
"Revert" is still undocumented, and was only merged recently in #7478.

`REVERT` queries have a `RevertMigration` primitive, which, like `OnlineDDL` primitive, submits an online DDL request via `topo`. The primitive itself submits a _fake_ query request (e.g. `revert 'cc89c799_817b_11eb_9baf_f875a4d24e90'`), and that is later interpreted by the tablet servers.

Right now we enforce a string literal for the migratoin ID, but we can later iterate and support expressions.

Tests via: parser (unit), planner (unit), `endtoend/onlineddl/revert` (endtoend).

## Related Issue(s)

- #7604 
- #7478 
- #6926 

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [x]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Documentation to follow

**Comment by shlomi-noach** [comment]
Kind request for review :pray:

**Review by systay — APPROVED** [review]
sorry it took so long

**Comment by shlomi-noach** [comment]
Woohoo! Thank you :heart:

**Pull request merged**
