### PR TITLE
Default buildinfo tablet tags to off

### LINKED ISSUE #9186: Fix breaking change to `ListAllTablets`
#### Overview of the Issue
ListAllTablets output has changed, and breaks scripts or code that parses it.
Possibly other commands (like GetTablet) may also have this issue.

https://github.com/vitessio/vitess/pull/8973#issuecomment-964720741

#### Reproduction Steps
```
$ vtctlclient ... ListAllTablets
```

#### Binary version
Any build that includes e524e615593e4d3f619312c2ffc56cc85e77daa8

#### Operating system and Environment details
Any

### PR DESCRIPTION
**Pull request by ajm188**
Signed-off-by: Andrew Mason <amason@slack-corp.com>

## Description

This is follow-up to #8973 and fixes #9186.

Without changing any of the flags in the local example:

```
❯ vtctlclient -server ":15999" ListAllTablets
zone1-0000000100 commerce 0 primary localhost:15100 localhost:17100 [] 2021-11-10T20:29:30Z
zone1-0000000101 commerce 0 replica localhost:15101 localhost:17101 [] <null>
zone1-0000000102 commerce 0 rdonly localhost:15102 localhost:17102 [] <null>
```

## Related Issue(s)

Fixes #9186 

## Checklist
- [x] Should this PR be backported? **no**
- [x] Tests were added or are not required **n/a**
- [x] Documentation was added or is not required **n/a**

### CODE REVIEW

**Review by mattlord — APPROVED** [review]
Thank you! ❤️

**Comment by mattlord** [comment]
@ajm188 looks like we need to adjust the new end2end test based on what build flags are being ignored: https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletmanager/tm_init_test.go#L513

**Comment by ajm188** [comment]
oh right! i forgot about that, nice catch

**Review by deepthi — APPROVED** [review]
Is it worth writing a unit test to ensure that when the skip flag is set to "", all the tags do make it into the tablet record?
Otherwise LGTM.

**Pull request merged**
