### PR TITLE
tests: add tests for `go/sqlescape`

### PR DESCRIPTION
**Pull request by Maniktherana**
## Description
Adds tests for `go/sqlescape`

Question: if `EscapeID` for the string ``` a`a ``` returns ``` `a``a` ```, should `UnescapeID` reverse it? Because currently it simply returns ``` a``a ```, removing the outer backticks without halving the ones inside the string

## Related Issue(s)
#14931

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by mattlord — APPROVED** [review]
Thanks, @Maniktherana ! We can see that the package's code coverage went from 61.29% on main to 100% in the PR branch:
  -https://app.codecov.io/gh/vitessio/vitess/tree/main/go%2Fsqlescape
  - https://app.codecov.io/gh/vitessio/vitess/pull/14987/tree/go/sqlescape

Regarding your question... I think that Escape followed by Unescape should produce that same string that we started with. You're right that currently it does not as EscapeID escapes inner backticks but UnescapeID does not do the reverse. I think that's a bug. What do you think @rohit-nayak-ps ?

**Comment by Maniktherana** [comment]
@mattlord if this is the case, I'd be happy to raise an issue and follow it up with a fix

**Comment by rohit-nayak-ps** [comment]
>> Regarding your question... I think that Escape followed by Unescape should produce that same string that we started with. 

>You're right that currently it does not as EscapeID escapes inner backticks but UnescapeID does not do the reverse. I think that's a bug. What do you think @rohit-nayak-ps ?

Yes, this is a bug. `Unescape(Escape())` should exactly reverse.

**Comment by Maniktherana** [comment]
going to keep this as draft until #14992 is resolved

**Comment by GuptaManan100** [comment]
@Maniktherana Do you want to take a stab at fixing the issue as well, given that you're the one who uncovered it? If you don't want to, thats fine as well, in that case, I shall pick it up.

**Comment by Maniktherana** [comment]
@GuptaManan100 I'm already on it :)
refer to #15009

**Review by GuptaManan100 — APPROVED** [review]
Excellent work, both on finding the bug, and also on the fix.

**Pull request merged**
