### PR TITLE
[security] add possibility to disable pprof.

### PR DESCRIPTION
**Pull request by shmel1k**
Signed-off-by: Aleksandr Petrukhin <a.petrukhin@city-mobil.ru>

## Backport
YES

## Status
**DRAFT/READY**

## Description
The main goal is to add possibility to disable /debug/pprof page when it is not required. It is done to some security issues. You can easily query '/debug/pprof/cmdline' page and get passwords from cmdline, when you use flags from cmdline.

## Related Issue(s)
List related PRs against other branches:

## Todos
- [ ] Tests
- [ ] Documentation

## Impacted Areas in Vitess
This PR should affect nothing

### CODE REVIEW

**Comment by sougou** [comment]
Sorry about getting to this so late.

Is command line leak the only reason to do this? If so, it's not worth it because there are too many ways to discover the command line. This is why it's not good practice to specify passwords that way.

If there are other reasons to do this, we should implement this feature as part of the servenv package. This way, all binaries will automatically inherit the behavior.

**Comment by shlomi-noach** [comment]
Irrespective of the security aspect, I liked the singleton Mux approach. At th etime I tried consolidating all our http interfaces into using a single instance; I'll revisit that.

**Comment by shmel1k** [comment]
Hi, @sougou ! Thanks for answer!
In fact, our security developers discovered, that you can just check cmdline with simple curl even not having access to the remote server.
The 'cmdline' ban is, possibly, the easiest way to do it

**Comment by shmel1k** [comment]
@shlomi-noach , thanks! I just saw that http.Handle is used in most places, so I decided not to do any breaking changes and the singleton was the only way to do it

**Comment by SecurityEdge2** [comment]
I apologize for entering the discussion with a new question. I hope my question will help you

@sougou  can you name other places through which an external attacker can access debug information or cmdline?

I am convinced that software should be secure by default. Having a debug interface enabled by default with the ability to get a password in some cases is bad. This leads to the fact that people inadvertently make mistakes that lead to security problems.

**Comment by sougou** [comment]
As far as I know, none of the info exported under pprof is sensitive. Of course, this is based on the recommendation that you should not supply passwords through the command line. This is best practice in the industry. There are too many easy ways to find out the command line of a running process. Off the top of my head, a simple `ps` can tell you the contents. Also, if you're running under kubernetes, the pod info reveals the command line.

**Comment by shmel1k** [comment]
Hi, @sougou !
Thanks for all answers

If I understand correctly, you have to be logged in as 'sudo' user on some host to perform 'ps' command. In fact, with open pprof you can just use some port-scanner and get access to all cmdline information.

Can you please say, what to do next? Should I improve something in this PR in order to have ability to merge it or it should be closed?

**Comment by SecurityEdge2** [comment]
I apologize for my intrusiveness, I hope you don't mind if we continue to communicate

@sougou you are right. I hope you understand that when you have a large company, many different teams and practices, the presence of such weaknesses leads to vulnerabilities. One day someone will be lazy and will not launch the product correctly. I don’t like that we are creating preconditions for vulnerability. We must create the prerequisites for safe use.

In addition, your product can be used in networks with different security requirements. For example, in networks where products should not provide any additional information, incl. not containing sensitive data.

**Comment by sougou** [comment]
What I'm essentially saying is that a setup that specifies passwords on the command line will instantly fail a security audit. The only recommended fix will be to stop doing this. So, adding the additional protection will just be unnecessary complexity.

**Comment by sougou** [comment]
I was mainly objecting to the flag. As for the singleton approach, I believe the better way would be to do it in `servenv`. I've explained it in #7066.

**Comment by shmel1k** [comment]
@sougou , thanks for the answer!

Can we try to discuss it later when I move singleton approach to servenv?

**Comment by sougou** [comment]
Yes. Definitely!

**Comment by shmel1k** [comment]
@sougou , I moved 'GetMux' API from httputil2 to servenv :)
Looks like it worked well.

**Comment by shmel1k** [comment]
@sougou , hello!
Do you have any updates about this PR? :(

**Pull request closed without merging**
