### PR TITLE
VReplication: allow invalid (zero) values in date columns

### PR DESCRIPTION
**Pull request by rohit-nayak-ps**
While migrating with MoveTables, it is likely that the source database allowed zero values in dates (like 0000-00-00). The default connection options treat these as invalid and vreplication fails on rows with zero date values at the moment. The user's app will work fine since they will (presumably) be setting the connection options in the app (or globally) to allow invalid dates. 

We need to relax the sql options to allow invalid dates during all phases of vreplication since we will find invalid dates both during copy as well as when we stream (the 'replicate' phase).

Signed-off-by: Rohit Nayak <rohit@planetscale.com>

### CODE REVIEW

**Comment by rohit-nayak-ps** [comment]
> This looks good. Can you add a description for the PR? Something that explains what the bug was and what the fix does.

Hmm, while writing the description I realized that this implementation maybe not be complete. The connection setting is being reset to the original after the copy phase. While that works for FK checks (since during replication we expect constraints to be met), for zero dates the connection setting needs to be set also during replicate, correct?

**Comment by sougou** [comment]
> > This looks good. Can you add a description for the PR? Something that explains what the bug was and what the fix does.
> 
> Hmm, while writing the description I realized that this implementation maybe not be complete. The connection setting is being reset to the original after the copy phase. While that works for FK checks (since during replication we expect constraints to be met), for zero dates the connection setting needs to be set also during replicate, correct?

I still don't have a full understanding of the issue. But yeah, if it can happen during apply, we should take care of it there also.

**Comment by rohit-nayak-ps** [comment]
On reflection (mine, not golang's ...) this needs more work: we need to allow invalid dates for the replicate phase as well, not just for the copy phase.

**Comment by rohit-nayak-ps** [comment]
Closing this old incomplete PR since a lot of related code has changed. Will work on it fresh when this issue is prioritized.

**Pull request closed without merging**
