### PR TITLE
jdbc: set type of BigInteger as VARCHAR

### PR DESCRIPTION
**Pull request by acharis**
Signed-off-by: Alex Charis <acharis@hubspot.com>

### CODE REVIEW

**Comment by harshit-gangal** [comment]
In Mysql Bigint can have negative value hence is was kept as INT64.
Min Value : -2^63
Max Value : 9223372036854775807

**Comment by acharis** [comment]
yeah, i'm not really sure what the right thing to do is...we're mapping a Java BigInteger, which provides arbitrary precision signed integers, onto a mysql bigint, which can be signed or unsigned and has limited precision. and i'm guessing we don't know which we're mapping to at this point in the code.

**Comment by harshit-gangal** [comment]
@acharis Do you have reason for changing this to UINT64? Is it breaking things?
BigInteger can hold negative value which is same with Mysql.

We can think of sending it as string. Can you validate that.

**Comment by acharis** [comment]
Yes, things are broken as-is and this fixes them. Tested internally.

That being said, as above, I'm not sure what the right fix is.

**Comment by harshit-gangal** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vitessio/vitess/3940)*

**Comment by harshit-gangal** [comment]
LGTM

**Pull request merged**
