### PR TITLE
Add more timings binlog player

### PR DESCRIPTION
**Pull request by rafael**
### Desc

We are in the process of investigating some slowness with binlog player during shard splits. The following adds metric to help find where the bottleneck is. Specifically:

* Metric to track how long it takes to receive message from BinlogStreamer
* Add warning when binlog player is being throttled. 

Note: There are already timings for mysql time while processing transactions.

### CODE REVIEW

**Comment by sougou** [comment]
All tests were broken. I've restarted them to see if this was a one-off. If they fail again, we'll need to investigate.

**Comment by rafael** [comment]
Hmm yeah - I'll investigate why tests are broken.

**Comment by sougou** [comment]
I don't see why this should fail 'all' the tests. And any number of retries are failing. Maybe try to rebase this?

**Comment by rafael** [comment]
Yeah. Let's see. I do not understand either.

**Comment by rafael** [comment]
I'm going to close this for now. Re-open in the future when we pick up again this work.

**Pull request closed without merging**
