### PR TITLE
Experimental fast pool enabled (Test only)

### PR DESCRIPTION
**Pull request by gak**

### CODE REVIEW

**Comment by gak** [comment]
This PR was just to test on travis when fast pool is forcefully enabled #4697

**Comment by gak** [comment]
Looks like it's failing because of #4701

**Comment by sougou** [comment]
I assume the alternate implementation has been satisfactory. If so, I'll close this.

**Comment by sougou** [comment]
Closing this presuming the other solution is working satisfactorily.

**Pull request closed without merging**
