### PR TITLE
Fix: errant GTID in health streamer

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the health streamer issue described in https://github.com/vitessio/vitess/issues/13182. This is a partial back port of https://github.com/vitessio/vitess/pull/13121/

## Related Issue(s)

- #13182 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by deepthi — APPROVED** [review]
I see that you've followed the same pattern as `replTracker`. I can't say that I like this spreading around of primary/serving state between the various sub-structs of `tmState`, but there doesn't seem to be any better way of doing it.

**Comment by deepthi** [comment]
`unit_race` is actually failing. It's a good thing we run our unit tests with the race detector 😅

**Review by harshit-gangal — APPROVED** [review]

**Comment by GuptaManan100** [comment]
The upgrade downgrade failures look unrelated. I will investigate them separately.

**Comment by GuptaManan100** [comment]
@frouioui is taking a look at ☝️

**Pull request merged**
