### PR TITLE
Vindexes: Pass context in consistent lookup handleDup

### PR DESCRIPTION
**Pull request by brendar**
## Description

Context handling was refactored in  https://github.com/vitessio/vitess/commit/c43a162ea567f47a89b8d4a506d2995740737b79 which included [this TODO](https://github.com/vitessio/vitess/commit/c43a162ea567f47a89b8d4a506d2995740737b79#diff-0e06131de7d1c872b547136ccc5fa2318a7b6b99f5c3ba78c8d0ab2f6757980eR302-R303)
```go
// TODO: context needs to be passed on.
qr, err = vcursor.ExecuteKeyspaceID(context.Background(), lu.keyspace, existingksid, lu.lockOwnerQuery, bindVars, false /* rollbackOnError */, false /* autocommit */)
```

This causes consistent lookup duplicate row handling to fail when tablets are using strict table ACL enforcement because there is no caller id in the context.

It looks like the TODO and `context.Background()` was left behind inadvertently, so this PR simply passes the existing context through. cc @harshit-gangal in case there was a reason for it.

## Related Issue(s)

Fixes https://github.com/vitessio/vitess/issues/14652

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

## Deployment Notes

n/a

### CODE REVIEW

**Comment by brendar** [comment]
> Is it possible to add a unit test that verifies the new behavior?

I could update the consistent lookup unit tests in [go/vt/vtgate/vindexes/consistent_lookup_test.go](https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/vindexes/consistent_lookup_test.go) to assert that the same context is used for all queries, or I could update the vtgate lookup endtoend tests to use table ACLs by configuring them in [go/test/endtoend/vtgate/main_test.go](https://github.com/vitessio/vitess/blob/main/go/test/endtoend/vtgate/main_test.go).  

Either way would catch the bug and verify the fix. Do you have a preference? I'm not sure if the project has strong opinions about testing the implementation vs testing the behavior.

**Comment by shlomi-noach** [comment]
> I'm not sure if the project has strong opinions about testing the implementation vs testing the behavior.

Haha there's differing opinions her as well. But the general agreement is that unit testing is more predictable, less flaky, easier to debug. Also, at the end of the day, "why not both?"

**Comment by brendar** [comment]
I've updated the unit tests for consistent lookup vindexes to ensure they're passing the expected context whenever they execute a query. 

I didn't update the vtgate endtoend tests to use table ACLs since it would apply to all tests in that package. The tests still pass, but it could make debugging other issues more complicated. Happy to add that if you think it's worth doing.

**Review by harshit-gangal — APPROVED** [review]

**Comment by brendar** [comment]
Would it be possible to add backport labels to this PR? The bug presents a slight MySQL compatibility issue for clients in that they can't catch and recover from the expected duplicate entry error code 1062, so I think backporting it would be nice.

**Comment by shlomi-noach** [comment]
@harshit-gangal for backport consideration

**Review by shlomi-noach — APPROVED** [review]

**Pull request merged**
